---
sidebar: sidebar 
permalink: concept_searching_assets.html 
summary: Mithilfe erweiterter Suchtechniken können Sie die gesuchten Assets finden. 
keywords: asset page, objects, search, advanced, alerts 
---
= Hinweise und Tipps zur Suche nach Assets und Warnungen
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Zur Suche nach Daten oder Objekten in Ihrer überwachten Umgebung können mehrere Suchtechniken verwendet werden.

* *Platzhaltersuche*
+
Sie können eine Platzhaltersuche mit mehreren Zeichen durchführen, indem Sie das Zeichen * verwenden.  Beispielsweise würde _applic*n_ _application_ zurückgeben.

* *Bei der Suche verwendete Ausdrücke*
+
Eine Phrase ist eine Gruppe von Wörtern, die von doppelten Anführungszeichen umgeben sind, beispielsweise „VNX LUN 5“.  Sie können doppelte Anführungszeichen verwenden, um nach Dokumenten zu suchen, deren Namen oder Attribute Leerzeichen enthalten.

* *Boolesche Operatoren*
+
Mithilfe der Booleschen Operatoren OR, AND und NOT können Sie mehrere Begriffe kombinieren, um eine komplexere Abfrage zu erstellen.

+
ODER

+
Der ODER-Operator ist der Standard-Konjunktionsoperator.

+
Wenn zwischen zwei Begriffen kein Boolescher Operator steht, wird der ODER-Operator verwendet.

+
Der ODER-Operator verknüpft zwei Begriffe und findet ein passendes Dokument, wenn einer der Begriffe in einem Dokument vorhanden ist.

+
Beispielsweise sucht _storage OR netapp_ nach Dokumenten, die entweder _storage_ oder _netapp_ enthalten.

+
Dokumente, die den meisten Begriffen entsprechen, erhalten hohe Punktzahlen.

+
UND

+
Mit dem UND-Operator können Sie nach Dokumenten suchen, in denen beide Suchbegriffe in einem einzigen Dokument vorkommen.  Beispielsweise sucht _storage AND netapp_ nach Dokumenten, die sowohl _storage_ als auch _netapp_ enthalten.

+
Sie können das Symbol *&&* anstelle des Wortes AND verwenden.

+
NICHT

+
Wenn Sie den Operator NOT verwenden, werden alle Dokumente, die den Begriff nach NOT enthalten, aus den Suchergebnissen ausgeschlossen.  Beispielsweise sucht _storage NOT netapp_ nach Dokumenten, die nur _storage_ und nicht _netapp_ enthalten.

+
Sie können das Symbol *!* anstelle des Wortes NOT verwenden.



Bei der Suche wird die Groß-/Kleinschreibung nicht berücksichtigt.



== Suche mit indexierten Begriffen

Suchen, die mit mehr indexierten Begriffen übereinstimmen, führen zu höheren Punktzahlen.

Der Suchstring wird durch Leerzeichen in einzelne Suchbegriffe aufgeteilt.  Beispielsweise wird die Suchzeichenfolge „storage aurora netapp“ in drei Schlüsselwörter aufgeteilt: „storage“, „aurora“ und „netapp“.  Die Suche wird mit allen drei Begriffen durchgeführt.  Die Dokumente, die den meisten dieser Begriffe entsprechen, erhalten die höchste Punktzahl.  Je mehr Informationen Sie angeben, desto besser sind die Suchergebnisse.  Sie können beispielsweise nach einem Speicher anhand seines Namens und Modells suchen.

Die Benutzeroberfläche zeigt die Suchergebnisse kategorienübergreifend an, mit den drei besten Ergebnissen pro Kategorie.  Wenn Sie ein erwartetes Objekt nicht gefunden haben, können Sie weitere Begriffe in den Suchbegriff aufnehmen, um die Suchergebnisse zu verbessern.

Die folgende Tabelle enthält eine Liste indexierter Begriffe, die der Suchzeichenfolge hinzugefügt werden können.

|===
| Kategorie | Indizierte Begriffe 


| Storage | "Speicher" Name Anbieter Modell 


| Speicherpool | Name des „Speicherpools“ Name des Speichers IP-Adressen des Speichers Seriennummer des Speichers Speicheranbieter Speichermodell Namen aller zugehörigen internen Volumes Namen aller zugehörigen Datenträger 


| Internes Volumen | Name des „internen Datenträgers“ Name des Speichers IP-Adressen des Speichers Seriennummer des Speichers Speicheranbieter Speichermodell Name des Speicherpools Namen aller zugehörigen Freigaben Namen aller zugehörigen Anwendungen 


| Volumen | „Volume“-Name Bezeichnung Namen aller internen Volumes Name des Speicherpools Name des Speichers IP-Adressen des Speichers Seriennummer des Speichers Speicheranbieter Speichermodell 


| Speicherknoten | "storagenode" Name Name des Speichers IP-Adressen des Speichers Seriennummer des Speichers Speicheranbieter Speichermodell 


| Gastgeber | „Host“-Name IP-Adressen Namen aller zugehörigen Anwendungen 


| Datenspeicher | Name des „Datenspeichers“ Virtuelles Zentrum IP-Namen aller Datenträger Namen aller internen Datenträger 


| Virtuelle Maschinen | Name der „virtuellen Maschine“ DNS-Name IP-Adressen Name des Hosts IP-Adressen der Hostnamen aller Datenspeicher Namen aller zugehörigen Anwendungen 


| Switches (regulär und NPV) | "Switch" IP-Adresse WWN-Name Seriennummer Modell Domänen-ID Name des Fabric WWN des Fabric 


| Anwendung | "Anwendung" Name Mandant Geschäftsbereich Geschäftseinheit Projekt 


| Band | "Band" IP-Adresse Name Seriennummer Hersteller 


| Hafen | "Port" WWN-Name 


| Stoff | "Stoff" WWN-Name 


| Virtuelle Speichermaschine (SVM) | "storagevirtualmachine" Name UUID 
|===