---
sidebar: sidebar 
permalink: concept_determining_data_collector_acq_status.html 
summary: Erfassungsstatus des Datensammlers 
keywords: collector, acquisition, status 
---
= Ermitteln des Erfassungsstatus des Datensammlers
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Da Datensammler die primäre Informationsquelle für Data Infrastructure Insights sind, müssen Sie unbedingt sicherstellen, dass sie in einem laufenden Zustand bleiben.

Der Status des Datensammlers wird in der oberen rechten Ecke jeder Asset-Seite als Meldung „Vor N Minuten erfasst“ angezeigt, wobei N den aktuellsten Erfassungszeitpunkt des/der Datensammlers/Datensammler des Assets angibt.  Außerdem werden Uhrzeit und Datum der Erfassung angezeigt.

Wenn Sie auf die Nachricht klicken, wird eine Tabelle mit dem Namen, dem Status und der letzten erfolgreichen Erfassungszeit des Datensammlers angezeigt.  Wenn Sie als Administrator angemeldet sind, gelangen Sie durch Klicken auf den Link mit dem Namen des Datensammlers in der Tabelle zur Detailseite dieses Datensammlers.
