---
sidebar: sidebar 
permalink: concept_telegraf_display_options.html 
keywords: telegraf, data, display, 
summary: Telegraf-Datenanzeigeoptionen 
---
= Metriken transformieren
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Data Infrastructure Insights bietet verschiedene *Transformations*optionen für bestimmte Metriken in Widgets (insbesondere die als „Benutzerdefiniert“ oder „Integrationsmetriken“ bezeichneten Metriken, z. B. von Kubernetes, ONTAP Advanced Data, Telegraf-Plugins usw.), sodass Sie die Daten auf verschiedene Arten anzeigen können.  Wenn Sie einem Widget transformierbare Metriken hinzufügen, wird Ihnen ein Dropdown-Menü mit den folgenden Transformationsoptionen angezeigt:

Keine: Die Daten werden unverändert und ohne Manipulation angezeigt.

Rate: Aktueller Wert geteilt durch den Zeitraum seit der letzten Beobachtung.

Kumulativ: Die Ansammlung der Summe der vorherigen Werte und des aktuellen Werts.

Delta: Die Differenz zwischen dem vorherigen Beobachtungswert und dem aktuellen Wert.

Deltarate: Deltawert geteilt durch den Zeitraum seit der letzten Beobachtung.

Kumulative Rate: Kumulativer Wert geteilt durch den Zeitraum seit der letzten Beobachtung.

Beachten Sie, dass durch die Transformation von Metriken nicht die zugrunde liegenden Daten selbst geändert werden, sondern nur die Art und Weise, wie die Daten angezeigt werden.
