---
sidebar: sidebar 
permalink: concept_cs_api.html 
keywords: api, access, token, swagger 
summary: Workload Security umfasst eine leistungsstarke API zur Integration in andere Applikationen wie CMDBs. 
---
= Workload-Sicherheits-API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die Workload-Sicherheits-API ermöglicht NetApp Kunden und unabhängigen Software-Anbietern (ISVs) die Integration der Workload-Sicherheit in andere Applikationen wie CMDB- oder andere Ticketsysteme.

Anforderungen für API-Zugriff:

* Ein API-Zugriffstoken-Modell wird verwendet, um den Zugriff zu gewähren.
* Das Management von API-Token wird von Workload Security-Benutzern mit der Administratorrolle durchgeführt.




== API-Dokumentation (Swagger)

Die neuesten API-Informationen finden Sie, indem Sie sich bei Workload Security anmelden und zu *Admin > API Access* navigieren. Klicken Sie auf den Link *API Documentation*. Die API-Dokumentation ist Swagger-basiert, die eine kurze Beschreibung und Nutzungsinformationen für die API bietet und es Ihnen ermöglicht, es auf Ihrem Mandanten auszuprobieren.


NOTE: Wenn Sie die Forensics Activity API aufrufen, verwenden Sie die API cloudSecure_forensics.activities.*v2*. Wenn Sie mehrere Aufrufe zu dieser API ausführen, stellen Sie sicher, dass die Aufrufe nacheinander und nicht parallel erfolgen. Mehrere parallele Aufrufe können dazu führen, dass die API-Zeit abgeht.



== API-Zugriffs-Tokens

Bevor Sie die Workload Security API verwenden, müssen Sie ein oder mehrere *API Access Token* erstellen. Access Tokens gewähren Leseberechtigungen. Sie können auch die Ablauffrist für jedes Access Token festlegen.

So erstellen Sie ein Access Token:

* Klicken Sie auf *Admin > API Access*
* Klicken Sie auf *+API Access Token*
* Geben Sie *Tokenname* Ein
* Geben Sie *Token Expiration* An



NOTE: Ihr Token kann nur während des Erstellungsvorgangs in die Zwischenablage kopiert und gespeichert werden. Token können nicht abgerufen werden, nachdem sie erstellt wurden. Daher wird dringend empfohlen, das Token zu kopieren und an einem sicheren Ort zu speichern. Sie werden aufgefordert, auf die Schaltfläche API-Zugriffstoken kopieren zu klicken, bevor Sie den Bildschirm zur Token-Erstellung schließen können.

Sie können Token deaktivieren, aktivieren und widerrufen. Deaktivierte Token können aktiviert werden.

Token gewähren allgemeinen Zugriff auf APIs aus Kundensicht, indem sie den Zugriff auf APIs im Rahmen ihres eigenen Mandanten verwalten.

Die Anwendung erhält ein Zugriffstoken, nachdem ein Benutzer den Zugriff erfolgreich authentifiziert und autorisiert hat, und übergibt das Access Token dann als Berechtigung, wenn es die Ziel-API anruft. Das übergebene Token informiert die API, dass der Inhaber des Tokens berechtigt ist, auf die API zuzugreifen und bestimmte Aktionen basierend auf dem Umfang auszuführen, den während der Autorisierung gewährt wurde.

Der HTTP-Header, in dem das Access Token übergeben wird, ist *X-CloudInsights-ApiKey:*

Verwenden Sie zum Abrufen von Lagerbeständen beispielsweise Folgendes:

 curl https://<Workload Security tenant>/rest/v1/cloudsecure/activities -H 'X-CloudInsights-ApiKey: <API_Access_Token>'
Dabei ist _<API_Access_Token>_ das Token, das Sie während der Erstellung des API-Zugriffsschlüssels gespeichert haben, und _<Workload Security Tenant>_ die Tenant-URL Ihrer Workload Security-Umgebung.

Detaillierte Informationen finden Sie im Link _API Documentation_ unter *Admin > API Access*.



== Skript zum Extrahieren von Daten über die API

Workload Security-Agenten enthalten ein Exportskript, um parallele Aufrufe an die v2-API zu ermöglichen, indem sie den angeforderten Zeitraum in kleinere Stapel aufteilen.

Das Skript befindet sich unter _/opt/NetApp/CloudSecure/Agent/Export-script_. Eine README-Datei im selben Verzeichnis enthält Anweisungen zur Verwendung.

Hier ist ein Beispielbefehl zum Aufrufen des Skripts:

[source]
----
python3 data-export.py --tenant_url <Workload Security tenant> --access_key %ACCESS_KEY% --path_filter "<dir path>" --user_name "<user>" --from_time "01-08-2024 00:00:00" --to_time "31-08-2024 23:59:59" --iteration_interval 12 --num_workers 3
----
Key Parameters: - `--iteration_interval 12`: Teilt den gewünschten Zeitbereich in Intervalle von 12 Stunden auf. - `--num_workers 3`: Holt diese Intervalle parallel mit 3 Threads.
