---
sidebar: sidebar 
permalink: concept_about_applications.html 
keywords: applications, asset, cost 
summary: Wenn Sie wissen, welche Anwendungen in der Umgebung Ihres Unternehmens verwendet werden, können Sie die Nutzung und Kosten Ihrer Anlagen besser im Auge behalten. 
---
= Nachverfolgen der Asset-Nutzung nach Anwendung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie wissen, welche Anwendungen in der Umgebung Ihres Unternehmens verwendet werden, können Sie die Nutzung und Kosten Ihrer Anlagen besser im Auge behalten.

Bevor Sie Daten zu den auf Ihrem Mandanten ausgeführten Anwendungen verfolgen können, müssen Sie diese Anwendungen zunächst definieren und sie den entsprechenden Assets zuordnen.  Sie können Anwendungen mit den folgenden Assets verknüpfen: Hosts, virtuelle Maschinen, Volumes, interne Volumes, Qtrees, Freigaben und Hypervisoren.

Dieses Thema bietet ein Beispiel für die Verfolgung der Nutzung virtueller Maschinen, die das Marketingteam für seine Exchange-E-Mails verwendet.

Sie können eine Tabelle ähnlich der folgenden erstellen, um die auf Ihrem Mandanten verwendeten Anwendungen zu identifizieren und die Gruppe oder Geschäftseinheit zu notieren, die die einzelnen Anwendungen verwendet.

[cols="5*"]
|===


| Mieter | Geschäftszweig | Geschäftseinheit | Projekt | Anwendungen 


| NetApp | Datenspeicherung | Rechtliches | Patente | Oracle Identity Manager, Oracle On Demand, PatentWiz 


| NetApp | Datenspeicherung | Marketing | Verkaufsveranstaltungen | Exchange, Oracle Shared DataBase, BlastOff-Eventplaner 
|===
Die Tabelle zeigt, dass das Marketingteam die Exchange-Anwendung verwendet.  Wir möchten die Auslastung ihrer virtuellen Maschinen für Exchange verfolgen, damit wir vorhersagen können, wann wir mehr Speicher hinzufügen müssen.  Wir können die Exchange-Anwendung mit allen virtuellen Maschinen von Marketing verknüpfen:

. Erstellen Sie eine Anwendung mit dem Namen _Exchange_
. Gehen Sie zu *Abfragen > +Neue Abfrage*, um eine neue Abfrage für virtuelle Maschinen zu erstellen (oder wählen Sie ggf. eine vorhandene VM-Abfrage aus).
+
Angenommen, alle VMs des Marketingteams haben einen Namen, der die Zeichenfolge „*mkt*“ enthält, erstellen Sie Ihre Abfrage, um den VM-Namen nach „mkt“ zu filtern.

. Wählen Sie die VMs aus.
. Verknüpfen Sie die VMs mit der _Exchange_-Anwendung mithilfe von *Massenaktionen > Anwendungen hinzufügen*.
. Wählen Sie die gewünschte Anwendung aus und klicken Sie auf *Speichern*.
. Wenn Sie fertig sind, *Speichern* Sie die Abfrage.

