= SVM-Ereignisratenprüfer (Leitfaden zur Agentendimensionierung)
:allow-uri-read: 


r--- Seitenleiste: Permalink zur Seitenleiste: concept_cs_event_rate_checker.html Zusammenfassung: Verwenden Sie den SVM Event Rate Checker, um die NFS/SMB-Ereignisraten zu messen und die optimale Agentengröße vor der Bereitstellung von Workload Security-Datensammlern zu bestimmen. Stichwörter: Ereignis, Prüfer, Rate, Dimensionierung, Cloud Secure ---



= SVM-Ereignisratenprüfer (Leitfaden zur Agentendimensionierung)

[role="lead"]
Mit dem Event Rate Checker wird die kombinierte NFS/SMB-Ereignisrate im SVM überprüft, bevor ein ONTAP SVM-Datensammler installiert wird, um zu sehen, wie viele SVMs eine Agentenmaschine überwachen kann.  Verwenden Sie den Event Rate Checker als Größenleitfaden zur Planung Ihrer Sicherheitsumgebung.

Ein Agent kann bis zu maximal 50 Datensammler unterstützen.



== Anforderungen:

* Cluster-IP
* Benutzername und Kennwort des Clusteradministrators



NOTE: Beim Ausführen dieses Skripts sollte kein ONTAP SVM Data Collector für die SVM ausgeführt werden, für die die Ereignisrate bestimmt wird.

Schritte:

. Installieren Sie den Agenten, indem Sie den Anweisungen in CloudSecure folgen.
. Sobald der Agent installiert ist, führen Sie das Skript _server_data_rate_checker.sh_ als Sudo-Benutzer aus:
+
 /opt/netapp/cloudsecure/agent/install/svm_event_rate_checker.sh
. Für dieses Skript muss _sshpass_ auf der Linux-Maschine installiert sein.  Es gibt zwei Möglichkeiten, es zu installieren:
+
.. Führen Sie den folgenden Befehl aus:
+
 linux_prompt> yum install sshpass
.. Wenn das nicht funktioniert, laden Sie _sshpass_ aus dem Internet auf die Linux-Maschine herunter und führen Sie den folgenden Befehl aus:
+
 linux_prompt> rpm -i sshpass


. Geben Sie die richtigen Werte ein, wenn Sie dazu aufgefordert werden.  Ein Beispiel finden Sie unten.
. Die Ausführung des Skripts dauert ungefähr 5 Minuten.
. Nach Abschluss des Laufs druckt das Skript die Ereignisrate vom SVM.  Sie können die Ereignisrate pro SVM in der Konsolenausgabe überprüfen:
+
 “Svm svm_rate is generating 100 events/sec”.


Jeder Ontap SVM-Datensammler kann mit einem einzelnen SVM verknüpft werden, was bedeutet, dass jeder Datensammler die Anzahl der Ereignisse empfangen kann, die ein einzelnes SVM generiert.

Beachten Sie Folgendes:

A) Verwenden Sie diese Tabelle als allgemeine Größenrichtlinie.  Sie können die Anzahl der Kerne und/oder den Speicher erhöhen, um die Anzahl der unterstützten Datensammler auf bis zu 50 Datensammler zu erhöhen:

|===


| Agent-Computerkonfiguration | Anzahl der SVM-Datensammler | Maximale Ereignisrate, die der Agent-Computer verarbeiten kann 


| 4 Kerne, 16 GB | 10 Datensammler | 20.000 Ereignisse/Sek. 


| 4 Kerne, 32 GB | 20 Datensammler | 20.000 Ereignisse/Sek. 
|===
B) Um Ihre Gesamtereignisse zu berechnen, addieren Sie die für alle SVMs für diesen Agenten generierten Ereignisse.

C) Wenn das Skript nicht während der Spitzenzeiten ausgeführt wird oder wenn der Spitzenverkehr schwer vorherzusagen ist, halten Sie einen Ereignisratenpuffer von 30 % ein.

B + C sollte kleiner als A sein, sonst schlägt die Überwachung durch die Agent-Maschine fehl.

Mit anderen Worten: Die Anzahl der Datensammler, die einer einzelnen Agentenmaschine hinzugefügt werden können, sollte der folgenden Formel entsprechen:

 Sum of all Event rate of all Data Source Collectors + Buffer Event rate of 30% < 20000 events/second
Siehe dielink:concept_cs_agent_requirements.html["Agentenanforderungen"] Seite für zusätzliche Voraussetzungen und Anforderungen.



== Beispiel

Nehmen wir an, wir haben drei SVMS, die Ereignisraten von 100, 200 bzw. 300 Ereignissen pro Sekunde generieren.

Wir wenden die Formel an:

....
 (100+200+300) + [(100+200+300)*30%] = 600+180 = 780events/sec
780 events/second is < 20000 events/second, so the 3 SVMs can be monitored via one agent box.
....
Die Konsolenausgabe ist auf der Agent-Maschine unter dem Dateinamen __fpolicy_stat_<SVM-Name>.log__ im aktuellen Arbeitsverzeichnis verfügbar.

Das Skript kann in den folgenden Fällen fehlerhafte Ergebnisse liefern:

* Es wurden falsche Anmeldeinformationen, IP-Adressen oder SVM-Namen angegeben.
* Eine bereits vorhandene fpolicy mit demselben Namen, derselben Sequenznummer usw. führt zu einem Fehler.
* Das Skript wird während der Ausführung abrupt gestoppt.


Ein Beispiel für die Ausführung eines Skripts wird unten angezeigt:

 [root@ci-cs-data agent]# /opt/netapp/cloudsecure/agent/install/svm_event_rate_checker.sh
....
Enter the cluster ip: 10.192.139.166
Enter the username to SSH: admin
Enter the password:
Getting event rate for NFS and SMB events.
Available SVMs in the Cluster
-----------------------------
QA_SVM
Stage_SVM
Qa-fas8020
Qa-fas8020-01
Qa-fas8020-02
audit_svm
svm_rate
vs_new
vs_new2
....
....
-----------------------------
Enter [1/5] SVM name to check (press enter to skip): svm_rate
Enter [2/5] SVM name to check (press enter to skip): audit_svm
Enter [3/5] SVM name to check (press enter to skip):
Enter [4/5] SVM name to check (press enter to skip):
Enter [5/5] SVM name to check (press enter to skip):
Running check for svm svm_rate...
Running check for svm audit_svm...
Waiting 5 minutes for stat collection
Stopping sample svm_rate_sample
Stopping sample audit_svm_sample
fpolicy stats of svm svm_rate is saved in fpolicy_stat_svm_rate.log
Svm svm_rate is generating 100 SMB events/sec and 100 NFS events/sec
Overall svm svm_rate is generating 200 events/sec
fpolicy stats of svm audit_svm is saved in fpolicy_stat_audit_svm.log
Svm audit_svm is generating 200 SMB events/sec and 100 NFS events/sec
Overall svm audit_svm is generating 300 events/sec
....
 [root@ci-cs-data agent]#


== Fehlerbehebung

|===


| Frage | Antwort 


| Wenn ich dieses Skript auf einer SVM ausführe, die bereits für Workload Security konfiguriert ist, verwendet es dann einfach die vorhandene fpolicy-Konfiguration auf der SVM oder richtet es eine temporäre ein und führt den Prozess aus? | Der Event Rate Checker kann auch für eine SVM, die bereits für Workload Security konfiguriert ist, einwandfrei ausgeführt werden.  Es sollte keine Auswirkungen geben. 


| Kann ich die Anzahl der SVMs erhöhen, auf denen das Skript ausgeführt werden kann? | Ja. Bearbeiten Sie einfach das Skript und ändern Sie die maximale Anzahl von SVMs von 5 auf eine beliebige Zahl. 


| Wenn ich die Anzahl der SVMs erhöhe, verlängert sich dann die Ausführungszeit des Skripts? | Nein. Das Skript wird maximal 5 Minuten lang ausgeführt, auch wenn die Anzahl der SVMs erhöht wird. 


| Kann ich die Anzahl der SVMs erhöhen, auf denen das Skript ausgeführt werden kann? | Ja. Sie müssen das Skript bearbeiten und die maximale Anzahl von SVMs von 5 auf eine beliebige Zahl ändern. 


| Wenn ich die Anzahl der SVMs erhöhe, verlängert sich dann die Ausführungszeit des Skripts? | Nein. Das Skript wird maximal 5 Minuten lang ausgeführt, auch wenn die Anzahl der SVMs erhöht wird. 


| Was passiert, wenn ich den Event Rate Checker mit einem vorhandenen Agenten ausführe? | Das Ausführen des Event Rate Checker für einen bereits vorhandenen Agenten kann zu einer Erhöhung der Latenz auf der SVM führen.  Diese Erhöhung ist vorübergehender Natur, während der Event Rate Checker ausgeführt wird. 
|===