---
sidebar: sidebar 
permalink: concept_about_applications.html 
keywords: applications, asset, cost 
summary: Wenn Sie sich über die Applikationen in der Umgebung Ihres Unternehmens informieren, können Sie die Nutzung und die Kosten Ihrer Ressourcen nachverfolgen. 
---
= Nachverfolgung der Asset-Nutzung nach Applikation
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie sich über die Applikationen in der Umgebung Ihres Unternehmens informieren, können Sie die Nutzung und die Kosten Ihrer Ressourcen nachverfolgen.

Bevor Sie die Daten verfolgen können, die mit den auf Ihrem Mandanten ausgeführten Anwendungen verknüpft sind, müssen Sie zunächst diese Anwendungen definieren und sie den entsprechenden Anlagen zuordnen. Applikationen können folgenden Assets zugewiesen werden: Hosts, virtuelle Maschinen, Volumes, interne Volumes, qtrees, Freigaben und Hypervisoren:

Dieses Thema enthält ein Beispiel für die Verfolgung der Verwendung virtueller Maschinen, die das Marketingteam für seine Exchange-E-Mail verwendet.

Möglicherweise möchten Sie eine Tabelle ähnlich der folgenden erstellen, um Applikationen zu identifizieren, die auf dem Mandanten verwendet werden, und um sich die Gruppe oder Geschäftseinheit, die die einzelnen Applikationen verwendet, notieren.

[cols="5*"]
|===


| Mandant | Geschäftsbereich | Geschäftsbereich | Projekt | Applikationen Unterstützt 


| NetApp | Datenspeicher | Legal | Patente | Oracle Identity Manager, Oracle On Demand, PatentWiz 


| NetApp | Datenspeicher | Marketing | Verkaufsveranstaltungen | Exchange, gemeinsam genutzte Oracle-Datenbank, BlastOff Event Planner 
|===
Diese Tabelle zeigt, dass das Marketing Team die Exchange-Applikation verwendet. Wir möchten die Auslastung ihrer Virtual Machines in Exchange nachverfolgen, damit wir vorhersagen können, wann wir mehr Storage hinzufügen müssen. Wir können die Exchange-Anwendung mit allen virtuellen Maschinen des Marketings verknüpfen:

. Erstellen Sie eine Anwendung mit dem Namen _Exchange_
. Gehen Sie zu *Abfragen > +Neue Abfrage*, um eine neue Abfrage für virtuelle Maschinen zu erstellen (oder wählen Sie ggf. eine vorhandene VM-Abfrage aus).
+
Wenn die VMs des Marketingteams alle einen Namen haben, der den String „*mkt*“ enthält, erstellen Sie Ihre Anfrage, um den VM-Namen für „mkt“ zu filtern.

. Wählen Sie die VMs aus.
. Verknüpfen Sie die VMs mit der Anwendung _Exchange_ unter Verwendung von *Massenaktionen > Anwendungen hinzufügen*.
. Wählen Sie die gewünschte Anwendung aus und klicken Sie auf *Speichern*.
. Wenn Sie fertig sind, *Speichern* die Abfrage.

