---
sidebar: sidebar 
permalink: cs_intro.html 
keywords: CloudSecure, Cloud Secure 
summary: Überblick 
---
= Informationen zur Speicher-Workload-Sicherheit
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights Storage Workload Security (früher Cloud Secure) hilft Ihnen, Ihre Daten mit verwertbaren Informationen zu Insider-Bedrohungen zu schützen.  Es bietet eine zentrale Sichtbarkeit und Kontrolle aller Unternehmensdatenzugriffe in Hybrid-Cloud-Umgebungen, um sicherzustellen, dass Sicherheits- und Compliance-Ziele erreicht werden.



== Sichtweite

Erhalten Sie zentrale Transparenz und Kontrolle über den Benutzerzugriff auf Ihre kritischen Unternehmensdaten, die vor Ort oder in der Cloud gespeichert sind.

Ersetzen Sie Tools und manuelle Prozesse, die keinen zeitnahen und genauen Einblick in den Datenzugriff und die Datenkontrolle bieten.  Workload Security funktioniert auf einzigartige Weise sowohl auf Cloud- als auch auf lokalen Speichersystemen und warnt Sie in Echtzeit vor böswilligem Benutzerverhalten.



== Schutz

Schützen Sie Unternehmensdaten durch fortschrittliches maschinelles Lernen und Anomalieerkennung vor Missbrauch durch böswillige oder kompromittierte Benutzer.

Warnt Sie bei abnormalen Datenzugriffen durch fortschrittliches maschinelles Lernen und Anomalieerkennung des Benutzerverhaltens.



== Einhaltung

Stellen Sie die Unternehmenskonformität sicher, indem Sie den Benutzerdatenzugriff auf Ihre kritischen Unternehmensdaten prüfen, die vor Ort oder in der Cloud gespeichert sind.
