---
sidebar: sidebar 
permalink: cs_intro.html 
keywords: CloudSecure, Cloud Secure 
summary: Schützen Sie Ihre Daten mit Storage Workload Securitys Funktionen zur Erkennung von Insiderbedrohungen, zentralisierter Transparenz in hybriden Umgebungen und fortschrittlichem maschinellem Lernen zur Anomalieerkennung und Compliance. 
---
= Informationen zur Speicher-Workload-Sicherheit
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Data Infrastructure Insights Storage Workload Security (ehemals Cloud Secure) schützt die Daten Ihres Unternehmens durch fortschrittliche Erkennung von Insiderbedrohungen und die Bereitstellung umsetzbarer Erkenntnisse. Zentrale Transparenz und Kontrolle über alle Datenzugriffe in hybriden Cloud-Umgebungen werden ermöglicht, während durch Echtzeitüberwachung und automatisierte Reaktionsfunktionen die Erreichung von Sicherheits- und Compliance-Zielen sichergestellt wird.



[[visibility]]
== Sichtweite

Erhalten Sie zentrale Transparenz und Kontrolle über den Benutzerzugriff auf Ihre kritischen Unternehmensdaten, die vor Ort oder in der Cloud gespeichert sind.

Ersetzen Sie Tools und manuelle Prozesse, die keinen zeitnahen und genauen Einblick in den Datenzugriff und die Datenkontrolle bieten.  Workload Security funktioniert auf einzigartige Weise sowohl auf Cloud- als auch auf lokalen Speichersystemen und warnt Sie in Echtzeit vor böswilligem Benutzerverhalten.



[[protection]]
== Schutz

Schützen Sie Unternehmensdaten durch fortschrittliches maschinelles Lernen und Anomalieerkennung vor Missbrauch durch böswillige oder kompromittierte Benutzer.

Warnt Sie bei abnormalen Datenzugriffen durch fortschrittliches maschinelles Lernen und Anomalieerkennung des Benutzerverhaltens.



[[compliance]]
== Einhaltung

Stellen Sie die Unternehmenskonformität sicher, indem Sie den Benutzerdatenzugriff auf Ihre kritischen Unternehmensdaten prüfen, die vor Ort oder in der Cloud gespeichert sind.
