---
sidebar: sidebar 
permalink: cs_notifications_email.html 
summary: Hinzufügen von E-Mail-Adressen für Benachrichtigungen zu Workload-Sicherheitswarnungen 
keywords: email, notifications, alerts, warnings, attacks 
---
= Konfigurieren von E-Mail-Benachrichtigungen für Warnungen, Warnungen und den Zustand des Agent/Data Source Collectors
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Um die Empfänger von Benachrichtigungen für die Workload-Sicherheit zu konfigurieren, klicken Sie auf *Admin > Benachrichtigungen* und geben Sie für jeden Empfänger eine E-Mail-Adresse in die entsprechenden Abschnitte ein.



== Potenzielle Angriffs- und Warnhinweise

Um Benachrichtigungen zu potenziellen Angriffen zu senden, geben Sie die E-Mail-Adressen der Empfänger im Abschnitt „ potenzielle Angriffswarnungen senden “ ein. Für jede Aktion der Warnmeldung werden E-Mail-Benachrichtigungen an die Benachrichtigungsliste gesendet.

Um _Warnhinweise zu senden, geben Sie die E-Mail-Adressen der Empfänger im Abschnitt „ Warnhinweise senden “ ein.



== Statusüberwachung von Agent und Data Collector

Sie können den Zustand von Agenten und Datenquellen über Benachrichtigungen überwachen.

Um Benachrichtigungen zu erhalten, wenn ein Agent oder Datenquellensammler nicht funktioniert, geben Sie die E-Mail-Adressen der Empfänger im Abschnitt „_Data Collection Health Alerts_“ ein.

Beachten Sie Folgendes:

* Zustandswarnmeldungen werden erst gesendet, nachdem der Agent/Sammler mindestens eine Stunde lang die Meldung beendet hat.
* Es wird nur eine E-Mail-Benachrichtigung an die vorgesehenen Empfänger in einem bestimmten Zeitraum von 24 Stunden gesendet, auch wenn der Agent oder der Datensammler länger getrennt ist.
* Bei einem Agent-Fehler wird eine Warnung gesendet (nicht eine pro Collector). Die E-Mail enthält eine Liste aller betroffenen SVMs.
* Active Directory-Sammlung Fehler wird als Warnung gemeldet; es hat keine Auswirkungen auf Ransomware-Erkennung.
* Die Setup-Liste „erste Schritte“ enthält jetzt eine neue Phase „_E-Mail-Benachrichtigungen konfigurieren_“.




== Empfangen Von Agent- Und Data Collector-Upgrade-Benachrichtigungen

* Geben Sie in „Data Collection Health Alerts“ die E-Mail-ID(s) ein.
* Das Kontrollkästchen „Upgrade-Benachrichtigungen aktivieren“ wird aktiviert.
* Die E-Mail-Benachrichtigungen für Agent- und Data Collector-Upgrades werden einen Tag vor dem geplanten Upgrade an die E-Mail-IDs gesendet.




== Fehlerbehebung

|===
| *Problem:* | *Teste das:* 


| E-Mail-IDs sind in den „Data Collector Health Alerts“ vorhanden, ich erhalte jedoch keine Benachrichtigungen. | Benachrichtigungs-E-Mails werden von der NetApp-Data-Infrastructure-Insights-Domain gesendet, d. h. von _accounts@service.cloudinsights.NetApp.com_. Einige Unternehmen blockieren eingehende E-Mails, wenn sie von einer externen Domäne stammen. Stellen Sie sicher, dass externe Benachrichtigungen aus NetApp-Dateninfrastrukturdomänen auf die Whitelist gesetzt sind. 
|===