---
sidebar: sidebar 
permalink: cs_notifications_email.html 
summary: Konfigurieren Sie E-Mail-Benachrichtigungen, um Warnungen vor potenziellen Angriffen, Sicherheitswarnungen und den Status des Agenten/Datensammlers in Echtzeit zu erhalten. 
keywords: email, notifications, alerts, warnings, attacks 
---
= Konfigurieren von E-Mail-Benachrichtigungen für Alarme, Warnungen und den Zustand von Agenten/Datenquellen-Sammlern
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
E-Mail-Benachrichtigungen ermöglichen es Ihnen, über potenzielle Angriffe, Sicherheitswarnungen und Probleme mit der Infrastruktur auf dem Laufenden zu bleiben, sobald diese auftreten. Konfigurieren Sie die E-Mail-Adressen der Empfänger unter Admin > Benachrichtigungen, um Echtzeit-Benachrichtigungen zu erhalten, die auf die jeweiligen Verantwortlichkeiten der Empfänger zugeschnitten sind.



== Alarme und Warnungen vor potenziellen Angriffen

Um Warnmeldungen zu _potenziellen Angriffen_ zu senden, geben Sie die E-Mail-Adressen der Empfänger im Abschnitt _Warnmeldungen zu potenziellen Angriffen senden_ ein.  Für jede Aktion im Zusammenhang mit der Warnung werden E-Mail-Benachrichtigungen an die Empfängerliste der Warnung gesendet.

Um _Warnbenachrichtigungen_ zu senden, geben Sie die E-Mail-Adressen der Empfänger im Abschnitt _Warnmeldungen senden_ ein.



== Integritätsüberwachung für Agenten und Datensammler

Sie können den Zustand von Agenten und Datenquellen durch Benachrichtigungen überwachen.

Um Benachrichtigungen zu erhalten, falls ein Agent oder Datenquellensammler nicht funktioniert, geben Sie die E-Mail-Adressen der Empfänger im Abschnitt „Warnungen zum Zustand der Datensammlung“ ein.

Beachten Sie Folgendes:

* Gesundheitswarnungen werden erst gesendet, wenn der Agent/Sammler mindestens eine Stunde lang keine Berichte mehr sendet.
* Innerhalb eines Zeitraums von 24 Stunden wird nur eine E-Mail-Benachrichtigung an die vorgesehenen Empfänger gesendet, selbst wenn die Verbindung zum Agenten oder Datensammler für einen längeren Zeitraum unterbrochen ist.
* Im Falle eines Agentenfehlers wird eine Warnung gesendet (nicht eine pro Collector).  Die E-Mail enthält eine Liste aller betroffenen SVMs.
* Ein Fehler bei der Active Directory-Datenerfassung wird als Warnung gemeldet; er hat keinen Einfluss auf die Bedrohungserkennung.
* Die Setup-Liste „Erste Schritte“ enthält jetzt eine neue Phase „E-Mail-Benachrichtigungen konfigurieren“.




== Empfangen von Agent- und Data Collector-Upgrade-Benachrichtigungen

* Geben Sie die E-Mail-ID(s) in den „Health Alerts zur Datenerfassung“ ein.
* Das Kontrollkästchen „Upgrade-Benachrichtigungen aktivieren“ wird aktiviert.
* E-Mail-Benachrichtigungen zu Agent- und Data Collector-Upgrades werden einen Tag vor dem geplanten Upgrade an die E-Mail-IDs gesendet.




== Fehlerbehebung

|===
| *Problem:* | *Versuchen Sie Folgendes:* 


| In den „Data Collector Health Alerts“ sind E-Mail-IDs vorhanden, ich erhalte jedoch keine Benachrichtigungen. | Benachrichtigungs-E-Mails werden von der NetApp Data Infrastructure Insights Domäne gesendet, d. h. von _accounts@service.cloudinsights.netapp.com_.  Einige Unternehmen blockieren eingehende E-Mails, wenn diese von einer externen Domäne stammen.  Stellen Sie sicher, dass externe Benachrichtigungen von NetApp Data Infrastructure Insights -Domänen auf die Whitelist gesetzt werden. 
|===