---
sidebar: sidebar 
permalink: forensic_alert_detail.html 
keywords: alert, Critical, Warning, Low, alert detail Synopsis, Time range, Start time, End time, user 
summary: Alarmdetails 
---
= Alarmdetails
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Wenn Sie auf die Zusammenfassung einer Warnung klicken, wird die Seite mit ausführlichen Informationen zum Benutzer und der von ihm ausgelösten Warnung geöffnet.



== Die Seite „Alarmdetails“ zeigt den Benutzer

Unter „Alarmdetails“ finden Sie Informationen zu dem auf der Seite „Alarme“ ausgewählten Alarm.

* Der Schweregrad der Warnung
* Der Benutzer, der den Alarm ausgelöst hat, und der Alarmtyp:
+
** Ungewöhnlicher Zugriff durch den Benutzer
** Anormaler Zugriff durch die Community
** Anormaler Zugriff durch Benutzer in der Community
** Der Benutzer ist vielen Communities beigetreten


* Datum und Uhrzeit der Erkennung der Warnung
* Die ergriffenen Maßnahmen
+
** Unter Quarantäne gestellt
** Sonstige
** Sonstige


* Der Status der Warnung
+
** Neu
** Im Gange
** Entlassen
** Gelöst


* Änderung der Aktivitätsrate des Benutzers
+
** Typische Aktivitäten pro Stunde
** Aktivitäten pro Stunde, als der Alarm ausgelöst wurde.
** Prozentsatz der Tarifänderung, die den Alarm verursacht hat.


* Ein Diagramm, das die durchschnittliche Aktivitätsrate im Verlauf und die Aktivitätsrate zeigt, die zur Warnung geführt hat.




=== Zugehöriger Benutzer

* Benutzername und Titel
* Abteilung
* E-Mail mit einem Link zur E-Mail-Adresse
* Manager
* Telefon
* Standort




=== Aktivität

Zeigt die Aktivität des Benutzers der letzten 7 Tage und den letzten Standort, von dem aus der Benutzer zugegriffen hat.

* Aktivitäten:
+
** Lesen
** Sonstige
** Erstellen


* Gesamtzahl der Warnungen in den letzten sieben Tagen.
* Gesamtzahl der Aktivitäten in den letzten 7 Tagen.


Klicken Sie auf *Aktivitätsdetails anzeigen*, um auf dielink:forensic_activity_history["Aktivitätsverlauf"] des untersuchten Benutzers.
