---
sidebar: sidebar 
permalink: forensic_user_overview.html 
keywords: Forensic, user, user, activity 
summary: forensische Benutzerdetails 
---
= Forensische Benutzerübersicht
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Informationen zu jedem Benutzer finden Sie in der Benutzerübersicht.  Verwenden Sie diese Ansichten, um Benutzermerkmale, zugehörige Entitäten und aktuelle Aktivitäten zu verstehen.



== Benutzerprofil

Zu den Benutzerprofilinformationen gehören Kontaktinformationen und Standort des Benutzers.  Das Profil enthält die folgenden Informationen:

* Name des Benutzers
* E-Mail-Adresse des Nutzers
* Benutzermanager
* Telefonkontakt für den Benutzer
* Standort des Benutzers




== Nutzerverhalten

Die Informationen zum Benutzerverhalten identifizieren die letzten Aktivitäten und Vorgänge, die der Benutzer durchgeführt hat.  Zu diesen Informationen gehören:

* Letzte Aktivität
+
** Letzter Zugriffsort
** Aktivitätsdiagramm
** Warnungen




* Operationen der letzten sieben Tage
+
** Anzahl der Operationen






== Aktualisierungsintervall

Die Benutzerliste wird alle 12 Stunden aktualisiert.



== Aufbewahrungsrichtlinie

Wenn die Benutzerliste nicht erneut aktualisiert wird, bleibt sie 13 Monate lang erhalten.  Nach 13 Monaten werden die Daten gelöscht.  Wenn Ihre Workload Security-Umgebung gelöscht wird, werden alle mit der Umgebung verknüpften Daten gelöscht.
