---
sidebar: sidebar 
permalink: insights_overview.html 
keywords: insight, greedy, degraded, impacted, impacting, impactful, impact, resources, consuming, workload, ttf, time to full, k8s, kubernetes, namespace 
summary: Mithilfe von Insights erhalten Sie Einblick in die Ressourcennutzung und Trends. 
---
= Einblicke
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Mithilfe von Insights können Sie beispielsweise die Ressourcennutzung und ihre Auswirkungen auf andere Ressourcen untersuchen oder die Zeit bis zur Fertigstellung analysieren.

Es stehen zahlreiche Einblicke zur Verfügung.  Navigieren Sie zu *Dashboards > Insights*, um einzutauchen. Sie können aktive Insights (aktuell auftretende Insights) auf der Hauptregisterkarte oder inaktive Insights auf der Registerkarte _Inaktive Insights_ anzeigen.  Inaktive Erkenntnisse sind Erkenntnisse, die zuvor aktiv waren, aber nicht mehr auftreten.



== Erkenntnistypen



=== Gemeinsam genutzte Ressourcen unter Stress

Workloads mit hoher Auswirkung können die Leistung anderer Workloads in einer gemeinsam genutzten Ressource beeinträchtigen.  Dadurch wird die gemeinsam genutzte Ressource belastet.  Data Infrastructure Insights bietet Tools, mit denen Sie die Ressourcensättigung und die Auswirkungen auf Ihren Mandanten untersuchen können.link:insights_shared_resources_under_stress.html["Weitere Informationen"]



=== Kubernetes-Namespaces haben nicht mehr genügend Speicherplatz

Die Einblicke in „Kubernetes-Namespaces, denen der Speicherplatz ausgeht“ geben Ihnen einen Überblick über die Workloads in Ihren Kubernetes-Namespaces, bei denen das Risiko besteht, dass ihnen der Speicherplatz ausgeht, und enthalten eine Schätzung der verbleibenden Tage, bis jeder Speicherplatz voll ist.link:insights_k8s_namespaces_running_out_of_space.html["Weitere Informationen"]



=== ONTAP Cold Storage zurückgewinnen

Der _Reclaim ONTAP Cold Storage_ Insight bietet Daten zur Kaltkapazität, zu potenziellen Kosten-/Stromeinsparungen und empfohlenen Aktionselementen für Volumes auf ONTAP Systemen.link:insights_reclaim_ontap_cold_storage.html["Weitere Informationen"]


NOTE: Dies ist eine _Vorschau_-Funktion und kann sich im Laufe der Zeit ändern, wenn Verbesserungen vorgenommen werden. link:/concept_preview_features.html["Mehr erfahren"] Informationen zu den Vorschaufunktionen von Data Infrastructure Insights .
