---
sidebar: sidebar 
permalink: pre-requisites_for_k8s_operator.html 
keywords: telegraf, installation, install, agent, telegraf agent, kubernetes, eks, operator, k8s 
summary: Data Infrastructure Insights unterstützt Telegraf als Agent für die Erfassung von Integrationsdaten auf Kubernetes. 
---
= Vor der Installation oder Aktualisierung des NetApp Kubernetes Monitoring Operator
:hardbreaks:
:allow-uri-read: 
:nofooter: 


[role="lead"]
Lesen Sie diese Informationen, bevor Sie daslink:task_config_telegraf_agent_k8s.html["Kubernetes-Überwachungsoperator"] .

|===
| Komponente | Erfordernis 


| Kubernetes-Version | Kubernetes v1.20 und höher. 


| Kubernetes-Distributionen | AWS Elastic Kubernetes Service (EKS) Azure Kubernetes Service (AKS) Google Kubernetes Engine (GKE) Red Hat OpenShift Rancher Kubernetes Engine (RKE) VMware Tanzu 


| Linux-Betriebssystem | Data Infrastructure Insights unterstützt keine Knoten, die mit Arm64-Architektur ausgeführt werden.  Netzwerküberwachung: Es muss Linux-Kernel Version 4.18.0 oder höher ausgeführt werden.  Photon OS wird nicht unterstützt. 


| Labels | Data Infrastructure Insights unterstützt die Überwachung von Kubernetes-Knoten, auf denen Linux ausgeführt wird, indem ein Kubernetes-Knotenselektor angegeben wird, der auf diesen Plattformen nach den folgenden Kubernetes-Labels sucht: Kubernetes v1.20 und höher: Kubernetes.io/os = Linux Rancher + cattle.io als Orchestrierungs-/Kubernetes-Plattform: cattle.io/os = Linux 


| Befehle | Die Befehle „curl“ und „kubectl“ müssen verfügbar sein. Für optimale Ergebnisse fügen Sie diese Befehle dem PATH hinzu. 


| Konnektivität | kubectl cli ist für die Kommunikation mit dem Ziel-K8s-Cluster konfiguriert und verfügt über eine Internetverbindung zu Ihrer Data Infrastructure Insights -Umgebung.  Wenn Sie sich während der Installation hinter einem Proxy befinden, folgen Sie den Anweisungen imlink:task_config_telegraf_agent_k8s.html#configuring-proxy-support["Konfigurieren der Proxy-Unterstützung"] Abschnitt der Operator-Installation.  Für eine genaue Prüfung und Datenberichterstattung synchronisieren Sie die Zeit auf dem Agent-Computer mithilfe des Network Time Protocol (NTP) oder Simple Network Time Protocol (SNTP). 


| Sonstige | Wenn Sie OpenShift 4.6 oder höher verwenden, müssen Sie die folgenden Schritte ausführen:link:task_config_telegraf_agent_k8s.html#openshift-instructions["OpenShift-Anweisungen"] zusätzlich zur Sicherstellung, dass diese Voraussetzungen erfüllt sind. 


| API-Token | Wenn Sie den Operator erneut bereitstellen (d. h. ihn aktualisieren oder ersetzen), müssen Sie kein neues API-Token erstellen. Sie können das vorherige Token wiederverwenden. 
|===


== Wichtige Hinweise vor dem Start

Wenn Sie mit einem<<configuring-proxy-support,Proxy>> , haben eine<<using-a-custom-or-private-docker-repository,benutzerdefiniertes Repository>> oder verwenden<<openshift-instructions,OpenShift>> , lesen Sie die folgenden Abschnitte sorgfältig durch.

Lesen Sie auch über<<Berechtigungen,Berechtigungen>> .



=== Konfigurieren der Proxy-Unterstützung

Es gibt zwei Stellen, an denen Sie einen Proxy auf Ihrem Mandanten verwenden können, um den NetApp Kubernetes Monitoring Operator zu installieren.  Dabei kann es sich um dasselbe oder um separate Proxy-Systeme handeln:

* Proxy, der während der Ausführung des Installationscode-Snippets (mit „curl“) benötigt wird, um das System, auf dem das Snippet ausgeführt wird, mit Ihrer Data Infrastructure Insights -Umgebung zu verbinden
* Proxy, der vom Ziel-Kubernetes-Cluster zur Kommunikation mit Ihrer Data Infrastructure Insights -Umgebung benötigt wird


Wenn Sie für eines oder beides einen Proxy verwenden, müssen Sie zur Installation des NetApp Kubernetes Operating Monitor zunächst sicherstellen, dass Ihr Proxy so konfiguriert ist, dass eine gute Kommunikation mit Ihrer Data Infrastructure Insights Umgebung möglich ist.  Beispielsweise müssen Sie von den Servern/VMs, von denen Sie den Operator installieren möchten, auf Data Infrastructure Insights zugreifen und Binärdateien von Data Infrastructure Insights herunterladen können.

Legen Sie für den Proxy, der zur Installation des NetApp Kubernetes Operating Monitor verwendet wird, vor der Installation des Operators die Umgebungsvariablen _http_proxy/https_proxy_ fest.  Für einige Proxy-Umgebungen müssen Sie möglicherweise auch die Umgebungsvariable _no_proxy_ festlegen.

Um die Variable(n) festzulegen, führen Sie *vor* der Installation des NetApp Kubernetes Monitoring Operator die folgenden Schritte auf Ihrem System aus:

. Legen Sie die Umgebungsvariable(n) _https_proxy_ und/oder _http_proxy_ für den aktuellen Benutzer fest:
+
.. Wenn der einzurichtende Proxy keine Authentifizierung (Benutzername/Passwort) hat, führen Sie den folgenden Befehl aus:
+
 export https_proxy=<proxy_server>:<proxy_port>
.. Wenn der einzurichtende Proxy über eine Authentifizierung (Benutzername/Passwort) verfügt, führen Sie diesen Befehl aus:
+
 export http_proxy=<proxy_username>:<proxy_password>@<proxy_server>:<proxy_port>




Damit der für Ihren Kubernetes-Cluster verwendete Proxy mit Ihrer Data Infrastructure Insights -Umgebung kommunizieren kann, installieren Sie nach dem Lesen aller dieser Anweisungen den NetApp Kubernetes Monitoring Operator.

Konfigurieren Sie den Proxy-Abschnitt der AgentConfiguration in operator-config.yaml, bevor Sie den NetApp Kubernetes Monitoring Operator bereitstellen.

[listing]
----
agent:
  ...
  proxy:
    server: <server for proxy>
    port: <port for proxy>
    username: <username for proxy>
    password: <password for proxy>

    # In the noproxy section, enter a comma-separated list of
    # IP addresses and/or resolvable hostnames that should bypass
    # the proxy
    noproxy: <comma separated list>

    isTelegrafProxyEnabled: true
    isFluentbitProxyEnabled: <true or false> # true if Events Log enabled
    isCollectorsProxyEnabled: <true or false> # true if Network Performance and Map enabled
    isAuProxyEnabled: <true or false> # true if AU enabled
  ...
...
----


=== Verwenden eines benutzerdefinierten oder privaten Docker-Repositorys

Standardmäßig ruft der NetApp Kubernetes Monitoring Operator Container-Images aus dem Data Infrastructure Insights -Repository ab.  Wenn Sie einen Kubernetes-Cluster als Ziel für die Überwachung verwenden und dieser Cluster so konfiguriert ist, dass er nur Container-Images aus einem benutzerdefinierten oder privaten Docker-Repository oder einer Container-Registrierung abruft, müssen Sie den Zugriff auf die vom NetApp Kubernetes Monitoring Operator benötigten Container konfigurieren.

Führen Sie das „Image Pull Snippet“ aus der Installationskachel des NetApp Monitoring Operator aus.  Mit diesem Befehl melden Sie sich beim Data Infrastructure Insights -Repository an, rufen alle Bildabhängigkeiten für den Operator ab und melden sich vom Data Infrastructure Insights -Repository ab.  Geben Sie bei der entsprechenden Aufforderung das bereitgestellte temporäre Repository-Passwort ein.  Dieser Befehl lädt alle vom Bediener verwendeten Bilder herunter, auch für optionale Funktionen.  Unten sehen Sie, für welche Funktionen diese Bilder verwendet werden.

Kernoperator-Funktionalität und Kubernetes-Überwachung

* NetApp-Überwachung
* Kube-RBAC-Proxy
* Kube-State-Metriken
* Telegraf
* Distroless-Root-Benutzer


Ereignisprotokoll

* fließendes Bit
* Kubernetes-Ereignis-Exporteur


Netzwerkleistung und Karte

* ci-net-observer


Übertragen Sie das Operator-Docker-Image gemäß Ihren Unternehmensrichtlinien in Ihr privates/lokales/Unternehmens-Docker-Repository.  Stellen Sie sicher, dass die Bild-Tags und Verzeichnispfade zu diesen Bildern in Ihrem Repository mit denen im Data Infrastructure Insights -Repository übereinstimmen.

Bearbeiten Sie die Bereitstellung des Überwachungsoperators in operator-deployment.yaml und ändern Sie alle Bildreferenzen, um Ihr privates Docker-Repository zu verwenden.

....
image: <docker repo of the enterprise/corp docker repo>/kube-rbac-proxy:<kube-rbac-proxy version>
image: <docker repo of the enterprise/corp docker repo>/netapp-monitoring:<version>
....
Bearbeiten Sie die AgentConfiguration in operator-config.yaml, um den neuen Speicherort des Docker-Repositorys widerzuspiegeln.  Erstellen Sie ein neues imagePullSecret für Ihr privates Repository. Weitere Informationen finden Sie unter _https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/_

[listing]
----
agent:
  ...
  # An optional docker registry where you want docker images to be pulled from as compared to CI's docker registry
  # Please see documentation for link:task_config_telegraf_agent_k8s.html#using-a-custom-or-private-docker-repository[using a custom or private docker repository].
  dockerRepo: your.docker.repo/long/path/to/test
  # Optional: A docker image pull secret that maybe needed for your private docker registry
  dockerImagePullSecret: docker-secret-name
----


=== OpenShift-Anweisungen

Wenn Sie OpenShift 4.6 oder höher verwenden, müssen Sie die AgentConfiguration in _operator-config.yaml_ bearbeiten, um die Einstellung _runPrivileged_ zu aktivieren:

....
# Set runPrivileged to true SELinux is enabled on your kubernetes nodes
runPrivileged: true
....
Openshift implementiert möglicherweise eine zusätzliche Sicherheitsebene, die den Zugriff auf einige Kubernetes-Komponenten blockieren kann.



=== Berechtigungen

Wenn der Cluster, den Sie überwachen, benutzerdefinierte Ressourcen enthält, die keine ClusterRole haben, dielink:https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles["Aggregate zum Anzeigen"] , müssen Sie dem Operator manuell Zugriff auf diese Ressourcen gewähren, um sie mit Ereignisprotokollen zu überwachen.

. Bearbeiten Sie _operator-additional-permissions.yaml_ vor der Installation oder bearbeiten Sie nach der Installation die Ressource _ClusterRole/<namespace>-additional-permissions_
. Erstellen Sie eine neue Regel für die gewünschten API-Gruppen und Ressourcen mit den Verben ["get", "watch", "list"].  Siehe \https://kubernetes.io/docs/reference/access-authn-authz/rbac/
. Wenden Sie Ihre Änderungen auf den Cluster an

