---
sidebar: sidebar 
permalink: reporting_overview.html 
summary: Vordefinierte und benutzerdefinierte Berichte zu Ihren Daten mit Data Infrastructure Insights. 
keywords: reporting, cognos, data warehouse, dwh 
---
= Übersicht über die Data Infrastructure Insights
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights Reporting ist ein Business Intelligence-Tool, mit dem Sie vordefinierte Berichte anzeigen oder benutzerdefinierte Berichte erstellen können.


NOTE: Die Berichtsfunktion ist in Data Infrastructure Insights verfügbarlink:concept_subscribing_to_cloud_insights.html["Premium Edition"] .  Die Verfügbarkeit der Berichtsfunktion unterliegt einer Mindestspeicherkapazitätsanforderung. link:https://www.netapp.com/forms/cloud-insights-contact-us/["Kontaktieren Sie Ihren NetApp Vertriebsmitarbeiter"] für weitere Informationen.

Mit Data Infrastructure Insights -Berichten können Sie die folgenden Aufgaben ausführen:

* Ausführen eines vordefinierten Berichts
* Erstellen eines benutzerdefinierten Berichts
* Passen Sie das Format und die Übermittlungsmethode eines Berichts an
* Planen Sie die automatische Ausführung von Berichten
* E-Mail-Berichte
* Verwenden Sie Farben, um Schwellenwerte für Daten darzustellen


Data Infrastructure Insights Reporting kann benutzerdefinierte Berichte für Bereiche wie Chargeback, Verbrauchsanalyse und Prognose erstellen und bei der Beantwortung von Fragen wie den folgenden helfen:

* Welchen Bestand habe ich?
* Wo ist mein Inventar?
* Wer nutzt unsere Vermögenswerte?
* Wie hoch ist die Rückbuchung für zugewiesenen Speicher für eine Geschäftseinheit?
* Wie lange dauert es, bis ich zusätzliche Speicherkapazität benötige?
* Sind die Geschäftseinheiten auf die richtigen Speicherebenen ausgerichtet?
* Wie ändert sich die Speicherzuweisung im Laufe eines Monats, Quartals oder Jahres?




== Zugriff auf Data Infrastructure Insights Reporting

Sie können auf die Data Infrastructure Insights -Berichterstellung zugreifen, indem Sie im Menü auf den Link *Berichte* klicken.

Sie werden zur Berichtsoberfläche weitergeleitet.  Data Infrastructure Insights verwendet IBM Cognos Analytics für seine Berichts-Engine.



== Was ist ETL?

Wenn Sie mit Reporting arbeiten, werden Sie die Begriffe „Data Warehouse“ und „ETL“ hören.  ETL steht für „Extract, Transform, and Load“.  Der ETL-Prozess ruft in Data Infrastructure Insights erfasste Daten ab und wandelt die Daten in ein Format um, das in der Berichterstattung verwendet werden kann.  „Data Warehouse“ bezieht sich auf die gesammelten Daten, die für die Berichterstattung zur Verfügung stehen.

Der ETL-Prozess umfasst diese einzelnen Prozesse:

* *Extrahieren*: Nimmt Daten von Data Infrastructure Insights.
* *Transformieren*: Wendet Geschäftslogikregeln oder -funktionen auf die Daten an, während sie aus Data Infrastructure Insights extrahiert werden.
* *Laden*: Speichert die transformierten Daten zur Verwendung im Reporting im Data Warehouse.

