---
sidebar: sidebar 
permalink: reporting_querying_database.html 
summary: Verwenden Sie Data Infrastructure Insights -APIs, um die Reporting-DB direkt abzufragen. 
keywords: reporting, cognos, data warehouse, dwh, API 
---
= Zugriff auf die Berichtsdatenbank über die API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die leistungsstarke API von Data Infrastructure Insights ermöglicht es Benutzern, die Data Infrastructure Insights Reporting-Datenbank direkt abzufragen, ohne die Cognos Reporting-Umgebung zu durchlaufen.


NOTE: Diese Dokumentation bezieht sich auf die Data Infrastructure Insights -Berichtsfunktion, die in der Data Infrastructure Insights Premium Edition verfügbar ist.



== Odata

Die Data Infrastructure Insights Reporting API folgt demlink:https://www.odata.org/["OData v4"] (Open Data Protocol)-Standard für die Abfrage der Reporting-Datenbank.  Weitere Informationen und weitere Informationen finden Sie unterlink:https://www.odata.org/getting-started/basic-tutorial/["dieses Tutorial"] auf OData.

Alle Anfragen beginnen mit der URL _\https://< Data Infrastructure Insights URL>/rest/v1/dwh-management/odata_



== Generieren eines API-Schlüssels

Lesen Sie mehr überlink:API_Overview.html["APIs für Data Infrastructure Insights"] .

Gehen Sie wie folgt vor, um einen API-Schlüssel zu generieren:

* Melden Sie sich bei Ihrer Data Infrastructure Insights Umgebung an und wählen Sie *Admin > API-Zugriff*.
* Klicken Sie auf „+ API-Zugriffstoken“.
* Geben Sie einen Namen und eine Beschreibung ein.
* Wählen Sie als Typ „Data Warehouse“ aus.
* Legen Sie die Berechtigungen auf Lesen/Schreiben fest.
* Legen Sie ein gewünschtes Ablaufdatum fest.
* Klicken Sie auf „Speichern“, kopieren Sie dann den Schlüssel und speichern Sie ihn an einem sicheren Ort.  Auf den vollständigen Schlüssel können Sie später nicht mehr zugreifen.


APIkeys sind gut für<<synchronous-or-asynchronous,_Sync_ oder _Async_>> .



== Direkte Abfrage von Tabellen

Mit dem vorhandenen API-Schlüssel sind nun direkte Abfragen der Reporting-Datenbank möglich.  Lange URLs können zu Anzeigezwecken auf \https://.../odata/ vereinfacht werden, anstatt auf die vollständige Version \https://< Data Infrastructure Insights URL>/rest/v1/dwh-management/odata/

Versuchen Sie es mit einfachen Abfragen wie

* \https://< URL der Data Infrastructure Insights >/rest/v1/dwh-management/odata/dwh_custom
* \https://< URL der Data Infrastructure Insights >/rest/v1/dwh-management/odata/dwh_inventory
* \https://< URL der Data Infrastructure Insights >/rest/v1/dwh-management/odata/dwh_inventory/storage
* \https://< URL der Data Infrastructure Insights >/rest/v1/dwh-management/odata/dwh_inventory/disk
* \https://.../odata/dwh_custom/custom_queries




== REST-API-Beispiele

Die URL für alle Aufrufe lautet _\https://< Data Infrastructure Insights URL>/rest/v1/dwh-management/odata_.

* GET /{schema}/** – Ruft Daten aus der Berichtsdatenbank ab.


Format: _\https://< Data Infrastructure Insights -URL>/rest/v1/dwh-management/odata/<schema_name>/<query>_

Beispiel:

 https://<domain>/rest/v1/dwh-management/odata/dwh_inventory/fabric?$count=true&$orderby=name
Ergebnis:

....
{
   "@odata.context": "$metadata#fabric",
   "@odata.count": 2,
   "value": [
       {
           "id": 851,
           "identifier": "10:00:50:EB:1A:40:3B:44",
           "wwn": "10:00:50:EB:1A:40:3B:44",
           "name": "10:00:50:EB:1A:40:3B:44",
           "vsanEnabled": "0",
           "vsanId": null,
           "zoningEnabled": "0",
           "url": "https://<domain>/web/#/assets/fabrics/941716"
       },
       {
           "id": 852,
           "identifier": "10:00:50:EB:1A:40:44:0C",
           "wwn": "10:00:50:EB:1A:40:44:0C",
           "name": "10:00:50:EB:1A:40:44:0C",
           "vsanEnabled": "0",
           "vsanId": null,
           "zoningEnabled": "0",
           "url": "https://<domain>/web/#/assets/fabrics/941836"
        }
    ]
}
....


== Hilfreiche Hinweise

Beachten Sie beim Arbeiten mit Reporting-API-Abfragen Folgendes.

* Die Abfragenutzlast muss eine gültige JSON-Zeichenfolge sein
* Die Abfragenutzlast muss in einer einzigen Zeile enthalten sein
* Doppelte Anführungszeichen müssen maskiert werden, d. h. \"
* Tabs werden als \t unterstützt
* Vermeiden Sie Kommentare
* Tabellennamen in Kleinbuchstaben werden unterstützt


Zusätzlich:

* 2 Header sind erforderlich:
+
** Name „X-CloudInsights-ApiKey“
** Attributwert „<apikey>“




Ihr API-Schlüssel ist spezifisch für Ihre Data Infrastructure Insights Umgebung.



== Synchron oder asynchron?

Standardmäßig wird ein API-Befehl im _synchronen_ Modus ausgeführt, d. h. Sie senden die Anfrage und die Antwort wird sofort zurückgegeben.  Manchmal kann die Ausführung einer Abfrage jedoch sehr lange dauern, was zu einer Zeitüberschreitung der Anforderung führen kann.  Um dies zu umgehen, können Sie eine Anfrage _asynchron_ ausführen.  Im asynchronen Modus gibt die Anfrage eine URL zurück, über die die Ausführung überwacht werden kann.  Die URL gibt das Ergebnis zurück, wenn es fertig ist.

Um eine Abfrage im asynchronen Modus auszuführen, fügen Sie den Header hinzu `*Prefer: respond-async*` auf die Anfrage.  Bei erfolgreicher Ausführung enthält die Antwort die folgenden Header:

....
Status Code: 202 (which means ACCEPTED)
preference-applied: respond-async
location: https://<Data Infrastructure Insights URL>/rest/v1/dwh-management/odata/dwh_custom/asyncStatus/<token>
....
Bei der Abfrage der Standort-URL werden dieselben Header zurückgegeben, wenn die Antwort noch nicht bereit ist, oder der Status 200, wenn die Antwort bereit ist.  Der Antwortinhalt ist vom Typ Text und enthält den HTTP-Status der ursprünglichen Abfrage und einige Metadaten, gefolgt von den Ergebnissen der ursprünglichen Abfrage.

....
HTTP/1.1 200 OK
 OData-Version: 4.0
 Content-Type: application/json;odata.metadata=minimal
 oDataResponseSizeCounted: true

 { <JSON_RESPONSE> }
....
Um eine Liste aller asynchronen Abfragen und deren Bereitschaft anzuzeigen, verwenden Sie den folgenden Befehl:

 GET https://<Data Infrastructure Insights URL>/rest/v1/dwh-management/odata/dwh_custom/asyncList
Die Antwort hat das folgende Format:

....
{
   "queries" : [
       {
           "Query": "https://<Data Infrastructure Insights URL>/rest/v1/dwh-management/odata/dwh_custom/heavy_left_join3?$count=true",
           "Location": "https://<Data Infrastructure Insights URL>/rest/v1/dwh-management/odata/dwh_custom/asyncStatus/<token>",
           "Finished": false
       }
   ]
}
....