---
sidebar: sidebar 
permalink: reporting_creating_custom_reports.html 
summary: 'Verwenden von Berichterstellungstools zum Erstellen benutzerdefinierter („Ad-hoc“) Berichte' 
keywords: reporting, cognos, data warehouse, dwh, ad-hoc, custom 
---
= Erstellen benutzerdefinierter Berichte
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Mit den Berichterstellungstools können Sie benutzerdefinierte Berichte erstellen.  Nachdem Sie Berichte erstellt haben, können Sie diese speichern und regelmäßig ausführen.  Die Ergebnisse der Berichte können automatisch per E-Mail an Sie selbst und andere gesendet werden.


NOTE: Die Berichtsfunktion ist in Data Infrastructure Insights verfügbarlink:concept_subscribing_to_cloud_insights.html["Premium Edition"] .

Die Beispiele in diesem Abschnitt zeigen den folgenden Prozess, der für alle Data Infrastructure Insights Reporting-Datenmodelle verwendet werden kann:

* Identifizieren einer Frage, die mit einem Bericht beantwortet werden soll
* Ermittlung der zur Unterstützung der Ergebnisse erforderlichen Daten
* Auswählen von Datenelementen für den Bericht


Bevor Sie Ihren benutzerdefinierten Bericht entwerfen, müssen Sie einige vorbereitende Aufgaben erledigen.  Wenn Sie diese nicht ausfüllen, können die Berichte ungenau oder unvollständig sein.

Wenn Sie beispielsweise den Geräteidentifizierungsprozess nicht abschließen, sind Ihre Kapazitätsberichte nicht genau.  Oder wenn Sie die Festlegung von Anmerkungen (wie Ebenen, Geschäftseinheiten und Rechenzentren) nicht abschließen, werden in Ihren benutzerdefinierten Berichten die Daten Ihrer Domäne möglicherweise nicht genau wiedergegeben oder für einige Datenpunkte wird „N/A“ angezeigt.

Bevor Sie Ihre Berichte entwerfen, führen Sie die folgenden Aufgaben aus:

* Konfigurieren Sie allelink:task_configure_data_collectors.html["Datensammler"] richtig.
* Geben Sie Anmerkungen (wie Ebenen, Rechenzentren und Geschäftseinheiten) zu Geräten und Ressourcen Ihres Mandanten ein.  Es ist von Vorteil, vor der Berichterstellung stabile Anmerkungen zu haben, da Data Infrastructure Insights Reporting historische Informationen sammelt.




== Berichterstellungsprozess

Der Prozess der Erstellung benutzerdefinierter (auch „Ad-hoc“-)Berichte umfasst mehrere Aufgaben:

* Planen Sie die Ergebnisse Ihres Berichts.
* Identifizieren Sie Daten, die Ihre Ergebnisse unterstützen.
* Wählen Sie das Datenmodell (z. B. Chargeback-Datenmodell, Inventar-Datenmodell usw.) aus, das die Daten enthält.
* Wählen Sie Datenelemente für den Bericht aus.
* Formatieren, sortieren und filtern Sie Berichtsergebnisse optional.




=== Planen der Ergebnisse Ihres benutzerdefinierten Berichts

Bevor Sie die Tools zur Berichterstellung öffnen, möchten Sie möglicherweise die Ergebnisse planen, die Sie mit dem Bericht erzielen möchten.  Mit Berichterstellungstools können Sie Berichte einfach erstellen und benötigen dafür möglicherweise nicht viel Planung. Es ist jedoch ratsam, sich beim Berichtsanforderer über die Berichtsanforderungen zu informieren.

* Identifizieren Sie die genaue Frage, die Sie beantworten möchten. Beispiel:
+
** Wie viel Kapazität habe ich noch?
** Wie hoch sind die Rückbuchungskosten pro Geschäftseinheit?
** Wie hoch ist die Kapazität pro Ebene, um sicherzustellen, dass die Geschäftseinheiten auf der richtigen Speicherebene ausgerichtet sind?
** Wie kann ich den Strom- und Kühlbedarf prognostizieren?  (Fügen Sie benutzerdefinierte Metadaten hinzu, indem Sie den Ressourcen Anmerkungen hinzufügen.)


* Identifizieren Sie die Datenelemente, die Sie zur Unterstützung der Antwort benötigen.
* Identifizieren Sie die Beziehungen zwischen Daten, die Sie in der Antwort sehen möchten.  Bauen Sie in Ihrer Frage keine unlogischen Zusammenhänge ein, wie zum Beispiel: „Ich möchte die Ports sehen, die mit der Kapazität in Zusammenhang stehen.“
* Identifizieren Sie alle für die Daten erforderlichen Berechnungen.
* Bestimmen Sie, welche Filtertypen erforderlich sind, um die Ergebnisse einzugrenzen.
* Bestimmen Sie, ob Sie aktuelle oder historische Daten verwenden müssen.
* Stellen Sie fest, ob Sie Zugriffsrechte für Berichte festlegen müssen, um die Daten auf bestimmte Zielgruppen zu beschränken.
* Legen Sie fest, wie der Bericht verteilt wird.  Soll es beispielsweise nach einem festgelegten Zeitplan per E-Mail versendet oder in den Ordnerbereich „Teaminhalte“ aufgenommen werden?
* Bestimmen Sie, wer den Bericht pflegen soll.  Dies kann sich auf die Komplexität des Designs auswirken.
* Erstellen Sie ein Modell des Berichts.




=== Tipps zum Gestalten von Berichten

Beim Entwerfen von Berichten können Ihnen einige Tipps hilfreich sein.

* Bestimmen Sie, ob Sie aktuelle oder historische Daten verwenden müssen.
+
Die meisten Berichte müssen nur über die neuesten in Data Infrastructure Insights verfügbaren Daten berichten.

* Data Infrastructure Insights Reporting bietet historische Informationen zu Kapazität und Leistung, jedoch nicht zum Inventar.
* Jeder sieht alle Daten. Möglicherweise müssen Sie die Daten jedoch auf bestimmte Zielgruppen beschränken.
+
Um die Informationen für verschiedene Benutzer zu segmentieren, können Sie Berichte erstellen und Zugriffsberechtigungen dafür festlegen.





== Berichtsdatenmodelle

Data Infrastructure Insights umfasst mehrere Datenmodelle, aus denen Sie entweder vordefinierte Berichte auswählen oder Ihren eigenen benutzerdefinierten Bericht erstellen können.

Jedes Datenmodell enthält einen einfachen Data Mart und einen erweiterten Data Mart:

* Der einfache Data Mart bietet schnellen Zugriff auf die am häufigsten verwendeten Datenelemente und enthält nur den letzten Snapshot der Data Warehouse-Daten; historische Daten sind nicht enthalten.
* Der erweiterte Data Mart bietet alle im einfachen Data Mart verfügbaren Werte und Details und umfasst den Zugriff auf historische Datenwerte.




=== Kapazitätsdatenmodelle

Ermöglicht Ihnen, Fragen zur Speicherkapazität, Dateisystemauslastung, internen Volumekapazität, Portkapazität, Qtree-Kapazität und Kapazität virtueller Maschinen (VM) zu beantworten.  Das Kapazitätsdatenmodell ist ein Container für mehrere Kapazitätsdatenmodelle.  Mit diesem Datenmodell können Sie Berichte erstellen, die verschiedene Arten von Fragen beantworten:



==== Datenmodell für Speicher und Speicherpoolkapazität

Ermöglicht Ihnen, Fragen zur Ressourcenplanung der Speicherkapazität zu beantworten, einschließlich Speicher und Speicherpools, und umfasst sowohl physische als auch virtuelle Speicherpooldaten.  Dieses einfache Datenmodell kann Ihnen dabei helfen, Fragen zur Kapazität auf der Etage und zur Kapazitätsnutzung von Speicherpools nach Ebene und Rechenzentrum im Zeitverlauf zu beantworten.  Wenn Sie mit der Kapazitätsberichterstattung noch nicht vertraut sind, sollten Sie mit diesem Datenmodell beginnen, da es sich um ein einfacheres, zielgerichteteres Datenmodell handelt.  Mithilfe dieses Datenmodells können Sie Fragen wie die folgenden beantworten:

* Wann wird voraussichtlich die Kapazitätsschwelle von 80 % meines physischen Speichers erreicht?
* Wie groß ist die physische Speicherkapazität eines Arrays für eine bestimmte Ebene?
* Wie hoch ist meine Speicherkapazität nach Hersteller und Familie sowie nach Rechenzentrum?
* Wie ist der Trend zur Speicherauslastung eines Arrays für alle Ebenen?
* Welches sind meine Top 10 Speichersysteme mit der höchsten Auslastung?
* Wie ist der Trend zur Speicherauslastung der Speicherpools?
* Wie viel Kapazität ist bereits vergeben?
* Welche Kapazität steht zur Zuteilung zur Verfügung?




==== Datenmodell zur Dateisystemnutzung

Dieses Datenmodell bietet Einblick in die Kapazitätsauslastung durch Hosts auf Dateisystemebene.  Administratoren können die zugewiesene und verwendete Kapazität pro Dateisystem ermitteln, den Typ des Dateisystems bestimmen und Trendstatistiken nach Dateisystemtyp identifizieren.  Mit diesem Datenmodell können Sie folgende Fragen beantworten:

* Wie groß ist das Dateisystem?
* Wo werden die Daten gespeichert und wie wird darauf zugegriffen, beispielsweise lokal oder SAN?
* Was sind die historischen Trends bei der Dateisystemkapazität?  Welchen zukünftigen Bedarf können wir auf dieser Grundlage voraussehen?




==== Datenmodell für die interne Volumekapazität

Ermöglicht Ihnen, Fragen zur genutzten Kapazität des internen Volumes, zur zugewiesenen Kapazität und zur Kapazitätsnutzung im Zeitverlauf zu beantworten:

* Welche internen Volumes haben eine Auslastung, die über einem vordefinierten Schwellenwert liegt?
* Welche internen Volumina laufen aufgrund eines Trends Gefahr, ihre Kapazitäten zu erreichen?  8 Wie hoch ist die genutzte Kapazität im Vergleich zur zugewiesenen Kapazität auf unseren internen Datenträgern?




==== Datenmodell für die Portkapazität

Ermöglicht Ihnen, Fragen zur Switch-Port-Konnektivität, zum Port-Status und zur Port-Geschwindigkeit im Zeitverlauf zu beantworten.  Sie können Fragen wie die folgenden beantworten, um die Anschaffung neuer Switches zu planen: Wie kann ich eine Port-Verbrauchsprognose erstellen, die die Ressourcenverfügbarkeit (Portverfügbarkeit) vorhersagt (je nach Rechenzentrum, Switch-Anbieter und Portgeschwindigkeit)?

* Welche Ports werden voraussichtlich nicht mehr über ausreichende Kapazitäten verfügen, was die Datengeschwindigkeit, das Rechenzentrum, den Anbieter und die Anzahl der Host- und Speicherports betrifft?
* Wie entwickeln sich die Kapazitäten der Switch-Ports im Laufe der Zeit?
* Wie hoch sind die Portgeschwindigkeiten?
* Welche Art von Portkapazität wird benötigt und welcher Organisation steht ein bestimmter Porttyp oder Anbieter bald nicht mehr zur Verfügung?
* Wann ist der optimale Zeitpunkt, diese Kapazität zu erwerben und bereitzustellen?




==== Qtree-Kapazitätsdatenmodell

Ermöglicht Ihnen, die Qtree-Auslastung (mit Daten wie genutzte Kapazität im Vergleich zur zugewiesenen Kapazität) im Zeitverlauf zu verfolgen.  Sie können die Informationen nach verschiedenen Dimensionen anzeigen, beispielsweise nach Geschäftseinheit, Anwendung, Ebene und Servicelevel.  Mit diesem Datenmodell können Sie folgende Fragen beantworten:

* Wie hoch ist die genutzte Kapazität für Qtrees im Vergleich zu den pro Anwendung oder Geschäftseinheit festgelegten Grenzwerten?
* Wie entwickeln sich unsere genutzten und freien Kapazitäten, damit wir eine Kapazitätsplanung durchführen können?
* Welche Geschäftseinheiten nutzen die größte Kapazität?
* Welche Anwendungen verbrauchen die meiste Kapazität?




==== VM-Kapazitätsdatenmodell

Ermöglicht Ihnen, Berichte über Ihre virtuelle Umgebung und deren Kapazitätsauslastung zu erstellen.  Mit diesem Datenmodell können Sie über Änderungen der Kapazitätsnutzung im Zeitverlauf für VMs und Datenspeicher berichten.  Das Datenmodell bietet auch Thin Provisioning- und Chargeback-Daten für virtuelle Maschinen.

* Wie kann ich die Kapazitätsrückbelastung basierend auf der für VMs und Datenspeicher bereitgestellten Kapazität ermitteln?
* Welche Kapazität wird von VMs nicht genutzt und welcher ungenutzte Anteil ist frei, verwaist oder anderweitig?
* Was müssen wir aufgrund der Konsumtrends kaufen?
* Welche Einsparungen bei der Speichereffizienz erziele ich durch den Einsatz von Storage Thin Provisioning- und Deduplizierungstechnologien?


Kapazitäten im VM-Kapazitätsdatenmodell werden von virtuellen Datenträgern (VMDKs) übernommen.  Dies bedeutet, dass die bereitgestellte Größe einer VM unter Verwendung des VM-Kapazitätsdatenmodells der Größe ihrer virtuellen Datenträger entspricht.  Dies unterscheidet sich von der bereitgestellten Kapazität in der Ansicht „Virtuelle Maschinen“ in Data Infrastructure Insights, die die bereitgestellte Größe für die VM selbst anzeigt.



==== Datenmodell „Volume Capacity“

Ermöglicht Ihnen, alle Aspekte der Volumes auf Ihrem Mandanten zu analysieren und Daten nach Anbieter, Modell, Ebene, Servicelevel und Rechenzentrum zu organisieren.

Sie können die Kapazität im Zusammenhang mit verwaisten Volumes, ungenutzten Volumes und Schutzvolumes (für die Replikation verwendet) anzeigen.  Sie können auch verschiedene Volume-Technologien (iSCSI oder FC) sehen und virtuelle Volumes mit nicht-virtuellen Volumes hinsichtlich Array-Virtualisierungsproblemen vergleichen.

Mit diesem Datenmodell können Sie Fragen wie die folgenden beantworten:

* Welche Volumes haben eine Auslastung, die über einem vordefinierten Schwellenwert liegt?
* Wie ist der Trend in meinem Rechenzentrum hinsichtlich der Kapazität verwaister Datenträger?
* Wie viel meiner Rechenzentrumskapazität ist virtualisiert oder Thin Provisioning-basiert?
* Wie viel meiner Rechenzentrumskapazität muss für die Replikation reserviert werden?




=== Chargeback-Datenmodell

Ermöglicht Ihnen, Fragen zur verwendeten Kapazität und zur zugewiesenen Kapazität von Speicherressourcen (Volumes, interne Volumes und Qtrees) zu beantworten.  Dieses Datenmodell bietet Informationen zur Speicherkapazitätsrückbelastung und Verantwortlichkeit nach Hosts, Anwendungen und Geschäftseinheiten und umfasst sowohl aktuelle als auch historische Daten.  Berichtsdaten können nach Servicelevel und Speicherebene kategorisiert werden.

Sie können dieses Datenmodell verwenden, um Rückbuchungsberichte zu erstellen, indem Sie die von einer Geschäftseinheit genutzte Kapazität ermitteln.  Mit diesem Datenmodell können Sie einheitliche Berichte für mehrere Protokolle erstellen (einschließlich NAS, SAN, FC und iSCSI).

* Bei Speichern ohne interne Volumes zeigen Chargeback-Berichte die Rückbuchung nach Volumes an.
* Für Speicher mit internen Volumes:
+
** Wenn Geschäftseinheiten Volumen zugewiesen sind, zeigen Rückbuchungsberichte die Rückbuchung nach Volumen an.
** Wenn Geschäftseinheiten nicht Volumes, sondern Qtrees zugewiesen sind, zeigen Chargeback-Berichte Chargebacks nach Qtrees an.
** Wenn Geschäftseinheiten keinen Volumes und keinen Qtrees zugewiesen sind, zeigen Chargeback-Berichte das interne Volume an.
** Die Entscheidung, ob Chargeback nach Volume, Qtree oder internem Volume angezeigt wird, wird für jedes interne Volume einzeln getroffen. Daher ist es möglich, dass verschiedene interne Volumes im selben Speicherpool Chargebacks auf unterschiedlichen Ebenen anzeigen.




Kapazitätsfakten werden nach einem Standardzeitintervall gelöscht.  Einzelheiten finden Sie unter Data Warehouse-Prozesse.

Berichte, die das Chargeback-Datenmodell verwenden, zeigen möglicherweise andere Werte an als Berichte, die das Speicherkapazitäts-Datenmodell verwenden.

* Bei Speicher-Arrays, die keine NetApp Speichersysteme sind, sind die Daten aus beiden Datenmodellen identisch.
* Bei NetApp und Celerra-Speichersystemen basiert das Chargeback-Datenmodell auf einer einzelnen Ebene (aus Volumes, internen Volumes oder Qtrees) zur Berechnung der Gebühren, während das Storage Capacity-Datenmodell auf mehreren Ebenen (aus Volumes und internen Volumes) zur Berechnung der Gebühren basiert.




=== Inventardatenmodell

Ermöglicht Ihnen, Fragen zu Inventarressourcen zu beantworten, darunter Hosts, Speichersysteme, Switches, Festplatten, Bänder, Qtrees, Kontingente, virtuelle Maschinen und Server sowie generische Geräte.  Das Inventory-Datenmodell umfasst mehrere Submarts, mit denen Sie Informationen zu Replikationen, FC-Pfaden, iSCSI-Pfaden, NFS-Pfaden und Verstößen anzeigen können.  Das Inventardatenmodell enthält keine historischen Daten.  Fragen, die Sie mit diesen Daten beantworten können

* Welche Vermögenswerte habe ich und wo sind sie?
* Wer nutzt die Vermögenswerte?
* Welche Arten von Geräten habe ich und was sind die Komponenten dieser Geräte?
* Wie viele Hosts pro Betriebssystem habe ich und wie viele Ports sind auf diesen Hosts vorhanden?
* Welche Speicher-Arrays pro Anbieter sind in jedem Rechenzentrum vorhanden?
* Wie viele Switches pro Anbieter habe ich in jedem Rechenzentrum?
* Wie viele Ports sind nicht lizenziert?
* Welche Bänder von welchem Anbieter verwenden wir und wie viele Ports sind auf jedem Band vorhanden? Werden alle generischen Geräte identifiziert, bevor wir mit der Arbeit an den Berichten beginnen?
* Wie lauten die Pfade zwischen Hosts und Speichervolumes oder Bändern?
* Welche Pfade gibt es zwischen generischen Geräten und Speichervolumes oder Bändern?
* Wie viele Verstöße jedes Typs habe ich pro Rechenzentrum?
* Was sind für jedes replizierte Volume die Quell- und Zielvolumes?
* Gibt es Firmware-Inkompatibilitäten oder nicht übereinstimmende Portgeschwindigkeiten zwischen Fibre Channel-Host-HBAs und Switches?




=== Leistungsdatenmodell

Ermöglicht Ihnen, Fragen zur Leistung von Volumes, Anwendungsvolumes, internen Volumes, Switches, Anwendungen, VMs, VMDKs, ESX im Vergleich zu VM, Hosts und Anwendungsknoten zu beantworten.  Viele davon melden stündliche Daten, tägliche Daten oder beides.  Mithilfe dieses Datenmodells können Sie Berichte erstellen, die verschiedene Arten von Fragen zum Leistungsmanagement beantworten:

* Welche Volumes oder internen Volumes wurden während eines bestimmten Zeitraums nicht verwendet oder nicht aufgerufen?
* Können wir eine mögliche Fehlkonfiguration des Speichers für eine Anwendung (unbenutzt) genau bestimmen?
* Wie war das allgemeine Zugriffsverhaltensmuster für eine Anwendung?
* Werden die abgestuften Volumes einer bestimmten Anwendung entsprechend zugewiesen?
* Könnten wir für eine derzeit laufende Anwendung günstigeren Speicher verwenden, ohne dass dies Auswirkungen auf die Anwendungsleistung hat?
* Welche Anwendungen führen zu mehr Zugriffen auf den aktuell konfigurierten Speicher?


Wenn Sie die Switch-Leistungstabellen verwenden, können Sie die folgenden Informationen erhalten:

* Ist mein Host-Verkehr über verbundene Ports ausgeglichen?
* Welche Switches oder Ports weisen eine hohe Fehleranzahl auf?
* Welche Switches werden basierend auf der Portleistung am häufigsten verwendet?
* Welche Switches werden auf Grundlage der Portleistung nicht ausreichend genutzt?
* Wie hoch ist der Trenddurchsatz des Hosts basierend auf der Portleistung?
* Wie hoch war die Leistungsauslastung für die letzten X Tage für einen bestimmten Host, ein bestimmtes Speichersystem, ein bestimmtes Band oder einen bestimmten Switch?
* Welche Geräte erzeugen Verkehr auf einem bestimmten Switch (z. B. welche Geräte sind für die Nutzung eines stark ausgelasteten Switches verantwortlich)?
* Wie hoch ist der Durchsatz für eine bestimmte Geschäftseinheit in unserer Umgebung?


Wenn Sie die Festplattenleistungstabellen verwenden, können Sie die folgenden Informationen erhalten:

* Wie hoch ist der Durchsatz für einen bestimmten Speicherpool basierend auf den Daten zur Festplattenleistung?
* Welcher Speicherpool wird am häufigsten genutzt?
* Wie hoch ist die durchschnittliche Festplattenauslastung für einen bestimmten Speicher?
* Wie ist der Nutzungstrend für ein Speichersystem oder einen Speicherpool basierend auf den Daten zur Festplattenleistung?
* Wie ist die Entwicklung der Datenträgernutzung für einen bestimmten Speicherpool?


Wenn Sie VM- und VMDK-Leistungstabellen verwenden, können Sie die folgenden Informationen erhalten:

* Erbringt meine virtuelle Umgebung die optimale Leistung?
* Welche VMDKs melden die höchsten Arbeitslasten?
* Wie kann ich die von VMDs, die verschiedenen Datenspeichern zugeordnet sind, gemeldete Leistung nutzen, um Entscheidungen über die Neuklassifizierung zu treffen?


Das Leistungsdatenmodell enthält Informationen, die Ihnen dabei helfen, die Eignung von Ebenen, Speicherfehlkonfigurationen für Anwendungen und die letzten Zugriffszeiten von Volumes und internen Volumes zu bestimmen.  Dieses Datenmodell stellt Daten wie Antwortzeiten, IOPs, Durchsatz, Anzahl ausstehender Schreibvorgänge und Zugriffsstatus bereit.



=== Datenmodell zur Speichereffizienz

Ermöglicht Ihnen, den Speichereffizienzwert und das Speicherpotenzial im Laufe der Zeit zu verfolgen.  In diesem Datenmodell werden nicht nur Messungen der bereitgestellten Kapazität gespeichert, sondern auch die Menge, die verwendet oder verbraucht wird (die physikalische Messung).  Wenn beispielsweise Thin Provisioning aktiviert ist, zeigt Data Infrastructure Insights an, wie viel Kapazität vom Gerät genutzt wird.  Sie können dieses Modell auch verwenden, um die Effizienz bei aktivierter Deduplizierung zu bestimmen.  Mithilfe des Datamarts zur Speichereffizienz können Sie verschiedene Fragen beantworten:

* Wie hoch sind unsere Einsparungen bei der Speichereffizienz durch die Implementierung von Thin Provisioning- und Deduplizierungstechnologien?
* Wie hoch sind die Speichereinsparungen in den Rechenzentren?
* Wann müssen wir auf der Grundlage historischer Kapazitätstrends zusätzlichen Speicher kaufen?
* Welche Kapazitätssteigerung würde es geben, wenn wir Technologien wie Thin Provisioning und Deduplizierung aktivieren würden?
* Bin ich jetzt hinsichtlich der Speicherkapazität gefährdet?




=== Fakten- und Dimensionstabellen des Datenmodells

Jedes Datenmodell enthält sowohl Fakten- als auch Dimensionstabellen.

* Faktentabellen: Enthalten gemessene Daten, beispielsweise Menge, Roh- und Nutzkapazität.  Enthalten Fremdschlüssel zu Dimensionstabellen.
* Dimensionstabellen: Enthalten beschreibende Informationen zu Fakten, beispielsweise Rechenzentren und Geschäftseinheiten.  Eine Dimension ist eine Struktur, die häufig aus Hierarchien besteht und Daten kategorisiert.  Dimensionsattribute helfen bei der Beschreibung der Dimensionswerte.


Mithilfe unterschiedlicher oder mehrerer Dimensionsattribute (die in den Berichten als Spalten angezeigt werden) erstellen Sie Berichte, die auf Daten für jede im Datenmodell beschriebene Dimension zugreifen.



=== In Datenmodellelementen verwendete Farben

Die Farben der Datenmodellelemente haben unterschiedliche Bedeutungen.

* Gelbe Assets: Stellen Messungen dar.
* Nicht gelbe Vermögenswerte: Stellen Attribute dar.  Diese Werte werden nicht aggregiert.




=== Verwenden mehrerer Datenmodelle in einem Bericht

Normalerweise verwenden Sie ein Datenmodell pro Bericht.  Sie können jedoch einen Bericht schreiben, der Daten aus mehreren Datenmodellen kombiniert.

Um einen Bericht zu schreiben, der Daten aus mehreren Datenmodellen kombiniert, wählen Sie eines der Datenmodelle als Basis aus und schreiben Sie dann SQL-Abfragen, um auf die Daten aus den zusätzlichen Data Marts zuzugreifen.  Mit der SQL-Join-Funktion können Sie die Daten aus den verschiedenen Abfragen in einer einzigen Abfrage kombinieren, die Sie zum Schreiben des Berichts verwenden können.

Angenommen, Sie möchten die aktuelle Kapazität für jedes Speicherarray und benutzerdefinierte Anmerkungen zu den Arrays erfassen.  Sie könnten den Bericht mithilfe des Datenmodells „Speicherkapazität“ erstellen.  Sie könnten die Elemente aus den Tabellen „Aktuelle Kapazität“ und „Dimension“ verwenden und eine separate SQL-Abfrage hinzufügen, um auf die Anmerkungsinformationen im Inventardatenmodell zuzugreifen.  Schließlich können Sie die Daten kombinieren, indem Sie die Inventarspeicherdaten mithilfe des Speichernamens und der Verknüpfungskriterien mit der Speicherdimensionstabelle verknüpfen.
