---
sidebar: sidebar 
permalink: security_information_and_region.html 
summary: Data Infrastructure Insights befolgt während des gesamten Release-Lebenszyklus bewährte Sicherheitspraktiken. 
keywords: security, risk, protection 
---
= Informationen und Region
:hardbreaks:
:allow-uri-read: 


[role="lead"]
NetApp nimmt die Sicherheit von Kundeninformationen sehr ernst.  Hier erfahren Sie, wie und wo Data Infrastructure Insights Ihre Informationen speichert.



== Welche Informationen speichert Data Infrastructure Insights ?

Data Infrastructure Insights speichert die folgenden Informationen:

* Leistungsdaten
+
Leistungsdaten sind Zeitreihendaten, die Informationen über die Leistung des überwachten Geräts/der überwachten Quelle liefern.  Hierzu zählen beispielsweise die Anzahl der von einem Speichersystem bereitgestellten E/A-Vorgänge, der Durchsatz eines FibreChannel-Ports, die Anzahl der von einem Webserver bereitgestellten Seiten, die Antwortzeit einer Datenbank und mehr.

* Bestandsdaten
+
Inventardaten bestehen aus Metadaten, die das überwachte Gerät/die überwachte Quelle und deren Konfiguration beschreiben.  Hierzu gehören beispielsweise installierte Hardware- und Softwareversionen, Festplatten und LUNs in einem Speichersystem, CPU-Kerne, RAM und Festplatten einer virtuellen Maschine, die Tablespaces einer Datenbank, die Anzahl und Art der Ports auf einem SAN-Switch, Verzeichnis-/Dateinamen (wenn Storage Workload Security aktiviert ist) usw.

* Konfigurationsdaten
+
Dies fasst die vom Kunden bereitgestellten Konfigurationsdaten zusammen, die zur Verwaltung des Kundenbestands und der Vorgänge verwendet werden, z. B. Hostnamen oder IP-Adressen der überwachten Geräte, Abfrageintervalle, Timeout-Werte usw.

* Geheimnisse
+
Geheimnisse bestehen aus den Anmeldeinformationen, die von der Data Infrastructure Insights Acquisition Unit für den Zugriff auf Kundengeräte und -dienste verwendet werden.  Diese Anmeldeinformationen werden mithilfe einer starken asymmetrischen Verschlüsselung verschlüsselt und die privaten Schlüssel werden nur auf den Erfassungseinheiten gespeichert und verlassen nie die Kundenumgebung.  Aufgrund dieses Designs können selbst privilegierte Data Infrastructure Insights SREs nicht auf Kundengeheimnisse im Klartext zugreifen.

* Funktionale Daten
+
Dabei handelt es sich um Daten, die durch die Bereitstellung des Cloud Data Service durch NetApp generiert werden und die NetApp bei der Entwicklung, Bereitstellung, dem Betrieb, der Wartung und der Sicherung des Cloud Data Service unterstützen.  Funktionale Daten enthalten keine Kundeninformationen oder personenbezogenen Daten.

* Benutzerzugriffsdaten
+
Authentifizierungs- und Zugriffsinformationen, die es der NetApp Console ermöglichen, mit regionalen Data Infrastructure Insights -Sites zu kommunizieren, einschließlich Daten zur Benutzerautorisierung.

* Speicher-Workload-Sicherheit Benutzerverzeichnisdaten
+
In Fällen, in denen die Workload-Sicherheitsfunktion aktiviert ist UND der Kunde den Benutzerverzeichnis-Collector aktiviert, speichert das System Benutzeranzeigenamen, Unternehmens-E-Mail-Adressen und andere aus Active Directory gesammelte Informationen.




NOTE: Benutzerverzeichnisdaten beziehen sich auf Benutzerverzeichnisinformationen, die vom Workload Security-Benutzerverzeichnis-Datensammler erfasst werden, und nicht auf Daten über die Benutzer von Data Infrastructure Insights/Workload Security selbst.

Es werden *keine expliziten personenbezogenen Daten* aus Infrastruktur- und Serviceressourcen erhoben.  Die gesammelten Informationen bestehen nur aus Leistungsmesswerten, Konfigurationsinformationen und Infrastrukturmetadaten, ähnlich wie bei vielen Anbietern von Phone-Homes, einschließlich NetApp Auto-Support und ActiveIQ.  Abhängig von den Namenskonventionen eines Kunden können Daten für Freigaben, Volumes, VMs, Qtrees, Anwendungen usw. jedoch personenbezogene Daten enthalten.

Wenn die Workload-Sicherheit aktiviert ist, prüft das System zusätzlich Datei- und Verzeichnisnamen auf SMB- oder anderen Freigaben, die möglicherweise personenbezogene Daten enthalten.  Wenn Kunden den Workload Security User Directory Collector aktivieren (der im Wesentlichen Windows-SIDs über Active Directory Benutzernamen zuordnet), werden der Anzeigename, die Unternehmens-E-Mail-Adresse und alle weiteren ausgewählten Attribute von Data Infrastructure Insights erfasst und gespeichert.

Darüber hinaus werden Zugriffsprotokolle für Data Infrastructure Insights geführt, die die IP- und E-Mail-Adressen der Benutzer enthalten, die sie zum Anmelden beim Dienst verwendet haben.



== Wo werden meine Informationen gespeichert?

Data Infrastructure Insights speichert Informationen entsprechend der Region, in der Ihre Umgebung erstellt wird.

Die folgenden Informationen werden in der Hostregion gespeichert:

* Telemetrie- und Asset-/Objektinformationen, einschließlich Zähler und Leistungsmetriken
* Informationen zur Erfassungseinheit
* Funktionale Daten
* Prüfinformationen zu Benutzeraktivitäten in Data Infrastructure Insights
* Informationen zur Workload-Sicherheit in Active Directory
* Informationen zum Workload-Sicherheitsaudit


Die folgenden Informationen befinden sich in den Vereinigten Staaten, unabhängig von der Region, in der Ihre Data Infrastructure Insights Umgebung gehostet wird:

* Informationen zur Umgebungssite (manchmal auch „Mandant“ genannt), z. B. Site-/Kontoinhaber.
* Informationen, die es der NetApp Console ermöglichen, mit regionalen Data Infrastructure Insights -Sites zu kommunizieren, einschließlich aller Informationen, die mit der Benutzerautorisierung zu tun haben.
* Informationen zur Beziehung zwischen dem Data Infrastructure Insights Benutzer und dem Mandanten.




=== Gastgeberregionen

Zu den Gastgeberregionen gehören:

* USA: us-east-1
* EMEA: eu-central-1
* APAC: ap-southeast-2




== Weitere Informationen

Weitere Informationen zum Datenschutz und zur Sicherheit von NetApp finden Sie unter den folgenden Links:

* link:https://www.netapp.com/us/company/trust-center/index.aspx["Vertrauenszentrum"]
* link:https://www.netapp.com/us/company/trust-center/privacy/data-location-cross-border-transfers.aspx["Grenzüberschreitende Datenübertragungen"]
* link:https://www.netapp.com/us/company/trust-center/privacy/bcr-binding-corporate-rules.aspx["Verbindliche Unternehmensregeln"]
* link:https://www.netapp.com/us/company/trust-center/transparency/third-party-data-requests.aspx["Antworten auf Datenanfragen von Drittanbietern"]
* link:https://www.netapp.com/us/company/trust-center/privacy/privacy-principles-security-safeguards.aspx["NetApp Datenschutzgrundsätze"]

