---
sidebar: sidebar 
permalink: task_dc_ibm_powervm.html 
keywords: IBM, powerVM, 
summary: Konfigurieren des IBM PowerVM-Datenkollektors. 
---
= Konfigurieren des IBM PowerVM-Datenkollektors
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Der IBM PowerVM (SSH)-Datenkollektor wird zum Sammeln von Informationen über virtuelle Partitionen verwendet, die auf IBM POWER-Hardwareinstanzen ausgeführt werden, die von einer Hardware Management Console (HMC) verwaltet werden.



== Terminologie

Data Infrastructure Insights erfasst Bestandsinformationen von den virtuellen Partitionen, die auf IBM POWER-Hardwareinstanzen ausgeführt werden.  Für jeden erworbenen Vermögenswerttyp wird die am häufigsten verwendete Terminologie für den Vermögenswert angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Festplatte | Virtuelle Festplatte 


| Verwaltetes System | Gastgeber 


| LPAR, VIO-Server | Virtuelle Maschine 


| Volumengruppe | Datenspeicher 


| Physisches Volumen | LUN 
|===
Hinweis: Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diesen Datensammler darstellen.



== Anforderungen

Zur Konfiguration und Nutzung dieses Datensammlers müssen folgende Voraussetzungen erfüllt sein:

* IP-Adresse der Hardware Management Console (HMC)
* Benutzername und Kennwort, die den Zugriff auf die Hardware Management Console (HMC) über SSH ermöglichen
* Portanforderung SSH-22
* Anzeigeberechtigung für alle Verwaltungssysteme und Sicherheitsdomänen logischer Partitionen
+
Der Benutzer muss außerdem über die Berechtigung zum Anzeigen von HMC-Konfigurationen und zum Sammeln von VPD-Informationen für die Sicherheitsgruppierung der HMC-Konsole verfügen.  Dem Benutzer muss außerdem der Zugriff auf Virtual IO Server Commands unter der Sicherheitsgruppierung „Logische Partition“ gestattet sein.  Es empfiehlt sich, mit der Rolle eines Operators zu beginnen und dann alle Rollen zu entfernen.  Nur-Lese-Benutzer auf der HMC haben keine Berechtigung zum Ausführen von Proxy-Befehlen auf AIX-Hosts.

* Die bewährte Vorgehensweise von IBM besteht darin, die Geräte von zwei oder mehr HMCs überwachen zu lassen.  Beachten Sie, dass dies dazu führen kann, dass OnCommand Insight doppelte Geräte meldet. Daher wird dringend empfohlen, redundante Geräte zur Liste „Geräte ausschließen“ in der erweiterten Konfiguration für diesen Datensammler hinzuzufügen.




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| IP-Adresse der Hardware Management Console (HMC) | IP-Adresse oder vollqualifizierter Domänenname der PowerVM Hardware Management Console 


| HMC-Benutzer | Benutzername für die Hardware Management Console 


| Passwort | Für die Hardware Management Console verwendetes Kennwort 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Inventarabfrageintervall (min) | Intervall zwischen den Bestandsabfragen. Der Standardwert beträgt 20 Minuten. 


| SSH-Port | Für SSH zur PowerVM verwendeter Port 


| Passwort | Für die Hardware Management Console verwendetes Kennwort 


| Anzahl der Wiederholungsversuche | Anzahl der Inventarisierungswiederholungsversuche 


| Geräte ausschließen | Durch Kommas getrennte Liste der auszuschließenden Geräte-IDs oder Anzeigenamen 
|===


== Fehlerbehebung

Weitere Informationen zu diesem Datensammler finden Sie imlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
