---
sidebar: sidebar 
permalink: task_dc_redhat_virtualization.html 
keywords: data collector, Red Hat Virtualization 
summary: Konfigurieren des Red Hat Virtualization-Datenkollektors. 
---
= Red Hat Virtualization-Datenkollektor
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Der DII-Datensammler für Red Hat Virtualization unterstützt auch das Open-Source-Projekt oVirt und Oracle Linux Virtualization Manager. Dieser Datensammler kommuniziert über REST API mit der HTTPS-Schnittstelle auf der Managementstation.



== Terminologie

Für jeden von Data Infrastructure Insights erfassten Asset-Typ wird die am häufigsten verwendete Terminologie für das Asset angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Scheibe | Virtuelle Festplatte 


| Gastgeber | Gastgeber 


| Virtuelle Maschine | Virtuelle Maschine 


| Speicherdomäne | Datenspeicher 


| Logische Einheit | LUN 
|===
Hinweis: Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diesen Datensammler darstellen.



== Anforderungen

* IP-Adresse/Hostname des RHV/oVirt/OLVM-Servers über Port 443 via REST-API
* Nur-Lese-Benutzername und -Passwort
* RHV Version 3.0+/Ovirt 4.0+/OLVM 4.0+




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| RHV/Ovirt/OLVM Server-IP-Adresse | IP-Adresse der Managementstation 


| Benutzername | Benutzername 


| Passwort | Passwort 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| HTTPS-Kommunikationsport | Für die HTTPS-Kommunikation mit RHEV verwendeter Port 


| Inventarabfrageintervall (min) | Der Standardwert beträgt 20 Minuten. 


| VM-Leistung | Leistungsdatenerfassung aktivieren 


| Leistungsabfrageintervall (Sek.) | Der Standardwert ist 900 
|===


== Fehlerbehebung

Weitere Informationen zu diesem Datensammler finden Sie imlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
