---
sidebar: sidebar 
permalink: task_dc_rubrik_cdm.html 
keywords: data collector, Rubrik, 
summary: Konfigurieren des Rubrik CDM-Datensammlers. 
---
= Rubrik CDM-Datensammler
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights verwendet den Rubrik-Datensammler, um Bestands- und Leistungsdaten von Rubrik-Speichergeräten zu erfassen.



== Terminologie

Data Infrastructure Insights erhält die folgenden Bestandsinformationen vom Rubrik-Datensammler.  Für jeden von Data Infrastructure Insights erworbenen Asset-Typ wird die am häufigsten verwendete Terminologie für dieses Asset angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Cluster | Speicher, Speicherpool 


| Node | Speicherknoten 


| Scheibe | Scheibe 
|===
Hinweis: Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diese Datenquelle darstellen.



== Anforderungen

Zur Konfiguration dieses Datensammlers sind folgende Voraussetzungen erforderlich:

* Die Data Infrastructure Insights Acquisition Unit initiiert Verbindungen zum TCP-Port 443 zum Rubrik-Cluster.  Ein Kollektor pro Cluster.
* IP-Adresse des Rubrik-Clusters.
* Benutzername und Passwort für den Cluster.
* IP-Adresse oder Hostname des Rubrik-Clusters.
* Für die Basisauthentifizierung ein Benutzername und ein Kennwort für den Cluster.  Wenn Sie die Authentifizierung auf Basis eines Dienstkontos bevorzugen, benötigen Sie ein Dienstkonto, ein Geheimnis und eine Organisations-ID
* Portanforderung: HTTPS 443




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| IP | IP-Adresse des Rubrik-Clusters 


| Benutzername / Dienstkonto | Benutzername für den Cluster 


| Passwort / Geheimnis | Kennwort für den Cluster 


| Organisations-ID für das Service-Konto | Dies muss die vollständige Zeichenfolge sein, z. B. „Organization:::nnnnnn-nnnn....“ 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Inventarabfrageintervall (min) | Der Standardwert ist 60 


| Leistungsabfrageintervall (Sek.) | Der Standardwert ist 300 
|===


== Fehlerbehebung

Wenn bei diesem Datensammler Probleme auftreten, können Sie Folgendes versuchen:



=== Inventar

[cols="2*"]
|===
| Problem: | Versuchen Sie Folgendes: 


| Ich habe eine Nachricht erhalten, dass mehr als ein Speicher erstellt wurde. | Überprüfen Sie, ob der Cluster richtig konfiguriert ist und der Collector auf einen einzelnen Cluster verweist. 


| Umfrage schlägt mit 400 [Ungültige Anfrage] fehl. ... Ungültige ManagedId.... | Sie haben das Feld „Organisations-ID“ mit einem Wert ausgefüllt, aber der Rubrik-Cluster glaubt NICHT, dass es sich um eine gültige Organisations-ID handelt, obwohl die Fehlermeldung von Rubrik darauf als „ManagedId“ verweist. 
|===
Weitere Informationen finden Sie in derlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
