---
sidebar: sidebar 
permalink: task_dc_emc_powerstore.html 
keywords: data collector, PowerStore, EMC, DELL 
summary: KONFIGURIEREN DES DELL EMC PowerStore-Datensammlers. 
---
= Dell EMC PowerStore-Datensammler
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Der EMC PowerStore Data Collector sammelt Bestandsdaten aus dem EMC PowerStore-Speicher. Zur Konfiguration benötigt der Datensammler die IP-Adresse der Speicherprozessoren sowie einen schreibgeschützten Benutzernamen und ein Kennwort.

Der EMC PowerStore Datensammler erfasst die Replikationsbeziehungen zwischen Volume und Volume, die PowerStore über andere Speicher-Arrays hinweg koordiniert. Data Infrastructure Insights zeigt ein Speicher-Array für jeden PowerStore-Cluster und sammelt Bestandsdaten für Knoten und Speicherports auf diesem Cluster. Es werden keine Storage-Pool- oder Volume-Daten erfasst.



== Terminologie

Data Infrastructure Insights erfasst die folgenden Bestandsinformationen aus diesem Datensammler. Für jeden Asset-Typ, der von Data Infrastructure Insights erworben wurde, wird die für diese Ressource am häufigsten verwendete Terminologie angezeigt. Beachten Sie bei der Anzeige oder Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter-/Modelllaufzeit | Einblicke Aus Der Dateninfrastruktur 


| Host | Host 


| Host_Volume_Zuordnung | Host_Volume_Zuordnung 


| Hardware (es hat Laufwerke unter „extra_Details“-Objekt): Laufwerke | Festplatte 


| Appliance | Storage Pool 


| Cluster | Storage Array Durchführt 


| Knoten | StorageNode 


| fc_Port | Port 


| Datenmenge | Datenmenge 


| InternalVolume | File_System 
|===
Hinweis: Es handelt sich hierbei nur um allgemeine Terminologiezuordnungen. Diese stellen für diesen Datensammler möglicherweise nicht alle Fälle dar.



== Anforderungen

Zur Konfiguration dieses Datensammlers sind folgende Informationen erforderlich:

* IP-Adresse oder vollqualifizierter Domain-Name des Speicherprozessors
* Schreibgeschützter Benutzername und Kennwort




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| PowerStore Gateway(s) | IP-Adressen oder vollqualifizierte Domain-Namen des PowerStore-Speichers 


| Benutzername | Benutzername für PowerStore 


| Passwort | Passwort, das für PowerStore verwendet wird 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| HTTPS-Anschluss | Der Standardwert ist 443 


| Abfrageintervall für Bestand (Minuten) | Intervall zwischen Bestandsabstimmungen Die Standardeinstellung ist 60 Minuten. 
|===
Die PowerStore Performance-Sammlung von Cloud Insight nutzt die 5-minütigen Granularitätsquelldaten von PowerStore. Daher fragt Data Infrastructure Insights diese Daten alle fünf Minuten ab. Dies ist nicht konfigurierbar.



== Fehlerbehebung

Weitere Informationen zu diesem Data Collector finden Sie auf der link:concept_requesting_support.html["Support"] Seite oder im link:reference_data_collector_support_matrix.html["Data Collector Supportmatrix"].
