---
sidebar: sidebar 
permalink: task_cs_add_collector_ontap.html 
keywords: data collector, ONTAP, SVM 
summary: Hinzufügen von Datensammlern 
---
= Konfigurieren des NetApp ONTAP Data Collector
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Workload Security verwendet Datensammler, um Datei- und Benutzerzugriffsdaten von Geräten zu erfassen.  Die Daten werden Workload Security zur Analyse bereitgestellt.

.Bevor Sie beginnen
Zur Konfiguration dieses Datensammlers benötigen Sie folgende Informationen:

* Ein Agent muss zum Sammeln von Daten konfiguriert werden
* Die SVM-Verwaltungs-IP-Adresse
* Ein Benutzername für den Zugriff auf die SVM
* Das Passwort für den Zugriff auf die SVM


.Schritte zur Konfiguration
. Melden Sie sich als Administrator oder Kontobesitzer bei Ihrer Workload Security-Umgebung an.
. Klicken Sie auf *Beobachtbarkeit > Sammler > +Datensammler*
+
Das System zeigt die verfügbaren Datensammler an.

. Klicken Sie in der NetApp ONTAP Kachel auf *+Monitor*.
+
Das System zeigt die Konfigurationsseite „Datensammler hinzufügen: Ontap SVM“ an.

. Geben Sie einen eindeutigen Namen für den Collector ein
. Wählen Sie den Agenten aus, der die Daten erfassen soll
. Geben Sie die SVM-Verwaltungs-IP-Adresse ein
. Geben Sie den Benutzernamen für den Zugriff auf die SVM ein
. Geben Sie das Kennwort ein, um auf die SVM zuzugreifen
. Klicken Sie auf *+Collector hinzufügen*


.Nach Abschluss
* Klicken Sie auf *Workload-Sicherheit > Collector*, um den Status des von Ihnen konfigurierten Collectors zu überprüfen.
+
Normalerweise kommt es zu einer Verzögerung, bevor der Collector-Status angezeigt wird.


