---
sidebar: sidebar 
permalink: task_create_annotation_rules.html 
summary: Sie erstellen Anmerkungsregeln, um Anmerkungen automatisch auf mehrere Assets anzuwenden. 
keywords: annotate, annotation, rules 
---
= Erstellen von Anmerkungsregeln
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Mithilfe von Anmerkungsregeln können Sie Anmerkungen basierend auf den von Ihnen definierten Kriterien automatisch auf mehrere Assets anwenden.  Data Infrastructure Insights weist die Anmerkungen den Assets basierend auf diesen Regeln zu.  Manuell auf einzelnen Asset-Seiten festgelegte Anmerkungen haben Vorrang vor regelbasierten Anmerkungen, wenn Cloud Insight die Anmerkungsregeln auswertet.

.Bevor Sie beginnen
Sie müssen eine Abfrage für die Anmerkungsregel erstellt haben.

.Schritte
. Klicken Sie im Data Infrastructure Insights -Menü auf *Verwalten > Anmerkungsregeln*.
. Klicken Sie auf *+ Regel*, um eine neue Anmerkungsregel hinzuzufügen.
+
Das Dialogfeld „Regel hinzufügen“ wird angezeigt.

. Gehen Sie folgendermaßen vor:
+
.. Geben Sie im Feld *Name* einen eindeutigen Namen ein, der die Regel beschreibt.
+
Der Name wird auf der Seite „Anmerkungsregeln“ angezeigt.

.. Klicken Sie auf *Abfrage* und wählen Sie die Abfrage aus, die Data Infrastructure Insights verwendet, um die Assets zu identifizieren, auf die sich die Anmerkung bezieht.
.. Klicken Sie auf *Anmerkung* und wählen Sie die Anmerkung aus, die Sie anwenden möchten.
.. Klicken Sie auf *Wert* und wählen Sie einen Wert für die Anmerkung aus.
+
Wenn Sie beispielsweise „Geburtstag“ als Anmerkung wählen, geben Sie ein Datum für den Wert an.

.. Klicken Sie auf *Speichern*
.. Klicken Sie auf *Alle Regeln ausführen*, wenn Sie alle Regeln sofort ausführen möchten. Andernfalls werden die Regeln in regelmäßigen Abständen ausgeführt.
+

NOTE: In einer großen Data Infrastructure Insights -Umgebung stellen Sie möglicherweise fest, dass die Ausführung von Anmerkungsregeln eine Weile zu dauern scheint.  Dies liegt daran, dass der Indexer zuerst ausgeführt wird und vor der Ausführung der Regeln abgeschlossen sein muss.  Der Indexer gibt Data Infrastructure Insights die Möglichkeit, in Ihren Daten nach neuen oder aktualisierten Objekten und Zählern zu suchen oder diese zu filtern.  Die Regel-Engine wartet, bis der Indexer seine Aktualisierung abgeschlossen hat, bevor sie die Regeln anwendet.







== Ändern von Anmerkungsregeln

Sie können eine Anmerkungsregel ändern, um den Namen der Regel, ihre Anmerkung, den Wert der Anmerkung oder die mit der Regel verknüpfte Abfrage zu ändern.

.Schritte
. Klicken Sie im Data Infrastructure Insights -Menü auf *Verwalten > Anmerkungsregeln*.
+
Auf der Seite „Annotationsregeln“ wird die Liste der vorhandenen Annotationsregeln angezeigt.

. Suchen Sie die Anmerkungsregel, die Sie ändern möchten.
+
Sie können die Anmerkungsregeln filtern, indem Sie einen Wert in das Filterfeld eingeben oder auf eine Seitenzahl klicken, um die Anmerkungsregeln seitenweise zu durchsuchen.

. Klicken Sie auf das Menüsymbol für die Regel, die Sie ändern möchten.
. Klicken Sie auf *Bearbeiten*
+
Das Dialogfeld „Regel bearbeiten“ wird angezeigt.

. Ändern Sie den Namen, die Anmerkung, den Wert oder die Abfrage der Anmerkungsregel.




== Ändern der Reihenfolge der Regeln

Anmerkungsregeln werden von oben nach unten in der Regelliste verarbeitet.  Um die Reihenfolge zu ändern, in der eine Regel verarbeitet wird, gehen Sie wie folgt vor:

.Schritte
. Klicken Sie auf das Menüsymbol für die Regel, die Sie verschieben möchten.
. Klicken Sie je nach Bedarf auf *Nach oben verschieben* oder *Nach unten verschieben*, bis die Regel an der gewünschten Stelle angezeigt wird.


Beachten Sie, dass beim Ausführen mehrerer Regeln, die dieselbe Anmerkung zu einem Asset aktualisieren, die erste Regel (von oben nach unten ausgeführt) die Anmerkung anwendet und das Asset aktualisiert. Anschließend wird die zweite Regel angewendet, ändert jedoch keine Anmerkungen, die bereits von der vorherigen Regel festgelegt wurden.



== Löschen von Anmerkungsregeln

Möglicherweise möchten Sie Anmerkungsregeln löschen, die nicht mehr verwendet werden.

.Schritte
. Klicken Sie im Data Infrastructure Insights -Menü auf *Verwalten > Anmerkungsregeln*.
+
Auf der Seite „Annotationsregeln“ wird die Liste der vorhandenen Annotationsregeln angezeigt.

. Suchen Sie die Anmerkungsregel, die Sie löschen möchten.
+
Sie können die Anmerkungsregeln filtern, indem Sie einen Wert in das Filterfeld eingeben oder auf eine Seitenzahl klicken, um die Anmerkungsregeln seitenweise zu durchsuchen.

. Klicken Sie auf das Menüsymbol für die Regel, die Sie löschen möchten.
. Klicken Sie auf *Löschen*
+
Es wird eine Bestätigungsmeldung angezeigt, in der Sie gefragt werden, ob Sie die Regel löschen möchten.

. Klicken Sie auf *OK*

