---
sidebar: sidebar 
permalink: task_dc_oracle_zfs.html 
keywords: data collector, Oracle, ZFS, storage applicance 
summary: Konfigurieren des Oracle ZFS-Datenkollektors. 
---
= Oracle ZFS Storage Appliance-Datenkollektor
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights verwendet den Oracle ZFS Storage Appliance-Datensammler, um Bestands- und Leistungsdaten zu erfassen.



== Terminologie

Data Infrastructure Insights erfasst Bestandsinformationen mit dem Oracle ZFS-Datenkollektor.  Für jeden von Data Infrastructure Insights erworbenen Asset-Typ wird die am häufigsten verwendete Terminologie für dieses Asset angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Festplatte (SSD) | Scheibe 


| Cluster | Storage 


| Regler | Speicherknoten 


| LUN | Volumen 


| LUN-Karte | Volumenkarte 


| Initiator, Ziel | Volumenmaske 


| Aktie | Internes Volumen 
|===
Hinweis: Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diese Datenquelle darstellen.



== Anforderungen

* Hostnamen für den ZFS-Controller-1 und den ZFS-Controller-2
* Administrator-Benutzername und -Passwort
* Portanforderung: 215 HTTP/HTTPS




== Erforderliche Leistungsmetriken

Oracle ZFS-Geräte bieten Speicheradministratoren große Flexibilität bei der Erfassung von Leistungsstatistiken.  Data Infrastructure Insights erwartet, dass Sie _jeden_ Controller in einem Hochverfügbarkeitspaar so konfigurieren, dass die folgenden Metriken erfasst werden:

* smb2.ops[teilen]
* nfs3.ops[teilen]
* nfs4.ops[teilen]
* nfs4-1.ops[teilen]


Wenn der Controller einige oder alle dieser Daten nicht erfasst, führt dies wahrscheinlich dazu, dass Data Infrastructure Insights die Arbeitslast auf den „internen Volumes“ nicht erfasst oder zu niedrig angibt.



== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| ZFS-Controller-1-Hostname | Hostname für Speichercontroller 1 


| ZFS-Controller-2-Hostname | Hostname für Speichercontroller 2 


| Benutzername | Benutzername für das Benutzerkonto des Speichersystemadministrators 


| Passwort | Kennwort für das Administrator-Benutzerkonto 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Verbindungstyp | HTTPS oder HTTP, zeigt auch den Standardport an 


| Verbindungsport überschreiben | Wenn das Feld „Verbindungstyp“ leer ist, verwenden Sie den Standardport. Andernfalls geben Sie den zu verwendenden Verbindungsport ein. 


| Inventarabfrageintervall | Der Standardwert beträgt 60 Sekunden 


| Leistungsabfrageintervall (Sek.) | Der Standardwert ist 300. 
|===


== Fehlerbehebung

Wenn bei diesem Datensammler Probleme auftreten, können Sie Folgendes versuchen:



=== Inventar

[cols="2a, 2a"]
|===
| Problem: | Versuchen Sie Folgendes: 


 a| 
„Ungültige Anmeldedaten“
 a| 
ZFS-Benutzerkonto und Passwort validieren



 a| 
„Anforderung fehlgeschlagen mit Status 404 \https://.....:215/api/access/v1“
 a| 
Ihr ZFS-Array ist möglicherweise zu alt, um REST-API-Unterstützung zu bieten.  AK 2013.1.3.0 war die erste REST-API-fähige ZFS-Betriebssystemversion und nicht alle ZFS-Geräte können darauf aktualisiert werden.



 a| 
„Konfigurationsfehler“ mit Fehlermeldung „REST-Dienst ist deaktiviert“
 a| 
Überprüfen Sie, ob der REST-Dienst auf diesem Gerät aktiviert ist.



 a| 
„Konfigurationsfehler“ mit Fehlermeldung „Benutzer nicht autorisiert für Befehl“
 a| 
Dieser Fehler ist wahrscheinlich darauf zurückzuführen, dass bestimmte Rollen (z. B. „advanced_analytics“) für den konfigurierten Benutzer nicht enthalten sind.

Durch Anwenden des Analytics-Bereichs für den Benutzer mit schreibgeschützter Rolle kann der Fehler möglicherweise behoben werden. Gehen Sie folgendermaßen vor:

. Bewegen Sie im ZFs-System im Bildschirm „Konfiguration -> Benutzer“ die Maus über die Rolle und doppelklicken Sie, um die Bearbeitung zu ermöglichen
. Wählen Sie „Analytics“ aus dem Dropdown-Menü „Bereich“ aus.  Es erscheint eine Liste der möglichen Eigenschaften.
. Klicken Sie auf das oberste Kontrollkästchen, um alle drei Eigenschaften auszuwählen.
. Klicken Sie auf der rechten Seite auf die Schaltfläche „Hinzufügen“.
. Klicken Sie oben rechts im Popup-Fenster auf die Schaltfläche „Übernehmen“.  Das Popup-Fenster wird geschlossen.


|===
Weitere Informationen finden Sie in derlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
