---
sidebar: sidebar 
permalink: task_dc_hds_hcp.html 
keywords: data collector, Hitachi HDS, HCP 
summary: HDS-Datensammler konfigurieren. 
---
= Hitachi HCP-Datensammler
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Dieser Datensammler unterstützt die Hitachi Content Platform (HCP) mithilfe der HCP Management API.


NOTE: Für die Hitachi Content Platform gilt ein anderer Preis für Raw TB als für Managed Units.  Jede 40 TB unformatierte HCP-Kapazität wird als 1 berechnetlink:concept_subscribing_to_cloud_insights.html#pricing["Verwaltete Einheit (MU)"] .



== Terminologie

Data Infrastructure Insights erhält die folgenden Bestandsinformationen vom Hitachi HCP-Datensammler.  Für jeden von Data Infrastructure Insights erworbenen Asset-Typ wird die am häufigsten verwendete Terminologie für dieses Asset angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| HCP-Cluster | Storage 


| Mieter | Speicherpool 


|  | Namensraum 


| Internes Volumen | Node 
|===
Hinweis: Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diesen Datensammler darstellen.



== Inventaranforderungen

Um Bestandsdaten erfassen zu können, benötigen Sie Folgendes:

* IP-Adresse des HCP-Servers
* Nur-Lese-Benutzername und Passwort für die HCP-Software und Peer-Berechtigungen




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| HCP-Host | IP-Adresse oder vollqualifizierter Domänenname des HCP-Hosts 


| HCP-Anschluss | Der Standardwert ist 9090 


| HCP-Benutzer-ID | Benutzername für den HCP-Host. 


| HCP-Passwort | Für den HCP-Host verwendetes Passwort. 


| HCP-Authentifizierungstyp | Wählen Sie HCP_LOCAL oder ACTIVE_DIRECTORY 
|===


== Erweiterte Konfiguration

|===


| Feld | Beschreibung 


| Inventarabfrageintervall (min) | Intervall zwischen den Bestandsabfragen.  Der Standardwert ist 60. 


| Leistungsabfrageintervall (Sek.) | Intervall zwischen Leistungsabfragen.  Der Standardwert ist 900. 
|===
Weitere Informationen finden Sie in derlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
