---
sidebar: sidebar 
permalink: task_dc_brocade_rest.html 
keywords: data collector, Brocade, FC switch, FOS, Rest 
summary: Konfigurieren des Brocade FOS REST-Datenkollektors. 
---
= Brocade FOS REST-Datenkollektor
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights verwendet den Brocade FOS REST-Collector, um Inventar und Leistung für Brocade -Switch-Geräte mit FabricOS (FOS)-Firmware 8.2 und höher zu ermitteln.  Bitte beachten Sie, dass frühe 8.2-FOS-Versionen möglicherweise REST-API-Fehler aufweisen. Es wird dringend empfohlen, die neuste FOS-Version auszuführen, die Ihre Plattform unterstützt.

Bitte beachten Sie: Die standardmäßige „Benutzer“-Ebene von FOS ist für Data Infrastructure Insights nicht leistungsfähig genug, um alle logischen Aspekte eines Geräts anzuzeigen. Wir benötigen ein Benutzerkonto mit aktivierter „Chassis-Rolle“ sowie Berechtigungen für alle auf einem Switch konfigurierten virtuellen Fabrics.

Hier ist ein Beispiel, wie Sie ein Benutzerkonto mit den geringsten Berechtigungen für die Verwendung von Data Infrastructure Insights in einer SSH-Sitzung mit einem FOS-Gerät erstellen können:

userConfig --add NetAppCIUser -r Benutzer -l 1-128 -c Benutzer -p Qwerty!

Dadurch wird ein Benutzer „NetAppCIUser“ mit dem Kennwort „Qwerty!“ erstellt.  Dieser Benutzer hat die Rolle „Benutzer“ (-r) für alle 128 möglichen virtuellen Fabrics ( -l ).  Dieser Benutzer verfügt zusätzlich über die erforderliche „Chassis“-Rolle (-c) mit zugewiesenem Zugriff auf Benutzerebene.

Standardmäßig versucht dieser Collector, alle FOS-Geräte zu erkennen, die Teil aller Fabrics sind, zu denen der Switch gehört.

Bitte beachten Sie: Der standardmäßige schreibgeschützte Benutzer „Benutzer“ von FOS verfügt NICHT über Anzeigeberechtigungen für alle virtuellen Fabrics und auch nicht über Berechtigungen für die „Chassis-Rolle“.  Dies bedeutet, dass die Erfolgsaussichten bei der Verwendung von „Benutzer“ mit Data Infrastructure Insights gering sind, da hierfür sowohl die physische als auch die logische Konfiguration des FOS-Geräts bekannt sein muss.



== Terminologie

Data Infrastructure Insights erhält die folgenden Bestandsinformationen vom Brocade FOS REST-Datensammler.  Für jeden von Data Infrastructure Insights erworbenen Asset-Typ wird die am häufigsten verwendete Terminologie für dieses Asset angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Schalten | Schalten 


| Hafen | Hafen 


| Virtuelles Gewebe, physisches Gewebe | Stoff 


| Zone | Zone 


| Logischer Switch | Logischer Switch 


| LSAN-Zone | IVR-Zone 
|===
Hinweis: Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diesen Datensammler darstellen.



== Anforderungen

* Es muss eine TCP-Konnektivität zu allen Switches im Fabric bestehen.  Dieser Datensammlertyp probiert nahtlos sowohl HTTP als auch HTTPS für jedes Gerät im Fabric aus.  Wenn Sie das Kontrollkästchen „Alle Switches im Fabric erkennen“ aktivieren, identifiziert Data Infrastructure Insights alle Switches im Fabric. Allerdings ist für die Erkennung dieser zusätzlichen Switches eine TCP-Verbindung erforderlich.
* Für alle Switches im Fabric ist global dasselbe Konto erforderlich.  Sie können den Zugriff über die Weboberfläche des Geräts bestätigen.




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| IP wechseln | IP-Adresse oder vollqualifizierter Domänenname des FOS-Switches 


| Benutzername | Benutzername für den Switch 


| Passwort | Passwort für den Switch 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Ausgeschlossene Geräte | Durch Kommas getrennte Liste von Geräte-IPv4-Adressen, die von der Abfrage ausgeschlossen werden sollen. 


| Inventarabfrageintervall (min) | Intervall zwischen den Bestandsabfragen.  Der Standardwert ist 60. 


| Entdecken Sie alle Switches im Fabric | Wählen Sie diese Option aus, um alle Switches im Fabric zu erkennen. 


| Wählen Sie HBA gegenüber Zonenaliasen | Wählen Sie, ob HBA- oder Zonenaliase bevorzugt werden sollen. 


| Anschlussart | HTTP oder HTTPS. 


| Beachten Sie, dass diese Einstellung nur ändert, welches Protokoll CI zuerst pro Gerät zu verwenden versucht. CI versucht automatisch das entgegengesetzte Protokoll, wenn die Standardeinstellung fehlschlägt. | TCP-Port überschreiben 


| Geben Sie einen Port an, wenn Sie nicht den Standardport verwenden. | Leistungsabfrageintervall (Sek.) 
|===


== Fehlerbehebung

Wenn bei diesem Datensammler Probleme auftreten, können Sie Folgendes versuchen:



=== Inventar

[cols="2*"]
|===
| Problem: | Versuchen Sie Folgendes: 


| Die Testfunktion warnt mich, dass auf ein Protokoll nicht zugegriffen werden kann | Ein bestimmtes Brocade FOS 8.2+-Gerät möchte nur über HTTP oder HTTPS kommunizieren. Wenn auf einem Switch ein digitales Zertifikat installiert ist, gibt der Switch HTTP-Fehler aus, wenn versucht wird, mit ihm über unverschlüsseltes HTTP statt HTTPS zu kommunizieren.  Die Testfunktion versucht, sowohl mit HTTP als auch mit HTTPS zu kommunizieren. Wenn der Test ergibt, dass ein Protokoll erfolgreich ist, können Sie den Collector sicher speichern und müssen sich keine Sorgen machen, dass das andere Protokoll nicht erfolgreich war. Der Collector versucht während der Erfassung beide Protokolle und schlägt nur fehl, wenn keines von beiden funktioniert. 


| Fehler: Inventarisierung schlägt mit 401 Unauthorized fehl...Ungültiger Sitzungsschlüssel... | Dies ist ein eindeutiger Fehler in einigen sehr frühen 8.2 FOS-Versionen wie 8.2.1c, die die HTTP-Basisauthentifizierung NICHT richtig unterstützen.  Upgrade auf eine spätere Version 8.2 oder 9.* 


| Fehler: „Data Infrastructure Insights hat eine ungültige Chassis-Rolle erhalten“ | Überprüfen Sie, ob dem in dieser Datenquelle konfigurierten Benutzer die Berechtigung für die Chassis-Rolle erteilt wurde. 


| Fehler: „Nicht übereinstimmende Gehäuse-IP-Adresse“ | Ändern Sie die Datenquellenkonfiguration, um die IP-Adresse des Gehäuses zu verwenden. 


| Die Inventur schlägt mit der Fehlermeldung „403 Forbidden“ fehl | Dies können einfach ungültige Anmeldeinformationen sein oder ein Hinweis darauf, dass Sie versuchen, eine Rolle mit unzureichenden Befugnissen zu verwenden. Bedenken Sie, dass Benutzer auf der Ebene „Benutzer“ NICHT über die erforderlichen Rechte für die „Chassis-Rolle“ verfügen oder keinen Anzeigezugriff auf nicht standardmäßige virtuelle Fabrics haben. 
|===
Weitere Informationen finden Sie in derlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
