---
sidebar: sidebar 
permalink: task_dc_hds_ops_center.html 
keywords: data collector, Hitachi Ops Center 
summary: Konfigurieren des HDS Ops Center-Datensammlers. 
---
= Hitachi Ops Center-Datensammler
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Dieser Datensammler verwendet die integrierte Anwendungssuite von Hitachi Ops Center, um auf Inventar- und Leistungsdaten mehrerer Speichergeräte zuzugreifen.  Zur Inventar- und Kapazitätsermittlung muss Ihre Ops Center-Installation sowohl die Komponenten „Common Services“ als auch „Administrator“ enthalten.  Für die Leistungserfassung müssen Sie zusätzlich „Analyzer“ bereitgestellt haben.



== Terminologie

Data Infrastructure Insights erhält von diesem Datensammler die folgenden Bestandsinformationen.  Für jeden von Data Infrastructure Insights erworbenen Asset-Typ wird die am häufigsten verwendete Terminologie für dieses Asset angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Speichersysteme | Storage 


| Volumen | Volumen 


| Paritätsgruppen | Speicherpool (RAID), Datenträgergruppen 


| Scheibe | Scheibe 


| Speicherpool | Speicherpool (Thin, SNAP) 


| Externe Paritätsgruppen | Speicherpool (Backend), Datenträgergruppen 


| Hafen | Speicherknoten → Controllerknoten → Port 


| Hostgruppen | Volumenzuordnung und -maskierung 


| Volumenpaare | Speichersynchronisierung 
|===
Hinweis: Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diesen Datensammler darstellen.



== Inventaranforderungen

Um Bestandsdaten erfassen zu können, benötigen Sie Folgendes:

* IP-Adresse oder Hostname des Ops Center-Servers, auf dem die Komponente „Common Services“ gehostet wird
* Root-/Sysadmin-Benutzerkonto und -Passwort, die auf allen Servern vorhanden sind, auf denen Ops Center-Komponenten gehostet werden.  HDS hat die REST-API-Unterstützung für die Verwendung durch LDAP/SSO-Benutzer erst ab Ops Center 10.8 implementiert.




== Leistungsanforderungen

Um Leistungsdaten erfassen zu können, müssen folgende Voraussetzungen erfüllt sein:

Das HDS Ops Center „Analyzer“-Modul muss installiert sein. Speicher-Arrays müssen das Ops Center „Analyzer“-Modul versorgen.



== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| IP-Adresse des Hitachi Ops Center | IP-Adresse oder vollqualifizierter Domänenname des Ops Center-Servers, auf dem die Komponente „Common Services“ gehostet wird 


| Benutzername | Benutzername für den Ops Center-Server. 


| Passwort | Für den Ops Center-Server verwendetes Kennwort. 
|===


== Erweiterte Konfiguration

|===


| Feld | Beschreibung 


| Verbindungstyp | HTTPS (Port 443) ist die Standardeinstellung 


| TCP-Port überschreiben | Geben Sie den zu verwendenden Port an, wenn dieser nicht der Standardport ist. 


| Inventarabfrageintervall (min) | Intervall zwischen den Bestandsabfragen.  Der Standardwert ist 40. 


| Wählen Sie „Ausschließen“ oder „Einschließen“, um eine Liste anzugeben | Geben Sie an, ob die unten stehende Array-Liste beim Sammeln von Daten ein- oder ausgeschlossen werden soll. 


| Geräteliste filtern | Durch Kommas getrennte Liste der Geräteseriennummern, die ein- oder ausgeschlossen werden sollen 


| Leistungsabfrageintervall (Sek.) | Intervall zwischen Leistungsabfragen.  Der Standardwert ist 300. 
|===
Weitere Informationen finden Sie in derlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
