---
sidebar: sidebar 
permalink: task_identify_inactive_devices.html 
keywords: inactive, device, remove, removing, identify, identifying 
summary: Durch die Identifizierung inaktiver Geräte können Sie diese löschen oder ihnen eine aktive Rolle zuweisen. 
---
= Identifizieren inaktiver Geräte
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Um die richtige Größe zu finden und ungenutzte Infrastruktur freizugeben, ist es entscheidend, die vorhandenen Ressourcen und deren Nutzer zu identifizieren.  Sie können nicht ausgelastete Ressourcen problemlos neu zuweisen oder außer Betrieb nehmen und unnötige Käufe vermeiden.

Führen Sie die folgenden Schritte aus, um inaktive Assets zu identifizieren.

.Schritte
* Navigieren Sie zu *Observability > Explore -> +Neue Metrikabfrage*.
* Wählen Sie _Speicher_ aus der Dropdown-Liste.
* Klicken Sie auf das Zahnrad und fügen Sie _isActive_ als Spalte hinzu.
+
Zeilen mit einem Häkchen sind aktiv.  „X“ zeigt inaktive Geräte an.



Um inaktive Geräte zu entfernen, wählen Sie einfach die zu entfernenden Geräte aus und wählen Sie im Dropdown-Menü *Massenaktionen* die Option _Inaktive Geräte löschen_.
