---
sidebar: sidebar 
permalink: task_create_application.html 
summary: Sie definieren Anwendungen, die Sie dann nach Bedarf auf die Assets Ihres Mandanten anwenden. 
keywords: application, create application, 
---
= Erstellen von Anwendungen
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Um Daten zu verfolgen, die mit bestimmten Anwendungen verknüpft sind, die auf Ihrem Mandanten ausgeführt werden, können Sie die Anwendungen in Data Infrastructure Insights definieren.

.Informationen zu diesem Vorgang
Mit Data Infrastructure Insights können Sie Daten von Assets, die mit Anwendungen verknüpft sind, für Zwecke wie Nutzungs- oder Kostenberichte verfolgen.

.Schritte
. Klicken Sie im Menü „Data Infrastructure Insights“ auf *Observability > Enrich > Applications*. Auswählen
+
Das Dialogfeld „Anwendung hinzufügen“ wird angezeigt.

. Geben Sie einen eindeutigen Namen für die Anwendung ein.
. Wählen Sie eine Priorität für die Anwendung aus.
. Klicken Sie auf *Speichern*.


Nachdem eine Anwendung definiert wurde, kann sie den Assets zugewiesen werden.



== Zuweisen von Anwendungen zu Assets

Dieses Verfahren weist die Anwendung beispielhaft einem Host zu.  Sie können einer Anwendung Host, virtuelle Maschine, Volume oder interne Volumes zuweisen.

.Schritte
. Suchen Sie das Asset, dem Sie die Anwendung zuweisen möchten:
. Klicken Sie auf *Abfragen > +Neue Abfrage* und suchen Sie nach Host.
. Aktivieren Sie das Kontrollkästchen links neben dem Host, den Sie mit der Anwendung verknüpfen möchten.
. Klicken Sie auf *Massenaktionen > Anwendung hinzufügen*.
. Wählen Sie die Anwendung aus, der Sie das Asset zuweisen.


Alle neuen Anwendungen, die Sie zuweisen, überschreiben alle Anwendungen auf dem Asset, die von einem anderen Asset abgeleitet wurden.  Beispielsweise erben Volumes Anwendungen von Hosts, und wenn einem Volume neue Anwendungen zugewiesen werden, hat die neue Anwendung Vorrang vor der abgeleiteten Anwendung.


NOTE: In Umgebungen mit einer großen Menge verwandter Assets kann die Vererbung von Anwendungszuweisungen zu diesen Assets mehrere Minuten dauern.  Bitte rechnen Sie mit einer längeren Vererbungszeit, wenn Sie über viele zusammenhängende Vermögenswerte verfügen.

.Nach Abschluss
Nachdem Sie der Anwendung den Host zugewiesen haben, können Sie der Anwendung die restlichen Assets zuweisen.  Um auf die Zielseite der Anwendung zuzugreifen, klicken Sie auf *Verwalten > Anwendung* und wählen Sie die von Ihnen erstellte Anwendung aus.
