---
sidebar: sidebar 
permalink: task_identify_inactive_devices.html 
keywords: inactive, device, remove, removing, identify, identifying 
summary: Wenn Sie inaktive Geräte identifizieren, können Sie sie löschen oder einer aktiven Rolle zuweisen. 
---
= Identifizieren von inaktiven Geräten
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Die Ermittlung der vorhandenen und von wem verwendeten Ressourcen ist entscheidend für die „richtige Dimensionierung“ und die Freigabe ungenutzter Infrastruktur. Ressourcen lassen sich leicht neu zuweisen oder ungenutzte Ressourcen abbauen und unnötige Käufe vermeiden.

Führen Sie die folgenden Schritte aus, um inaktive Assets zu identifizieren.

.Schritte
* Navigieren Sie zu *Observability > Explore -> +New Metric Query*.
* Wählen Sie _Storage_ aus der Dropdown-Liste aus.
* Klicken Sie auf das Zahnrad und fügen Sie _isActive_ als Spalte hinzu.
+
Zeilen, die eine Prüfung anzeigen, sind aktiv. „X“ zeigt inaktive Geräte an.



Um inaktive Geräte zu entfernen, wählen Sie einfach die zu entfernenden Geräte aus, und wählen Sie im Dropdown-Menü *Massenaktionen* die Option _inaktive Geräte löschen_.
