---
sidebar: sidebar 
permalink: task_config_telegraf_consul.html 
keywords: telegraf, installation, install, consul 
summary: Konfiguration des Consul-Datensammlers 
---
= Consul Data Collector
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Data Infrastructure Insights verwendet diesen Datensammler, um Metriken von Consul zu erfassen.



== Installation

. Klicken Sie unter *Observability > Collectors* auf *+Data Collector*. Wählen Sie Konsul.
+
Wenn Sie keinen Agenten für die Sammlung konfiguriert haben, werden Sie auf Ihrem Mandanten zu aufgefordertlink:task_config_telegraf_agent.html["Installieren Sie einen Agenten"].

+
Wenn Sie bereits einen Agenten konfiguriert haben, wählen Sie das entsprechende Betriebssystem oder die entsprechende Plattform aus, und klicken Sie auf *Weiter*.

. Befolgen Sie die Anweisungen auf dem Bildschirm Consul Configuration, um den Datensammler zu konfigurieren. Die Anweisungen hängen vom Betriebssystem oder der Plattform ab, die Sie zur Datenerfassung verwenden.




== Einrichtung

Informationen finden Sie im link:https://www.consul.io/docs/index.html["Dokumentation für Konsul"].



== Objekte und Zähler für Konsul

Folgende Objekte und ihre Zähler werden gesammelt:

[cols="<.<,<.<,<.<,<.<"]
|===
| Objekt: | Kennungen: | Attribute: | Datenpunkte: 


| Konsul | Namespace-ID-Service-Node prüfen | Node-IP Node OS Node UUID Node Name Service Name Check Name Service Service ID Status | Warnung Bei Kritischem Durchgang 
|===


== Fehlerbehebung

Weitere Informationen finden Sie auf der link:concept_requesting_support.html["Support"] Seite.
