---
sidebar: sidebar 
permalink: task_dc_emc_vplex.html 
keywords: data collector, VPLEX, EMC 
summary: Konfigurieren des VPLEX-Datenkollektors. 
---
= Konfigurieren des EMC VPLEX-Datenkollektors
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Dieser Datensammler erfasst Bestands- und Leistungsdaten von EMC VPLEX-Speichersystemen.  Zur Konfiguration benötigt der Datensammler eine IP-Adresse des VPLEX-Servers und ein Domänenkonto auf Administratorebene.


NOTE: Für die Leistungserfassung von Data Infrastructure Insights aus Vplex-Clustern muss der Leistungsarchivdienst betriebsbereit sein, um die CSV-Dateien und Protokolle zu füllen, die Data Infrastructure Insights über SCP-basierte Dateikopien abruft.  NetApp hat festgestellt, dass diese Funktionalität bei vielen Vplex-Firmware-Upgrades/Management-Station-Updates nicht mehr funktioniert.  Kunden, die solche Upgrades planen, möchten Dell/EMC möglicherweise proaktiv fragen, ob diese Funktionalität durch das geplante Upgrade nicht mehr funktionsfähig ist, und wenn ja, wie sie sie wieder aktivieren können, um Lücken in der Leistungstransparenz zu minimieren.  Der Vplex-Leistungscode von Cloud Insight prüft bei jeder Abfrage, ob alle erwarteten Dateien vorhanden sind und ob sie ordnungsgemäß aktualisiert werden. Wenn sie fehlen oder veraltet sind, protokolliert Data Infrastructure Insights Leistungserfassungsfehler.



== Terminologie

Data Infrastructure Insightst erhält die folgenden Bestandsinformationen vom VPLEX-Datensammler.  Für jeden erworbenen Vermögenswerttyp wird die am häufigsten verwendete Terminologie für diesen Vermögenswert angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Cluster | Storage 


| Motor | Speicherknoten 


| Gerät, Systemumfang | Backend-Speicherpool 


| Virtuelles Volume | Volumen 


| Front-End-Port, Back-End-Port | Hafen 


| Verteiltes Gerät | Speichersynchronisierung 


| Speicheransicht | Volumenkarte, Volumenmaske 


| Speichervolumen | Backend-LUN 


| ITLs | Backend-Pfad 
|===
Hinweis: Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diesen Datensammler darstellen.



== Anforderungen

* Eine IP-Adresse der VPLEX-Verwaltungskonsole
* Domänenkonto auf Administratorebene für den VPLEX-Server
* Port 443 (HTTPS).  Erfordert ausgehende Konnektivität zum TCP-Port 443 auf der VPLEX-Verwaltungsstation.
* Aus Leistungsgründen sind Benutzername und Kennwort für den SSH-/SCP-Zugriff schreibgeschützt.
* Aus Leistungsgründen ist Port 22 erforderlich.




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| IP-Adresse der VPLEX-Verwaltungskonsole | IP-Adresse oder vollqualifizierter Domänenname der VPLEX-Verwaltungskonsole 


| Benutzername | Benutzername für VPLEX CLI 


| Passwort | Für VPLEX CLI verwendetes Kennwort 


| Leistung Remote-IP-Adresse | Leistung Remote-IP-Adresse der VPLEX-Verwaltungskonsole 


| Performance Remote-Benutzername | Leistung Remote-Benutzername der VPLEX-Verwaltungskonsole 


| Performance Remote-Passwort | Leistungs-Remotekennwort der VPLEX-Verwaltungskonsole 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Kommunikationsanschluss | Für VPLEX CLI verwendeter Port.  Der Standardwert ist 443. 


| Inventarabfrageintervall (min) | Der Standardwert beträgt 20 Minuten. 


| Anzahl der Verbindungsversuche | Der Standardwert ist 3. 


| Leistungsabfrageintervall (Sek.) | Intervall zwischen Leistungsabfragen. Der Standardwert beträgt 600 Sekunden. 


| Anzahl der Wiederholungsversuche | Der Standardwert ist 2. 
|===


== Fehlerbehebung

Wenn bei diesem Datensammler Probleme auftreten, können Sie Folgendes versuchen:



=== Inventar

[cols="2*"]
|===
| Problem: | Versuchen Sie Folgendes: 


| Fehler: Benutzerauthentifizierung fehlgeschlagen. | Stellen Sie sicher, dass Ihre Anmeldeinformationen für dieses Gerät korrekt sind. 
|===


=== Performance

[cols="2*"]
|===
| Problem: | Versuchen Sie Folgendes: 


| Fehler: Die VPLEX-Leistung für Versionen unter 5.3 wird nicht unterstützt. | Aktualisieren Sie VPLEX auf 5.3 oder höher 


| Fehler: Nicht genügend Daten gesammelt. | • Prüfen Sie den Erfassungszeitstempel in der Protokolldatei und ändern Sie das Abfrageintervall entsprechend. • Warten Sie länger 


| Fehler: Perpetual-Log-Dateien werden nicht aktualisiert. | Bitte kontaktieren Sie den EMC-Support, um die Aktualisierung der permanenten Protokolldateien zu aktivieren 


| Fehler: Das Leistungsabfrageintervall ist zu groß. | Überprüfen Sie den Erfassungszeitstempel in der Protokolldatei ${logfile} und ändern Sie das Abfrageintervall entsprechend 


| Fehler: Die Remote-IP-Adresse der VPLEX-Verwaltungskonsole ist nicht konfiguriert. | Bearbeiten Sie die Datenquelle, um die Performance-Remote-IP-Adresse der VPLEX-Verwaltungskonsole festzulegen. 


| Fehler: Keine Leistungsdaten vom Direktor gemeldet | • Überprüfen Sie, ob die Systemleistungsmonitore ordnungsgemäß ausgeführt werden. • Wenden Sie sich an den EMC-Support, um die Aktualisierung der Protokolldateien des Systemleistungsmonitors zu ermöglichen. 
|===
Weitere Informationen finden Sie in derlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
