---
sidebar: sidebar 
permalink: task_io_density_report_no_root.html 
summary: Beim Abfragen für eine hohe I/O-Dichte möchten Sie Root-Volumes ausschließen. 
keywords: NetApp, root volume, high I/O, 
---
= Berichte zur I/O-Dichte beschreiben nur interne Daten-Volumes
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Das Root-Volume von NetApp enthält Verzeichnisse und Konfigurationsdateien zum Management des Storage-Systems. Beim Abfragen für eine hohe I/O-Dichte möchten Sie diese Root-Volumes ausschließen.

Bei der Überwachung Ihrer Umgebung ist es wichtiger, zu ermitteln, welche internen Datenvolumen eine hohe I/O-Dichte erzeugen. Damit nur die Daten-Volumes präzise ermittelt werden können, müssen die internen NetApp Volumes von Anfragen isoliert werden, die zur Überwachung der I/O-Dichte erforderlich sind.

Dieser Leitfaden beschreibt, wie NetApp Root-Aggregate leicht identifiziert, von den Ergebnissen interner Volume-Abfragen isoliert und Regeln erstellt werden können, die beim Hinzufügen zum System neue NetApp Root-Aggregate ausschließen. Die folgenden Insight Funktionen sorgen dafür, dass die Berichte zur I/O-Dichte von internen Daten-Volumes abgeleitet werden:

* Es wird eine Abfrage erstellt, um alle NetApp Root-Aggregate zu identifizieren, die von Insight überwacht werden.
* Jedem NetApp Root-Aggregat wird eine Annotation zugewiesen.
* Es wird eine Annotation-Regel erstellt, um die Annotation auf neue NetApp Root-Aggregate anzuwenden.


Die in diesem Leitfaden aufgeführten Schritte können auch auf Storage-Systeme anderer Anbieter angewendet werden. Sie müssen die Volumes identifizieren, die Verzeichnisse und Konfigurationsdateien für die Verwaltung des Speichersystems enthalten, und ähnliche Schritte verwenden, um diese Volumes auszuschließen.



== Erstellen einer Abfrage zur Identifizierung von NetApp-Root-Aggregaten

Abfragen ermöglichen die Suche auf granularer Ebene, basierend auf vom Benutzer ausgewählten Kriterien. Mithilfe einer Abfrage können Sie in Ihrem Mandanten nach internen Volumes suchen, die das Root-Aggregat von NetApp enthalten.

.Schritte
. Erstellen Sie eine Abfrage, um NetApp-Root-Aggregate auf Ihrem Mandanten zu identifizieren: Klicken Sie auf *Abfragen > Neue Abfrage > Ressourcentyp auswählen* (?)
. Klicken Sie auf *Speicherpool*
. Geben Sie den Namen für das Root-Aggregat ein
+
Dieses Beispiel verwendet für den Namen „aggr0“. Beim Erstellen eines Aggregats müssen nur die folgenden Anforderungen für den Namen erfüllt werden:

+
.. Er muss entweder mit einem Buchstaben oder einem Unterstrich (_) beginnen.
.. Er darf nur Buchstaben, Ziffern und Unterstriche enthalten.
.. Sie kann maximal 250 Zeichen umfassen. In den meisten Fällen ist das Aggregat der Name aggr0, aggr_0, oder etwas ähnliches. Es kann ein iterativer Prozess erforderlich sein, um alle NetApp-Root-Aggregate auf dem Mandanten zu identifizieren.


. Klicken Sie auf *Speichern* und geben Sie einen Namen für die neue Abfrage ein.
+
Wie bereits erwähnt, könnte dies ein iterativer Prozess sein und mehrere Anfragen zur Identifizierung aller NetApp Root-Aggregate erfordern.





== Erstellen Sie eine Anmerkung für die von Ihren Abfragen zurückgegebenen Root-Volumes

Anmerkungen sind spezielle Notizen, die Sie Ihren Assets zuweisen, damit Sie Assets nach ihren Anmerkungen filtern können. Die von Ihnen erstellte Annotation dient dazu, die NetApp-Root-Aggregate Ihres Mandanten zu identifizieren und sicherzustellen, dass diese nicht in einem bestimmten Bericht enthalten sind.

.Bevor Sie beginnen
Sie müssen alle Root-Aggregate identifiziert haben, die Sie aus dem Bericht „hohe I/O-Dichte“ ausschließen möchten.

.Schritte
. Klicken Sie im Menü Data Infrastructure Insights auf *Verwalten > Anmerkungen*
. Klicken Sie Auf *Hinzufügen*
+
.. Geben Sie den Namen für die Anmerkung ein: *RootAggr*
.. Geben Sie eine Beschreibung der Anmerkung ein: *Root-Aggregat aus dem Bericht "hohe I/O-Dichte" entfernen*
.. Geben Sie den Typ der Anmerkung ein: *Boolean*


. Klicken Sie Auf *Speichern*




== Erstellen einer Annotation-Regel, um bestimmte Aggregate aus Ihrem I/O-Dichtebericht zu automatisieren

Alternativ zum manuellen Anwenden von Anmerkungen auf einzelne Assets können Sie mithilfe von Anmerkungsregeln automatisch Anmerkungen auf mehrere Assets anwenden. Anmerkungsregeln basieren auf Abfragen, die Sie erstellen, und wenn sie auf dem System ausgeführt werden, fügen sie vorhandenen Assets neue Assets hinzu. Wenn diese Vermögenswerte von einem Bericht ausgeschlossen werden, werden auch die neuen Vermögenswerte automatisch ausgeschlossen.

.Bevor Sie beginnen
Sie müssen eine Abfrage zur Identifikation der NetApp-Root-Aggregate erstellt und gespeichert haben, die Sie auf Ihrem Mandanten identifiziert haben.

.Schritte
. Klicken Sie in der Symbolleiste Data Infrastructure Insights auf *Verwalten > Anmerkungsregeln*.
. Klicken Sie Auf *Hinzufügen*. Das Dialogfeld Regel hinzufügen wird angezeigt.
+
.. Geben Sie im Feld Name einen eindeutigen Namen ein, der die Regel *"RootAggrExclude"* beschreibt
.. Klicken Sie auf Query und wählen Sie die Abfrage aus, die Insight verwenden soll, um die Annotationsregel auf: *„Aggregate0“* anzuwenden
.. Klicken Sie auf Anmerkung und wählen Sie *"Root agg exclude"*
.. Klicken Sie auf *Wert* und geben Sie *true* ein



