---
sidebar: sidebar 
permalink: task_dc_na_solidfire.html 
summary: Konfigurieren des NetApp SolidFire Datenkollektors 
keywords: data collector, queries, create 
---
= NetApp SolidFire All-Flash Array-Datenkollektor
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Der NetApp SolidFire All-Flash Array-Datenkollektor unterstützt die Bestandsaufnahme und Leistungserfassung von iSCSI- und Fibre Channel SolidFire Konfigurationen.

Der SolidFire Datensammler verwendet die SolidFire REST-API.  Die Erfassungseinheit, auf der sich der Datensammler befindet, muss in der Lage sein, HTTPS-Verbindungen zum TCP-Port 443 der SolidFire -Clusterverwaltungs-IP-Adresse herzustellen.  Der Datensammler benötigt Anmeldeinformationen, die REST-API-Abfragen im SolidFire Cluster durchführen können.



== Terminologie

Data Infrastructure Insights erhält die folgenden Bestandsinformationen vom NetApp SolidFire All-Flash Array-Datenkollektor.  Für jeden von Data Infrastructure Insights erworbenen Asset-Typ wird die am häufigsten verwendete Terminologie für dieses Asset angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Fahren | Scheibe 


| Cluster | Storage 


| Node | Speicherknoten 


| Volumen | Volumen 


| Fibre-Channel-Anschluss | Hafen 


| Volume-Zugriffsgruppe, LUN-Zuweisung | Volumenkarte 


| iSCSI-Sitzung | Volumenmaske 
|===
Hinweis: Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diesen Datensammler darstellen.



== Anforderungen

Für die Konfiguration dieses Datensammlers gelten die folgenden Voraussetzungen:

* Virtuelle Verwaltungs-IP-Adresse
* Benutzername und Anmeldeinformationen sind schreibgeschützt
* Port 443




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Virtuelle Verwaltungs-IP-Adresse (MVIP) | Virtuelle IP-Adresse des SolidFire -Clusters verwalten 


| Benutzername | Name, der für die Anmeldung beim SolidFire -Cluster verwendet wird 


| Passwort | Kennwort zum Anmelden beim SolidFire -Cluster 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Verbindungstyp | Verbindungstyp auswählen 


| Kommunikationsanschluss | Für die NetApp API verwendeter Port 


| Inventarabfrageintervall (min) | Der Standardwert ist 20 Minuten 


| Leistungsabfrageintervall (Sek.) | Der Standardwert ist 300 Sekunden 
|===


== Fehlerbehebung

Wenn SolidFire einen Fehler meldet, wird dieser in Data Infrastructure Insights wie folgt angezeigt:

_Beim Versuch, Daten abzurufen, wurde eine Fehlermeldung von einem SolidFire -Gerät empfangen.  Der Aufruf war <Methode> (<ParameterString>).  Die Fehlermeldung des Geräts lautete (siehe Gerätehandbuch): <message>_

Wo:

* Die <Methode> ist eine HTTP-Methode, beispielsweise GET oder PUT.
* Der <parameterString> ist eine durch Kommas getrennte Liste von Parametern, die im REST-Aufruf enthalten waren.
* Die <message> ist die vom Gerät zurückgegebene Fehlermeldung.


Weitere Informationen zu diesem Datensammler finden Sie imlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
