---
sidebar: sidebar 
permalink: task_dc_ibm_svc.html 
keywords: IBM, SVC,SAN 
summary: Konfigurieren des IBM SAN-Volume-Controller-Datensammlers. 
---
= Konfigurieren des IBM SAN Volume Controller-Datensammlers
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Der IBM SAN Volume Controller (SVC)-Datensammler sammelt Bestands- und Performancedaten mithilfe von SSH und unterstützt eine Vielzahl von Geräten, auf denen das SVC-Betriebssystem ausgeführt wird.

Die Liste der unterstützten Geräte umfasst Modelle wie SVC, v7000, v5000 und v3700. Unterstützte Modelle und Firmware-Versionen finden Sie in der Data Infrastructure Insights Supportmatrix.



== Terminologie

Data Infrastructure Insights erfasst die folgenden Inventarinformationen aus dem IBM SVC-Datensammler. Für jeden Asset-Typ, der von Data Infrastructure Insights erworben wurde, wird die für diese Ressource am häufigsten verwendete Terminologie angezeigt. Beachten Sie bei der Anzeige oder Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter-/Modelllaufzeit | Einblicke Aus Der Dateninfrastruktur 


| Laufwerk | Festplatte 


| Cluster | Storage 


| Knoten | Storage-Node 


| Mdisk-Gruppe | Storage-Pool 


| Vdisk | Datenmenge 


| Mdisk | Back-End-LUNs und -Pfade 
|===
Hinweis: Es handelt sich hierbei nur um allgemeine Terminologiezuordnungen. Diese stellen für diesen Datensammler möglicherweise nicht alle Fälle dar.



=== Inventaranforderungen

* IP-Adresse jedes SVC-Clusters
* Port 22 verfügbar
* Schreibgeschützter Benutzername und Kennwort




=== Performance-Anforderungen Erfüllt

* SVC-Konsole, die für jeden SVC-Cluster obligatorisch und für das Foundation-Paket für die SVC-Erkennung erforderlich ist
* Mit den Anmeldedaten ist nur Administratorzugriff erforderlich, um Performance-Dateien von Cluster-Nodes auf den Konfigurations-Node zu kopieren.
* Aktivieren Sie die Datensammlung, indem Sie über SSH eine Verbindung zum SVC-Cluster herstellen und ausführen: _Svctask startstats -Interval 1_
+
Hinweis: Alternativ können Sie die Datenerfassung über die SVC Management-Benutzeroberfläche aktivieren.





== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Cluster-IP-Adressen | IP-Adressen oder vollqualifizierte Domain-Namen des SVC-Speichers 


| Benutzername Des Inventurbenutzers | Benutzername für die SVC-CLI 


| Inventurpasswort | Passwort für die SVC-CLI 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Abfrageintervall für Bestand (min) | Intervall zwischen Bestandsabstimmungen Die Standardeinstellung ist 40 Minuten. 


| Leistungsintervall (Sek.) | Intervall zwischen Performance-Abstimmungen Die Standardeinstellung ist 300 Sekunden. 


| Um dumpte Statistikdateien zu bereinigen | Aktivieren Sie dieses Kontrollkästchen, um heruntergelegte Statistikdateien zu bereinigen 
|===


== Fehlerbehebung

Einige Dinge zu versuchen, wenn Sie Probleme mit diesem Datensammler stoßen:

[cols="2*"]
|===
| Problem: | Versuchen Sie dies: 


| Fehler: „Der Befehl kann nicht initiiert werden, da er nicht auf dem Konfigurations-Node ausgeführt wurde.“ | Der Befehl muss auf dem Konfigurationsknoten ausgeführt werden. 
|===
Einige Dinge zu versuchen, wenn Sie Probleme mit diesem Datensammler stoßen:

[cols="2*"]
|===
| Problem: | Versuchen Sie dies: 


| Fehler: „Der Befehl kann nicht initiiert werden, da er nicht auf dem Konfigurations-Node ausgeführt wurde.“ | Der Befehl muss auf dem Konfigurationsknoten ausgeführt werden. 
|===
Weitere Informationen zu diesem Data Collector finden Sie auf der link:concept_requesting_support.html["Support"] Seite oder im link:reference_data_collector_support_matrix.html["Data Collector Supportmatrix"].
