---
sidebar: sidebar 
permalink: task_cs_add_collector_ontap.html 
keywords: data collector, ONTAP, SVM 
summary: Hinzufügen von Datensammlern 
---
= Konfigurieren des NetApp ONTAP Data Collectors
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Workload Security verwendet Datensammler, um Datei- und Benutzerzugriffsdaten von Geräten zu erfassen. Die Daten werden der Workload Security zur Analyse zur Verfügung gestellt.

.Bevor Sie beginnen
Sie benötigen die folgenden Informationen, um diesen Datensammler zu konfigurieren:

* Ein Agent muss für das Sammeln von Daten konfiguriert sein
* Die SVM-Management-IP-Adresse
* Ein Benutzername für den Zugriff auf die SVM
* Das Passwort für den Zugriff auf die SVM


.Schritte zur Konfiguration
. Melden Sie sich als Administrator oder Account-Inhaber an Ihrer Workload Security-Umgebung an.
. Klicken Sie Auf *Observability > Collectors > +Data Collectors*
+
Das System zeigt die verfügbaren Datensammler an.

. Klicken Sie auf *+Monitor* in der Kachel NetApp ONTAP.
+
Das System zeigt die Konfigurationsseite Data Collector: ONTAP SVM hinzufügen an.

. Geben Sie einen eindeutigen Namen für den Sammler ein
. Wählen Sie den Agenten aus, der die Daten sammelt
. Geben Sie die SVM-Management-IP-Adresse ein
. Geben Sie den Benutzernamen für den Zugriff auf die SVM ein
. Geben Sie das Passwort für den Zugriff auf die SVM ein
. Klicken Sie Auf *+Collector Hinzufügen*


.Nachdem Sie fertig sind
* Klicken Sie auf *Workload Security > Collectors*, um den Status des konfigurierten Collectors zu überprüfen.
+
Es liegt normalerweise eine Verzögerung vor der Anzeige des Kollektorstatus vor.


