---
sidebar: sidebar 
permalink: task_dc_emc_vnx_file.html 
keywords: data collector, Celerra, EMC, DELL, VNX File 
summary: Konfigurieren des DELL EMC Celerra-Datenkollektors. 
---
= DELL EMC VNX File (früher Celerra Unified Storage System) Datenkollektor
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Dieser Datensammler ruft Inventarinformationen vom VNX File Storage System ab.  Zur Konfiguration benötigt dieser Datensammler die IP-Adresse der Speicherprozessoren sowie einen schreibgeschützten Benutzernamen und ein Passwort.



== Terminologie

Data Infrastructure Insights erhält die folgenden Bestandsinformationen vom VNX File-Datenkollektor.  Für jeden von Data Infrastructure Insights erworbenen Asset-Typ wird die am häufigsten verwendete Terminologie für dieses Asset angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Celerra-Netzwerkserver/Celerra-Speicherpool | Speicherpool 


| Dateisystem | Internes Volumen 


| Datenverschieber | Regler 


| Auf einem Data Mover gemountetes Dateisystem | Dateifreigabe 


| CIFS- und NFS-Exporte | Aktie 


| Datenträgervolumen | Backend-LUN 
|===
Hinweis: Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diesen Datensammler darstellen.



== Anforderungen

Zur Konfiguration dieses Datensammlers benötigen Sie Folgendes:

* Die IP-Adresse des Speicherprozessors
* Benutzername und Kennwort nur zum Lesen
* SSH-Port 22




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| VNX-Datei-IP-Adresse | IP-Adresse oder vollqualifizierter Domänenname des VNX-Dateigeräts 


| Benutzername | Name, der für die Anmeldung beim VNX-Dateigerät verwendet wird 


| Passwort | Kennwort zum Anmelden beim VNX-Dateigerät 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Inventarabfrageintervall (Minuten) | Intervall zwischen den Bestandsabfragen. Der Standardwert beträgt 20 Minuten. 
|===


== Fehlerbehebung

Wenn bei diesem Datensammler Probleme auftreten, können Sie Folgendes versuchen:



=== Inventar

[cols="2*"]
|===
| Problem: | Versuchen Sie Folgendes: 


| Fehler: Fortfahren nicht möglich, während DART-Update läuft | Mögliche Lösung: Halten Sie den Datensammler an und warten Sie, bis das DART-Upgrade abgeschlossen ist, bevor Sie eine weitere Erfassungsanforderung versuchen. 
|===
Weitere Informationen finden Sie in derlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
