---
sidebar: sidebar 
permalink: task_dc_brocade_rest.html 
keywords: data collector, Brocade, FC switch, FOS, Rest 
summary: Konfigurieren des Brocade FOS REST-Datensammlers 
---
= Brocade FOS REST Data Collector
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights verwendet den Brocade FOS REST Collector, um Bestand und Performance für Brocade-Switch-Geräte mit FabricOS (FOS) Firmware 8.2 und höher zu ermitteln.

Bitte beachten Sie: FOS' Standard "user"-Ebene ist nicht ausreichend leistungsfähig, damit Data Infrastructure Insights alle logischen Aspekte eines Geräts anzeigen kann - wir benötigen ein Benutzerkonto mit aktivierter "Chassis Role" sowie Berechtigungen für alle auf einem Switch konfigurierten virtuellen Fabrics.

Hier ist ein Beispiel dafür, wie Sie ein Benutzerkonto mit den geringsten Berechtigungen für die Verwendung von Data Infrastructure Insights in einer SSH-Sitzung auf einem FOS-Gerät erstellen können:

UserConfig --add NetAppCIUser -r user -l 1-128 -c user -p Qwerty!

Dadurch wird ein User „NetAppCIUser“ mit einem Passwort von „Qwerty!“ eingerichtet. Dieser Benutzer hat die „user“-Rolle (-r) für alle 128 möglichen virtuellen Fabrics ( -l ). Dieser Benutzer verfügt zusätzlich über die erforderliche „Chassis“-Rolle ( -c) mit zugewiesenem Zugriff auf Benutzerebene.

Standardmäßig versucht dieser Collector, alle FOS-Geräte zu ermitteln, die Teil aller Fabrics sind, zu denen der Switch gehört.



== Terminologie

Data Infrastructure Insights erfasst die folgenden Bestandsinformationen aus dem Brocade FOS REST Data Collector. Für jeden Asset-Typ, der von Data Infrastructure Insights erworben wurde, wird die für diese Ressource am häufigsten verwendete Terminologie angezeigt. Beachten Sie bei der Anzeige oder Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter-/Modelllaufzeit | Einblicke Aus Der Dateninfrastruktur 


| Switch | Switch 


| Port | Port 


| Virtual Fabric, Physische Fabric | Fabric 


| Zone | Zone 


| Logischer Switch | Logischer Switch 


| LSAN-Zone zu erreichen | IVR-Zone zu erreichen 
|===
Hinweis: Es handelt sich hierbei nur um allgemeine Terminologiezuordnungen. Diese stellen für diesen Datensammler möglicherweise nicht alle Fälle dar.



== Anforderungen

* Es muss eine TCP-Verbindung zu allen Switches in der Fabric vorhanden sein. Dieser Datensammlertyp versucht nahtlos sowohl HTTP als auch HTTPS für jedes Gerät in der Fabric. Wenn Sie das Kontrollkästchen _Discover all Switches in the Fabric_ aktivieren, identifiziert Data Infrastructure Insights alle Switches in der Fabric; es benötigt jedoch TCP-Konnektivität zu diesen zusätzlichen Switches, um sie zu erkennen.
* Weltweit ist dasselbe Konto über alle Switches in der Fabric erforderlich. Sie können den Zugriff über die Webschnittstelle des Geräts bestätigen.




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Switch-IP | IP-Adresse oder vollständig qualifizierter Domänenname des FOS-Switches 


| Benutzername | Benutzername für den Switch 


| Passwort | Passwort für den Switch 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Ausgeschlossene Geräte | Kommagetrennte Liste der Geräte-IPv4-Adressen, die von der Abfrage ausgeschlossen werden sollen. 


| Abfrageintervall für Bestand (min) | Intervall zwischen Bestandsabstimmungen Der Standardwert ist 60. 


| Erkennung aller Switches in der Fabric | Wählen Sie diese Option aus, um alle Switches in der Fabric zu ermitteln. 


| Wählen Sie „HBA vs. Zone Aliases bevorzugen“ | Wählen Sie aus, ob HBA- oder Zonenaliase bevorzugt werden sollen. 


| Verbindungstyp | HTTP oder HTTPS. 


| Beachten Sie, dass diese Einstellung nur ändert, welches Protokoll-CI zuerst pro Gerät verwendet. CI versucht automatisch, das andere Protokoll zu verwenden, wenn die Standardeinstellung fehlschlägt | TCP-Port überschreiben 


| Geben Sie einen Port an, wenn der Standardwert nicht verwendet wird. | Leistungsintervall (Sek.) 
|===


== Fehlerbehebung

Einige Dinge zu versuchen, wenn Sie Probleme mit diesem Datensammler stoßen:



=== Inventar

[cols="2*"]
|===
| Problem: | Versuchen Sie dies: 


| Die Testfunktion warnt mich, dass ein Protokoll nicht zugänglich ist | Ein bestimmtes Brocade FOS 8.2+ Gerät will nur über HTTP oder HTTPS sprechen - wenn ein Switch ein digitales Zertifikat installiert hat, wirft der Switch HTTP-Fehler auf, wenn man versucht, mit unverschlüsseltem HTTP gegen HTTPS zu kommunizieren. Die Testfunktion versucht die Kommunikation mit HTTP und HTTPS - wenn der Test Ihnen mitteilt, dass ein Protokoll erfolgreich ist, können Sie den Collector sicher speichern und sich keine Sorgen machen, dass das andere Protokoll nicht erfolgreich war - der Collector versucht beide Protokolle während der Sammlung und schlägt nur fehl, wenn keines funktioniert. 


| Fehler: „Data Infrastructure Insights received invalid Chassis role“ | Vergewissern Sie sich, dass dem in dieser Datenquelle konfigurierten Benutzer die Berechtigung für die Gehäuserolle erteilt wurde. 


| Fehler: „IP-Adresse des Gehäuses nicht stimmt überein“ | Ändern Sie die Konfiguration der Datenquelle, um die Gehäuse-IP-Adresse zu verwenden. 


| Die Inventur schlägt mit einer 403 Verbotenen fehl | Dies kann einfach schlechte Anmeldeinformationen sein, oder es kann bezeichnend sein, dass Sie versuchen, eine nicht ausreichend leistungsstarke Rolle zu verwenden - denken Sie daran, dass Benutzer auf Benutzerebene nicht über das erforderliche Recht auf „Gehäuserolle“ verfügen oder den Zugriff auf nicht standardmäßige virtuelle Fabrics anzeigen. 
|===
Weitere Informationen finden Sie auf der link:concept_requesting_support.html["Support"] Seite oder im link:reference_data_collector_support_matrix.html["Data Collector Supportmatrix"].
