---
sidebar: sidebar 
permalink: task_dc_pure_flashblade.html 
keywords: data collector, Pure Storage, pure, FlashBlade 
summary: Konfigurieren des Pure Storage-Datensammlers. 
---
= Pure Storage FlashBlade-Datensammler
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights verwendet den Pure Storage FlashBlade-Datensammler, um Bestands- und Leistungsdaten von FlashBlade-Clustern zu sammeln, die Version 2 ihrer REST-API bereitstellen.



== Terminologie

Für jeden von Data Infrastructure Insights erfassten Asset-Typ wird die am häufigsten verwendete Terminologie für das Asset angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Laufwerk (SSD) | Scheibe 


| Anordnung | Storage 


| Klinge | Speicherknoten 


| Dateisystem | Internes Volumen 


| Objektspeicher-Bucket | Qtree 


| Initiator, Ziel | Volumenmaske 
|===
Hinweis: Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diesen Datensammler darstellen.



== Anforderungen

* IP-Adresse oder vollqualifizierter Domänenname des Speichersystems
* API-Token, idealerweise mit unbegrenzter Lebensdauer.  Ein Benutzer mit Leseberechtigung sollte ausreichen.
* Portanforderung: HTTPS 443




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| FlashBlade-Host-IP-Adresse | IP-Adresse des Speichersystems 


| Benutzername | Benutzername, damit sich Data Infrastructure Insights -Administratoren merken können, zu welchem ​​Benutzer ihr API-Token gehört 


| API-Token | API-Token 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Anschlussart | Wählen Sie HTTP oder HTTPS.  Zeigt auch den Standardport an. 


| TCP-Port überschreiben | Wenn das Feld „Verbindungstyp“ leer ist, verwenden Sie den Standardport. Andernfalls geben Sie den zu verwendenden Verbindungsport ein. 


| Inventarabfrageintervall (min) | Der Standardwert beträgt 60 Minuten 


| Leistungsabfrageintervall (Sek.) | Der Standardwert ist 300 
|===


== Fehlerbehebung

Wenn bei diesem Datensammler Probleme auftreten, können Sie Folgendes versuchen:



=== Inventar

[cols="2*"]
|===
| Problem: | Versuchen Sie Folgendes: 


| „Ungültige Anmeldeinformationen“ mit den Fehlermeldungen „Richtlinie lässt dies nicht zu“ oder „Sie sind nicht autorisiert“ | Validieren Sie das Pure-Benutzerkonto und das Passwort über die Pure-HTTP-Schnittstelle 
|===
Weitere Informationen finden Sie in derlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
