---
sidebar: sidebar 
permalink: task_view_configured_data_collectors.html 
keywords: acquisition, AU, data collector, collector, bulk edit, postpone polling, resume polling 
summary: Eine Zusammenfassung. 
---
= Verwalten konfigurierter Datenkollektoren
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die Seite „Installierte Datensammler“ bietet Zugriff auf die Datensammler, die für Data Infrastructure Insights konfiguriert wurden.  Auf dieser Seite können Sie vorhandene Datensammler ändern.

.Schritte
. Klicken Sie im Menü „Data Infrastructure Insights“ auf *Observability > Collectors*
+
Der Bildschirm „Verfügbare Datensammler“ wird angezeigt.

. Klicken Sie auf *Installierte Datensammler*
+
Es wird eine Liste aller installierten Datensammler angezeigt.  Die Liste enthält den Namen und Status des Collectors, die IP-Adresse, auf die der Collector zugreift, und das Datum, an dem zuletzt Daten von einem Gerät abgerufen wurden.  Auf diesem Bildschirm können unter anderem folgende Aktionen ausgeführt werden:

+
** Kontrollabfragen
** Ändern der Anmeldeinformationen des Datensammlers
** Klonen von Datensammlern






== Steuern der Datensammlerabfrage

Nachdem Sie eine Änderung an einem Datensammler vorgenommen haben, möchten Sie möglicherweise, dass dieser sofort eine Abfrage durchführt, um Ihre Änderungen zu überprüfen. Oder Sie möchten die Datenerfassung auf einem Datensammler um einen, drei oder fünf Tage verschieben, während Sie an einem Problem arbeiten.

.Schritte
. Klicken Sie im Menü „Data Infrastructure Insights“ auf *Observability > Collectors*
. Klicken Sie auf *Installierte Datensammler*
. Aktivieren Sie das Kontrollkästchen links neben dem Datensammler, den Sie ändern möchten
. Klicken Sie auf *Massenaktionen* und wählen Sie die gewünschte Umfrageaktion aus.
+
Massenaktionen können gleichzeitig auf mehreren Datensammlern ausgeführt werden.  Wählen Sie die Datensammler aus und wählen Sie die auszuführende Aktion aus dem Menü *Massenaktion*.





== Bearbeiten von Datenkollektorinformationen

Sie können vorhandene Einrichtungsinformationen des Datensammlers bearbeiten.

.So bearbeiten Sie einen einzelnen Datensammler:
. Klicken Sie im Menü „Data Infrastructure Insights“ auf *Observability > Collectors*, um die Liste der installierten Datensammler zu öffnen.
. Klicken Sie im Optionsmenü rechts neben dem Datensammler, den Sie ändern möchten, auf *Bearbeiten*.
+
Der Dialog „Collector bearbeiten“ wird geöffnet.

. Geben Sie die Änderungen ein und klicken Sie auf *Konfiguration testen*, um die neue Konfiguration zu testen, oder klicken Sie auf *Speichern*, um die Konfiguration zu speichern.


Sie können auch mehrere Datensammler bearbeiten:

. Aktivieren Sie das Kontrollkästchen links neben jedem Datensammler, den Sie ändern möchten.
. Klicken Sie auf die Schaltfläche *Massenaktionen* und wählen Sie *Bearbeiten*, um das Dialogfeld „Datensammler bearbeiten“ zu öffnen.
. Ändern Sie die Felder wie oben.
+

NOTE: Die ausgewählten Datensammler müssen vom selben Anbieter und Modell sein und sich auf derselben Erfassungseinheit befinden.

+
Beim Bearbeiten mehrerer Datensammler wird im Feld „Name des Datensammlers“ „Gemischt“ angezeigt und kann nicht bearbeitet werden.  Andere Felder wie Benutzername und Passwort zeigen „Gemischt“ an und können bearbeitet werden.  Felder, die in allen ausgewählten Datensammlern denselben Wert aufweisen, zeigen die aktuellen Werte an und können bearbeitet werden.

+
Beim Bearbeiten mehrerer Datensammler ist die Schaltfläche *Konfiguration testen* nicht verfügbar.





== Klonen von Datenkollektoren

Mithilfe der Klonfunktion können Sie schnell eine Datenquelle hinzufügen, die über dieselben Anmeldeinformationen und Attribute wie eine andere Datenquelle verfügt.  Durch Klonen können Sie problemlos mehrere Instanzen desselben Gerätetyps konfigurieren.

.Schritte
. Klicken Sie im Menü „Data Infrastructure Insights“ auf *Observability > Collectors*.
. Klicken Sie auf *Installierte Datensammler*.
. Klicken Sie auf das Kontrollkästchen links neben dem Datensammler, den Sie kopieren möchten.
. Klicken Sie im Optionsmenü rechts neben dem ausgewählten Datensammler auf *Klonen*.
+
Das Dialogfeld „Datensammler klonen“ wird angezeigt.

. Geben Sie in den erforderlichen Feldern neue Informationen ein.
. Klicken Sie auf *Speichern*.


.Nach Abschluss
Der Klonvorgang kopiert alle anderen Attribute und Einstellungen, um den neuen Datensammler zu erstellen.



== Durchführen von Massenaktionen auf Datensammlern

Sie können einige Informationen für mehrere Datensammler gleichzeitig bearbeiten.  Mit dieser Funktion können Sie eine Umfrage starten, die Umfrage verschieben und die Umfrage auf mehreren Datensammlern fortsetzen.  Darüber hinaus können Sie mehrere Datensammler löschen.

.Schritte
. Klicken Sie im Menü „Data Infrastructure Insights“ auf *Observability > Collectors*
. Klicken Sie auf *Installierte Datensammler*
. Klicken Sie auf das Kontrollkästchen links neben den Datensammlern, die Sie ändern möchten.
. Klicken Sie im Optionsmenü rechts auf die Option, die Sie ausführen möchten.


.Nach Abschluss
Der von Ihnen ausgewählte Vorgang wird auf den Datensammlern ausgeführt.  Wenn Sie sich für das Löschen von Datensammlern entscheiden, wird ein Dialogfeld angezeigt, in dem Sie aufgefordert werden, die Aktion zu bestätigen.
