---
sidebar: sidebar 
permalink: task_dc_ibm_ds4000.html 
keywords: data collector, IBM, DS4000 
summary: IBM TotalStorage DS4000 Datenkollektor 
---
= IBM TotalStorage DS4000 Datenkollektor
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Dieser Datensammler erfasst Bestands- und Leistungsinformationen vom IBM DS4000-Speichersystem.  Es gibt zwei mögliche Konfigurationen (Firmware 6.x und Firmware 7.x+) und beide haben die gleichen Werte.



== Terminologie

Data Infrastructure Insights erhält die folgenden Bestandsinformationen vom IBM DS4000-Datenkollektor.  Für jeden erworbenen Vermögenswerttyp wird die am häufigsten verwendete Terminologie für diesen Vermögenswert angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Scheibe | Scheibe 


| Volumengruppe | Datenträgergruppe 


| Speicher-Array | Storage 


| Regler | Speicherknoten 


| Volumengruppe | Speicherpool 


| Volumen | Volumen 
|===
Hinweis: Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diesen Datensammler darstellen.



== Anforderungen

* IP-Adresse jedes DS5- oder FAStT-Arrays
* Zugriffsvalidierung durch Pingen der IP-Adresse beider Controller auf dem Array
* Portanforderungen: 2463




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Durch Kommas getrennte Liste der Array SANtricity Controller-IPs | IP-Adressen und/oder vollqualifizierte Domänennamen für die Array-Controller 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Inventarabfrageintervall (min) | Der Standardwert ist 30 Minuten 


| Leistungsabfrageintervall bis zu 3600 Sekunden | Der Standardwert ist 300 Sekunden 
|===


== Fehlerbehebung

Weitere Informationen zu diesem Datensammler finden Sie imlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
