---
sidebar: sidebar 
permalink: task_dc_brocade_bna.html 
keywords: data collector, Brocade, BNA 
summary: Konfigurieren von Brocade BNA Collector 
---
= Datensammler Brocade Network Advisor
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Dateninfrastrukturanalysen verwenden den Datensammler Brocade Netzwerkberater, um Bestands- und Performancedaten von Brocade-Switches zu erfassen.



== Terminologie

Data Infrastructure Insights erfasst die folgenden Inventarinformationen aus dem Brocade Netzwerkberater-Datensammler. Für jeden Asset-Typ, der von Data Infrastructure Insights erworben wurde, wird die für diese Ressource am häufigsten verwendete Terminologie angezeigt. Beachten Sie bei der Anzeige oder Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter-/Modelllaufzeit | Einblicke Aus Der Dateninfrastruktur 


| Switch | Switch 


| Port | Port 


| Virtual Fabric, Physische Fabric | Fabric 


| Logischer Switch | Logischer Switch 
|===
Hinweis: Es handelt sich hierbei nur um allgemeine Terminologiezuordnungen. Diese stellen für diesen Datensammler möglicherweise nicht alle Fälle dar.



== Anforderungen

Zur Konfiguration dieses Datensammlers sind folgende Voraussetzungen erforderlich:

* Die Data Infrastructure Insights Acquisition Unit führt Verbindungen zu TCP-Port 443 auf dem BNA-Server ein. BNA-Server muss Version 14.2.1 oder höher ausführen.
* IP-Adresse des Brocade Network Advisor Servers
* Benutzername und Kennwort für ein Administratorkonto
* Port-Anforderung: HTTP/HTTPS 443




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Brocade Network Advisor Server IP | IP-Adresse des Network Advisor-Servers 


| Benutzername | Benutzername für den Switch 


| Benutzername | Administrator-Benutzername 


| Passwort | Administratorpasswort 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Verbindungstyp | HTTPS (Standardport 443) oder HTTP (Standardport 80) 


| Verbindungs-Port Überschreiben | Wenn Sie leer sind, verwenden Sie den Standardport im Feld Verbindungstyp. Andernfalls geben Sie den zu verwendenden Anschluss ein 


| Passwort | Passwort für den Switch 


| Abfrageintervall für Bestand (min) | Der Standardwert ist 40 


| Access Gateway Melden | Aktivieren Sie diese Option, um Geräte im Access Gateway-Modus einzubeziehen 


| Leistungsintervall (Sek.) | Der Standardwert ist 1800 
|===


== Fehlerbehebung

Einige Dinge zu versuchen, wenn Sie Probleme mit diesem Datensammler stoßen:



=== Inventar

[cols="2*"]
|===
| Problem: | Versuchen Sie dies: 


| Sie erhalten eine Meldung, dass mehr als 1 Knoten am Access Gateway-Port angemeldet ist, oder Datensammler kann das Access Gateway-Gerät nicht erkennen. | Überprüfen Sie, ob das NPV-Gerät ordnungsgemäß funktioniert und dass alle verbundenen WWNs erwartet werden. Erwerben Sie das NPV-Gerät nicht direkt. Stattdessen erfasst die Akquisition des Core Fabric Switch die NPV Geräte-Daten. 
|===
Weitere Informationen finden Sie auf der link:concept_requesting_support.html["Support"] Seite oder im link:reference_data_collector_support_matrix.html["Data Collector Supportmatrix"].
