---
sidebar: sidebar 
permalink: task_query_copy_table_values.html 
summary: Tabellenwerte können mithilfe der Textauswahl oder der Ein-Klick-Kopierung in die Zwischenablage kopiert werden, was einen effizienten Datentransfer in Suchfelder und externe Anwendungen ermöglicht. 
keywords: query, queries, copy, values, clipboard 
---
= Tabellenwerte kopieren
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Optimieren Sie Ihren Workflow, indem Sie Tabellenwerte direkt in die Zwischenablage kopieren und für Suchvorgänge oder externe Anwendungen verwenden. Es besteht die Wahl zwischen manueller Textauswahl oder komfortablem Kopieren mit einem Klick für Felder mit Einzelwerten und Asset-Links.

.Informationen zu diesem Vorgang
Es gibt zwei Methoden, mit denen Sie Werte aus Tabellen oder Abfrageergebnissen in die Zwischenablage kopieren können.

.Schritte
. Methode 1: Markieren Sie den gewünschten Text mit der Maus, kopieren Sie ihn und fügen Sie ihn in Suchfelder oder andere Anwendungen ein.
. Methode 2: Bewegen Sie bei Einzelwertfeldern den Mauszeiger über das Feld und klicken Sie auf das angezeigte Zwischenablagesymbol.  Der Wert wird zur Verwendung in Suchfeldern oder anderen Anwendungen in die Zwischenablage kopiert.
+
Beachten Sie, dass mit dieser Methode nur Werte kopiert werden können, die Links zu Assets sind.  Nur Felder, die einzelne Werte enthalten (also keine Listen sind), verfügen über das Kopiersymbol.


