---
sidebar: sidebar 
permalink: task_create_application.html 
summary: Sie definieren Anwendungen, die Sie dann bei Bedarf auf Anlagen auf Ihrem Mandanten anwenden. 
keywords: application, create application, 
---
= Anwendungen Werden Erstellt
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Zum Nachverfolgen von Daten, die bestimmten auf dem Mandanten ausgeführten Applikationen zugeordnet sind, können Sie die Applikationen in Data Infrastructure Insights definieren.

.Über diese Aufgabe
Anhand von Einblicke in die Dateninfrastruktur lassen sich Daten von Applikationen-Assets nachverfolgen, beispielsweise zur Nutzung oder zur Kostenberichterstellung.

.Schritte
. Klicken Sie im Menü Data Infrastructure Insights auf *Observability > Enrich > Applications*. Wählen Sie
+
Das Dialogfeld Anwendung hinzufügen wird angezeigt.

. Geben Sie einen eindeutigen Namen für die Anwendung ein.
. Wählen Sie eine Priorität für die Anwendung aus.
. Klicken Sie Auf *Speichern*.


Nach dem Definieren einer Anwendung kann sie Assets zugewiesen werden.



== Zuweisen von Anwendungen zu Assets

Diese Prozedur weist die Anwendung einem Host als Beispiel zu. Sie können einer Applikation Host, Virtual Machine, Volume oder interne Volumes zuweisen.

.Schritte
. Suchen Sie das Asset, dem Sie der Anwendung zuweisen möchten:
. Klicken Sie auf *Abfragen > +Neue Abfrage* und suchen Sie nach Host.
. Klicken Sie auf das Kontrollkästchen links neben dem Host, den Sie der Anwendung zuordnen möchten.
. Klicken Sie Auf *Massenaktionen > Anwendung Hinzufügen*.
. Wählen Sie die Anwendung aus, der Sie die Anlage zuweisen.


Neue Anwendungen, die Sie zuweisen, überschreiben alle Anwendungen auf dem Asset, die von einem anderen Asset abgeleitet wurden. Beispielsweise übernehmen Volumes Applikationen von Hosts, und wenn neuen Applikationen einem Volume zugewiesen werden, hat die neue Applikation Vorrang vor der abgeleiteten Applikation.


NOTE: In Umgebungen mit großen Mengen verwandter Assets kann die Vererbung von Applikationszuweisungen an diese Ressourcen mehrere Minuten dauern. Bitte geben Sie mehr Zeit für Vererbung, wenn Sie viele verwandte Vermögenswerte haben.

.Nachdem Sie fertig sind
Nachdem Sie den Host der Anwendung zugewiesen haben, können Sie die verbleibenden Assets der Anwendung zuweisen. Um auf die Landing Page für die Anwendung zuzugreifen, klicken Sie auf *Verwalten > Anwendung* und wählen Sie die von Ihnen erstellte Anwendung aus.
