---
sidebar: sidebar 
permalink: task_dc_emc_unity.html 
keywords: data collector, VNXe, EMC, Unity 
summary: VNXe-Datensammler wird konfiguriert. 
---
= Konfigurieren des EMC Unity Data Collector
:hardbreaks:
:allow-uri-read: 


[role="lead"]
DER DELL EMC Unity (ehemals VNXe)-Datensammler bietet Bestandsunterstützung für VNXe Unified Storage-Arrays. Data Infrastructure Insights unterstützt derzeit iSCSI- und NAS-Protokolle.



== Anforderungen

* Der Unity Data Collector ist CLI-basiert. Sie müssen Unisphere for Unity CLI (uemcli.exe) auf der Erfassungseinheit installieren, in der sich Ihr VNXe Data Collector befindet.
* uemcli.exe verwendet HTTPS als Transportprotokoll, sodass die Erfassungseinheit in der Lage sein muss, HTTPS-Verbindungen zur Unity zu initiieren.
* IP-Adresse oder vollqualifizierter Domänenname des Unity-Geräts
* Sie müssen mindestens einen schreibgeschützten Benutzer zur Verwendung durch den Datensammler haben.
* HTTPS am Port 443 ist erforderlich
* Der EMC Unity Data Collector bietet NAS- und iSCSI-Unterstützung für die Bestandsaufnahme. Fibre-Channel-Volumes werden erkannt, Data Infrastructure Insights jedoch keine Berichte zu FC-Mapping, -Masking oder -Speicherports.




== Terminologie

Data Infrastructure Insights bezieht die folgenden Inventarinformationen aus dem Unity-Datensammler. Für jeden Asset-Typ, der von Data Infrastructure Insights erworben wurde, wird die für diese Ressource am häufigsten verwendete Terminologie angezeigt. Beachten Sie bei der Anzeige oder Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter-/Modelllaufzeit | Einblicke Aus Der Dateninfrastruktur 


| Festplatte | Festplatte 


| Storage Array Durchführt | Storage 


| Prozessor | Storage-Node 


| Storage-Pool | Storage-Pool 


| Allgemeine Informationen zu iSCSI Block, VMware VMFS | Share 


| Remote-Replikationssystem | Synchronisierung 


| ISCSI-Node | ISCSI-Ziel-Node 


| ISCSI-Initiator | ISCSI-Target-Initiator 
|===
Hinweis: Es handelt sich hierbei nur um allgemeine Terminologiezuordnungen. In dieser Datenquelle fallen möglicherweise nicht alle Fälle an.



== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Unity Storage | IP-Adresse oder vollqualifizierter Domänenname des Unity-Geräts 


| Benutzername | Benutzername für das Unity-Gerät 


| Passwort | Kennwort für das Unity-Gerät 


| Vollständiger Pfad zur ausführbaren UEMCLI | Vollständiger Pfad zum Ordner mit der ausführbaren Datei _uemcli.exe_ 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Abfrageintervall für Bestand (min) | Intervall zwischen Bestandsabstimmungen Der Standardwert ist 40 Minuten 


| Unity-CLI-Port | Port, der für die Unity-CLI verwendet wird 


| Leistungsintervall (Sek.) | Der Standardwert ist 300. 
|===


== Fehlerbehebung

Einige Dinge zu versuchen, wenn Sie Probleme mit diesem Datensammler stoßen:



=== Inventar

[cols="2*"]
|===
| Problem: | Versuchen Sie dies: 


| „Externes Dienstprogramm konnte nicht ausgeführt werden“ mit Fehlermeldungen „Unisphere executable uemcli konnte nicht gefunden werden“ | * Korrekte IP-Adresse, Benutzername und Kennwort überprüfen * Bestätigen Sie, dass Unisphere CLI auf der Data Infrastructure Insights Acquisition Unit installiert ist * Bestätigen Sie, dass das Unisphere CLI-Installationsverzeichnis in der Datenquelle korrekt ist * Bestätigen Sie, dass die IP-Adresse der VNXe in der Konfiguration der Datenquelle korrekt ist. Öffnen Sie in der Data Infrastructure Insights Acquisition Unit eine CMD und wechseln Sie in das konfigurierte Installationsverzeichnis: €{INSTALLDIR. Versuchen Sie, eine Verbindung zum VNXe-Gerät herzustellen, indem Sie Folgendes eingeben: Uemcli -d <Ihre IP> -U <Ihre ID> /sys/General show 
|===
Weitere Informationen finden Sie auf der link:concept_requesting_support.html["Support"] Seite oder im link:reference_data_collector_support_matrix.html["Data Collector Supportmatrix"].
