---
sidebar: sidebar 
permalink: task_dc_infinidat_infinibox.html 
keywords: data collector, infinidat, InfiniBox 
summary: Konfigurieren des Infinidat InfiniBox-Datensammlers. 
---
= Infinidat InfiniBox Datensammler
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Der Infinidat InfiniBox (HTTP)-Datensammler wird zum Sammeln von Bestandsinformationen vom Infinidat InfiniBox-Speichersystem verwendet.



== Terminologie

Data Infrastructure Insights erhält die folgenden Bestandsinformationen vom Infinidat InfiniBox-Datensammler.  Für jeden von Data Infrastructure Insights erworbenen Asset-Typ wird die am häufigsten verwendete Terminologie für dieses Asset angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Speicherpool | Speicherpool 


| Node | Regler 


| Dateisystem | Internes Volumen 


| Dateisystem | Dateifreigabe 


| Dateisystemexporte | Aktie 
|===


== Anforderungen

Im Folgenden sind die Anforderungen für die Konfiguration dieses Datensammlers aufgeführt.

* IP-Adresse oder FQDN des InfiniBox-Verwaltungsknotens
* Administrator-Benutzer-ID und -Passwort
* Port 443 über REST-API




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| InfiniBox-Host | IP-Adresse oder vollqualifizierter Domänenname des InfiniBox-Verwaltungsknotens 


| Benutzername | Benutzername für den InfiniBox-Verwaltungsknoten 


| Passwort | Passwort für den InfiniBox-Verwaltungsknoten 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| TCP-Port | TCP-Port, der für die Verbindung mit dem InfiniBox-Server verwendet wird.  Der Standardwert ist 443. 


| Inventarabfrageintervall | Intervall zwischen den Bestandsabfragen. Der Standardwert beträgt 60 Minuten. 
|===


== Fehlerbehebung

Weitere Informationen zu diesem Datensammler finden Sie imlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
