---
sidebar: sidebar 
permalink: task_view_queries.html 
summary: Anzeigen erstellter Abfragen 
keywords: query, queries, viewing 
---
= Anzeigen von Abfragen
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Sie können Ihre Abfragen anzeigen, um Ihre Vermögenswerte zu überwachen und die Anzeige der mit Ihren Vermögenswerten verbundenen Daten in Ihren Abfragen zu ändern.

.Schritte
. Melden Sie sich bei Ihrem Data Infrastructure Insights Mandanten an.
. Klicken Sie auf *Abfragen* und wählen Sie *Alle Abfragen anzeigen*.  Sie können die Anzeige von Abfragen wie folgt ändern:
. Sie können Text in das Filterfeld eingeben, um nach bestimmten Abfragen zu suchen.
. Sie können die Sortierreihenfolge der Spalten in der Abfragetabelle entweder aufsteigend (Pfeil nach oben) oder absteigend (Pfeil nach unten) ändern, indem Sie auf den Pfeil in der Spaltenüberschrift klicken.
. Um die Größe einer Spalte zu ändern, bewegen Sie die Maus über die Spaltenüberschrift, bis ein blauer Balken angezeigt wird.  Platzieren Sie die Maus über der Leiste und ziehen Sie sie nach rechts oder links.
. Um eine Spalte zu verschieben, klicken Sie auf die Spaltenüberschrift und ziehen Sie sie nach rechts oder links.


Beachten Sie beim Durchblättern der Abfrageergebnisse, dass sich die Ergebnisse ändern können, da Data Infrastructure Insights Ihre Datensammler automatisch abfragt.  Dies kann dazu führen, dass einige Elemente fehlen oder einige Elemente je nach Sortierung in der falschen Reihenfolge angezeigt werden.
