---
sidebar: sidebar 
permalink: task_device_resolution_rules.html 
keywords: Automatic, AR, AHR, Host, automatic device resolution 
summary: Mithilfe der Geräteauflösung können Sie die Leistung und den Bestand in Ihrer Umgebung genau verfolgen. 
---
= Regeln zur Geräteauflösung
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Sie erstellen Geräteauflösungsregeln, um Hosts, Speicher und Bänder zu identifizieren, die derzeit nicht automatisch von Data Infrastructure Insights identifiziert werden.  Die von Ihnen erstellten Regeln identifizieren Geräte, die sich derzeit in Ihrer Umgebung befinden, und identifizieren auch ähnliche Geräte, wenn sie Ihrer Umgebung hinzugefügt werden.



== Erstellen von Geräteauflösungsregeln

Wenn Sie Regeln erstellen, identifizieren Sie zunächst die Informationsquelle, auf die die Regel angewendet wird, die zum Extrahieren der Informationen verwendete Methode und ob auf die Ergebnisse der Regel eine DNS-Suche angewendet wird.

[cols="2*"]
|===


| Quelle, die zur Identifizierung des Geräts verwendet wird | * SRM-Aliase für Hosts * Speicheralias mit eingebettetem Host- oder Bandnamen * Switch-Alias mit eingebettetem Host- oder Bandnamen * Zonennamen mit eingebettetem Hostnamen 


| Methode, die zum Extrahieren des Gerätenamens aus der Quelle verwendet wird | * Wie es ist (einen Namen aus einem SRM extrahieren) * Trennzeichen * Reguläre Ausdrücke 


| DNS-Suche | Gibt an, ob Sie DNS zur Überprüfung des Hostnamens verwenden 
|===
Sie erstellen Regeln auf der Registerkarte „Regeln für die automatische Auflösung“.  Die folgenden Schritte beschreiben den Regelerstellungsprozess.

.Verfahren
. Klicken Sie auf *Verwalten > Geräteauflösung*
. Klicken Sie auf der Registerkarte *Regeln zur automatischen Auflösung* auf *+ Host-Regel* oder *+ Bandregel*.
+
Der Bildschirm *Auflösungsregel* wird angezeigt.

+

NOTE: Klicken Sie auf den Link „Übereinstimmungskriterien anzeigen“, um Hilfe und Beispiele zum Erstellen regulärer Ausdrücke zu erhalten.

. Wählen Sie in der Liste *Typ* das Gerät aus, das Sie identifizieren möchten.
+
Sie können _Host_ oder _Tape_ auswählen.

. Wählen Sie in der Liste *Quelle* die Quelle aus, die Sie zur Identifizierung des Hosts verwenden möchten.
+
Abhängig von der ausgewählten Quelle zeigt Data Infrastructure Insights die folgende Antwort an:

+
.. *Zonen* listet die Zonen und WWN auf, die von Data Infrastructure Insights identifiziert werden müssen.
.. *SRM* listet die nicht identifizierten Aliase auf, die von Data Infrastructure Insights identifiziert werden müssen
.. *Speicheralias* listet Speicheraliase und WWN auf, die von Data Infrastructure Insights identifiziert werden müssen
.. *Switch-Alias* listet die Switch-Aliase auf, die von Data Infrastructure Insights identifiziert werden müssen


. Wählen Sie in der Liste *Methode* die Methode aus, die Sie zur Identifizierung des Hosts verwenden möchten.
+
|===


| Quelle | Verfahren 


| SRM | Wie es ist, Trennzeichen, reguläre Ausdrücke 


| Speicheralias | Trennzeichen, reguläre Ausdrücke 


| Alias wechseln | Trennzeichen, reguläre Ausdrücke 


| Zonen | Trennzeichen, reguläre Ausdrücke 
|===
+
** Regeln mit Trennzeichen erfordern die Trennzeichen und die Mindestlänge des Hostnamens.  Die Mindestlänge des Hostnamens ist die Anzahl der Zeichen, die Data Infrastructure Insights zur Identifizierung eines Hosts verwenden soll.  Data Infrastructure Insights führt DNS-Lookups nur für Hostnamen durch, die so lang oder länger sind.
+
Bei Regeln mit Trennzeichen wird die Eingabezeichenfolge durch das Trennzeichen tokenisiert und eine Liste mit Hostnamenkandidaten wird erstellt, indem mehrere Kombinationen des angrenzenden Tokens erstellt werden.  Die Liste wird dann von groß nach klein sortiert.  Beispielsweise würde die Liste bei einer Eingabezeichenfolge von _vipsnq03_hba3_emc3_12ep0_ Folgendes ergeben:

+
*** vipsnq03_hba3_emc3_12ep0
*** vipsnq03_hba3_emc3
*** hba3 emc3_12ep0
*** vipsnq03_hba3
*** emc3_12ep0
*** hba3_emc3
*** vipsnq03
*** 12ep0
*** emc3
*** hba3


** Regeln, die reguläre Ausdrücke verwenden, erfordern einen regulären Ausdruck, das Format und die Auswahl der Groß-/Kleinschreibung.


. Klicken Sie auf *AR ausführen*, um alle Regeln auszuführen, oder klicken Sie auf den Abwärtspfeil in der Schaltfläche, um die von Ihnen erstellte Regel auszuführen (und alle anderen Regeln, die seit der letzten vollständigen Ausführung von AR erstellt wurden).
+
Die Ergebnisse des Regellaufs werden auf der Registerkarte *FC-Identifizierung* angezeigt.





== Starten einer automatischen Aktualisierung der Geräteauflösung

Bei einer Aktualisierung der Geräteauflösung werden manuelle Änderungen übernommen, die seit dem letzten vollautomatischen Geräteauflösungslauf hinzugefügt wurden.  Durch Ausführen eines Updates können nur die neuen manuellen Einträge in der Geräteauflösungskonfiguration übernommen und ausgeführt werden.  Es wird kein vollständiger Geräteauflösungslauf durchgeführt.

.Verfahren
. Melden Sie sich bei der Web-Benutzeroberfläche von Data Infrastructure Insights an.
. Klicken Sie auf *Verwalten > Geräteauflösung*
. Klicken Sie im Bildschirm *Geräteauflösung* auf den Abwärtspfeil in der Schaltfläche *AR ausführen*.
. Klicken Sie auf *Aktualisieren*, um das Update zu starten.




== Regelgestützte manuelle Identifikation

Diese Funktion wird für Sonderfälle verwendet, in denen Sie eine bestimmte Regel oder eine Liste von Regeln (mit oder ohne einmalige Neuordnung) ausführen möchten, um unbekannte Hosts, Speicher- und Bandgeräte aufzulösen.

.Bevor Sie beginnen
Sie haben eine Reihe von Geräten, die nicht identifiziert wurden, und Sie haben auch mehrere Regeln, die andere Geräte erfolgreich identifiziert haben.


NOTE: Wenn Ihre Quelle nur einen Teil eines Host- oder Gerätenamens enthält, verwenden Sie eine reguläre Ausdrucksregel und formatieren Sie sie, um den fehlenden Text hinzuzufügen.

.Verfahren
. Melden Sie sich bei der Web-Benutzeroberfläche von Data Infrastructure Insights an.
. Klicken Sie auf *Verwalten > Geräteauflösung*
. Klicken Sie auf die Registerkarte *Fibre Channel Identify*.
+
Das System zeigt die Geräte zusammen mit ihrem Auflösungsstatus an.

. Wählen Sie mehrere nicht identifizierte Geräte aus.
. Klicken Sie auf *Massenaktionen* und wählen Sie *Hostauflösung festlegen* oder *Bandauflösung festlegen*.
+
Das System zeigt den Bildschirm „Identifizieren“ an, der eine Liste aller Regeln enthält, die Geräte erfolgreich identifiziert haben.

. Ändern Sie die Reihenfolge der Regeln in eine Reihenfolge, die Ihren Anforderungen entspricht.
+
Die Reihenfolge der Regeln wird im Identifizierungsbildschirm geändert, jedoch nicht global.

. Wählen Sie die Methode aus, die Ihren Anforderungen entspricht.


Data Infrastructure Insights führt den Hostauflösungsprozess in der Reihenfolge aus, in der die Methoden angezeigt werden, beginnend mit denen ganz oben.

Wenn zutreffende Regeln gefunden werden, werden die Regelnamen in der Spalte „Regeln“ angezeigt und als „manuell“ gekennzeichnet.

Verwandt:link:task_device_resolution_fibre_channel.html["Fibre Channel-Geräteauflösung"] link:task_device_resolution_ip.html["IP-Geräteauflösung"] link:task_device_resolution_preferences.html["Festlegen der Geräteauflösungseinstellungen"]
