---
sidebar: sidebar 
permalink: task_dc_na_amazon_fsx.html 
keywords: 'data collector, stout, fsx, fsx-netapp, Amazon, AWS, cluster, volume, share, LUN"' 
summary: Amazon FSx for NetApp ONTAP Data Collector 
---
= Amazon FSx for NetApp ONTAP Datenkollektor
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Dieser Datensammler erfasst Bestands- und Leistungsdaten von Amazon FSx for NetApp ONTAP.  Dieser Datensammler wird schrittweise in allen Serviceregionen von Data Infrastructure Insights verfügbar gemacht.  Wenden Sie sich an Ihren Vertriebsmitarbeiter, wenn Sie das Symbol für diesen Collector in Ihrer Data Infrastructure Insights -Umgebung nicht sehen.


NOTE: Dieser Data Infrastructure Insights Collector erfordert einen ONTAP Benutzer mit einer _Filesystem-Scoped_-Rolle.  Bitte überprüfen Sie die AWSlink:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/roles-and-users.html["Rollen und Regeln"] Informationen zu verfügbaren Optionen finden Sie in der Dokumentation.  Derzeit unterstützt AWS nur eine Art von Benutzerrolle mit Dateisystembereich, nämlich _fsxadmin_.  Dies ist die geeignete Rolle für den Data Infrastructure Insights -Collector.  Dem Benutzer sollten außerdem alle drei dieser Anwendungen zugewiesen sein: http, ontapi, ssh.



== Terminologie

Data Infrastructure Insights erfasst Bestands- und Leistungsdaten vom FSx- NetApp Datenkollektor.  Für jeden erworbenen Vermögenswerttyp wird die am häufigsten verwendete Terminologie für den Vermögenswert angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Cluster | Storage 


| LUN | Volumen 


| Volumen | Internes Volumen 
|===


== FSx- NetApp -Terminologie

Die folgenden Bedingungen gelten für Objekte oder Referenzen, die Sie möglicherweise auf den Zielseiten der FSx- NetApp Speicherressourcen finden.  Viele dieser Begriffe gelten auch für andere Datensammler.



=== Storage

* Modell – Eine durch Kommas getrennte Liste der eindeutigen, diskreten Modellnamen innerhalb dieses Clusters.
* Anbieter – AWS
* Seriennummer – Die Seriennummer des Arrays.
* IP – im Allgemeinen handelt es sich dabei um die in der Datenquelle konfigurierten IPs oder Hostnamen.
* Rohkapazität – Basis-2-Summe des gesamten dem FSx-Dateisystem zugewiesenen SSD-Speichers.
* Latenz – eine Darstellung der Arbeitslasten, die der Host sowohl beim Lesen als auch beim Schreiben erfährt.  Im Idealfall bezieht Data Infrastructure Insights diesen Wert direkt, dies ist jedoch häufig nicht der Fall.  Anstelle des Arrays, das dies anbietet, führt Data Infrastructure Insights im Allgemeinen eine IOP-gewichtete Berechnung durch, die aus den Statistiken der einzelnen internen Volumes abgeleitet wird.
* Durchsatz – aggregiert aus internen Volumes.  Verwaltung – dies kann einen Hyperlink zur Verwaltungsschnittstelle des Geräts enthalten.  Programmgesteuert von der Data Infrastructure Insights Datenquelle als Teil der Bestandsberichterstattung erstellt.




=== Speicherpool

* Speicher – auf welchem Speicher-Array dieser Pool lebt.  Obligatorisch.
* Typ – ein beschreibender Wert aus einer Liste mit aufgezählten Möglichkeiten.  Am häufigsten wird „Aggregat“ oder „RAID-Gruppe“ verwendet.
* Kapazität – die Werte hier sind die logisch genutzte, nutzbare Kapazität und die logische Gesamtkapazität sowie der davon genutzte Prozentsatz.
* IOPS – die Summe der IOPs aller diesem Speicherpool zugewiesenen Volumes.
* Durchsatz – der Gesamtdurchsatz aller diesem Speicherpool zugewiesenen Volumes.




== Anforderungen

Für die Konfiguration und Verwendung dieses Datensammlers gelten die folgenden Voraussetzungen:

* Sie müssen Zugriff auf ein Konto mit der Rolle „fsxadmin“ haben, dem drei Anwendungen zugewiesen sind – ssh, ontapi, http
* Zu den Kontodetails gehören Benutzername und Passwort.
* Portanforderungen: 443




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| NetApp Management IP | IP-Adresse oder vollqualifizierter Domänenname des NetApp -Clusters 


| Benutzername | Benutzername für NetApp Cluster 


| Passwort | Passwort für NetApp -Cluster 
|===


== Erweiterte Metriken

Dieser Datensammler sammelt die folgenden erweiterten Metriken aus dem FSx für NetApp ONTAP -Speicher:

* fpolicy
* nfsv3
* nfsv3:Knoten
* nfsv4
* nfsv4_1
* nfsv4_1:Knoten
* nfsv4:Knoten
* Richtliniengruppe
* qtree
* Volumen
* Arbeitslastvolumen


Beachten Sie, dass FSx CLI- und API-Befehle einige Kapazitätswerte abrufen, die Data Infrastructure Insights ZAPI nicht erfasst. Daher können bestimmte Kapazitätswerte (z. B. für Speicherpools) in Data Infrastructure Insights anders sein als auf dem FSx selbst.



== Fehlerbehebung

Wenn bei diesem Datensammler Probleme auftreten, können Sie Folgendes versuchen:



=== Inventar

[cols="2*"]
|===
| Problem: | Versuchen Sie Folgendes: 


| Erhalten Sie die HTTP-Antwort 401 oder den ZAPI-Fehlercode 13003 und ZAPI gibt „Unzureichende Berechtigungen“ oder „Nicht für diesen Befehl autorisiert“ zurück. | Überprüfen Sie Benutzernamen und Passwort sowie Benutzerrechte/Berechtigungen. 


| ZAPI gibt „Clusterrolle ist nicht cluster_mgmt LIF“ zurück. | AU muss mit der Cluster-Management-IP kommunizieren.  Überprüfen Sie die IP und wechseln Sie gegebenenfalls zu einer anderen IP 


| ZAPI-Befehl schlägt nach erneutem Versuch fehl | AU hat ein Kommunikationsproblem mit dem Cluster.  Überprüfen Sie Netzwerk, Portnummer und IP-Adresse.  Der Benutzer sollte auch versuchen, einen Befehl über die Befehlszeile der AU-Maschine auszuführen. 


| AU konnte keine Verbindung zu ZAPI über HTTP herstellen | Überprüfen Sie, ob der ZAPI-Port Klartext akzeptiert.  Wenn AU versucht, Klartext an einen SSL-Socket zu senden, schlägt die Kommunikation fehl. 


| Die Kommunikation schlägt mit SSLException fehl | AU versucht, SSL an einen Klartext-Port auf einem Filer zu senden.  Überprüfen Sie, ob der ZAPI-Port SSL akzeptiert, oder verwenden Sie einen anderen Port. 


| Weitere Verbindungsfehler: Die ZAPI-Antwort hat den Fehlercode 13001, „Datenbank ist nicht geöffnet“. Der ZAPI-Fehlercode ist 60 und die Antwort enthält „API wurde nicht rechtzeitig beendet“. Die ZAPI-Antwort enthält „initialize_session() hat eine NULL-Umgebung zurückgegeben“. Der ZAPI-Fehlercode ist 14007 und die Antwort enthält „Knoten ist nicht fehlerfrei“. | Überprüfen Sie Netzwerk, Portnummer und IP-Adresse.  Der Benutzer sollte auch versuchen, einen Befehl über die Befehlszeile der AU-Maschine auszuführen. 
|===
Weitere Informationen finden Sie in derlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
