---
sidebar: sidebar 
permalink: task_dc_emc_vnx_unified.html 
keywords: data collector, VNX, EMC, Dell 
summary: VNX-Datenkollektor konfigurieren. 
---
= Konfigurieren des Dell EMC VNX Unified-Datenkollektors
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Zur Konfiguration benötigt der Dell EMC VNX Unified (SSH)-Datensammler die IP-Adresse der Control Station sowie einen schreibgeschützten Benutzernamen und ein Kennwort.



== Terminologie

Data Infrastructure Insights erhält von diesem Datensammler die folgenden Bestandsinformationen.  Für jeden von Data Infrastructure Insights erworbenen Asset-Typ wird die am häufigsten verwendete Terminologie für dieses Asset angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Scheibe | Scheibe 


| Datenträgerordner | Datenträgergruppe 


| Dateisystem | Internes Volumen 


| Storage | Storage 


| Speicherprozessor | Speicherknoten 


| Speicherpool, RAID-Gruppe | Speicherpool 


| LUN | Volumen 


| Datenverschieber | Regler 


| Auf einem Data Mover gemountetes Dateisystem | Dateifreigabe 


| CIFS- und NFS-Exporte | Aktie 


| Datenträgervolumen | Backend-LUN 
|===


== Anforderungen

Zum Konfigurieren des VNX (SSH)-Datenkollektors benötigen Sie Folgendes:

* VNX-IP-Adresse und Anmeldeinformationen für die Celerra Control Station.
* Benutzername und Passwort sind schreibgeschützt.
* Der Datensammler kann NaviCLI/NaviSecCLI-Befehle auf dem Backend-Array ausführen, indem er die DART OS NAS-Köpfe nutzt.




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| VNX-IP-Adresse | IP-Adresse oder vollqualifizierter Domänenname der VNX Control Station 


| Benutzername | Benutzername für die VNX Control Station 


| Passwort | Passwort für die VNX Control Station 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Inventarabfrageintervall (min) | Intervall zwischen den Bestandsabfragen. Der Standardwert beträgt 40 Minuten. 


| Leistungsabfrageintervall (Sek.). | Intervall zwischen Leistungsabfragen. Der Standardwert beträgt 300 Sekunden. 
|===


== Fehlerbehebung

Weitere Informationen zu diesem Datensammler finden Sie imlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
