---
sidebar: sidebar 
permalink: task_config_telegraf_kubernetes.html 
keywords: telegraf 
summary: Datensammler für Kubernetes 
---
= Datensammler: Kubernetes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Data Infrastructure Insights verwendet diesen Datensammler, um Kubernetes-Pod-, Node- und Container-Metriken zu erfassen.



== Installation

Anweisungen zur Installation von Kubernetes finden Sie imlink:task_config_telegraf_agent_k8s.html["Kubernetes-Überwachungsoperator"] Seite.



== Über Kube-State-Metrics

Der Kubernetes Monitoring Operator installiert kube-state-metrics automatisch; es ist keine Benutzerinteraktion erforderlich.



=== Kube-State-Metrics-Zähler

Der NetApp Kubernetes Monitoring Operator extrahiert die unten aufgeführten Kube-State-Metrics-Zähler.  Weitere Einzelheiten zu den einzelnen Zählern finden Sie unter: https://github.com/kubernetes/kube-state-metrics/tree/main/docs#exposed-metrics[] .

. DaemonSet-Metriken
. Bereitstellungsmetriken
. Namespace-Metriken
. Knotenmetriken
. Persistente Volumenmetriken
. Metriken für persistente Volumenansprüche
. Pod-Metriken
. ReplicaSet-Metriken
. Servicemetriken
. StatefulSet-Metriken
. Horizontal Pod AutoScaler-Metriken
. Cronjob-Metriken
. Jobmetriken
. Ressourcenkontingentmetriken

