---
sidebar: sidebar 
permalink: task_modify_delete_query.html 
summary: Vorhandene Abfragen lassen sich durch Ändern von Kriterien und Spalten anpassen, mit flexiblen Speicheroptionen zum Aktualisieren, Umbenennen oder Erstellen neuer Versionen sowie Optionen zum Löschen von Abfragen, wenn diese nicht mehr benötigt werden. 
keywords: query, queries, modify, edit, delete, remove 
---
= Ändern oder Löschen einer Abfrage
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Abfragen lassen sich effizient verwalten, indem Suchkriterien angepasst, Spalten hinzugefügt oder entfernt und aus flexiblen Speicheroptionen gewählt wird. Bestehende Abfragen können aktualisiert, neue Versionen erstellt oder nicht mehr benötigte Abfragen gelöscht werden, sodass die Bibliothek organisiert und aktuell bleibt.



[[modifying-a-query]]
== Ändern einer Abfrage

.Schritte
. Klicken Sie auf *Erkunden* und wählen Sie *Alle Metrikabfragen* aus.
+
Die Seite „Abfragen“ wird angezeigt.

. Klicken Sie auf den Abfragenamen
. Um der Abfrage ein Kriterium hinzuzufügen, klicken Sie auf das Spaltensymbol und wählen Sie eine Metrik oder ein Attribut aus der Liste aus.


Wenn Sie alle erforderlichen Änderungen vorgenommen haben, führen Sie einen der folgenden Schritte aus:

* Klicken Sie auf die Schaltfläche *Speichern*, um die Abfrage unter dem ursprünglich verwendeten Namen zu speichern.
* Klicken Sie auf das Dropdown-Menü neben der Schaltfläche *Speichern* und wählen Sie *Speichern unter*, um die Abfrage unter einem anderen Namen zu speichern.  Dadurch wird die ursprüngliche Abfrage nicht überschrieben.
* Klicken Sie auf das Dropdown-Menü neben der Schaltfläche *Speichern* und wählen Sie *Umbenennen*, um den ursprünglich verwendeten Abfragenamen zu ändern.  Dadurch wird die ursprüngliche Abfrage überschrieben.
* Klicken Sie auf das Dropdown-Menü neben der Schaltfläche *Speichern* und wählen Sie *Änderungen verwerfen*, um die Abfrage auf die zuletzt gespeicherten Änderungen zurückzusetzen.




[[deleting-a-query]]
== Löschen einer Abfrage

Um eine Abfrage zu löschen, klicken Sie auf *Abfragen*, wählen Sie *Alle Abfragen anzeigen* und führen Sie einen der folgenden Schritte aus:

. Klicken Sie auf das Drei-Punkte-Menü rechts neben der Abfrage und klicken Sie auf *Löschen*.
. Klicken Sie auf den Abfragenamen und wählen Sie *Löschen* aus dem Dropdown-Menü *Speichern*.

