---
sidebar: sidebar 
permalink: task_config_cs_incloud.html 
keywords: Cloud, Storage, AWS, Cloud Volumes, Cloud ONTAP, firewall, VPC, Subnet,  cloud secure 
summary: Richten Sie Workload Security-Datensammler für Cloud Volumes ONTAP und Amazon FSx for NetApp ONTAP ein, um den Dateizugriff und die Benutzeraktivität zu überwachen sowie Bedrohungen in Ihrer Cloud-Speicherinfrastruktur zu erkennen. 
---
= Konfigurieren des Cloud Volumes ONTAP und Amazon FSx for NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Überwachen Sie den Datei- und Benutzerzugriff in Ihrer Cloud-Speicherinfrastruktur, indem Sie Workload Security-Datensammler für Cloud Volumes ONTAP und Amazon FSx for NetApp ONTAP konfigurieren. Dieser Leitfaden bietet eine Schritt-für-Schritt-Anleitung zum Bereitstellen von Agents in AWS und zum Verbinden dieser Agents mit Ihren Cloud-Speicherinstanzen.



== Cloud Volumes ONTAP Speicherkonfiguration

Informationen zum Konfigurieren einer AWS-Instanz mit einem einzelnen Knoten/HA zum Hosten des Workload Security Agent finden Sie in der OnCommand Cloud Volumes ONTAP Dokumentation:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html[]

Nachdem die Konfiguration abgeschlossen ist, befolgen Sie die Schritte zum Einrichten Ihres SVM:https://docs.netapp.com/us-en/cloudinsights/task_add_collector_svm.html[]



== Unterstützte Plattformen

* Cloud Volumes ONTAP, wird von allen verfügbaren Cloud-Service-Anbietern unterstützt, sofern verfügbar.  Zum Beispiel: Amazon, Azure, Google Cloud.
* ONTAP Amazon FSx




== Agent-Computerkonfiguration

Die Agent-Maschine muss in den jeweiligen Subnetzen der Cloud-Dienstanbieter konfiguriert werden.  Weitere Informationen zum Netzwerkzugriff finden Sie in den [Agentenanforderungen].

Nachfolgend finden Sie die Schritte zur Agenteninstallation in AWS.  Für die Installation können in Azure oder Google Cloud die entsprechenden Schritte ausgeführt werden, sofern diese für den Cloud-Dienstanbieter gelten.

Führen Sie in AWS die folgenden Schritte aus, um die Maschine für die Verwendung als Workload Security Agent zu konfigurieren:

Führen Sie die folgenden Schritte aus, um die Maschine für die Verwendung als Workload Security Agent zu konfigurieren:

.Schritte
. Melden Sie sich bei der AWS-Konsole an, navigieren Sie zur Seite „EC2-Instances“ und wählen Sie „Instanz starten“ aus.
. Wählen Sie ein RHEL- oder CentOS-AMI mit der entsprechenden Version aus, wie auf dieser Seite erwähnt:https://docs.netapp.com/us-en/cloudinsights/concept_cs_agent_requirements.html[]
. Wählen Sie die VPC und das Subnetz aus, in denen sich die Cloud ONTAP -Instanz befindet.
. Wählen Sie _t2.xlarge_ (4 vcpus und 16 GB RAM) als zugewiesene Ressourcen.
+
.. Erstellen Sie die EC2-Instanz.


. Installieren Sie die erforderlichen Linux-Pakete mit dem YUM-Paketmanager:
+
.. Installieren Sie _wget_ und _unzip_ native Linux-Pakete.






== Installieren des Workload Security Agent

. Melden Sie sich als Administrator oder Kontoinhaber bei Ihrer Data Infrastructure Insights Umgebung an.
. Navigieren Sie zu Workload Security *Collectors* und klicken Sie auf die Registerkarte *Agents*.
. Klicken Sie auf *+Agent* und geben Sie RHEL als Zielplattform an.
. Kopieren Sie den Befehl zur Agenteninstallation.
. Fügen Sie den Agent-Installationsbefehl in die RHEL EC2-Instanz ein, bei der Sie angemeldet sind.  Dadurch wird der Workload Security-Agent installiert, der allelink:concept_cs_agent_requirements.html["Agentenvoraussetzungen"] erfüllt sind.


Detaillierte Schritte finden Sie unter diesem Link: https://docs.netapp.com/us-en/cloudinsights/task_cs_add_agent.html#steps-to-install-agent



== Fehlerbehebung

Bekannte Probleme und deren Lösungen werden in der folgenden Tabelle beschrieben.

|===


| Problem | Auflösung 


| Der Datensammler zeigt den Fehler „Workload-Sicherheit: ONTAP -Typ für Amazon FxSN-Datensammler konnte nicht ermittelt werden“ an.  Der Kunde kann keinen neuen Amazon FSxN-Datensammler zu Workload Security hinzufügen.  Bei der Verbindung vom Agenten zum FSxN-Cluster auf Port 443 kommt es zu einer Zeitüberschreitung.  Für Firewall- und AWS-Sicherheitsgruppen sind die erforderlichen Regeln aktiviert, um die Kommunikation zu ermöglichen.  Ein Agent ist bereits bereitgestellt und befindet sich auch im selben AWS-Konto.  Derselbe Agent wird zum Verbinden und Überwachen der verbleibenden NetApp -Geräte verwendet (und alle funktionieren). | Lösen Sie dieses Problem, indem Sie der Sicherheitsregel des Agenten das LIF-Netzwerksegment fsxadmin hinzufügen.  Alle Ports zulassen, wenn Sie sich bei den Ports nicht sicher sind. 
|===