---
sidebar: sidebar 
permalink: task_dc_netapp_eseries_rest.html 
keywords: data collector, ontap, clustered ontap, REST 
summary: Konfigurieren des REST-Datenkollektors der NetApp E-Serie. 
---
= NetApp E-Series REST-Datenkollektor
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Der REST-Datenkollektor der NetApp E-Serie sammelt Inventar- und Leistungsdaten.  Der Collector unterstützt Firmware 7.x+ mit denselben Konfigurationen und meldet dieselben Daten.  Der REST-Collector überwacht den Verschlüsselungsstatus von Speicherpools sowie den Verschlüsselungsstatus zugehöriger Festplatten und Volumes und bietet die CPU-Auslastung des Speicherknotens als Leistungsindikator – eine Funktion, die im älteren SANtricity E-Series-Collector nicht verfügbar ist.



== Terminologie

Cloud Insight erfasst mithilfe von REST die folgenden Bestandsinformationen von der NetApp E-Serie.  Für jeden erworbenen Vermögenswerttyp wird die am häufigsten verwendete Terminologie für diesen Vermögenswert angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Scheibe | Scheibe 


| Volumengruppe | Datenträgergruppe 


| Speicher-Array | Storage 


| Regler | Speicherknoten 


| Volumengruppe | Speicherpool 


| Volumen | Volumen 
|===
Hinweis: Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diesen Datensammler darstellen.



== Anforderungen

* Die IP-Adresse jedes Controllers im Array
* Dieser Collector unterstützt nur E-Series-Modell-Arrays mit *nativen REST-API-Funktionen*.  Die E-Series-Organisation liefert eine außerhalb des Arrays installierbare REST-API-Distribution für ältere E-Series-Arrays: Dieser Collector unterstützt dieses Szenario nicht.  Benutzer mit älteren Arrays sollten weiterhin Data Infrastructure Insights verwenden.link:task_dc_na_eseries.html["E-Serie SANtricity API"] Kollektor.
* Das Feld „IP-Adressen des E-Series-Controllers“ unterstützt eine durch Kommas getrennte Zeichenfolge mit zwei IP-/Hostnamen. Der Collector versucht automatisch, den zweiten IP-/Hostnamen zu verwenden, wenn auf den ersten nicht zugegriffen werden kann.
* HTTPS-Port: Standard ist 8443.




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| IP-Adressen der E-Serie-Controller | Komma-getrennte IP-Adressen und/oder vollqualifizierte Domänennamen für die Array-Controller 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Inventarabfrageintervall (min) | Der Standardwert ist 30 Minuten 


| Leistungsabfrageintervall bis zu 3600 Sekunden | Der Standardwert ist 300 Sekunden 
|===


== E-Series-Terminologie (Landingpage)

Die folgenden Bedingungen gelten für Objekte oder Referenzen, die Sie möglicherweise auf den Zielseiten der NetApp E-Series-Assets finden.  Viele dieser Begriffe gelten auch für andere Datensammler.



=== Storage

* Modell – Modellname des Geräts.
* Anbieter – derselbe Anbietername, den Sie sehen würden, wenn Sie eine neue Datenquelle konfigurieren würden
* Seriennummer – Die Seriennummer des Arrays.  Bei Speichersystemen mit Clusterarchitektur wie NetApp Clustered Data Ontap ist diese Seriennummer möglicherweise weniger nützlich als die Seriennummern der einzelnen „Storage Nodes“.
* IP – im Allgemeinen die IP(s) oder Hostnamen, wie sie in der Datenquelle konfiguriert sind
* Mikrocode-Version – Firmware
* Rohkapazität – Basis-2-Summierung aller physischen Festplatten im System, unabhängig von ihrer Rolle
* Latenz – eine Darstellung der Arbeitslasten, die der Host sowohl beim Lesen als auch beim Schreiben erfährt.  Im Idealfall bezieht Data Infrastructure Insights diesen Wert direkt, dies ist jedoch häufig nicht der Fall.  Anstelle des Arrays, das dies anbietet, führt Data Infrastructure Insights im Allgemeinen eine IOP-gewichtete Berechnung durch, die aus den Statistiken der einzelnen Volumes abgeleitet wird.
* Durchsatz – der gesamte Host-Durchsatz des Arrays.  Idealerweise direkt aus dem Array bezogen, falls nicht verfügbar, summiert Data Infrastructure Insights den Durchsatz der Volumes, um diesen Wert abzuleiten
* Verwaltung – dies kann einen Hyperlink zur Verwaltungsschnittstelle des Geräts enthalten.  Programmgesteuert von der Data Infrastructure Insights -Datenquelle als Teil der Bestandsberichterstattung erstellt  




=== Speicherpool

* Speicher – auf welchem Speicher-Array dieser Pool lebt. Obligatorisch
* Typ – ein beschreibender Wert aus einer Liste mit aufgezählten Möglichkeiten.  Am häufigsten werden „Thin Provisioning“ oder „RAID-Gruppe“ verwendet.
* Knoten – Wenn die Architektur dieses Speicherarrays so ist, dass Pools zu einem bestimmten Speicherknoten gehören, wird sein Name hier als Hyperlink zu seiner eigenen Zielseite angezeigt.
* Verwendet Flash Pool – Ja/Nein-Wert
* Redundanz – RAID-Level oder Schutzschema.  E-Serie meldet „RAID 7“ für DDP-Pools
* Kapazität – die Werte hier sind die logisch genutzte, nutzbare Kapazität und die logische Gesamtkapazität sowie der davon genutzte Prozentsatz.  Diese Werte beinhalten beide die „Erhaltungskapazität“ der E-Serie, was dazu führt, dass sowohl die Zahlen als auch der Prozentsatz höher sind als das, was die Benutzeroberfläche der E-Serie möglicherweise anzeigt
* Überbelegte Kapazität – Wenn Sie über Effizienztechnologien eine Gesamtsumme an Volume- oder internen Volume-Kapazitäten zugewiesen haben, die größer ist als die logische Kapazität des Speicherpools, ist der Prozentwert hier größer als 0 %.
* Snapshot – verwendete und gesamt Snapshot-Kapazitäten, wenn Ihre Speicherpoolarchitektur einen Teil ihrer Kapazität Segmentbereichen ausschließlich für Snapshots zuweist
* Auslastung – ein Prozentwert, der den höchsten Prozentsatz der Festplattenauslastung aller Festplatten anzeigt, die Kapazität zu diesem Speicherpool beitragen.  Die Festplattenauslastung weist nicht unbedingt eine starke Korrelation mit der Array-Leistung auf. Die Auslastung kann aufgrund von Festplattenneuaufbauten, Deduplizierungsaktivitäten usw. hoch sein, wenn keine vom Host gesteuerten Workloads vorliegen.  Darüber hinaus kann die Replikationsimplementierung vieler Arrays die Festplattenauslastung erhöhen, ohne dass dies als Volume-Arbeitslast angezeigt wird.
* IOPS – die Summe der IOPs aller Festplatten, die Kapazität zu diesem Speicherpool beitragen.  Wenn auf einer bestimmten Plattform keine Festplatten-IOPs verfügbar sind, wird dieser Wert aus der Summe der Volume-IOPs für alle Volumes in diesem Speicherpool ermittelt.
* Durchsatz – der Gesamtdurchsatz aller Festplatten, die Kapazität zu diesem Speicherpool beitragen.  Wenn auf einer bestimmten Plattform kein Festplattendurchsatz verfügbar ist, wird dieser Wert aus der Summe der Datenträger aller Datenträger in diesem Speicherpool ermittelt.




=== Speicherknoten

* Speicher – zu welchem Speicherarray dieser Knoten gehört. Obligatorisch
* HA-Partner – auf Plattformen, auf denen ein Knoten auf einen und nur einen anderen Knoten umgeschaltet wird, wird er im Allgemeinen hier angezeigt
* Status – Integrität des Knotens.  Nur verfügbar, wenn das Array gesund genug ist, um von einer Datenquelle inventarisiert zu werden
* Modell – Modellname des Knotens
* Version – Versionsname des Geräts.
* Seriennummer – Die Seriennummer des Knotens
* Speicher – Basis-2-Speicher, falls verfügbar
* Auslastung – Im Allgemeinen eine CPU-Auslastungszahl oder im Fall von NetApp Ontap ein Controller-Stressindex.  Die Nutzung ist derzeit für die NetApp E-Serie nicht verfügbar
* IOPS – eine Zahl, die die hostgesteuerten IOPs auf diesem Controller darstellt.  Idealerweise wird die Quelle direkt aus dem Array bezogen. Wenn sie nicht verfügbar ist, wird sie durch Summieren aller IOPs für Volumes berechnet, die ausschließlich zu diesem Knoten gehören.
* Latenz – eine Zahl, die die typische Host-Latenz oder Reaktionszeit auf diesem Controller darstellt.  Idealerweise wird die Quelle direkt aus dem Array bezogen. Wenn sie nicht verfügbar ist, wird sie durch eine IOP-gewichtete Berechnung aus Volumes berechnet, die ausschließlich zu diesem Knoten gehören.
* Durchsatz – eine Zahl, die den hostgesteuerten Durchsatz auf diesem Controller darstellt.  Idealerweise wird der Datendurchsatz direkt aus dem Array bezogen. Falls er nicht verfügbar ist, wird er durch Summieren des gesamten Durchsatzes für Volumes berechnet, die ausschließlich zu diesem Knoten gehören.
* Prozessoren – CPU-Anzahl




== Fehlerbehebung

Weitere Informationen zu diesem Datensammler finden Sie imlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
