---
sidebar: sidebar 
permalink: task_query_copy_table_values.html 
summary: Sie können Werte aus einer Tabelle in die Zwischenablage kopieren, um sie in anderen Anwendungen zu verwenden. 
keywords: query, queries, copy, values, clipboard 
---
= Tabellenwerte kopieren
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Sie können Werte in Tabellen in die Zwischenablage kopieren, um sie in Suchfeldern oder anderen Anwendungen zu verwenden.

.Informationen zu diesem Vorgang
Es gibt zwei Methoden, mit denen Sie Werte aus Tabellen oder Abfrageergebnissen in die Zwischenablage kopieren können.

.Schritte
. Methode 1: Markieren Sie den gewünschten Text mit der Maus, kopieren Sie ihn und fügen Sie ihn in Suchfelder oder andere Anwendungen ein.
. Methode 2: Bewegen Sie bei Einzelwertfeldern den Mauszeiger über das Feld und klicken Sie auf das angezeigte Zwischenablagesymbol.  Der Wert wird zur Verwendung in Suchfeldern oder anderen Anwendungen in die Zwischenablage kopiert.
+
Beachten Sie, dass mit dieser Methode nur Werte kopiert werden können, die Links zu Assets sind.  Nur Felder, die einzelne Werte enthalten (also keine Listen sind), verfügen über das Kopiersymbol.


