---
sidebar: sidebar 
permalink: task_defining_annotations.html 
keywords: annotations, monitor, notes, tags 
summary: Verfolgen Sie Daten mithilfe von Anmerkungen. 
---
= Anmerkungen definieren
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie Data Infrastructure Insights anpassen, um Daten für Ihre Unternehmensanforderungen zu verfolgen, können Sie spezielle Notizen, sogenannte Anmerkungen, definieren und sie Ihren Assets zuweisen.

Sie können Assets Anmerkungen mit Informationen wie dem Ende der Lebensdauer des Assets, dem Rechenzentrum, dem Gebäudestandort, der Speicherebene oder dem Volume-Servicelevel zuweisen.

Die Verwendung von Anmerkungen zur Überwachung Ihrer Umgebung umfasst die folgenden übergeordneten Aufgaben:

* Erstellen oder Bearbeiten von Definitionen für alle Anmerkungstypen.
* Anzeigen von Asset-Seiten und Zuordnen jedes Assets zu einer oder mehreren Anmerkungen.
+
Wenn beispielsweise ein Vermögenswert geleast wird und der Leasingvertrag innerhalb von zwei Monaten abläuft, möchten Sie dem Vermögenswert möglicherweise eine End-of-Life-Anmerkung hinzufügen.  Dadurch wird verhindert, dass andere dieses Gut über einen längeren Zeitraum hinweg verwenden.

* Erstellen von Regeln zum automatischen Anwenden von Anmerkungen auf mehrere Assets desselben Typs.
* Filtern Sie Assets nach ihren Anmerkungen.




== Standard-Annotationstypen

Data Infrastructure Insights bietet einige Standardanmerkungstypen.  Diese Anmerkungen können zum Filtern oder Gruppieren von Daten verwendet werden.

Sie können Assets mit Standardanmerkungstypen wie den folgenden verknüpfen:

* Lebenszyklus von Anlagen, z. B. Geburtstag, Sonnenuntergang oder Ende der Lebensdauer
* Standortinformationen zu einem Gerät, z. B. Rechenzentrum, Gebäude oder Stockwerk
* Klassifizierung von Assets, beispielsweise nach Qualität (Tiers), nach angeschlossenen Geräten (Switch-Level) oder nach Service-Level
* Status, z. B. „heiß“ (hohe Auslastung)


In der folgenden Tabelle sind die von Data Infrastructure Insights bereitgestellten Anmerkungstypen aufgeführt.

[cols="30,53, 16"]
|===


| Anmerkungstypen | Beschreibung | Typ 


| Alias | Benutzerfreundlicher Name für eine Ressource | Text 


| Compute-Ressourcengruppe | Vom Host- und VM-Dateisystem-Datensammler verwendete Gruppenzuweisung | Liste 


| Rechenzentrum | Physischer Standort | Liste 


| Heiß | Geräte, die regelmäßig stark beansprucht werden oder an der Grenze ihrer Kapazität stehen | Boolescher Wert 


| Hinweis | Mit einer Ressource verknüpfte Kommentare | Prüfen 


| Service-Level | Eine Reihe unterstützter Servicelevel, die Sie Ressourcen zuweisen können.  Bietet eine geordnete Optionsliste für interne Volumes, Qtree und Volumes.  Bearbeiten Sie Service-Levels, um Leistungsrichtlinien für verschiedene Level festzulegen. | Liste 


| Sonnenuntergang | Festgelegter Schwellenwert, nach dessen Überschreitung keine neuen Zuweisungen mehr zu diesem Gerät vorgenommen werden können.  Nützlich für geplante Migrationen und andere anstehende Netzwerkänderungen. | Datum 


| Schalterebene | Vordefinierte Optionen zum Einrichten von Kategorien für Schalter.  Normalerweise bleiben diese Bezeichnungen für die gesamte Lebensdauer des Geräts bestehen, Sie können sie jedoch bearbeiten.  Nur für Schalter verfügbar. | Liste 


| Stufe | Kann verwendet werden, um verschiedene Serviceebenen innerhalb Ihrer Umgebung zu definieren.  Mit den Stufen kann die Art des Levels definiert werden, beispielsweise die erforderliche Geschwindigkeit (z. B. Gold oder Silber).  Diese Funktion ist nur auf internen Volumes, Qtrees, Speicher-Arrays, Speicherpools und Volumes verfügbar. | Liste 


| Schweregrad des Verstoßes | Rang (z. B. schwerwiegend) eines Verstoßes (z. B. fehlende Host-Ports oder fehlende Redundanz) in einer Hierarchie von der höchsten bis zur niedrigsten Wichtigkeit. | Liste 
|===

NOTE: Alias, Data Center, Hot, Service Level, Sunset, Switch Level, Tier und Violation Severity sind Anmerkungen auf Systemebene, die Sie nicht löschen oder umbenennen können. Sie können nur die ihnen zugewiesenen Werte ändern.



== Erstellen benutzerdefinierter Anmerkungen

Mithilfe von Anmerkungen können Sie den Assets benutzerdefinierte, geschäftsspezifische Daten hinzufügen, die Ihren Geschäftsanforderungen entsprechen.  Obwohl Data Infrastructure Insights eine Reihe von Standardanmerkungen bereitstellt, möchten Sie die Daten möglicherweise auf andere Weise anzeigen.  Die Daten in benutzerdefinierten Anmerkungen ergänzen bereits erfasste Gerätedaten, wie etwa Speicherhersteller, Anzahl der Datenträger und Leistungsstatistiken.  Die Daten, die Sie mithilfe von Anmerkungen hinzufügen, werden von Data Infrastructure Insights nicht erkannt.

.Schritte
. Klicken Sie im Data Infrastructure Insights -Menü auf *Verwalten > Anmerkungen*.
+
Auf der Seite „Anmerkungen“ wird die Liste der Anmerkungen angezeigt.

. Klicken Sie auf *+Hinzufügen*
. Geben Sie einen *Namen* und eine *Beschreibung* der Anmerkung ein.
+
Sie können in diese Felder bis zu 255 Zeichen eingeben.

. Klicken Sie auf *Typ* und wählen Sie dann eine der folgenden Optionen aus, die den in dieser Anmerkung zulässigen Datentyp darstellt:


.Anmerkungstypen
* Boolesch: Erstellt eine Dropdownliste mit den Auswahlmöglichkeiten „Ja“ und „Nein“. Beispielsweise ist die Anmerkung „Direkt verbunden“ boolesch.
* Datum: Dadurch wird ein Feld erstellt, das ein Datum enthält. Wenn die Anmerkung beispielsweise ein Datum sein soll, wählen Sie dies aus.
* Liste: Erstellt eines der folgenden Elemente:
+
** Eine Dropdown-Liste mit festen
+
Wenn andere diesen Anmerkungstyp einem Gerät zuweisen, können sie der Liste keine weiteren Werte hinzufügen.

** Eine flexible Dropdown-Liste
+
Wenn Sie beim Erstellen dieser Liste die Option „Neue Werte spontan hinzufügen“ auswählen, können andere Personen, die diesen Anmerkungstyp einem Gerät zuweisen, der Liste weitere Werte hinzufügen.



* Nummer: Erstellt ein Feld, in das der Benutzer, der die Anmerkung zuweist, eine Nummer eingeben kann.  Wenn der Anmerkungstyp beispielsweise „Etage“ ist, kann der Benutzer den Werttyp „Nummer“ auswählen und die Etagennummer eingeben.
* Text: Erstellt ein Feld, das Freitext zulässt.  Sie können beispielsweise „Sprache“ als Anmerkungstyp eingeben, „Text“ als Werttyp auswählen und eine Sprache als Wert eingeben.



NOTE: Nachdem Sie den Typ festgelegt und Ihre Änderungen gespeichert haben, können Sie den Typ der Anmerkung nicht mehr ändern.  Wenn Sie den Typ ändern müssen, müssen Sie die Anmerkung löschen und eine neue erstellen.

. Wenn Sie „Liste“ als Anmerkungstyp auswählen, gehen Sie wie folgt vor:
+
.. Wählen Sie *Neue Werte spontan hinzufügen*, wenn Sie der Anmerkung auf einer Asset-Seite weitere Werte hinzufügen möchten, wodurch eine flexible Liste erstellt wird.
+
Angenommen, Sie befinden sich auf einer Asset-Seite und das Asset verfügt über die Stadtanmerkung mit den Werten Detroit, Tampa und Boston.  Wenn Sie die Option *Neue Werte spontan hinzufügen* ausgewählt haben, können Sie der Stadt zusätzliche Werte wie San Francisco und Chicago direkt auf der Asset-Seite hinzufügen, anstatt sie auf der Anmerkungsseite hinzufügen zu müssen.  Wenn Sie diese Option nicht wählen, können Sie beim Anwenden der Annotation keine neuen Annotationswerte hinzufügen. Dadurch wird eine feste Liste erstellt.

.. Geben Sie in die Felder *Wert* und *Beschreibung* einen Wert und eine Beschreibung ein.
.. Klicken Sie auf *+Hinzufügen+*, um weitere Werte hinzuzufügen.
.. Klicken Sie auf das Papierkorbsymbol, um einen Wert zu löschen.


. Klicken Sie auf *Speichern*
+
Ihre Anmerkungen werden in der Liste auf der Anmerkungsseite angezeigt.



.Ein Hinweis zu Booleschen Anmerkungen
Beim Filtern nach einer Booleschen Anmerkung werden Ihnen möglicherweise die folgenden Werte zum Filtern angezeigt:

* *Beliebig*: Dies gibt _alle_ Ergebnisse zurück, einschließlich der Ergebnisse, die auf „Ja“, „Nein“ oder gar nicht festgelegt sind.
* *Ja*: Gibt nur „Ja“-Ergebnisse zurück. Beachten Sie, dass DII in den meisten Tabellen „Ja“ als Häkchen anzeigt. Die Werte können auf „True“, „On“ usw. gesetzt werden; DII behandelt alle diese Werte als „Yes“.
* *Nein*: Gibt nur „Nein“-Ergebnisse zurück. Beachten Sie, dass DII in den meisten Tabellen „Nein“ als „X“ anzeigt. Die Werte können auf „Falsch“, „Aus“ usw. gesetzt werden; DII behandelt alle diese Werte als „Nein“.
* *Keine*: Gibt nur Ergebnisse zurück, bei denen die Anmerkung überhaupt nicht festgelegt wurde. Auch als „Null“-Werte bezeichnet.


.Nach Abschluss
In der Benutzeroberfläche steht die Anmerkung sofort zur Verwendung bereit.
