---
sidebar: sidebar 
permalink: task_dc_na_7mode.html 
keywords: data collector, 7-mode, NetApp 
summary: Konfigurieren des NetApp 7-Mode-Datenkollektors. 
---
= NetApp Data ONTAP im 7-Mode-Datenkollektor
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Für Speichersysteme mit Data ONTAP -Software im 7-Mode verwenden Sie den 7-Mode-Datenkollektor, der die CLI zum Abrufen von Kapazitäts- und Leistungsdaten nutzt.



== Terminologie

Data Infrastructure Insights erhält die folgenden Bestandsinformationen vom NetApp 7-Mode-Datenkollektor.  Für jeden erworbenen Vermögenswerttyp wird die am häufigsten verwendete Terminologie für diesen Vermögenswert angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:


NOTE: Dieser Datensammler istlink:task_getting_started_with_cloud_insights.html#useful-definitions["veraltet"] .

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Scheibe | Scheibe 


| Raid-Gruppe | Datenträgergruppe 


| Filer | Storage 


| Filer | Speicherknoten 


| Aggregat | Speicherpool 


| LUN | Volumen 


| Volumen | Internes Volumen 
|===
Hinweis: Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diesen Datensammler darstellen.



== Anforderungen

Zur Konfiguration und Nutzung dieses Datensammlers benötigen Sie Folgendes:

* IP-Adressen des FAS Speichercontrollers und -Partners.
* Port 443
* Ein benutzerdefinierter Benutzername und ein Passwort auf Administratorebene für Controller und Partner-Controller mit den folgenden Rollenfunktionen für 7-Mode:
+
** „api-*“: Verwenden Sie dies, um OnCommand Insight die Ausführung aller NetApp Speicher-API-Befehle zu ermöglichen.
** „login-http-admin“: Verwenden Sie dies, um OnCommand Insight die Verbindung zum NetApp -Speicher über HTTP zu ermöglichen.
** „security-api-vfiler“: Verwenden Sie dies, um OnCommand Insight die Ausführung von NetApp -Speicher-API-Befehlen zum Abrufen von vFiler-Einheiteninformationen zu ermöglichen.
** „cli-options“: Verwenden Sie dies, um Speichersystemoptionen zu lesen.
** „cli-lun“: Greifen Sie auf diese Befehle zum Verwalten von LUNs zu.  Zeigt den Status (LUN-Pfad, Größe, Online-/Offline-Status und Freigabestatus) der angegebenen LUN oder LUN-Klasse an.
** „cli-df“: Verwenden Sie dies, um den freien Speicherplatz anzuzeigen.
** „cli-ifconfig“: Verwenden Sie dies, um Schnittstellen und IP-Adressen anzuzeigen.






== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Adresse des Speichersystems | IP-Adresse oder vollqualifizierter Domänenname für das NetApp -Speichersystem 


| Benutzername | Benutzername für das NetApp -Speichersystem 


| Passwort | Passwort für das NetApp -Speichersystem 


| Adresse des HA-Partners im Cluster | IP-Adresse oder vollqualifizierter Domänenname für den HA-Partner 


| Benutzername des HA-Partners im Cluster | Benutzername für den HA-Partner 


| Kennwort des HA-Partner-Filers im Cluster | Passwort für den HA-Partner 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Inventarabfrageintervall (min) | Intervall zwischen den Bestandsabfragen. Der Standardwert beträgt 20 Minuten. 


| Verbindungstyp | HTTPS oder HTTP, zeigt auch den Standardport an 


| Verbindungsport überschreiben | Wenn das Feld „Verbindungstyp“ leer ist, verwenden Sie den Standardport. Andernfalls geben Sie den zu verwendenden Verbindungsport ein. 


| Leistungsabfrageintervall (Sek.) | Intervall zwischen Leistungsabfragen. Der Standardwert beträgt 300 Sekunden. 
|===


== Speichersystemanbindung

Alternativ zur Verwendung des standardmäßigen Administratorbenutzers für diesen Datensammler können Sie einen Benutzer mit Administratorrechten direkt auf den NetApp -Speichersystemen konfigurieren, sodass dieser Datensammler Daten von NetApp -Speichersystemen abrufen kann.

Für die Verbindung mit NetApp -Speichersystemen muss der Benutzer, der beim Erwerb des Haupt-Pfilers (auf dem sich das Speichersystem befindet) angegeben wird, die folgenden Bedingungen erfüllen:

* Der Benutzer muss sich auf vfiler0 (Root-Filer/Pfiler) befinden.
+
Speichersysteme werden beim Erwerb des Haupt-Pfilers erworben.

* Die folgenden Befehle definieren die Funktionen der Benutzerrolle:
+
** „api-*“: Verwenden Sie dies, um Data Infrastructure Insights die Ausführung aller NetApp -Speicher-API-Befehle zu ermöglichen.
+
Dieser Befehl ist zur Verwendung der ZAPI erforderlich.

** „login-http-admin“: Verwenden Sie dies, um Data Infrastructure Insights die Verbindung zum NetApp -Speicher über HTTP zu ermöglichen.  Dieser Befehl ist zur Verwendung der ZAPI erforderlich.
** „security-api-vfiler“: Verwenden Sie dies, um Data Infrastructure Insights die Ausführung von NetApp -Speicher-API-Befehlen zum Abrufen von vFiler-Einheiteninformationen zu ermöglichen.
** „cli-options“: Für den Befehl „Optionen“ und wird für Partner-IP und aktivierte Lizenzen verwendet.
** „cli-lun“: Greifen Sie auf diese Befehle zum Verwalten von LUNs zu.  Zeigt den Status (LUN-Pfad, Größe, Online-/Offline-Status und Freigabestatus) der angegebenen LUN oder LUN-Klasse an.
** „cli-df“: Für die Befehle „df -s“, „df -r“, „df -A -r“ und wird zum Anzeigen des freien Speicherplatzes verwendet.
** „cli-ifconfig“: Für den Befehl „ifconfig -a“ und zum Abrufen der Filer-IP-Adresse.
** „cli-rdfile“: Für den Befehl „rdfile /etc/netgroup“ und zum Abrufen von Netzgruppen verwendet.
** „cli-date“: Für den Befehl „date“ und wird verwendet, um das vollständige Datum zum Abrufen von Snapshot-Kopien zu erhalten.
** „cli-snap“: Für den Befehl „Snap List“ und zum Abrufen von Snapshot-Kopien.




Wenn keine CLI-Date- oder CLI-Snap-Berechtigungen bereitgestellt werden, kann die Erfassung abgeschlossen werden, es werden jedoch keine Snapshot-Kopien gemeldet.

Um eine 7-Mode-Datenquelle erfolgreich zu erwerben und keine Warnungen auf dem Speichersystem zu generieren, sollten Sie eine der folgenden Befehlszeichenfolgen verwenden, um Ihre Benutzerrollen zu definieren.  Die zweite hier aufgeführte Zeichenfolge ist eine optimierte Version der ersten:

* Login-http-admin, API-*, Sicherheits-API-vfile, CLI-rdfile, CLI-Optionen, CLI-df, CLI-lun, CLI-ifconfig, CLI-date, CLI-snap,_
* login-http-admin,api-* ,security-api-vfile,cli-




== Fehlerbehebung

Wenn bei diesem Datensammler Probleme auftreten, können Sie Folgendes versuchen:



=== Inventar

[cols="2*"]
|===
| Problem: | Versuchen Sie Folgendes: 


| Erhalten Sie die HTTP-Antwort 401 oder den ZAPI-Fehlercode 13003 und ZAPI gibt „Unzureichende Berechtigungen“ oder „Nicht für diesen Befehl autorisiert“ zurück. | Überprüfen Sie Benutzernamen und Passwort sowie Benutzerrechte/Berechtigungen. 


| Fehler „Befehl konnte nicht ausgeführt werden“ | Überprüfen Sie, ob der Benutzer über die folgenden Berechtigungen auf dem Gerät verfügt: • api-* • cli-date • cli-df • cli-ifconfig • cli-lun • cli-operations • cli-rdfile • cli-snap • login-http-admin • security-api-vfiler Überprüfen Sie außerdem, ob die ONTAP Version von Data Infrastructure Insights unterstützt wird, und stellen Sie sicher, dass die verwendeten Anmeldeinformationen mit den Anmeldeinformationen des Geräts übereinstimmen. 


| Clusterversion ist < 8.1 | Die minimal unterstützte Clusterversion ist 8.1.  Aktualisieren Sie auf die minimal unterstützte Version. 


| ZAPI gibt „Clusterrolle ist nicht cluster_mgmt LIF“ zurück. | AU muss mit der Cluster-Management-IP kommunizieren.  Überprüfen Sie die IP und wechseln Sie gegebenenfalls zu einer anderen IP 


| Fehler: „7-Modus-Filer werden nicht unterstützt“ | Dies kann passieren, wenn Sie diesen Datensammler verwenden, um 7-Modus-Filer zu ermitteln.  Ändern Sie die IP, sodass sie stattdessen auf den CDOT-Filer verweist. 


| ZAPI-Befehl schlägt nach erneutem Versuch fehl | AU hat ein Kommunikationsproblem mit dem Cluster.  Überprüfen Sie Netzwerk, Portnummer und IP-Adresse.  Der Benutzer sollte auch versuchen, einen Befehl über die Befehlszeile der AU-Maschine auszuführen. 


| AU konnte keine Verbindung zu ZAPI herstellen | Überprüfen Sie die IP-/Port-Konnektivität und bestätigen Sie die ZAPI-Konfiguration. 


| AU konnte keine Verbindung zu ZAPI über HTTP herstellen | Überprüfen Sie, ob der ZAPI-Port Klartext akzeptiert.  Wenn AU versucht, Klartext an einen SSL-Socket zu senden, schlägt die Kommunikation fehl. 


| Die Kommunikation schlägt mit SSLException fehl | AU versucht, SSL an einen Klartext-Port auf einem Filer zu senden.  Überprüfen Sie, ob der ZAPI-Port SSL akzeptiert, oder verwenden Sie einen anderen Port. 


| Weitere Verbindungsfehler: Die ZAPI-Antwort hat den Fehlercode 13001, „Datenbank ist nicht geöffnet“. Der ZAPI-Fehlercode ist 60 und die Antwort enthält „API wurde nicht rechtzeitig beendet“. Die ZAPI-Antwort enthält „initialize_session() hat eine NULL-Umgebung zurückgegeben“. Der ZAPI-Fehlercode ist 14007 und die Antwort enthält „Knoten ist nicht fehlerfrei“. | Überprüfen Sie Netzwerk, Portnummer und IP-Adresse.  Der Benutzer sollte auch versuchen, einen Befehl über die Befehlszeile der AU-Maschine auszuführen. 


| Socket-Timeout-Fehler mit ZAPI | Überprüfen Sie die Filer-Konnektivität und/oder erhöhen Sie das Timeout. 


| Fehler „C-Modus-Cluster werden von der 7-Modus-Datenquelle nicht unterstützt“ | Überprüfen Sie die IP und ändern Sie die IP in einen 7-Modus-Cluster. 


| Fehler „Verbindung zum vFiler fehlgeschlagen“ | Überprüfen Sie, ob die Berechtigungen des abrufenden Benutzers mindestens Folgendes umfassen: api-* security-api-vfiler login-http-admin. Bestätigen Sie, dass auf dem Filer mindestens ONTAPI Version 1.7 ausgeführt wird. 
|===
Weitere Informationen finden Sie in derlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
