---
sidebar: sidebar 
permalink: task_dc_na_cdot.html 
keywords: data collector, ontap, ontap, CDOT 
summary: ONTAP-Datensammler 
---
= Datenkollektor der NetApp ONTAP Data Management Software
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Dieser Datensammler erfasst Inventar- und Leistungsdaten von Speichersystemen, auf denen ONTAP ausgeführt wird, mithilfe von schreibgeschützten API-Aufrufen von einem ONTAP Konto.  Dieser Datensammler erstellt außerdem einen Datensatz im Cluster-Anwendungsregister, um den Support zu beschleunigen.



== Terminologie

Data Infrastructure Insights erfasst Bestands- und Leistungsdaten vom ONTAP Datensammler.  Für jeden erworbenen Vermögenswerttyp wird die am häufigsten verwendete Terminologie für den Vermögenswert angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Scheibe | Scheibe 


| Raid-Gruppe | Datenträgergruppe 


| Cluster | Storage 


| Node | Speicherknoten 


| Aggregat | Speicherpool 


| LUN | Volumen 


| Volumen | Internes Volumen 
|===


== ONTAP Datenmanagement-Terminologie

Die folgenden Bedingungen gelten für Objekte oder Verweise, die Sie möglicherweise auf den Zielseiten der ONTAP Data Management-Speicherressourcen finden.  Viele dieser Begriffe gelten auch für andere Datensammler.



=== Storage

* Modell – Eine durch Kommas getrennte Liste der eindeutigen, diskreten Knotenmodellnamen innerhalb dieses Clusters.  Wenn alle Knoten in den Clustern vom gleichen Modelltyp sind, wird nur ein Modellname angezeigt.
* Anbieter – derselbe Anbietername, den Sie sehen würden, wenn Sie eine neue Datenquelle konfigurieren würden.
* Seriennummer – Die Seriennummer des Arrays.  Bei Speichersystemen mit Clusterarchitektur wie ONTAP Data Management ist diese Seriennummer möglicherweise weniger nützlich als die Seriennummern der einzelnen „Storage Nodes“.
* IP – im Allgemeinen handelt es sich dabei um die in der Datenquelle konfigurierten IPs oder Hostnamen.
* Mikrocode-Version – Firmware.
* Rohkapazität – Summe aller physischen Festplatten im System zur Basis 2, unabhängig von ihrer Rolle.
* Latenz – eine Darstellung der Arbeitslasten, die der Host sowohl beim Lesen als auch beim Schreiben erfährt.  Im Idealfall bezieht Data Infrastructure Insights diesen Wert direkt, dies ist jedoch häufig nicht der Fall.  Anstelle des Arrays, das dies anbietet, führt Data Infrastructure Insights im Allgemeinen eine IOP-gewichtete Berechnung durch, die aus den Statistiken der einzelnen internen Volumes abgeleitet wird.
* Durchsatz – aggregiert aus internen Volumes.  Verwaltung – dies kann einen Hyperlink zur Verwaltungsschnittstelle des Geräts enthalten.  Programmgesteuert von der Data Infrastructure Insights Datenquelle als Teil der Bestandsberichterstattung erstellt.




=== Speicherpool

* Speicher – auf welchem Speicher-Array dieser Pool lebt.  Obligatorisch.
* Typ – ein beschreibender Wert aus einer Liste mit aufgezählten Möglichkeiten.  Am häufigsten wird „Aggregat“ oder „RAID-Gruppe“ verwendet.
* Knoten – Wenn die Architektur dieses Speicherarrays so ist, dass Pools zu einem bestimmten Speicherknoten gehören, wird sein Name hier als Hyperlink zu seiner eigenen Zielseite angezeigt.
* Verwendet Flash-Pool – Ja/Nein-Wert – verfügt dieser SATA/SAS-basierte Pool über SSDs, die zur Caching-Beschleunigung verwendet werden?
* Redundanz – RAID-Level oder Schutzschema.  RAID_DP ist doppelte Parität, RAID_TP ist dreifache Parität.
* Kapazität – die Werte hier sind die logisch genutzte, nutzbare Kapazität und die logische Gesamtkapazität sowie der davon genutzte Prozentsatz.
* Überbelegte Kapazität – Wenn Sie durch den Einsatz von Effizienztechnologien eine Gesamtsumme an Volume- oder internen Volume-Kapazitäten zugewiesen haben, die größer ist als die logische Kapazität des Speicherpools, ist der Prozentwert hier größer als 0 %.
* Snapshot – verwendete und gesamte Snapshot-Kapazitäten, wenn Ihre Speicherpoolarchitektur einen Teil ihrer Kapazität Segmentbereichen ausschließlich für Snapshots zuweist.  Bei ONTAP in MetroCluster -Konfigurationen ist dies wahrscheinlich, bei anderen ONTAP Konfigurationen ist dies weniger der Fall.
* Auslastung – ein Prozentwert, der den höchsten Prozentsatz der Festplattenauslastung aller Festplatten anzeigt, die Kapazität zu diesem Speicherpool beitragen.  Die Festplattenauslastung weist nicht unbedingt eine starke Korrelation mit der Array-Leistung auf. Die Auslastung kann aufgrund von Festplattenneuaufbauten, Deduplizierungsaktivitäten usw. hoch sein, wenn keine vom Host gesteuerten Workloads vorliegen.  Darüber hinaus können Replikationsimplementierungen vieler Arrays die Festplattenauslastung erhöhen, ohne dass dies als internes Volume oder Volume-Workload angezeigt wird.
* IOPS – die Summe der IOPs aller Festplatten, die Kapazität zu diesem Speicherpool beitragen.  Durchsatz – der Gesamtdurchsatz aller Festplatten, die Kapazität zu diesem Speicherpool beitragen.




=== Speicherknoten

* Speicher – zu welchem Speicherarray dieser Knoten gehört.  Obligatorisch.
* HA-Partner – auf Plattformen, auf denen ein Knoten auf einen und nur einen anderen Knoten umgeschaltet wird, wird er im Allgemeinen hier angezeigt.
* Status – Integrität des Knotens.  Nur verfügbar, wenn das Array fehlerfrei genug ist, um von einer Datenquelle inventarisiert zu werden.
* Modell – Modellname des Knotens.
* Version – Versionsname des Geräts.
* Seriennummer – Die Seriennummer des Knotens.
* Speicher – Basis-2-Speicher, falls verfügbar.
* Auslastung – Bei ONTAP ist dies ein Controller-Stressindex aus einem proprietären Algorithmus.  Bei jeder Leistungsabfrage wird eine Zahl zwischen 0 und 100 % gemeldet, die entweder der höheren WAFL Festplattenkonflikt- oder der durchschnittlichen CPU-Auslastung entspricht.  Wenn Sie anhaltende Werte > 50 % beobachten, deutet dies auf eine Unterdimensionierung hin – möglicherweise ist ein Controller/Knoten nicht groß genug oder es sind nicht genügend rotierende Festplatten vorhanden, um die Schreibarbeitslast aufzunehmen.
* IOPS – Direkt abgeleitet von ONTAP ZAPI-Aufrufen des Knotenobjekts.
* Latenz – Wird direkt aus ONTAP ZAPI-Aufrufen des Knotenobjekts abgeleitet.
* Durchsatz – Wird direkt aus ONTAP ZAPI-Aufrufen des Knotenobjekts abgeleitet.
* Prozessoren – CPU-Anzahl.




== Anforderungen

Für die Konfiguration und Verwendung dieses Datensammlers gelten die folgenden Voraussetzungen:

* Sie müssen Zugriff auf ein Administratorkonto haben, das für schreibgeschützte API-Aufrufe konfiguriert ist.
* Zu den Kontodetails gehören Benutzername und Passwort.
* Portanforderungen: 80 oder 443
* Kontoberechtigungen:
+
** Nur-Lese-Rollennamen für die Ontapi-Anwendung auf dem Standard-Vserver
** Möglicherweise benötigen Sie zusätzliche optionale Schreibberechtigungen.  Siehe den Hinweis zu Berechtigungen weiter unten.


* ONTAP -Lizenzanforderungen:
+
** FCP-Lizenz und zugeordnete/maskierte Volumes für die Fibre-Channel-Erkennung erforderlich






=== Berechtigungsanforderungen für die Erfassung von ONTAP Switch-Metriken

Data Infrastructure Insights bietet die Möglichkeit, ONTAP Cluster-Switch-Daten als Option im Collector zu sammeln<<advanced-configuration,Erweiterte Konfiguration>> Einstellungen.  Zusätzlich zur Aktivierung auf dem Data Infrastructure Insights Kollektor müssen Sie auch *das ONTAP -System* selbst konfigurieren, um Folgendes bereitzustellen:link:https://docs.netapp.com/us-en/ontap-cli-98/system-switch-ethernet-create.html["Switch-Informationen"] und stellen Sie sicher, dass die richtige<<a-note-about-permissions,Berechtigungen>> gesetzt, um die Switch-Daten an Data Infrastructure Insights senden zu können.



== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| NetApp Management IP | IP-Adresse oder vollqualifizierter Domänenname des NetApp -Clusters 


| Benutzername | Benutzername für NetApp Cluster 


| Passwort | Passwort für NetApp -Cluster 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Anschlussart | Wählen Sie HTTP (Standardport 80) oder HTTPS (Standardport 443).  Der Standardwert ist HTTPS 


| Kommunikationsanschluss überschreiben | Geben Sie einen anderen Port an, wenn Sie nicht den Standardport verwenden möchten 


| Inventarabfrageintervall (min) | Der Standardwert ist 60 Minuten. 


| Für TLS für HTTPS | Lassen Sie TLS nur als Protokoll zu, wenn Sie HTTPS verwenden 


| Netzgruppen automatisch suchen | Aktivieren Sie die automatische Netzgruppensuche für Exportrichtlinienregeln 


| Netgroup-Erweiterung | Expansionsstrategie der Netgroup.  Wählen Sie _Datei_ oder _Shell_.  Der Standardwert ist _shell_. 


| HTTP-Lesezeitlimit (Sekunden) | Der Standardwert ist 30 


| Erzwingen Sie Antworten als UTF-8 | Zwingt den Datensammlercode, Antworten von der CLI als in UTF-8 vorliegend zu interpretieren 


| Leistungsabfrageintervall (Sek.) | Der Standardwert ist 900 Sekunden. 


| Erweiterte Zählerdatenerfassung | Aktivieren Sie die ONTAP Integration.  Wählen Sie diese Option aus, um ONTAP Advanced Counter-Daten in Umfragen einzubeziehen.  Wählen Sie die gewünschten Zähler aus der Liste aus. 


| Cluster-Switch-Metriken | Erlauben Sie Data Infrastructure Insights , Cluster-Switch-Daten zu erfassen.  Beachten Sie, dass Sie zusätzlich zur Aktivierung auf der Data Infrastructure Insights Seite auch das ONTAP -System so konfigurieren müssen, dass eslink:https://docs.netapp.com/us-en/ontap-cli-98/system-switch-ethernet-create.html["Switch-Informationen"] und stellen Sie sicher, dass die richtige<<a-note-about-permissions,Berechtigungen>> gesetzt, um die Switch-Daten an Data Infrastructure Insights senden zu können.  Siehe „Hinweis zu Berechtigungen“ weiter unten. 
|===


== ONTAP Leistungsmetriken

Mehrere ONTAP -Modelle bieten Leistungsmetriken für Data Infrastructure Insights , die zur Überwachung oder für Warnmeldungen verwendet werden können.


NOTE: Diese Listen sind nicht vollständig und können sich ändern.  Wenn ein Modell zur selben Familie gehört wie ein Modell auf der Liste, sollte die Unterstützung grundsätzlich dieselbe sein, dies kann jedoch nicht garantiert werden.  Wenn Sie nicht sicher sind, ob Ihr Modell Leistungsmetriken unterstützt, wenden Sie sich an den ONTAP Support.

Unterstützte Modelle:

A200 A220 A250 A300 A320 A400 A700 A700s A800 A900 C190 FAS2240-4 FAS2552 FAS2650 FAS2720 FAS2750 FAS8200 FAS8300 FAS8700 FAS9000

Nicht unterstützte Modelle:

FAS2620 FAS3250 FAS3270 FAS500f FAS6280 FAS/ AFF 8020 FAS/ AFF 8040 FAS/ AFF 8060 FAS/ AFF 8080



== Ein Hinweis zu Berechtigungen

Da eine Reihe von ONTAP -Dashboards von Data Infrastructure Insights auf erweiterten ONTAP -Zählern basieren, müssen Sie im Abschnitt „Erweiterte Konfiguration“ des Datensammlers die Option „Erweiterte Zählerdatenerfassung“ aktivieren.

Sie sollten außerdem sicherstellen, dass die Schreibberechtigung für die ONTAP -API aktiviert ist.  Dies erfordert normalerweise ein Konto auf Clusterebene mit den erforderlichen Berechtigungen.

Um ein lokales Konto für Data Infrastructure Insights auf Clusterebene zu erstellen, melden Sie sich bei ONTAP mit dem Benutzernamen/Passwort des Clusterverwaltungsadministrators an und führen Sie die folgenden Befehle auf dem ONTAP -Server aus:

. Bevor Sie beginnen, müssen Sie mit einem _Administrator_-Konto bei ONTAP angemeldet sein und _Befehle auf Diagnoseebene_ müssen aktiviert sein.
. Erstellen Sie mit den folgenden Befehlen eine schreibgeschützte Rolle.
+
....
security login role create -role ci_readonly -cmddirname DEFAULT -access readonly
security login role create -role ci_readonly -cmddirname security -access readonly
security login role create -role ci_readonly -access all -cmddirname {cluster application-record create}
....
. Erstellen Sie den schreibgeschützten Benutzer mit dem folgenden Befehl.  Nachdem Sie den Befehl „Erstellen“ ausgeführt haben, werden Sie aufgefordert, ein Kennwort für diesen Benutzer einzugeben.
+
 security login create -username ci_user -application ontapi -authentication-method password -role ci_readonly


Wenn ein AD/LDAP-Konto verwendet wird, sollte der Befehl

 security login create -user-or-group-name DOMAIN\aduser/adgroup -application ontapi -authentication-method domain -role ci_readonly
Wenn Sie Cluster-Switch-Daten erfassen:

....
security login rest-role create -role ci_readonly_rest -api /api/network/ethernet -access readonly
security login create -user-or-group-name ci_user -application http -authmethod password -role ci_readonly_rest
....
Die resultierende Rolle und Benutzeranmeldung werden etwa wie folgt aussehen.  Ihre tatsächliche Ausgabe kann abweichen:

....
Role Command/ Access
Vserver Name Directory Query Level
---------- ------------- --------- ------------------ --------
cluster1 ci_readonly DEFAULT read only
cluster1 ci_readonly security readonly
....
....
cluster1:security login> show
Vserver: cluster1
Authentication Acct
UserName    Application   Method      Role Name      Locked
---------   -------      ----------- -------------- --------
ci_user     ontapi      password    ci_readonly   no
....

NOTE: Wenn die ONTAP Zugriffskontrolle nicht richtig eingestellt ist, können Data Infrastructure Insights REST-Aufrufe fehlschlagen, was zu Datenlücken für das Gerät führt.  Wenn Sie es beispielsweise auf dem Data Infrastructure Insights -Collector aktiviert, die Berechtigungen auf dem ONTAP jedoch nicht konfiguriert haben, schlägt die Erfassung fehl.  Wenn die Rolle zuvor auf ONTAP definiert wurde und Sie die Rest-API-Funktionen hinzufügen, stellen Sie außerdem sicher, dass _http_ zur Rolle hinzugefügt wird.



== Fehlerbehebung

Wenn bei diesem Datensammler Probleme auftreten, können Sie Folgendes versuchen:



=== Inventar

[cols="2*"]
|===
| Problem: | Versuchen Sie Folgendes: 


| Erhalten Sie die HTTP-Antwort 401 oder den ZAPI-Fehlercode 13003 und ZAPI gibt „Unzureichende Berechtigungen“ oder „Nicht für diesen Befehl autorisiert“ zurück. | Überprüfen Sie Benutzernamen und Passwort sowie Benutzerrechte/Berechtigungen. 


| Clusterversion ist < 8.1 | Die minimal unterstützte Clusterversion ist 8.1.  Aktualisieren Sie auf die minimal unterstützte Version. 


| ZAPI gibt „Clusterrolle ist nicht cluster_mgmt LIF“ zurück. | AU muss mit der Cluster-Management-IP kommunizieren.  Überprüfen Sie die IP und wechseln Sie gegebenenfalls zu einer anderen IP 


| Fehler: „7-Modus-Filer werden nicht unterstützt“ | Dies kann passieren, wenn Sie diesen Datensammler verwenden, um 7-Modus-Filer zu ermitteln.  Ändern Sie die IP, sodass sie stattdessen auf den CDOT-Cluster verweist. 


| ZAPI-Befehl schlägt nach erneutem Versuch fehl | AU hat ein Kommunikationsproblem mit dem Cluster.  Überprüfen Sie Netzwerk, Portnummer und IP-Adresse.  Der Benutzer sollte auch versuchen, einen Befehl über die Befehlszeile der AU-Maschine auszuführen. 


| AU konnte keine Verbindung zu ZAPI über HTTP herstellen | Überprüfen Sie, ob der ZAPI-Port Klartext akzeptiert.  Wenn AU versucht, Klartext an einen SSL-Socket zu senden, schlägt die Kommunikation fehl. 


| Die Kommunikation schlägt mit SSLException fehl | AU versucht, SSL an einen Klartext-Port auf einem Filer zu senden.  Überprüfen Sie, ob der ZAPI-Port SSL akzeptiert, oder verwenden Sie einen anderen Port. 


| Weitere Verbindungsfehler: Die ZAPI-Antwort hat den Fehlercode 13001, „Datenbank ist nicht geöffnet“. Der ZAPI-Fehlercode ist 60 und die Antwort enthält „API wurde nicht rechtzeitig beendet“. Die ZAPI-Antwort enthält „initialize_session() hat eine NULL-Umgebung zurückgegeben“. Der ZAPI-Fehlercode ist 14007 und die Antwort enthält „Knoten ist nicht fehlerfrei“. | Überprüfen Sie Netzwerk, Portnummer und IP-Adresse.  Der Benutzer sollte auch versuchen, einen Befehl über die Befehlszeile der AU-Maschine auszuführen. 
|===


=== Performance

[cols="2*"]
|===
| Problem: | Versuchen Sie Folgendes: 


| Fehler „Leistung konnte nicht von ZAPI erfasst werden“ | Dies liegt normalerweise daran, dass die Leistungsstatistik nicht ausgeführt wird.  Versuchen Sie auf jedem Knoten den folgenden Befehl: > _system node systemshell -node * -command “spmctl -h cmd –stop; spmctl -h cmd –exec”_ 
|===
Weitere Informationen finden Sie in derlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
