---
sidebar: sidebar 
permalink: task_dc_emc_xio.html 
keywords: data collector, XtremeIO, EMC 
summary: Konfigurieren des XtremeIO-Datenkollektors. 
---
= Dell EMC XtremeIO-Datenkollektor
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Der EMC XtremIO-Datenkollektor erfasst Bestands- und Leistungsdaten vom EMC XtremIO-Speichersystem.



[[requirements]]
== Anforderungen

Zum Konfigurieren des EMC XtremIO (HTTP)-Datenkollektors benötigen Sie:

* Die Hostadresse des XtremIO Management Servers (XMS)
* Ein Konto mit Administratorrechten
* Zugriff auf Port 443 (HTTPS)




[[terminology]]
== Terminologie

Data Infrastructure Insights erhält die folgenden Bestandsinformationen vom EMC XtremIO-Datenkollektor.  Für jeden von Data Infrastructure Insights erworbenen Asset-Typ wird die am häufigsten verwendete Terminologie für dieses Asset angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieser Datenquelle die folgende Terminologie:

[cols="50,50"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Festplatte (SSD) | Scheibe 


| Cluster | Storage 


| Regler | Speicherknoten 


| Volumen | Volumen 


| LUN-Karte | Volumenkarte 


| Ziel-FC-Initiator | Volumenmaske 
|===
Hinweis: Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diese Datenquelle darstellen.



[[requirements]]
== Anforderungen

* Die Host-IP-Adresse des XtremIO Management Server (XMS)
* Administratorbenutzername und -kennwort für XtremIO




[[configuration]]
== Konfiguration

[cols="50,50"]
|===
| Feld | Beschreibung 


| XMS-Host | IP-Adresse oder vollqualifizierter Domänenname des XtremIO-Managementservers 


| Benutzername | Benutzername für den XtremIO-Managementserver 


| Passwort | Kennwort für den XtremIO-Managementserver 
|===


[[advanced-configuration]]
== Erweiterte Konfiguration

[cols="50,50"]
|===
| Feld | Beschreibung 


| TCP-Port | TCP-Port, der für die Verbindung mit dem XTremIO-Verwaltungsserver verwendet wird.  Der Standardwert ist 443. 


| Inventarabfrageintervall (min) | Intervall zwischen den Bestandsabfragen. Der Standardwert beträgt 60 Minuten. 


| Leistungsabfrageintervall (Sek.) | Intervall zwischen Leistungsabfragen. Der Standardwert beträgt 300 Sekunden. 
|===


[[troubleshooting]]
== Fehlerbehebung

Weitere Informationen zu diesem Datensammler finden Sie imlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
