---
sidebar: sidebar 
permalink: task_dc_emc_datadomain.html 
keywords: data collector, Data Domain, EMC, DELL 
summary: Konfigurieren des DELL EMC Data Domain-Datenkollektors. 
---
= DELL EMC Data Domain-Datenkollektor
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Dieser Datensammler sammelt Bestands- und Leistungsinformationen von DELL EMC Data Domain-Deduplizierungsspeichersystemen.  Zum Konfigurieren dieses Datensammlers müssen Sie bestimmte Konfigurationsanweisungen und Verwendungsempfehlungen befolgen.



== Terminologie

Data Infrastructure Insights erhält die folgenden Bestandsinformationen vom Data Domain-Datenkollektor.  Für jeden von Data Infrastructure Insights erworbenen Asset-Typ wird die am häufigsten verwendete Terminologie für dieses Asset angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Scheibe | Scheibe 


| Anordnung | Storage 


| FC-Anschluss | Hafen 


| Dateisystem | Internes Volumen 


| Quote | Quote 


| NFS- und CIFS-Freigabe | Dateifreigabe 
|===
Hinweis: Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diesen Datensammler darstellen.



== Anforderungen

Zur Konfiguration dieses Datensammlers benötigen Sie folgende Informationen:

* IP-Adresse des Data Domain-Geräts
* Nur-Lese-Benutzername und Kennwort für den Data Domain-Speicher
* SSH-Port 22




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| IP-Adresse | Die IP-Adresse oder der vollqualifizierte Domänenname des Data Domain-Speicherarrays 


| Benutzername | Der Benutzername für das Data Domain-Speicherarray 


| Passwort | Das Kennwort für das Data Domain-Speicherarray 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Inventarabfrageintervall (min) | Intervall zwischen den Bestandsabfragen.  Der Standardwert ist 20. 


| SSH-Port | SSH-Dienstport 
|===


== Fehlerbehebung

Weitere Informationen zu diesem Datensammler finden Sie imlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
