---
sidebar: sidebar 
permalink: task_dc_vmware.html 
keywords: data collector, VMware, 
summary: Konfigurieren des VMware-Datenkollektors. 
---
= Konfigurieren des VMware VSphere-Datenkollektors
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Der Datensammler für VMware vSphere sammelt Leistungs- und Konfigurationsinformationen von VM-Gästen und ESXi-Hosts und erfordert schreibgeschützte Berechtigungen für alle Objekte innerhalb von vSphere.  Ab August 2024 bringt der vSphere-Collector zusätzlich Protokollnachrichten aus vSphere-Umgebungen und einige VMware-spezifische Metriken ein.  Bitte beachten Sie, dass Data Infrastructure Insights nur VMware-Protokollinformationen aus Umgebungen mit vSphere 8.0.1 oder höher abrufen kann.  Ebenso werden die anbieterspezifischen Metriken nur für vSphere 7+-Umgebungen unterstützt.  Daher möchten Sie möglicherweise das Kontrollkästchen „Protokolle“ und/oder „Anbieterspezifische Metriken“ bei einem bestimmten Collector deaktivieren, wenn dieser auf eine ältere vSphere-Instanz verweist.



== Terminologie

Data Infrastructure Insights erhält die folgenden Bestandsinformationen vom VMware vSphere-Datenkollektor.  Für jeden erworbenen Vermögenswerttyp wird die am häufigsten verwendete Terminologie für den Vermögenswert angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Virtuelle Festplatte | Scheibe 


| Gastgeber | Gastgeber 


| Virtuelle Maschine | Virtuelle Maschine 


| Datenspeicher | Datenspeicher 


| LUN | Volumen 


| Fibre-Channel-Anschluss | Hafen 
|===
Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diesen Datensammler darstellen.



== Anforderungen

Zur Konfiguration dieses Datensammlers sind folgende Angaben erforderlich:

* IP-Adresse des Virtual Center-Servers
* Benutzername und Kennwort im Virtual Center sind schreibgeschützt
* Wir benötigen nur Leseberechtigungen für alle Objekte im Virtual Center.
* SDK-Zugriff auf den Virtual Center-Server – normalerweise bereits eingerichtet.
* Portanforderungen: http-80 https-443
* Zugriff validieren:
+
** Melden Sie sich mit dem oben genannten Benutzernamen und Kennwort beim Virtual Center Client an
** Überprüfen Sie, ob das SDK aktiviert ist: Telnet <vc_ip> 443






== Einrichtung und Anschluss

[cols="2*"]
|===
| Feld | Beschreibung 


| Name | Eindeutiger Name für den Datensammler 


| Erfassungseinheit | Name der Erfassungseinheit 
|===


== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| IP-Adresse des virtuellen Zentrums | IP-Adresse des Virtual Centers 


| Benutzername | Benutzername für den Zugriff auf das Virtual Center 


| Passwort | Passwort für den Zugriff auf das Virtual Center 
|===


== Erweiterte Konfiguration

Aktivieren Sie im Bildschirm „Erweiterte Konfiguration“ das Kontrollkästchen *VM-Leistung*, um Leistungsdaten zu erfassen.  Die Inventarerfassung ist standardmäßig aktiviert.  Die folgenden Felder können konfiguriert werden:

[cols="2*"]
|===


| Feld | Beschreibung 


| Inventarabfrageintervall (min) | Der Standardwert ist 20 


| Filtern von VMs | Wählen Sie CLUSTER, DATACENTER oder ESX HOST 


| Wählen Sie „Ausschließen“ oder „Einschließen“, um eine Liste anzugeben | Erstellen Sie eine Filterliste (CLUSTER, DATACENTER und/oder ESX_HOST). 


| Anzahl der Wiederholungsversuche | Der Standardwert ist 3 


| Kommunikationsanschluss | Der Standardwert ist 443 


| Geräteliste filtern... | Diese Liste muss aus exakten Zeichenfolgenübereinstimmungen bestehen. Wenn Sie nach ESX_HOST filtern möchten, müssen Sie eine durch Kommas getrennte Liste der exakten „Namen“ Ihrer ESX-Hosts erstellen, wie sie sowohl in Data Infrastructure Insights als auch in vSphere gemeldet werden.  Bei diesen „Namen“ kann es sich entweder um IP-Adressen, einfache Hostnamen oder vollqualifizierte Domänennamen (FQDNs) handeln. Dies wird dadurch bestimmt, wie diese Hosts benannt wurden, als sie ursprünglich zu vSphere hinzugefügt wurden.  Verwenden Sie beim Filtern nach CLUSTER die Clusternamen im Data Infrastructure Insights-Stil, wie sie von CI auf Hypervisoren gemeldet werden – Data Infrastructure Insights stellt dem vSphere-Clusternamen den Namen des vSphere-Rechenzentrums und einen Schrägstrich voran – „DC1/clusterA“ ist der Clustername, den Data Infrastructure Insights auf einem Hypervisor in ClusterA innerhalb des Rechenzentrums DC1 melden würde. 


| Leistungsabfrageintervall (Sek.) | Der Standardwert ist 300 
|===


== Zuordnen von VMware-Tags zu Data Infrastructure Insights -Anmerkungen

Mit dem VMware-Datensammler können Sie Data Infrastructure Insights -Anmerkungen mit auf VMware konfigurierten Tags füllen.  Der DII-Annotationsname muss mit dem VMware-*Kategorie*namen identisch sein. Das Tag wird dann als Annotationswert einer DII-Annotation mit demselben Namen wie die Kategorie angewendet.  Data Infrastructure Insights füllt immer gleichnamige Textanmerkungen aus und unternimmt den bestmöglichen Versuch, Anmerkungen anderer Typen (Zahl, Boolescher Wert usw.) auszufüllen.  Wenn Ihre Anmerkung einen anderen Typ hat und der Datensammler sie nicht ausfüllen kann, kann es erforderlich sein, die Anmerkung zu entfernen und als Texttyp neu zu erstellen.

Beachten Sie, dass bei VMware-Tags die Groß- und Kleinschreibung beachtet werden kann, bei Data Infrastructure Insights -Tags hingegen nicht.  Wenn Sie also in Data Infrastructure Insights eine Annotation mit dem Namen „OWNER“ und in VMware Tags mit den Namen „OWNER“, „Owner“ und „owner“ erstellen, werden alle diese Variationen von „owner“ der Annotation „OWNER“ von Cloud Insight zugeordnet.

Beachten Sie Folgendes:

* Data Infrastructure Insights veröffentlicht derzeit nur automatisch Supportinformationen für NetApp -Geräte.
* Da diese Supportinformationen in Form von Anmerkungen vorliegen, können Sie sie abfragen oder in Dashboards verwenden.
* Wenn ein Benutzer den Annotationswert überschreibt oder leert, wird der Wert automatisch erneut ausgefüllt, wenn Data Infrastructure Insights die Annotationen aktualisiert, was einmal täglich geschieht.




== Fehlerbehebung

Wenn bei diesem Datensammler Probleme auftreten, können Sie Folgendes versuchen:



=== Inventar

[cols="2*"]
|===
| Problem: | Versuchen Sie Folgendes: 


| Fehler: Die Einschlussliste zum Filtern von VMs darf nicht leer sein | Wenn „Liste einschließen“ ausgewählt ist, listen Sie bitte gültige DataCenter-, Cluster- oder Hostnamen auf, um VMs zu filtern 


| Fehler: Es konnte keine Verbindung zu VirtualCenter unter IP hergestellt werden | Mögliche Lösungen: * Überprüfen Sie die eingegebenen Anmeldeinformationen und die IP-Adresse.  * Versuchen Sie, über den VMware Infrastructure Client mit Virtual Center zu kommunizieren.  * Versuchen Sie, über den Managed Object Browser (z. B. MOB) mit Virtual Center zu kommunizieren. 


| Fehler: VirtualCenter bei IP verfügt über ein nicht konformes Zertifikat, das JVM benötigt | Mögliche Lösungen: * Empfohlen: Generieren Sie das Zertifikat für Virtual Center neu, indem Sie einen stärkeren (z. B. 1024-Bit) RSA-Schlüssel verwenden.  * Nicht empfohlen: Ändern Sie die JVM-Konfiguration java.security, um die Einschränkung jdk.certpath.disabledAlgorithms zu nutzen und einen 512-Bit-RSA-Schlüssel zuzulassen. Sehen link:http://www.oracle.com/technetwork/java/javase/7u40-relnotes-2004172.html["Versionshinweise zu JDK 7 Update 40"] . 


| Ich sehe die Meldung: „VMware Logs-Paket wird auf VMware unter Version 8.0.1 nicht unterstützt.“ | Die Protokollerfassung wird auf VMware-Versionen vor 8.0.1 nicht unterstützt.  Aktualisieren Sie Ihre VI Center-Infrastruktur auf Version 8.0.1 oder höher, wenn Sie die Funktion „Protokollsammlungen“ in Data Infrastructure Insights verwenden möchten.  Weitere Informationen finden Sie hierlink:https://kb.netapp.com/Cloud/ncds/nds/dii/dii_kbs/Data_Infrastructure_Insights_Brocade_data_source_fails_performance_collection_with_a_timeout_due_to_default_SNMP_configuration["KB-Artikel"] . 
|===
Weitere Informationen finden Sie in derlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
