---
sidebar: sidebar 
permalink: task_dc_pure_flasharray.html 
keywords: data collector, Pure Storage, pure 
summary: Konfigurieren des Pure Storage-Datensammlers. 
---
= Pure Storage FlashArray-Datensammler
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights verwendet den Pure Storage FlashArray-Datensammler, um Bestands- und Leistungsdaten zu erfassen.



== Terminologie

Für jeden von Data Infrastructure Insights erfassten Asset-Typ wird die am häufigsten verwendete Terminologie für das Asset angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Laufwerk (SSD) | Scheibe 


| Anordnung | Storage 


| Regler | Speicherknoten 


| Volumen | Volumen 


| LUN-Karte | Volumenkarte 


| Initiator, Ziel | Volumenmaske 
|===
Hinweis: Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diesen Datensammler darstellen.



== Anforderungen

* IP-Adresse des Speichersystems
* Benutzername und Passwort für das Administratorkonto des Pure-Speichersystems.
* Portanforderung: HTTP/HTTPS 80/443




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| FlashArray-Host-IP-Adresse | IP-Adresse des Speichersystems 


| Benutzername | Benutzername mit Administratorrechten 


| Kennwort für das Administratorkonto | Passwort 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Anschlussart | Wählen Sie HTTP oder HTTPS.  Zeigt auch den Standardport an. 


| TCP-Port überschreiben | Wenn das Feld „Verbindungstyp“ leer ist, verwenden Sie den Standardport. Andernfalls geben Sie den zu verwendenden Verbindungsport ein. 


| Inventarabfrageintervall (min) | Der Standardwert beträgt 60 Minuten 


| Leistungsabfrageintervall (Sek.) | Der Standardwert ist 300 
|===


== Fehlerbehebung

Wenn bei diesem Datensammler Probleme auftreten, können Sie Folgendes versuchen:



=== Inventar

[cols="2*"]
|===
| Problem: | Versuchen Sie Folgendes: 


| „Ungültige Anmeldeinformationen“ mit den Fehlermeldungen „Richtlinie lässt dies nicht zu“ oder „Sie sind nicht autorisiert“ | Validieren Sie das Pure-Benutzerkonto und das Passwort über die Pure-HTTP-Schnittstelle 
|===
Weitere Informationen finden Sie in derlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
