---
sidebar: sidebar 
permalink: task_dc_ibm_cs.html 
keywords: data collector, IBM CS, CS Series 
summary: Konfigurieren des IBM CS-Datenkollektors. 
---
= IBM CS-Datenkollektor
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights verwendet diesen Datensammler, um Bestands- und Leistungsdaten für IBM CS-Speichersysteme zu ermitteln.



== Terminologie

Data Infrastructure Insights erhält die folgenden Bestandsinformationen vom IBM CS-Datenkollektor.  Für jeden von Data Infrastructure Insights erworbenen Asset-Typ wird die am häufigsten verwendete Terminologie für dieses Asset angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Speicherpool | Speicherpool 


| Container | Internes Volumen 


| Container | Dateifreigabe 


| NFS-Freigabe | Aktie 
|===
Hinweis: Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diesen Datensammler darstellen.



== Anforderungen

* Die IP-Adresse der externen Datendienste für den Cluster
* Administrator-Benutzername und -Passwort
* Port 9440




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Externe Prism-IP-Adresse | Die IP-Adresse der externen Datendienste für den Cluster 


| Benutzername | Benutzername für das Admin-Konto 


| Passwort | Passwort für das Admin-Konto 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| TCP-Port | TCP-Port, der für die Verbindung mit dem IBM CS-Array verwendet wird.  Der Standardwert ist 9440. 


| Inventarabfrageintervall (min) | Intervall zwischen den Bestandsabfragen. Der Standardwert beträgt 60 Minuten. 


| Leistungsabfrageintervall (Sek.) | Intervall zwischen Leistungsabfragen. Der Standardwert beträgt 300 Sekunden. 
|===


== Fehlerbehebung

Weitere Informationen zu diesem Datensammler finden Sie imlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
