---
sidebar: sidebar 
permalink: task_modify_delete_query.html 
summary: Ändern oder Löschen einer Abfrage 
keywords: query, queries, modify, edit, delete, remove 
---
= Ändern oder Löschen einer Abfrage
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Sie können die mit einer Abfrage verknüpften Kriterien ändern, wenn Sie die Suchkriterien für die abgefragten Assets ändern möchten.



== Ändern einer Abfrage

.Schritte
. Klicken Sie auf *Erkunden* und wählen Sie *Alle Metrikabfragen* aus.
+
Die Seite „Abfragen“ wird angezeigt.

. Klicken Sie auf den Abfragenamen
. Um der Abfrage ein Kriterium hinzuzufügen, klicken Sie auf das Spaltensymbol und wählen Sie eine Metrik oder ein Attribut aus der Liste aus.


Wenn Sie alle erforderlichen Änderungen vorgenommen haben, führen Sie einen der folgenden Schritte aus:

* Klicken Sie auf die Schaltfläche *Speichern*, um die Abfrage unter dem ursprünglich verwendeten Namen zu speichern.
* Klicken Sie auf das Dropdown-Menü neben der Schaltfläche *Speichern* und wählen Sie *Speichern unter*, um die Abfrage unter einem anderen Namen zu speichern.  Dadurch wird die ursprüngliche Abfrage nicht überschrieben.
* Klicken Sie auf das Dropdown-Menü neben der Schaltfläche *Speichern* und wählen Sie *Umbenennen*, um den ursprünglich verwendeten Abfragenamen zu ändern.  Dadurch wird die ursprüngliche Abfrage überschrieben.
* Klicken Sie auf das Dropdown-Menü neben der Schaltfläche *Speichern* und wählen Sie *Änderungen verwerfen*, um die Abfrage auf die zuletzt gespeicherten Änderungen zurückzusetzen.




== Löschen einer Abfrage

Um eine Abfrage zu löschen, klicken Sie auf *Abfragen*, wählen Sie *Alle Abfragen anzeigen* und führen Sie einen der folgenden Schritte aus:

. Klicken Sie auf das Drei-Punkte-Menü rechts neben der Abfrage und klicken Sie auf *Löschen*.
. Klicken Sie auf den Abfragenamen und wählen Sie *Löschen* aus dem Dropdown-Menü *Speichern*.

