---
sidebar: sidebar 
permalink: task_dc_na_storagegrid.html 
summary: Konfigurieren des NetApp StorageGRID Datenkollektors 
keywords: data collector, queries, create, storagegrid 
---
= NetApp StorageGRID Datenkollektor
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Der NetApp StorageGRID Datenkollektor unterstützt die Bestands- und Leistungserfassung von StorageGRID Konfigurationen.

[NOTE]
====
Um eine konsistente Messung der DII-Berechtigungen über alle StorageGRID -Systeme hinweg unabhängig von der zugrunde liegenden Hardwaretopologie und -konfiguration zu gewährleisten, verwendet Data Infrastructure Insights die gesamte verfügbare Kapazität (storagegrid_storage_utilization_total_space_bytes) anstelle der RAW-Kapazität basierend auf dem physischen Festplattenlayout.

Für Kunden, die das kapazitätsbasierte Lizenzmodell verwenden, wird StorageGRID als „Objekt“-Speicher gemessen.

Für Kunden, die das alte (MU) Lizenzmodell verwenden, wird StorageGRID als Sekundärspeicher mit einem Satz von 40 TiB zu 1 MU gemessen.

====


== Terminologie

Data Infrastructure Insights erhält die folgenden Bestandsinformationen vom NetApp StorageGRID Collector.  Für jeden erworbenen Vermögenswerttyp wird die am häufigsten verwendete Terminologie für diesen Vermögenswert angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| StorageGRID | Storage 


| Node | Node 


| Mieter | Speicherpool 


| Eimer | Internes Volumen 
|===


== Anforderungen

Für die Konfiguration dieser Datenquelle gelten die folgenden Voraussetzungen:

* StorageGRID Host-IP-Adresse
* Ein Benutzername und ein Kennwort für einen Benutzer, dem die Rollen „Metrikabfrage“ und „Mandantenzugriff“ zugewiesen wurden
* Port 443




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| StorageGRID Host-IP-Adresse | Verwaltung Virtuelle IP-Adresse des StorageGRID -Geräts 


| Benutzername | Name, der für die Anmeldung beim StorageGRID -Gerät verwendet wird 


| Passwort | Kennwort zum Anmelden bei der StorageGRID -Appliance 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Inventarabfrageintervall (min) | Der Standardwert ist 60 Minuten 


| Leistungsabfrageintervall (Sek.) | Der Standardwert ist 900 Sekunden 
|===


== Einmaliges Anmelden (SSO)

Derlink:https://docs.netapp.com/sgws-112/index.jsp["StorageGRID"] Firmware-Versionen haben entsprechende API-Versionen; 3.0 API und neuere Versionen unterstützen die Single Sign-On-Anmeldung (SSO).

|===


| Firmware-Version | API-Version | Unterstützt Single Sign-On (SSO) 


| 11,1 | 2 | Nein 


| 11,2 | 3,0 | Ja 


| 11,5 | 3,3 | Ja 
|===


== Fehlerbehebung

Weitere Informationen zu diesem Datensammler finden Sie imlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
