---
sidebar: sidebar 
permalink: task_dc_brocade_sphereon_intrepid.html 
keywords: data collector, Brocade, Sphereon Intrepid, 
summary: Konfigurieren des Datensammlers Brocade Sphereon/Intrepid Switch 
---
= Konfigurieren des Datensammlers Brocade Sphereon/Intrepid Switch
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Dateninfrastruktur Insights verwendet den Brocade-Datensammler Sphereon/Intrepid Switch (SNMP) zur Bestandsaufnahme von Brocade Sphereon oder Intrepid Switches.



== Anforderungen

Zur Konfiguration dieses Datensammlers müssen die folgenden Anforderungen erfüllt sein:

* Es muss eine IP-Verbindung zu allen Switches in der Fabric vorhanden sein. Wenn Sie das Kontrollkästchen Alle Switches in der Fabric ermitteln aktivieren, identifiziert Data Infrastructure Insights alle Switches in der Fabric, benötigt jedoch IP-Konnektivität zu diesen zusätzlichen Switches, um sie zu erkennen.
* Schreibgeschützte Community-Zeichenfolge bei Verwendung von SNMP V1 oder SNMP V2
* HTTP-Zugriff auf den Switch, um Zoning-Informationen zu erhalten.
* Zugriffsvalidierung durch Ausführen des snmpwalk-Dienstprogramms zum Switch (siehe _<install_path>\bin\_).




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Sphereon Switch | IP-Adresse oder vollqualifizierter Domain-Name des Switches 


| SNMP-Version | SNMP-Version 


| SNMP-Community-Zeichenfolge | SNMP read-only Community String verwendet, um auf den Switch zugreifen 


| SNMP-Benutzername | SMI-S-Benutzername für den Switch (nur SNMP v3) 


| SNMP-Kennwort | SMI-S-Kennwort für den Switch (nur SNMP v3) 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Abfrageintervall für Bestand (min) | Intervall zwischen Bestandsabstimmungen Die Standardeinstellung ist 15 Minuten. 


| SNMP-Auth-Protokoll | SNMP-Authentifizierungsprotokoll (nur SNMP v3) 


| SNMP-Datenschutzkennwort | SNMP-Datenschutzkennwort (nur SNMP v3) 


| SNMP-Anzahl der Wiederholungen | Anzahl der SNMP-Wiederholungsversuche 


| Fabric-Name | Der Fabric-Name wird vom Data Collector gemeldet. Lassen Sie das Feld leer, um den Fabric-Namen als WWN zu melden. 


| Trapping Aktivieren | Wählen Sie diese Option aus, um die Erfassung beim Empfang eines SNMP-Trap vom Gerät zu aktivieren. Wenn Sie Trapping aktivieren auswählen, müssen Sie auch SNMP aktivieren. 


| Mindestzeit zwischen Traps (Sekunden) | Mindestzeit zwischen durch Traps ausgelösten Erfassungsversuchen. Die Standardeinstellung ist 10 Sekunden. 


| Leistungsintervall (Sek.) | Intervall zwischen Performance-Abstimmungen Die Standardeinstellung ist 300 Sekunden. 
|===


== Fehlerbehebung

Weitere Informationen zu diesem Data Collector finden Sie auf der link:concept_requesting_support.html["Support"] Seite oder im link:reference_data_collector_support_matrix.html["Data Collector Supportmatrix"].
