---
sidebar: sidebar 
permalink: task_dc_dell_xc_series.html 
keywords: data collector, Dell, EMC, xc 
summary: Konfigurieren des Datenkollektors der Dell EMC XC-Serie. 
---
= Datensammler der Dell EMC XC-Serie
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights verwendet diesen Datensammler, um Bestands- und Leistungsinformationen für die Speicher-Arrays der Dell EMC XC-Serie zu ermitteln.



== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Externe Prism-IP-Adresse | IP-Adresse des XC-Servers 


| Benutzername | Benutzername für den XC-Server 


| Passwort | Für den XC-Server verwendetes Passwort 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| TCP-Port | Für die TCP-Kommunikation mit dem XC-Server verwendeter Port 


| Inventarabfrageintervall (min) | Intervall zwischen den Bestandsabfragen. Der Standardwert beträgt 60 Minuten. 


| Leistungsabfrageintervall (min) | Intervall zwischen Leistungsabfragen. Der Standardwert beträgt 300 Sekunden. 
|===


== Fehlerbehebung

Weitere Informationen finden Sie in derlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
