---
sidebar: sidebar 
permalink: task_dc_pure_flashblade.html 
keywords: data collector, Pure Storage, pure, FlashBlade 
summary: Pure Storage Data Collector wird konfiguriert. 
---
= Datensammler Pure Storage FlashBlade
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights verwendet den Pure Storage FlashBlade Data Collector, um Inventar- und Performance-Daten von FlashBlade-Clustern zu erfassen, die Version 2 ihrer REST-API bieten



== Terminologie

Für jeden Asset-Typ, der von Data Infrastructure Insights erworben wurde, wird die gängigste Terminologie für die Ressource angezeigt. Beachten Sie bei der Anzeige oder Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter-/Modelllaufzeit | Einblicke Aus Der Dateninfrastruktur 


| Laufwerk (SSD) | Festplatte 


| Array Erledigen | Storage 


| Klinge | Storage-Node 


| File-System | Internes Volumen 


| Objekt-Storage-Bucket | Qtree 


| Initiator, Ziel | Volume-Maske 
|===
Hinweis: Es handelt sich hierbei nur um allgemeine Terminologiezuordnungen. Diese stellen für diesen Datensammler möglicherweise nicht alle Fälle dar.



== Anforderungen

* IP-Adresse des Speichersystems oder vollständig qualifizierter Domänenname
* API-Token, ideal mit einer unendlichen Lebensdauer. Ein Benutzer der schreibgeschützten Ebene sollte ausreichen.
* Port-Anforderung: HTTPS 443




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| FlashBlade Host-IP-Adresse | IP-Adresse des Storage-Systems 


| Benutzername | Benutzername, der Data Infrastructure Insights Administratoren hilft, sich zu merken, zu welchem Benutzer ihr API-Token gehört 


| API-Token | API-Token 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Verbindungstyp | Wählen Sie HTTP oder HTTPS. Zeigt auch den Standardport an. 


| TCP-Port überschreiben | Wenn Sie leer sind, verwenden Sie den Standardport im Feld Verbindungstyp. Andernfalls geben Sie den zu verwendenden Anschluss ein 


| Abfrageintervall für Bestand (min) | Der Standardwert ist 60 Minuten 


| Leistungsintervall (Sek.) | Der Standardwert ist 300 
|===


== Fehlerbehebung

Einige Dinge zu versuchen, wenn Sie Probleme mit diesem Datensammler stoßen:



=== Inventar

[cols="2*"]
|===
| Problem: | Versuchen Sie dies: 


| „Ungültige Anmeldeinformationen“ mit Fehlermeldungen „Richtlinie lässt nicht zu“ oder „Sie sind nicht autorisiert“ | Validierung des Pure Benutzerkontos und Passworts über die Pure http Schnittstelle 
|===
Weitere Informationen finden Sie auf der link:concept_requesting_support.html["Support"] Seite oder im link:reference_data_collector_support_matrix.html["Data Collector Supportmatrix"].
