---
sidebar: sidebar 
permalink: task_dc_emc_powerstore.html 
keywords: data collector, PowerStore, EMC, DELL 
summary: Konfigurieren des DELL EMC PowerStore-Datenkollektors. 
---
= Dell EMC PowerStore-Datenkollektor
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Der EMC PowerStore-Datenkollektor sammelt Bestandsinformationen vom EMC PowerStore-Speicher.  Zur Konfiguration benötigt der Datensammler die IP-Adresse der Speicherprozessoren sowie einen schreibgeschützten Benutzernamen und ein Passwort.

Der EMC PowerStore-Datenkollektor erfasst die Volume-zu-Volume-Replikationsbeziehungen, die PowerStore über andere Speicher-Arrays hinweg koordiniert.  Data Infrastructure Insights zeigt ein Speicherarray für jeden PowerStore-Cluster und sammelt Bestandsdaten für Knoten und Speicherports auf diesem Cluster.  Es werden keine Speicherpool- oder Volumedaten erfasst.



== Terminologie

Data Infrastructure Insights erhält von diesem Datensammler die folgenden Bestandsinformationen.  Für jeden von Data Infrastructure Insights erworbenen Asset-Typ wird die am häufigsten verwendete Terminologie für dieses Asset angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Gastgeber | Gastgeber 


| Host-Volume-Zuordnung | Host-Volume-Zuordnung 


| Hardware (es hat Laufwerke unter dem Objekt "extra_details"): Laufwerke | Scheibe 


| Gerät | Speicherpool 


| Cluster | Speicher-Array 


| Node | Speicherknoten 


| fc_port | Hafen 


| Volumen | Volumen 


| Internes Volumen | Dateisystem 
|===
Hinweis: Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diesen Datensammler darstellen.



== Anforderungen

Zur Konfiguration dieses Datensammlers sind folgende Angaben erforderlich:

* IP-Adresse oder vollqualifizierter Domänenname des Speicherprozessors
* Benutzername und Kennwort nur zum Lesen




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| PowerStore-Gateway(s) | IP-Adressen oder vollqualifizierte Domänennamen des PowerStore-Speichers 


| Benutzername | Benutzername für PowerStore 


| Passwort | Für PowerStore verwendetes Kennwort 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| HTTPS-Port | Der Standardwert ist 443 


| Inventarabfrageintervall (Minuten) | Intervall zwischen den Bestandsabfragen. Der Standardwert beträgt 60 Minuten. 
|===
Die PowerStore-Leistungssammlung von Cloud Insight nutzt die Quelldaten von PowerStore mit einer Granularität von 5 Minuten.  Daher fragt Data Infrastructure Insights diese Daten alle fünf Minuten ab, und dies ist nicht konfigurierbar.



== Fehlerbehebung

Weitere Informationen zu diesem Datensammler finden Sie imlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
