---
sidebar: sidebar 
permalink: task_dc_emc_scaleio.html 
keywords: data collector, scaleIO, PowerFlex EMC, DELL 
summary: Konfigurieren des DELL EMC ScaleIO/PowerFlex-Datensammlers. 
---
= DELL EMC ScaleIO/PowerFlex-Datensammler
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Der Datensammler ScaleIO/PowerFlex erfasst Bestandsdaten aus ScaleIO und PowerFlex-Speicher. Für die Konfiguration benötigt dieser Datensammler die ScaleIO/PowerFlex-Gateway-Adresse sowie einen Admin-Benutzernamen und ein Passwort.



== Terminologie

Data Infrastructure Insights erfasst die folgenden Bestandsinformationen aus dem Datensammler ScaleIO/PowerFlex. Für jeden Asset-Typ, der von Data Infrastructure Insights erworben wurde, wird die für diese Ressource am häufigsten verwendete Terminologie angezeigt. Beachten Sie bei der Anzeige oder Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter-/Modelllaufzeit | Einblicke Aus Der Dateninfrastruktur 


| MDM-Cluster (Meta Data Manager | Storage 


| SDS (ScaleIO/PowerFlex Data Server) | Storage-Node 


| Storage-Pool | Storage-Pool 


| Datenmenge | Datenmenge 


| Gerät | Festplatte 
|===
Hinweis: Es handelt sich hierbei nur um allgemeine Terminologiezuordnungen. Diese stellen für diesen Datensammler möglicherweise nicht alle Fälle dar.



== Anforderungen

* Schreibgeschützter Zugriff auf das Admin-Benutzerkonto
* Port-Anforderung: HTTPS-Port 443




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| ScaleIO/PowerFlex-Gateway(s) | IP-Adressen oder FQDNs von ScaleIO/PowerFlex Gateways, getrennt durch Komma (,) oder Semikolon (;) 


| Benutzername | Admin-Benutzername für die Anmeldung beim ScaleIO/PowerFlex-Gerät 


| Passwort | Passwort für die Anmeldung beim ScaleIO/PowerFlex-Gerät 
|===


== Erweiterte Konfiguration

Klicken Sie auf das Kontrollkästchen Inventar, um die Bestandssammlung zu aktivieren.

[cols="2*"]
|===
| Feld | Beschreibung 


| HTTPS-Port | 443 


| Abfrageintervall für Bestand (min) | Der Standardwert ist 60. 


| Verbindungs-Timeout (s) | Der Standardwert ist 60. 
|===


== Fehlerbehebung

Weitere Informationen finden Sie auf der link:concept_requesting_support.html["Support"] Seite oder im link:reference_data_collector_support_matrix.html["Data Collector Supportmatrix"].
