---
sidebar: sidebar 
permalink: task_dc_lenovo.html 
keywords: data collector,Lenovo, HX Series 
summary: Lenovo-Datensammler konfigurieren. 
---
= Lenovo Datensammler
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights verwendet den Lenovo-Datensammler, um Bestands- und Leistungsdaten für Lenovo HX-Speichersysteme zu ermitteln.

Hinweis: Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diesen Datensammler darstellen.



== Anforderungen

* Externe Prism-IP-Adresse
* Administrator-Benutzername und -Passwort
* TCP-Port-Anforderung: 9440




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Externe Prism-IP-Adresse | Die IP-Adresse der externen Datendienste für den Cluster 


| Benutzername | Benutzername für das Admin-Konto 


| Passwort | Passwort für das Admin-Konto 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| TCP-Port | TCP-Port, der für die Verbindung mit dem Array verwendet wird.  Der Standardwert ist 9440. 


| Inventarabfrageintervall (min) | Intervall zwischen den Bestandsabfragen. Der Standardwert beträgt 60 Minuten. 


| Leistungsabfrageintervall (Sek.) | Intervall zwischen Leistungsabfragen. Der Standardwert beträgt 300 Sekunden. 
|===


== Fehlerbehebung

Weitere Informationen zu diesem Datensammler finden Sie imlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
