---
sidebar: sidebar 
permalink: task_dc_hpe_nimble.html 
keywords: data collector, HP Nimble, HP, HPE, Alletra 6000 
summary: 'Konfigurieren des HP Enterprise Alletra 6000-Datensammlers (ehemals Nimble).' 
---
= HPE Alletra 6000 Datenkollektor
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Der HP Enterprise Alletra 6000 (früher Nimble) Datensammler unterstützt Inventar- und Leistungsdaten für Alletra 6000-Speicherarrays.



== Terminologie

Data Infrastructure Insights erhält von diesem Collector die folgenden Bestandsinformationen.  Für jeden von Data Infrastructure Insights erworbenen Asset-Typ wird die am häufigsten verwendete Terminologie für dieses Asset angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Anordnung | Storage 


| Scheibe | Scheibe 


| Volumen | Volumen 


| Pool | Speicherpool 


| Initiator | Speicherhost-Alias 


| Regler | Speicherknoten 


| Fibre-Channel-Schnittstelle | Regler 
|===
Hinweis: Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diesen Datensammler darstellen.



== Anforderungen

Um Inventar- und Konfigurationsdaten vom Speicherarray zu erfassen, müssen Sie über Folgendes verfügen:

* Das Array muss installiert und konfiguriert sein und vom Client über seinen vollqualifizierten Domänennamen (FQDN) oder die Array-Verwaltungs-IP-Adresse erreichbar sein.
* Auf dem Array muss NimbleOS 2.3.x oder höher ausgeführt werden.
* Sie müssen über einen gültigen Benutzernamen und ein gültiges Kennwort für das Array verfügen und mindestens über die Rolle „Operator“ verfügen.  Die Rolle „Gast“ verfügt nicht über ausreichend Zugriff, um die Initiatorkonfigurationen zu verstehen.
* Port 5392 muss auf dem Array geöffnet sein.


Um Leistungsdaten vom Speicherarray zu erfassen, müssen Sie über Folgendes verfügen:

* Auf dem Array muss NimbleOS 4.0.0 oder höher ausgeführt werden.
* Für das Array müssen Volumes konfiguriert sein.  Die einzige Performance-API, die NimbleOS hat, ist für Volumes, und alle statistischen Data Infrastructure Insights -Berichte werden aus den Statistiken zu Volumes abgeleitet




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Array-Management-IP-Adresse | Vollqualifizierter Domänenname (FQDN) oder IP-Adresse für die Array-Verwaltung. 


| Benutzername | Benutzername für das Array 


| Passwort | Passwort für das Array 
|===


== Erweiterte Konfiguration

|===


| Feld | Beschreibung 


| Hafen | Von der Nimble REST API verwendeter Port.  Der Standardwert ist 5392. 


| Inventarabfrageintervall (min) | Intervall zwischen den Bestandsabfragen. Der Standardwert beträgt 60 Minuten. 
|===
Hinweis: Das Standardintervall für die Leistungsabfrage beträgt 300 Sekunden und kann nicht geändert werden.  Dies ist das einzige von HPE Alletra 6000 unterstützte Intervall.
