---
sidebar: sidebar 
permalink: task_dc_redhat_virtualization.html 
keywords: data collector, Red Hat Virtualization 
summary: Konfigurieren des Red Hat Virtualization-Datenkollektors. 
---
= Red Hat Virtualization-Datenkollektor
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights verwendet den Red Hat Virtualization-Datensammler, um Inventardaten von virtualisierten Linux- und Microsoft Windows-Workloads zu sammeln.



== Terminologie

Für jeden von Data Infrastructure Insights erfassten Asset-Typ wird die am häufigsten verwendete Terminologie für das Asset angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Scheibe | Virtuelle Festplatte 


| Gastgeber | Gastgeber 


| Virtuelle Maschine | Virtuelle Maschine 


| Speicherdomäne | Datenspeicher 


| Logische Einheit | LUN 
|===
Hinweis: Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diesen Datensammler darstellen.



== Anforderungen

* IP-Adresse des RHEV-Servers über Port 443 per REST-API
* Nur-Lese-Benutzername und -Passwort
* RHEV Version 3.0+




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| RHEV-Server-IP-Adresse | IP-Adresse des Speichersystems 


| Benutzername | Benutzername mit Administratorrechten 


| Kennwort für das Administratorkonto | Passwort 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| HTTPS-Kommunikationsport | Für die HTTPS-Kommunikation mit RHEV verwendeter Port 


| Inventarabfrageintervall (min) | Der Standardwert beträgt 20 Minuten. 
|===


== Fehlerbehebung

Weitere Informationen zu diesem Datensammler finden Sie imlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
