---
sidebar: sidebar 
permalink: task_dc_emc_unisphere_rest.html 
keywords: data collector, Unisphere, EMC 
summary: Konfigurieren des Dell EMC Unisphere REST-Datenkollektors. 
---
= Konfigurieren des Dell EMC Unisphere REST-Datenkollektors
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Dieser Datensammler erfasst Inventar- und Leistungsdaten von Dell EMC Unisphere für PowerMax/Vmax 3-Verwaltungssysteme.

Bitte beachten Sie, dass Dell/EMC erst mit Unisphere 10.0 Statistiken pro Volume eingeführt hat. Dieser Datensammler unterstützt 9.2.0+, kann jedoch keine Volumestatistiken erfassen, da diese nicht vorhanden sind.

Eine Unisphere für Vmax/PowerMax-Instanz verwaltet möglicherweise ein oder mehrere Symmetrix Vmax 3- oder höhere Speicher-Arrays. Dieser Collector versucht standardmäßig, alle Arrays zu ermitteln, die für diese Unisphere-Instanz „lokal“ sind.  Wenn eine Unisphere-Instanz „Remote“-Arrays erkennt (d. h. solche, die über die SRDF-Replikation verbunden sind), werden diese ignoriert. Um diese zu erkennen, sollten Sie in Data Infrastructure Insights einen zusätzlichen Unisphere-Collector erstellen, der auf die Unisphere-Instanz an diesem Standort verweist, die sie als lokal erkennt.

Zur Konfiguration benötigt der Datensammler eine IP-Adresse/einen FQDN des Unisphere-Servers, eine TCP-Verbindung zum Port 8443 sowie einen Benutzernamen und ein Passwort.



== Anforderungen

* Eine IP-Adresse/ein vollständig qualifizierter Domänenname des Unisphere-Servers
* Benutzername und Passwort
* Port 8443.




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| IP-Adresse des Unisphere-Servers | IP-Adresse oder vollqualifizierter Domänenname des Unisphere-Servers 


| Unisphere-Port | Der Standardwert ist 8443 


| Benutzername | Benutzername für den Unisphere-Server 


| Passwort | Für den Unisphere-Server verwendetes Kennwort 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Inventarabfrageintervall (min) | Der Standardwert beträgt 40 Minuten. 


| Leistungsabfrageintervall (Sek.) | Intervall zwischen Leistungsabfragen. 


| Wählen Sie „Ausschließen“ oder „Einschließen“, um eine Liste anzugeben | Angeben, ob VMs ein- oder ausgeschlossen werden sollen 


| Inventarfilter-Geräteliste | Liste der zu filternden VMs (durch Komma getrennt oder durch Semikolon getrennt, wenn im Wert ein Komma verwendet wird) zum Filtern 


| Unisphere Performance Poll-Intervall (Sek.) | Der Standardwert beträgt 300 Sekunden 
|===


== Fehlerbehebung

Wenn bei diesem Datensammler Probleme auftreten, können Sie Folgendes versuchen:



=== Inventar

[cols="2*"]
|===
| Problem: | Versuchen Sie Folgendes: 


| Fehler: Benutzerauthentifizierung fehlgeschlagen. | Stellen Sie sicher, dass Ihre Anmeldeinformationen für dieses Gerät korrekt sind. 


| Inventar Aktueller Status: Unerwartete Daten abgerufen - Array meldete 0 Volumen | Zeigt normalerweise ein Autorisierungsproblem (kein Authentifizierungsproblem) an.  Stellen Sie sicher, dass Ihre Anmeldeinformationen korrekt sind und dass der Benutzername die Berechtigung hat, alle Volumes aufzulisten und ihre Attribute anzuzeigen. 
|===
Weitere Informationen finden Sie in derlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
