---
sidebar: sidebar 
permalink: task_configure_data_collectors.html 
keywords: acquisition, AU, data collector, collector, notification, notify, 
summary: Allgemeine Anweisungen zum Datensammler 
---
= Konfigurieren von Datenkollektoren
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Sie konfigurieren Datenkollektoren in Ihrer Data Infrastructure Insights Umgebung, um Daten von Geräten im Rechenzentrum zu erfassen.

.Bevor Sie beginnen
* Sie müssen eine Erfassungseinheit konfiguriert haben, bevor Sie mit der Datenerfassung beginnen können.
* Sie benötigen Anmeldeinformationen für die Geräte, von denen Sie Daten erfassen.
* Für alle Geräte, von denen Sie Daten erfassen, sind Gerätenetzwerkadressen, Kontoinformationen und Passwörter erforderlich.


.Schritte
. Klicken Sie im Menü „Data Infrastructure Insights“ auf *Observability > Collectors*
+
Das System zeigt die verfügbaren Datensammler nach Anbieter sortiert an.

. Klicken Sie auf *+ Collector* und wählen Sie den zu konfigurierenden Datensammler aus.
+
Im Dialogfeld können Sie den Datensammler konfigurieren und eine Erfassungseinheit hinzufügen.

. Geben Sie einen Namen für den Datensammler ein.
. Klicken Sie auf *Erweiterte Konfiguration*, um zusätzliche Konfigurationsfelder hinzuzufügen.  (Nicht alle Datensammler erfordern eine erweiterte Konfiguration.)
. Klicken Sie auf *Konfiguration testen*, um zu überprüfen, ob der Datensammler richtig konfiguriert ist.
. Klicken Sie auf *Collector hinzufügen*, um die Konfiguration zu speichern und den Datensammler zu Ihrem Data Infrastructure Insights Mandanten hinzuzufügen.


Es kann bis zu zwei Abfrageperioden dauern, bis Daten des Dienstes in Dashboards angezeigt werden oder für Abfragen verfügbar sind.

* 1. Bestandsaufnahme: sofort
* 1. Leistungsdatenabfrage zur Ermittlung einer Baseline: unmittelbar nach der Bestandsabfrage
* 2. Leistungsumfrage: innerhalb von 15 Sekunden nach Abschluss der 1. Leistungsumfrage


Die Abfrage erfolgt dann gemäß den konfigurierten Bestands- und Leistungsabfrageintervallen.
