---
sidebar: sidebar 
permalink: task_query_assign_multiple_applications.html 
summary: Verwenden Sie eine Abfrage, um Objekten mehrere Anwendungen oder Anmerkungen zuzuweisen oder mehrere Anwendungen oder Anmerkungen von Objekten zu entfernen. 
keywords: query, queries, application, annotation, multiple 
---
= Zuweisen mehrerer Anwendungen zu oder Entfernen mehrerer Anwendungen von Assets
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Sie können mehrerelink:task_create_application.html["Anwendungen"] Sie können mehrere Anwendungen mithilfe einer Abfrage zu Assets hinzufügen oder daraus entfernen, anstatt sie manuell zuweisen oder entfernen zu müssen.


NOTE: Mit diesen Schritten können Sie hinzufügen oder entfernenlink:task_defining_annotations.html["Anmerkungen"] auf die gleiche Weise.

.Bevor Sie beginnen
Sie müssen bereits eine Abfrage erstellt haben, die alle Assets findet, die Sie bearbeiten möchten.

.Schritte
. Klicken Sie auf *Erkunden* und wählen Sie *Metrikabfragen* aus.
+
Die Seite „Abfragen“ wird angezeigt.

. Klicken Sie auf den Namen der Abfrage, die die Assets findet.
+
Die Liste der mit der Abfrage verknüpften Assets wird angezeigt.

. Wählen Sie die gewünschten Assets in der Liste aus oder klicken Sie auf das obere Kontrollkästchen, um „Alle“ auszuwählen.
+
Das Dropdown-Menü „Massenaktionen“ wird angezeigt.

. Um den ausgewählten Assets eine Anwendung hinzuzufügen, klicken Sie auf Massenaktionen und wählen Sie *Anwendung hinzufügen*.
. Wählen Sie eine oder mehrere Anwendungen aus.
+
Sie können mehrere Anwendungen für Hosts, interne Volumes, Qtrees und virtuelle Maschinen auswählen. Für ein Volume oder eine Freigabe können Sie jedoch nur eine Anwendung auswählen.

. Klicken Sie auf *Speichern*.
. Um eine den Assets zugewiesene Anwendung zu entfernen, klicken Sie auf „Massenaktionen“ und wählen Sie „Anwendung entfernen“ aus.
. Wählen Sie die Anwendung(en) aus, die Sie entfernen möchten.
. Klicken Sie auf *Löschen*.


Alle neuen Anwendungen, die Sie zuweisen, überschreiben alle Anwendungen auf dem Asset, die von einem anderen Asset abgeleitet wurden.  Beispielsweise erben Volumes Anwendungen von Hosts, und wenn einem Volume neue Anwendungen zugewiesen werden, hat die neue Anwendung Vorrang vor der abgeleiteten Anwendung.

Nachdem Sie bei einer Massenhinzufügungsaktion auf _Speichern_ oder bei einer Massenlöschaktion auf _Entfernen_ geklickt haben, werden Sie von Data Infrastructure Insights darüber informiert, dass die Aktion einige Zeit in Anspruch nehmen wird.  Sie können diese Meldung ignorieren; die Aktion wird im Hintergrund fortgesetzt.


NOTE: In Umgebungen mit einer großen Menge verwandter Assets kann die Vererbung von Anwendungszuweisungen zu diesen Assets mehrere Minuten dauern.  Bitte rechnen Sie mit einer längeren Vererbungszeit, wenn Sie über viele zusammenhängende Vermögenswerte verfügen.
