---
sidebar: sidebar 
permalink: task_dc_redhat_openshift_virtualization.html 
keywords: data collector, Red Hat OpenShift Virtualization 
summary: Konfiguration des Red Hat OpenShift Virtualization-Datensammlers. 
---
= Red Hat OpenShift Virtualisierungs-Datensammler
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Der DII Red Hat OpenShift Virtualization Collector versucht, die OSV-Compute-Workloads zu erkennen, die in einer OpenShift Virtualization-Umgebung ausgeführt werden – dieser Collector erkennt nicht alle OpenShift-Pods. Dies ist ein HTTPS-REST-API-basierter Collector. Es wird empfohlen, pro OSV-Cluster einen Collector zu erstellen.

Der Authentifizierungsansatz für diesen Collector ist ein Authentifizierungs-Token, das an ein Dienstkonto gebunden ist. So erstellen Sie sowohl das Benutzerkonto als auch das Token:

....
oc create sa acq-readonly-cluster-user -n default
oc adm policy add-cluster-role-to-user cluster-reader -z acq-readonly-cluster-user --rolebinding-name acq-readonly-cluster-user-binding
oc adm policy add-cluster-role-to-user cluster-monitoring-view -z acq-readonly-cluster-user --rolebinding-name acq-readonly-cluster-monitor-user-binding
....
Führen Sie diese 3 Befehle aus und achten Sie auf Fehler.

Wenn die Befehle abgeschlossen sind:

 oc sa new-token acq-readonly-cluster-user
Dadurch wird ein Token erstellt, das an Ihren Benutzer gebunden ist.

Abschließend möchten Sie möglicherweise auch, dass Ihr OSV Administrator Folgendes ausführt:

 oc cluster-info
Dadurch wird der Hostname/die IP-Adresse für die Verwaltung zurückgegeben. Jeder DII OSV-Collector muss auf die IP/den Hostnamen für die OSV-Verwaltung verweisen.



== Terminologie

Für jeden von Data Infrastructure Insights erfassten Asset-Typ wird die am häufigsten verwendete Terminologie für das Asset angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Scheibe | Virtuelle Festplatte 


| Gastgeber | Gastgeber 


| Virtuelle Maschine | Virtuelle Maschine 


| Speicherdomäne | Datenspeicher 


| Logische Einheit | LUN 
|===
Hinweis: Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diesen Datensammler darstellen.



== Anforderungen

* IP-Adresse des Red Hat OpenShift Virtualisierungsservers über Port 443 via REST-API
* Nur-Lese-Benutzername und -Passwort
* RHEV Version 3.0+




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| RHEV-Server-IP-Adresse | IP-Adresse des Speichersystems 


| Benutzername | Benutzername mit Administratorrechten 


| Kennwort für das Administratorkonto | Passwort 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| HTTPS-Kommunikationsport | Port, der für die HTTPS-Kommunikation zu RHOV verwendet wird 


| Inventarabfrageintervall (min) | Der Standardwert beträgt 20 Minuten. 
|===


== Fehlerbehebung

Weitere Informationen zu diesem Datensammler finden Sie imlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
