---
sidebar: sidebar 
permalink: task_dc_emc_ecs.html 
keywords: data collector, ecs, EMC 
summary: ECS-Datensammler konfigurieren. 
---
= Konfigurieren des EMC ECS-Datenkollektors
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Dieser Datensammler erfasst Bestands- und Leistungsdaten von EMC ECS-Speichersystemen.  Zur Konfiguration benötigt der Datensammler eine IP-Adresse oder den Hostnamen des ECS-Clusters sowie einen Benutzernamen und ein Passwort.


NOTE: Dell EMC ECS wird zu einem anderen Preis als Raw TB und Managed Unit berechnet.  Jede 40 TB unformatierte ECS-Kapazität wird als 1 berechnetlink:concept_subscribing_to_cloud_insights.html#pricing["Verwaltete Einheit (MU)"] .



== Terminologie

Data Infrastructure Insights erhält die folgenden Bestandsinformationen vom ECS-Datensammler.  Für jeden erworbenen Vermögenswerttyp wird die am häufigsten verwendete Terminologie für diesen Vermögenswert angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Cluster | Storage 


| Mieter | Speicherpool 


| Eimer | Internes Volumen 


| Scheibe | Scheibe 
|===
Hinweis: Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diesen Datensammler darstellen.



== Anforderungen

* Eine IP-Adresse oder ein Hostname des ECS-Clusters
* Ein Benutzername und ein Passwort für das ECS-System
* Port 4443 (HTTPS).  Erfordert ausgehende Konnektivität zum TCP-Port 4443 auf dem ECS-System.




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| ECS-Host | IP-Adresse oder vollqualifizierter Domänenname des ECS-Systems 


| ECS-Host-Port | Für die Kommunikation mit dem ECS-Host verwendeter Port 


| ECS-Benutzer-ID | Benutzer-ID für ECS 


| Passwort | Für ECS verwendetes Passwort 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Inventarabfrageintervall (min) | Der Standardwert beträgt 360 Minuten. 
|===


== Fehlerbehebung

Wenn bei diesem Datensammler Probleme auftreten, können Sie Folgendes versuchen:



=== Inventar

[cols="2*"]
|===
| Problem: | Versuchen Sie Folgendes: 


| Fehler: Benutzerauthentifizierung fehlgeschlagen. | Stellen Sie sicher, dass Ihre Anmeldeinformationen für dieses Gerät korrekt sind. 
|===


=== Performance

[cols="2*"]
|===
| Problem: | Versuchen Sie Folgendes: 


| Fehler: Nicht genügend Daten gesammelt. | * Überprüfen Sie den Erfassungszeitstempel in der Protokolldatei und ändern Sie das Abfrageintervall entsprechend. * Warten Sie länger 


| Fehler: Das Leistungsabfrageintervall ist zu groß. | Überprüfen Sie den Erfassungszeitstempel in der Protokolldatei ${logfile} und ändern Sie das Abfrageintervall entsprechend 
|===
Weitere Informationen finden Sie in derlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
