---
sidebar: sidebar 
permalink: task_dc_ms_anf.html 
keywords: data collector, azure, Netapp files, anf 
summary: Konfigurieren des Azure NetApp Files Datensammlers. 
---
= Konfigurieren des Azure NetApp Files Datensammlers
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights verwendet den Azure NetApp Files Datensammler, um Bestands- und Leistungsdaten zu erfassen.



== Anforderungen

Zur Konfiguration dieses Datensammlers benötigen Sie folgende Informationen.

* Portanforderung: 443 HTTPS
* Azure Management Rest-IP (management.azure.com)
* Azure-Dienstprinzipal-Client-ID (Benutzerkonto)
* Azure-Dienstprinzipal-Authentifizierungsschlüssel (Benutzerkennwort)
* Sie müssen für die Data Infrastructure Insights Erkennung ein Azure-Konto einrichten.
+
Sobald das Konto ordnungsgemäß konfiguriert ist und Sie die Anwendung in Azure registrieren, verfügen Sie über die erforderlichen Anmeldeinformationen, um die Azure-Instanz mit Data Infrastructure Insights zu ermitteln.  Unter folgendem Link wird beschrieben, wie Sie das Konto für die Erkennung einrichten:



https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal[]



== Konfiguration

Geben Sie die Daten in die Felder des Datensammlers gemäß der folgenden Tabelle ein:

[cols="2*"]
|===
| Feld | Beschreibung 


| Azure-Dienstprinzipal-Client-ID | Anmelde-ID für Azure 


| Azure-Mandanten-ID | Azure-Mandanten-ID 


| Azure-Dienstprinzipalauthentifizierungsschlüssel | Login-Authentifizierungsschlüssel 


| Mir ist bekannt, dass Microsoft mir API-Anfragen in Rechnung stellt. | Aktivieren Sie dies, um zu bestätigen, dass Sie verstanden haben, dass Microsoft Ihnen für API-Anfragen, die durch Insight-Polling gestellt werden, eine Rechnung stellt. 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Inventarabfrageintervall (min) | Der Standardwert ist 60 
|===


== Fehlerbehebung

* Die von Ihrem ANF-Datensammler verwendeten Anmeldeinformationen müssen Zugriff auf alle Azure-Abonnements haben, die ANF-Volumes enthalten.
* Wenn die Leistungserfassung aufgrund des Leserzugriffs fehlschlägt, versuchen Sie, dem Mitwirkenden Zugriff auf Ressourcengruppenebene zu gewähren.


Weitere Informationen zu diesem Datensammler finden Sie imlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
