---
sidebar: sidebar 
permalink: task_dc_ibm_ds4000.html 
keywords: data collector, IBM, DS4000 
summary: IBM TotalStorage DS4000 Datensammler 
---
= IBM TotalStorage DS4000 Datensammler
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Dieser Datensammler erfasst Bestands- und Performance-Informationen aus dem IBM DS4000 Storage-System. Es gibt zwei mögliche Konfigurationen (Firmware 6.x und Firmware 7.x+), und beide haben die gleichen Werte.



== Terminologie

Data Infrastructure Insights erfasst die folgenden Inventarinformationen aus dem IBM DS4000 Datensammler. Für jeden erfassten Asset-Typ wird die am häufigsten für dieses Dokument verwendete Terminologie angezeigt. Beachten Sie bei der Anzeige oder Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter-/Modelllaufzeit | Einblicke Aus Der Dateninfrastruktur 


| Festplatte | Festplatte 


| Volume-Gruppe | Festplattengruppe 


| Storage Array Durchführt | Storage 


| Controller | Storage-Node 


| Volume-Gruppe | Storage-Pool 


| Datenmenge | Datenmenge 
|===
Hinweis: Es handelt sich hierbei nur um allgemeine Terminologiezuordnungen. Diese stellen für diesen Datensammler möglicherweise nicht alle Fälle dar.



== Anforderungen

* Die IP-Adresse jedes DS5- oder FAStT-Arrays
* Zugriffsvalidierung durch Ping der IP-Adresse beider Controller auf dem Array
* Anforderungen an den Hafen: 2463




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Kommagetrennte Liste der Array-SANtricity-Controller-IPs | IP-Adressen und/oder vollqualifizierte Domain-Namen für die Array Controller 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Abfrageintervall für Bestand (min) | Der Standardwert ist 30 Minuten 


| Leistungsintervall bis zu 3600 Sekunden | Der Standardwert ist 300 Sekunden 
|===


== Fehlerbehebung

Weitere Informationen zu diesem Data Collector finden Sie auf der link:concept_requesting_support.html["Support"] Seite oder im link:reference_data_collector_support_matrix.html["Data Collector Supportmatrix"].
