---
sidebar: sidebar 
permalink: task_dc_emc_vnxe.html 
keywords: data collector, VNXe, EMC 
summary: Konfigurieren des VNXe-Datenkollektors. 
---
= Konfigurieren des EMC VNXe-Datenkollektors
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Der DELL EMC VNXe-Datenkollektor bietet Inventarunterstützung für VNXe Unified Storage-Arrays.  Data Infrastructure Insights unterstützt derzeit iSCSI- und NAS-Protokolle.



== Anforderungen

* Der VNXe-Datenkollektor ist CLI-basiert. Sie müssen die Unisphere für VNXe-CLI (uemcli.exe) auf der Erfassungseinheit installieren, auf der sich Ihr VNXe-Datenkollektor befindet.
* uemcli.exe verwendet HTTPS als Transportprotokoll, daher muss die Erfassungseinheit in der Lage sein, HTTPS-Verbindungen zum VNXe herzustellen.
* IP-Adresse oder vollqualifizierter Domänenname des VNXe-Geräts
* Für die Verwendung durch den Datensammler müssen Sie mindestens über einen schreibgeschützten Benutzer verfügen.
* IP-Adresse des verwaltenden Solutions Enabler-Servers.
* HTTPS auf Port 443 ist erforderlich
* Der EMC VNXe-Datenkollektor bietet NAS- und iSCSI-Unterstützung für die Bestandsaufnahme. Fibre-Channel-Volumes werden erkannt, Data Infrastructure Insights meldet jedoch keine FC-Zuordnung, Maskierung oder Speicherports.




== Terminologie

Data Infrastructure Insights erhält die folgenden Bestandsinformationen vom VNXe-Datensammler.  Für jeden von Data Infrastructure Insights erworbenen Asset-Typ wird die am häufigsten verwendete Terminologie für dieses Asset angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Scheibe | Scheibe 


| Speicher-Array | Storage 


| Prozessor | Speicherknoten 


| Speicherpool | Speicherpool 


| Allgemeine iSCSI-Blockinformationen, VMware VMFS | Aktie 


| Replikations-Remotesystem | Synchronisation 


| iSCSI-Knoten | iSCSI-Zielknoten 


| iSCSI-Initiator | iSCSI-Zielinitiator 
|===
Hinweis: Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diese Datenquelle darstellen.



== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| VNXe-Speicher | IP-Adresse oder vollqualifizierter Domänenname des VNXe-Geräts 


| Benutzername | Benutzername für das VNXe-Gerät 


| Passwort | Kennwort für das VNXe-Gerät 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Inventarabfrageintervall (min) | Intervall zwischen den Bestandsabfragen.  Der Standardwert beträgt 40 Minuten 


| CLI-Port | Für die VNXe-CLI verwendeter Port 


| Leistungsabfrageintervall (Sek.) | Der Standardwert ist 300. 
|===


== Fehlerbehebung

Wenn bei diesem Datensammler Probleme auftreten, können Sie Folgendes versuchen:



=== Inventar

[cols="2*"]
|===
| Problem: | Versuchen Sie Folgendes: 


| „Fehler beim Ausführen des externen Dienstprogramms“ mit der Fehlermeldung „Ausführbare Unisphere-Uemcli konnte nicht gefunden werden“ | * Überprüfen Sie, ob die IP-Adresse, der Benutzername und das Kennwort korrekt sind. * Bestätigen Sie, dass Unisphere CLI auf der Data Infrastructure Insights Acquisition Unit installiert ist. * Bestätigen Sie, dass das Installationsverzeichnis von Unisphere CLI in der Datenquellenkonfiguration korrekt ist. * Bestätigen Sie, dass die IP des VNXe in der Konfiguration der Datenquelle korrekt ist.  Öffnen Sie in der Data Infrastructure Insights Acquisition Unit eine CMD und wechseln Sie zum konfigurierten Installationsverzeichnis: ${INSTALLDIR.  Versuchen Sie, eine Verbindung mit dem VNXe-Gerät herzustellen, indem Sie Folgendes eingeben: uemcli -d <Ihre IP> -u <Ihre ID> /sys/general show 
|===
Weitere Informationen finden Sie in derlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
