---
sidebar: sidebar 
permalink: task_dc_hds_nas.html 
keywords: data collector, HDS HNAS, HDS NAS 
summary: 'Konfigurieren des HDS NAS (HNAS)-Datensammlers.' 
---
= Konfigurieren des Hitachi Vantara NAS-Datenkollektors
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Der Hitachi Vantara NAS-Datensammler ist ein Inventar- und Konfigurationsdatensammler, der die Erkennung von HDS NAS-Clustern unterstützt.  Data Infrastructure Insights unterstützt die Erkennung von NFS- und CIFS-Freigaben, Dateisystemen (internen Volumes) und Spans (Speicherpools).



== Terminologie

Data Infrastructure Insights erhält die folgenden Bestandsinformationen vom HNAS-Datensammler.  Für jeden von Data Infrastructure Insights erworbenen Asset-Typ wird die am häufigsten verwendete Terminologie für dieses Asset angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Stufe | Datenträgergruppe 


| Cluster | Storage 


| Node | Speicherknoten 


| Spanne | Speicherpool 


| Systemlaufwerk | Backend-Lun 


| Dateisystem | Internes Volumen 
|===
Hinweis: Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diesen Datensammler darstellen.



== Anforderungen

* IP-Adresse des Geräts
* Port 22, SSH-Protokoll
* Benutzername und Passwort – Berechtigungsstufe: Supervisor
* Hinweis: Dieser Datensammler ist SSH-basiert, daher muss die AU, die ihn hostet, in der Lage sein, SSH-Sitzungen zu TCP 22 auf dem HNAS selbst oder der Systems Management Unit (SMU), mit der der Cluster verbunden ist, zu initiieren.




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| HNAS-Host | IP-Adresse oder vollqualifizierter Domänenname des HNAS-Verwaltungshosts 


| Benutzername | Benutzername für HNAS CLI 


| Passwort | Für HNAS CLI verwendetes Passwort 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Inventarabfrageintervall (min) | Intervall zwischen den Bestandsabfragen. Der Standardwert beträgt 30 Minuten. 
|===


== Fehlerbehebung

Wenn bei diesem Datensammler Probleme auftreten, können Sie Folgendes versuchen:



=== Inventar

[cols="2*"]
|===
| Problem: | Versuchen Sie Folgendes: 


| „Fehler beim Verbinden“ mit den Fehlermeldungen „Fehler beim Einrichten des Shell-Kanals:“ oder „Fehler beim Öffnen des Shell-Kanals“ | Wird wahrscheinlich durch Probleme mit der Netzwerkverbindung oder eine falsche SSH-Konfiguration verursacht.  Bestätigen Sie die Verbindung mit einem alternativen SSH-Client 


| „Timeout“ oder „Fehler beim Abrufen der Daten“ mit der Fehlermeldung „Befehl: XXX hat eine Zeitüberschreitung.“ | * Versuchen Sie den Befehl mit einem anderen SSH-Client. * Erhöhen Sie das Timeout. 


| „Fehler beim Verbinden“ oder „Ungültige Anmeldeinformationen“ mit der Fehlermeldung „Konnte nicht mit dem Gerät kommunizieren:“ | * IP-Adresse prüfen * Benutzernamen und Passwort prüfen * Verbindung mit alternativem SSH-Client bestätigen 
|===
Weitere Informationen finden Sie in derlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
