---
sidebar: sidebar 
permalink: task_cs_getting_started.html 
keywords: collectors, data collectors, configure, introduction, browsers, Cloud Secure 
summary: Setzen Sie Workload-Security-Agenten und Datensammler ein, um die Benutzeraktivität zu überwachen und Sicherheitsbedrohungen zu erkennen. 
---
= Erste Schritte mit Workload-Sicherheit
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Workload Security hilft Ihnen, die Benutzeraktivität zu überwachen und potenzielle Sicherheitsbedrohungen in Ihrer Speicherumgebung zu erkennen.  Bevor Sie mit der Überwachung beginnen können, müssen Sie Agenten, Datensammler und Verzeichnisdienste konfigurieren, um die Grundlage für eine umfassende Sicherheitsüberwachung zu schaffen.

Das Workload Security-System verwendet einen Agenten, um Zugriffsdaten von Speichersystemen und Benutzerinformationen von Directory Services-Servern zu sammeln.

Bevor Sie mit der Datenerfassung beginnen können, müssen Sie Folgendes konfigurieren:

[cols="2*"]
|===


| Aufgabe | Ähnliche Informationen 


| Konfigurieren eines Agenten  a| 
link:concept_cs_agent_requirements.html["Agentenanforderungen"]

link:task_cs_add_agent.html["Agent hinzufügen"]



| Konfigurieren eines Benutzerverzeichnis-Connectors | link:task_config_user_dir_connect.html["Benutzerverzeichnis-Connector hinzufügen"] 


| Konfigurieren von Datensammlern | Klicken Sie auf *Workload-Sicherheit > Collector*. Klicken Sie auf den Datensammler, den Sie konfigurieren möchten. Informationen zu den Datensammlern finden Sie im Abschnitt „Referenz der Datensammler-Anbieter“ der Dokumentation. 


| Benutzerkonten erstellen | link:concept_user_roles.html["Benutzerkonten verwalten"] 
|===
Workload Security kann auch in andere Tools integriert werden.  Zum Beispiel,link:http://docs.netapp.com/us-en/cloudinsights/CloudInsights_CloudSecure_Splunk_integration_guide.pdf["siehe diese Anleitung"] zur Integration mit Splunk.
