---
sidebar: sidebar 
permalink: task_dc_emc_recoverpoint.html 
keywords: data collector, RecoverPoint, EMC, DELL 
summary: Konfigurieren VON DELL EMC RecoverPoint Data Collector 
---
= Dell EMC RecoverPoint Data Collector
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Der primäre Anwendungsfall des EMC RecoverPoint Data Collector ist die Ermittlung von Replikationsbeziehungen zwischen Volumes, die von der RecoverPoint-Speicher-Appliance unterstützt werden. Dieser Sammler entdeckt auch das RecoverPoint-Gerät selbst. Bitte beachten Sie, dass Dell/EMC eine VMware Backup-Lösung für VMs--„RecoverPoint for VMs“ verkauft, die von diesem Collector nicht unterstützt wird

Zur Konfiguration benötigt der Datensammler die IP-Adresse der Speicherprozessoren sowie einen schreibgeschützten Benutzernamen und ein Kennwort.

Der EMC RecoverPoint Data Collector sammelt die Replikationsbeziehungen zwischen Volume und Volume, die RecoverPoint über andere Speicher-Arrays hinweg koordiniert. Data Infrastructure Insights zeigt ein Speicher-Array für jeden RecoverPoint-Cluster an und sammelt Bestandsdaten für Knoten und Speicherports auf diesem Cluster. Es werden keine Storage-Pool- oder Volume-Daten erfasst.



== Anforderungen

Zur Konfiguration dieses Datensammlers sind folgende Informationen erforderlich:

* IP-Adresse oder vollqualifizierter Domain-Name des Speicherprozessors
* Schreibgeschützter Benutzername und Kennwort
* REST-API-Zugriff über Port 443




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Adresse von RecoverPoint | IP-Adresse oder vollqualifizierter Domain-Name des RecoverPoint-Clusters 


| Benutzername | Benutzername für das RecoverPoint-Cluster 


| Passwort | Passwort, das für den RecoverPoint-Cluster verwendet wird 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| TCP-Anschluss | TCP-Port für die Verbindung mit dem RecoverPoint-Cluster 


| Abfrageintervall für Bestand (Minuten) | Intervall zwischen Bestandsabstimmungen Die Standardeinstellung ist 20 Minuten. 


| Ausgeschlossene Cluster | Kommagetrennte Liste von Cluster-IDs oder Namen, die beim Abfragen ausgeschlossen werden sollen. 
|===


== Fehlerbehebung

Weitere Informationen zu diesem Data Collector finden Sie auf der link:concept_requesting_support.html["Support"] Seite oder im link:reference_data_collector_support_matrix.html["Data Collector Supportmatrix"].
