---
sidebar: sidebar 
permalink: task_dc_cohesity_smartfiles.html 
keywords: data collector, cohesity 
summary: Konfigurieren des Cohesity SmartFiles-Datensammlers. 
---
= Cohesity SmartFiles-Datensammler
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Dieser auf REST-API basierende Collector erwirbt einen Cohesity-Cluster, erkennt die „Ansichten“ (als interne Volumes von Data Infrastructure Insights ) und die verschiedenen Knoten und sammelt Leistungsmetriken.



== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Cohesity-Cluster-IP | IP-Adresse des Cohesity-Clusters 


| Benutzername | Benutzername für den Cohesity-Cluster 


| Passwort | Für den Cohesity-Cluster verwendetes Passwort 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| TCP-Port | Für die TCP-Kommunikation mit dem Cohesity-Cluster verwendeter Port 


| Inventarabfrageintervall (min) | Intervall zwischen den Bestandsabfragen. Der Standardwert beträgt 60 Minuten. 


| Leistungsabfrageintervall (min) | Intervall zwischen Leistungsabfragen. Der Standardwert beträgt 900 Sekunden. 
|===


== Fehlerbehebung

Weitere Informationen finden Sie in derlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
