---
sidebar: sidebar 
permalink: task_config_telegraf_consul.html 
keywords: telegraf, installation, install, consul 
summary: Konfiguration des Consul-Datensammlers 
---
= Konsul-Datensammler
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights verwendet diesen Datensammler, um Metriken von Consul zu sammeln.



== Installation

. Klicken Sie unter *Observability > Collectors* auf *+Data Collector*.  Wählen Sie Konsul.
+
Wenn Sie keinen Agenten für die Sammlung konfiguriert haben, werden Sie aufgefordert,link:task_config_telegraf_agent.html["Installieren eines Agenten"] auf Ihrem Mieter.

+
Wenn Sie bereits einen Agenten konfiguriert haben, wählen Sie das entsprechende Betriebssystem oder die entsprechende Plattform aus und klicken Sie auf *Weiter*.

. Befolgen Sie die Anweisungen im Consul-Konfigurationsbildschirm, um den Datensammler zu konfigurieren.  Die Anweisungen variieren je nach Art des Betriebssystems oder der Plattform, die Sie zum Sammeln von Daten verwenden.




== Aufstellen

Informationen finden Sie imlink:https://www.consul.io/docs/index.html["Konsuldokumentation"] .



== Objekte und Zähler für Konsul

Die folgenden Objekte und ihre Zähler werden gesammelt:

[cols="<.<,<.<,<.<,<.<"]
|===
| Objekt: | Kennungen: | Merkmale: | Datenpunkte: 


| Konsul | Namespace-Check-ID-Dienstknoten | Knoten-IP Knoten-Betriebssystem Knoten-UUID Knotenname Dienstname Name prüfen Dienst-ID Status | Warnung vor kritischem Überholen 
|===


== Fehlerbehebung

Weitere Informationen finden Sie in derlink:concept_requesting_support.html["Support"] Seite.
