---
sidebar: sidebar 
permalink: task_dc_oracle_zfs.html 
keywords: data collector, Oracle, ZFS, storage applicance 
summary: Oracle ZFS-Datensammler konfigurieren. 
---
= Datensammler der Oracle ZFS Storage Appliance
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights verwendet den Datensammler der Oracle ZFS Storage Appliance zur Erfassung von Bestands- und Leistungsdaten.



== Terminologie

Data Infrastructure Insights erfasst Bestandsinformationen mit dem Oracle ZFS-Datensammler. Für jeden Asset-Typ, der von Data Infrastructure Insights erworben wurde, wird die für diese Ressource am häufigsten verwendete Terminologie angezeigt. Beachten Sie bei der Anzeige oder Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter-/Modelllaufzeit | Einblicke Aus Der Dateninfrastruktur 


| Festplatte (SSD) | Festplatte 


| Cluster | Storage 


| Controller | Storage-Node 


| LUN | Datenmenge 


| LUN-Zuordnung | Volume-Zuordnung 


| Initiator, Ziel | Volume-Maske 


| Share | Internes Volumen 
|===
Hinweis: Es handelt sich hierbei nur um allgemeine Terminologiezuordnungen. In dieser Datenquelle fallen möglicherweise nicht alle Fälle an.



== Anforderungen

* Host-Namen für den ZFS-Controller-1 und den ZFS-Controller-2
* Administrator-Benutzername und -Passwort
* Port-Anforderung: 215 HTTP/HTTPS




== Erforderliche Performance-Metriken

Oracle ZFS Appliances stellen Storage-Verwaltungen große Flexibilität zur Erfassung von Performance-Statistiken zur Verfügung. Data Infrastructure Insights erwartet, dass Sie in einem Hochverfügbarkeitspaar _each_ Controller konfiguriert haben, um die folgenden Kennzahlen zu erfassen:

* smb2.OPS[Freigabe]
* nfs3.OPS[Freigabe]
* nfs4.OPS[Share]
* nfs4-1.OPS[Share]


Wird ein Controller diese oder alle Funktionen nicht erfassen, führt dies wahrscheinlich dazu, dass Data Infrastructure Insights den Workload auf den „internen Volumes“ nicht oder nur unzureichend meldet.



== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| ZFS Controller-1-Hostname | Host-Name für Storage Controller 1 


| ZFS Controller-2-Hostname | Host-Name für Storage Controller 2 


| Benutzername | Benutzername für das Benutzerkonto des Speichersystemadministrators 


| Passwort | Kennwort für das Administratorbenutzerkonto 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Verbindungstyp | HTTPS oder HTTP: Zeigt auch den Standardport an 


| Verbindungs-Port Überschreiben | Wenn Sie leer sind, verwenden Sie den Standardport im Feld Verbindungstyp. Andernfalls geben Sie den zu verwendenden Anschluss ein 


| Abfrageintervall für den Bestand | Der Standardwert beträgt 60 Sekunden 


| Leistungsintervall (Sek.) | Der Standardwert ist 300. 
|===


== Fehlerbehebung

Einige Dinge zu versuchen, wenn Sie Probleme mit diesem Datensammler stoßen:



=== Inventar

[cols="2a, 2a"]
|===
| Problem: | Versuchen Sie dies: 


 a| 
„Ungültige Anmeldeinformationen“
 a| 
ZFS-Benutzerkonto und -Passwort validieren



 a| 
„Anfrage mit Status 404 \https://.....:215/api/access/v1" fehlgeschlagen
 a| 
Ihr ZFS-Array ist möglicherweise zu alt, um REST-API-Unterstützung zu erhalten. AK 2013.1.3.0 war die erste REST API-fähige ZFS OS-Version, und nicht alle ZFS-Appliances können darauf aktualisiert werden.



 a| 
„Konfigurationsfehler“ mit Fehlermeldung „REST Service ist deaktiviert“
 a| 
Vergewissern Sie sich, dass DER REST-Dienst auf diesem Gerät aktiviert ist.



 a| 
„Konfigurationsfehler“ mit Fehlermeldung „Benutzer nicht autorisiert für Befehl“
 a| 
Dieser Fehler ist wahrscheinlich darauf zurückzuführen, dass bestimmte Rollen (z. B. „Advanced_Analytics“) für den konfigurierten Benutzer nicht enthalten sind.

Durch die Anwendung des Analysebereichs für den Benutzer mit schreibgeschützter Rolle kann der Fehler behoben werden. Führen Sie hierzu folgende Schritte aus:

. Bewegen Sie auf dem ZFS-System im Bildschirm Konfiguration -> Benutzer die Maus über die Rolle und doppelklicken Sie, um die Bearbeitung zu ermöglichen
. Wählen Sie im Dropdown-Menü „Bereich“ die Option „Analyse“ aus. Eine Liste der möglichen Eigenschaften wird angezeigt.
. Klicken Sie auf das Kontrollkästchen am oberen Ende, um alle drei Eigenschaften auszuwählen.
. Klicken Sie auf der rechten Seite auf die Schaltfläche Hinzufügen.
. Klicken Sie oben rechts im Popup-Fenster auf die Schaltfläche Übernehmen. Das Popup-Fenster wird geschlossen.


|===
Weitere Informationen finden Sie auf der link:concept_requesting_support.html["Support"] Seite oder im link:reference_data_collector_support_matrix.html["Data Collector Supportmatrix"].
