---
sidebar: sidebar 
permalink: task_dc_qumulo_rest.html 
keywords: data collector, qumulo, rest 
summary: Konfiguration des Qumulo REST-Datensammlers. 
---
= Qumulo REST-Datensammler
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Data Infrastructure Insights verwendet diesen Datensammler, um Inventar- und Leistungsdaten aus dem Qumulo-Speicher zu erfassen.



== Terminologie

Data Infrastructure Insights erhält von diesem Datensammler die folgenden Bestandsinformationen.  Für jeden von Data Infrastructure Insights erworbenen Asset-Typ wird die am häufigsten verwendete Terminologie für dieses Asset angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Fahren | Scheibe 


| Cluster | Storage 


| Node | Speicherknoten 
|===
Hinweis: Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diesen Datensammler darstellen.



== Anforderungen

Zur Konfiguration dieses Datensammlers benötigen Sie folgende Informationen:

* Ein Benutzerkonto und ein Passwort mit mindestens Leseberechtigung.
* IP-Adresse / Vollqualifizierter Domänenname des Qumulo-Clusters
* HTTPS-Zugriff auf Port 8000




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Qumulo IP-Adresse | Die IP-Adresse oder der vollqualifizierte Domänenname des Qumulo-Speichers 


| Benutzername | Benutzername für Qumulo 


| Passwort | Passwort für Qumulo 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| HTTPS-Port | Der Standardwert ist 8000. 


| Inventarabfrageintervall (min) | Intervall zwischen den Bestandsabfragen. Der Standardwert ist 30. 


| Leistungsabfrageintervall (min) | Intervall zwischen den Leistungsabfragen. Der Standardwert ist 5. 
|===


== Fehlerbehebung

Weitere Informationen finden Sie in derlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
