---
sidebar: sidebar 
permalink: task_dc_emc_ecs.html 
keywords: data collector, ecs, EMC 
summary: Konfiguration des ECS Datensammlers 
---
= Konfigurieren des EMC ECS-Datensammlers
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Dieser Datensammler erfasst Bestands- und Performancedaten von EMC ECS-Speichersystemen. Für die Konfiguration benötigt der Datensammler eine IP-Adresse oder einen Hostnamen des ECS-Clusters sowie einen Benutzernamen und ein Passwort.


NOTE: Dell EMC ECS wird mit einer anderen Rate von Raw TB zu Managed Units gemessen. Jede 40 TB unformatierte ECS-Kapazität wird als 1 berechnetlink:concept_subscribing_to_cloud_insights.html#pricing["Verwaltete Einheit (ME)"].



== Terminologie

Data Infrastructure Insights erfasst die folgenden Bestandsinformationen aus dem ECS-Datensammler. Für jeden erfassten Asset-Typ wird die am häufigsten für dieses Dokument verwendete Terminologie angezeigt. Beachten Sie bei der Anzeige oder Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter-/Modelllaufzeit | Einblicke Aus Der Dateninfrastruktur 


| Cluster | Storage 


| Mandant | Storage-Pool 


| Eimer | Internes Volumen 


| Festplatte | Festplatte 
|===
Hinweis: Es handelt sich hierbei nur um allgemeine Terminologiezuordnungen. Diese stellen für diesen Datensammler möglicherweise nicht alle Fälle dar.



== Anforderungen

* Eine IP-Adresse oder ein Hostname des ECS-Clusters
* Benutzername und Passwort für das ECS-System
* Port 4443 (HTTPS). Erfordert ausgehende Verbindungen zum TCP-Port 4443 auf dem ECS-System.




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| ECS Host | IP-Adresse oder vollqualifizierter Domain-Name des ECS-Systems 


| ECS-Host-Port | Port, der für die Kommunikation mit ECS Host verwendet wird 


| ECS-Benutzer-ID | Benutzer-ID für ECS 


| Passwort | Passwort wird für ECS verwendet 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Abfrageintervall für Bestand (min) | Die Standardeinstellung ist 360 Minuten. 
|===


== Fehlerbehebung

Einige Dinge zu versuchen, wenn Sie Probleme mit diesem Datensammler stoßen:



==== Inventar

[cols="2*"]
|===
| Problem: | Versuchen Sie dies: 


| Fehler: Benutzerauthentifizierung fehlgeschlagen. | Stellen Sie sicher, dass Ihre Anmeldeinformationen für dieses Gerät korrekt sind. 
|===


==== Performance

[cols="2*"]
|===
| Problem: | Versuchen Sie dies: 


| Fehler: Es wurden nicht genügend Daten erfasst. | • Prüfen Sie den Zeitstempel der Sammlung in der Protokolldatei und ändern Sie das Abfrageintervall entsprechend • Warten Sie länger 


| Fehler: Das Abfrageintervall für die Performance ist zu groß. | Überprüfen Sie den Sammlungs-Zeitstempel in der Protokolldatei €{logfile} und ändern Sie das Abfrageintervall entsprechend 
|===
Weitere Informationen finden Sie auf der link:concept_requesting_support.html["Support"] Seite oder im link:reference_data_collector_support_matrix.html["Data Collector Supportmatrix"].
