---
sidebar: sidebar 
permalink: task_device_resolution_preferences.html 
keywords: Automatic, AR, AHR, Host, automatic device resolution, FC, Identify 
summary:  
---
= Einstelloptionen auf der Registerkarte „Einstellungen“
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Auf der Registerkarte „Einstellungen für die Geräteauflösung“ können Sie einen Zeitplan für die automatische Auflösung erstellen, Speicher- und Bandanbieter angeben, die in die Identifizierung einbezogen oder davon ausgeschlossen werden sollen, und DNS-Suchoptionen festlegen.



== Zeitplan für die automatische Auflösung

Ein Zeitplan für die automatische Auflösung kann angeben, wann die automatische Geräteauflösung ausgeführt wird:

|===


| Option | Beschreibung 


| Jeder | Verwenden Sie diese Option, um die automatische Geräteauflösung in Intervallen von Tagen, Stunden oder Minuten auszuführen. 


| Täglich | Verwenden Sie diese Option, um die automatische Geräteauflösung täglich zu einer bestimmten Zeit auszuführen. 


| Manuell | Verwenden Sie diese Option, um die automatische Geräteauflösung nur manuell auszuführen. 


| Bei jeder Umgebungsänderung | Verwenden Sie diese Option, um bei jeder Änderung der Umgebung eine automatische Geräteauflösung auszuführen. 
|===
Wenn Sie _Manuell_ angeben, wird die nächtliche automatische Geräteauflösung deaktiviert.



== DNS-Verarbeitungsoptionen

Mit den DNS-Verarbeitungsoptionen können Sie die folgenden Funktionen auswählen:

* Wenn die Verarbeitung der DNS-Suchergebnisse aktiviert ist, können Sie eine Liste mit DNS-Namen hinzufügen, die an aufgelöste Geräte angehängt werden sollen.
* Sie können „Automatische Auflösung von IPs“ auswählen, um die automatische Hostauflösung für iSCSI-Initiatoren und Hosts zu aktivieren, die per DNS-Lookup auf NFS-Freigaben zugreifen.  Wenn dies nicht angegeben ist, wird nur eine FC-basierte Auflösung durchgeführt.
* Sie können Unterstriche in Hostnamen zulassen und in Ergebnissen einen „Verbunden mit“-Alias anstelle des Standard-Port-Alias verwenden.




=== Einbeziehung oder Ausschluss bestimmter Speicher- und Bandanbieter

Sie können bestimmte Speicher- und Bandanbieter zur automatischen Lösung ein- oder ausschließen.  Möglicherweise möchten Sie bestimmte Anbieter ausschließen, wenn Sie beispielsweise wissen, dass ein bestimmter Host zu einem Legacy-Host wird und aus Ihrer neuen Umgebung ausgeschlossen werden sollte.  Sie können auch Anbieter erneut hinzufügen, die Sie zuvor ausgeschlossen hatten, aber nicht mehr ausschließen möchten.


NOTE: Geräteauflösungsregeln für Bänder funktionieren nur für WWNs, bei denen der Anbieter für dieses WWN in den Anbietereinstellungen auf _Nur als Band enthalten_ eingestellt ist.

Siehe auch:link:concept_device_resolution_regex_examples.html["Beispiele für reguläre Ausdrücke"]
