---
sidebar: sidebar 
permalink: task_dc_emc_vnx_block.html 
keywords: data collector, EMC, clariion, VNX block 
summary: 'Konfigurieren von DELL EMC VNX Block Storage (früher CLARiiON).' 
---
= Dell EMC VNX Block Storage (NaviCLI)-Datenkollektor
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights verwendet den Datensammler Dell EMC VNX Block Storage (NaviSec) (ehemals CLARiiON), um Bestands- und Leistungsdaten zu erfassen.



== Terminologie

Data Infrastructure Insights erhält die folgenden Bestandsinformationen vom EMC VNX Block Storage-Datenkollektor.  Für jeden von Data Infrastructure Insights erworbenen Asset-Typ wird die am häufigsten verwendete Terminologie für dieses Asset angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Scheibe | Scheibe 


| Storage | Storage 


| Speicherprozessor | Speicherknoten 


| Dieser Pool, RAID-Gruppe | Speicherpool 


| LUN | Volumen 
|===
Hinweis: Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diese Datenquelle darstellen.



== Anforderungen

Für die Datenerhebung müssen folgende Voraussetzungen erfüllt sein:

* Eine IP-Adresse jedes VNX-Blockspeicherprozessors
* Schreibgeschützter Navisphere-Benutzername und -Passwort für die VNX-Blockspeicher-Arrays
* NaviSecCli muss auf der Data Infrastructure Insights AU installiert sein
* Zugriffsvalidierung: Führen Sie NaviSecCLI von der Data Infrastructure Insights AU mit dem Benutzernamen und dem Kennwort für jedes Array aus.
* Portanforderungen: 80, 443
* Die NaviSecCLI-Version sollte dem neuesten FLARE-Code auf Ihrem Array entsprechen
* Aus Leistungsgründen muss die Statistikprotokollierung aktiviert sein.




== Syntax der NaviSphere-Befehlszeilenschnittstelle

naviseccli.exe -h <IP-Adresse> -user <Benutzer> -password <Passwort> -scope <Bereich, verwenden Sie 0 für den globalen Bereich> -port <verwenden Sie standardmäßig 443> Befehl



== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| VNX-Blockspeicher-IP-Adresse | IP-Adresse oder vollqualifizierter Domänenname des VNX-Blockspeichers 


| Benutzername | Name, der für die Anmeldung beim VNX-Blockspeichergerät verwendet wird. 


| Passwort | Kennwort zum Anmelden beim VNX-Blockspeichergerät. 


| CLI-Pfad zu naviseccli.exe | Vollständiger Pfad zum Ordner, der die ausführbare Datei _naviseccli.exe_ enthält 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Inventarabfrageintervall (min) | Intervall zwischen den Bestandsabfragen.  Der Standardwert ist 40 Minuten. 


| Umfang | Der sichere Clientbereich.  Die Standardeinstellung ist „Global“. 


| Leistungsabfrageintervall (Sek.) | Intervall zwischen Leistungsabfragen. Der Standardwert beträgt 300 Sekunden. 
|===


== Fehlerbehebung

Wenn bei diesem Datensammler Probleme auftreten, können Sie Folgendes versuchen:



=== Inventar

[cols="2a, 2a"]
|===
| Problem: | Versuchen Sie Folgendes: 


 a| 
Fehler:

* Agent wird nicht ausgeführt
* Naviseccli konnte nicht gefunden werden
* Kein Befehl konnte ausgeführt werden

 a| 
* Bestätigen Sie, dass NaviSphere CLI auf der Cloud Insight Acquisition Unit installiert ist
* Sie haben im Konfigurationsassistenten des Datensammlers nicht die Option „Sicheren Client verwenden“ ausgewählt und keine nicht sichere Version von Naviphere CLI installiert.
* Bestätigen Sie, dass das NaviSphere CLI-Installationsverzeichnis in der Datensammlerkonfiguration korrekt ist
* Bestätigen Sie, dass die IP des VNX-Blockspeichers in der Datensammlerkonfiguration korrekt ist:
* Von der Data Infrastructure Insights Acquisition Unit:
+
** Öffnen Sie eine CMD.
** Ändern Sie das Verzeichnis in das konfigurierte Installationsverzeichnis
** Versuchen Sie, eine Verbindung mit dem VNX-Blockspeichergerät herzustellen, indem Sie „navicli -h {ip} getagent“ eingeben (ersetzen Sie {ip} durch die tatsächliche IP).






 a| 
Fehler: 4.29 emc235848 emc241018 getall Fehler beim Parsen der Host-Alias-Informationen
 a| 
Dies wird wahrscheinlich durch ein FLARE 29-Beschädigungsproblem der Host-Initiator-Datenbank auf dem Array selbst verursacht.  Siehe EMC-Wissensdatenbankartikel: emc235848, emc241018.  Sie können auch überprüfen https://now.netapp.com/Knowledgebase/solutionarea.asp?id=kb58128[]



 a| 
Fehler: Meta-LUNs konnten nicht abgerufen werden.  Fehler beim Ausführen von java -jar navicli.jar
 a| 
* Ändern Sie die Datensammlerkonfiguration, um den sicheren Client zu verwenden (empfohlen)
* Installieren Sie navicli.jar im CLI-Pfad zu navicli.exe ODER naviseccli.exe
* Hinweis: navicli.jar ist ab EMC Navisphere Version 6.26 veraltet.
* Die navicli.jar ist möglicherweise verfügbar auf \http://powerlink.emc.com




 a| 
Fehler: Speicherpools melden keine Datenträger auf dem Serviceprozessor unter der konfigurierten IP-Adresse
 a| 
Konfigurieren Sie den Datensammler mit beiden Serviceprozessor-IPs, getrennt durch ein Komma



 a| 
Fehler: Revisionskonflikt
 a| 
* Dies wird normalerweise dadurch verursacht, dass die Firmware auf dem VNX-Blockspeichergerät aktualisiert wird, nicht jedoch die Installation von NaviCLI.exe.  Dies kann auch daran liegen, dass auf verschiedenen Geräten unterschiedliche Firmwares vorhanden sind, aber nur eine CLI (mit einer anderen Firmware-Version) installiert ist.
* Stellen Sie sicher, dass auf dem Gerät und dem Host identische Versionen der Software ausgeführt werden:
+
** Öffnen Sie in der Data Infrastructure Insights Acquisition Unit ein Befehlszeilenfenster
** Ändern Sie das Verzeichnis in das konfigurierte Installationsverzeichnis
** Stellen Sie eine Verbindung mit dem CLARiiON-Gerät her, indem Sie „navicli -h <ip> getagent“ eingeben.
** Suchen Sie in den ersten Zeilen nach der Versionsnummer.  Beispiel: „Agent Rev: 6.16.2 (0.1)“
** Suchen und vergleichen Sie die Version in der ersten Zeile.  Beispiel: „Navisphere CLI Revision 6.07.00.04.07“






 a| 
Fehler: Nicht unterstützte Konfiguration – Keine Fibre Channel-Ports
 a| 
Das Gerät ist nicht mit Fibre-Channel-Ports konfiguriert.  Derzeit werden nur FC-Konfigurationen unterstützt.  Überprüfen Sie, ob diese Version/Firmware unterstützt wird.

|===
Weitere Informationen finden Sie in derlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
