---
sidebar: sidebar 
permalink: task_dc_emc_datadomain.html 
keywords: data collector, Data Domain, EMC, DELL 
summary: KONFIGURIEREN DES DELL EMC Data Domain-Datensammlers. 
---
= DELL EMC Data Domain-Datensammler
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Dieser Datensammler erfasst Bestands- und Performance-Informationen von DELL EMC Data Domain Deduplizierungs-Storage-Systemen. Zur Konfiguration dieses Datensammlers sind spezifische Konfigurationsanweisungen und Nutzungsempfehlungen zu beachten.



== Terminologie

Data Infrastructure Insights bezieht die folgenden Bestandsinformationen aus dem Data Domain-Datensammler. Für jeden Asset-Typ, der von Data Infrastructure Insights erworben wurde, wird die für diese Ressource am häufigsten verwendete Terminologie angezeigt. Beachten Sie bei der Anzeige oder Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter-/Modelllaufzeit | Einblicke Aus Der Dateninfrastruktur 


| Festplatte | Festplatte 


| Array Erledigen | Storage 


| FC-Anschluss | Port 


| File-System | Internes Volumen 


| Kontingente | Kontingente 


| NFS- und CIFS-Freigabe | Dateifreigabe 
|===
Hinweis: Es handelt sich hierbei nur um allgemeine Terminologiezuordnungen. In diesem Datencolletor sind dies möglicherweise nicht alle Fälle.



== Anforderungen

Sie benötigen die folgenden Informationen, um diesen Datensammler zu konfigurieren:

* IP-Adresse des Data Domain-Geräts
* Schreibgeschützter Benutzername und Kennwort für den Data Domain-Speicher
* SSH-Port 22




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| IP-Adresse | Die IP-Adresse oder der vollqualifizierte Domänenname des Data Domain-Speicherarrays 


| Benutzername | Der Benutzername für das Data Domain-Speicherarray 


| Passwort | Das Kennwort für das Data Domain-Speicherarray 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Abfrageintervall für Bestand (min) | Intervall zwischen Bestandsabstimmungen Der Standardwert ist 20. 


| SSH-Anschluss | SSH-Service-Port 
|===


== Fehlerbehebung

Weitere Informationen zu diesem Data Collector finden Sie auf der link:concept_requesting_support.html["Support"] Seite oder im link:reference_data_collector_support_matrix.html["Data Collector Supportmatrix"].
