---
sidebar: sidebar 
permalink: task_dc_hds_commandsuite.html 
keywords: data collector, Hitachi Vantara Command Suite, Hitachi 
summary: Konfiguration des HDS Command Suite Device Manager-Datensammlers 
---
= Datensammler der Hitachi Vantara Command Suite
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Der Datensammler der Hitachi Vantara Command Suite unterstützt den HiCommand Device Manager-Server. Data Infrastructure Insights kommuniziert über die standardmäßige HiCommand API mit dem HiCommand Device Manager-Server.



== Terminologie

Data Infrastructure Insights erfasst die folgenden Bestandsinformationen aus dem Datensammler der Hitachi Vantara Command Suite. Für jeden Asset-Typ, der von Data Infrastructure Insights erworben wurde, wird die für diese Ressource am häufigsten verwendete Terminologie angezeigt. Beachten Sie bei der Anzeige oder Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter-/Modelllaufzeit | Einblicke Aus Der Dateninfrastruktur 


| PDEV | Festplatte 


| Journalpool | Festplattengruppe 


| Storage Array Durchführt | Storage 


| Port Controller | Storage-Node 


| Array-Gruppe, HDS-Pool | Storage-Pool 


| Logische Einheit, LDEV | Datenmenge 
|===
Hinweis: Es handelt sich hierbei nur um allgemeine Terminologiezuordnungen. Diese stellen für diesen Datensammler möglicherweise nicht alle Fälle dar.



=== Storage

Die folgenden Begriffe beziehen sich auf Objekte oder Referenzen, die auf HDS Storage Asset Landing Pages zu finden sind. Viele dieser Bedingungen gelten auch für andere Datensammler.

* Name – kommt direkt aus dem Attribut „Name“ des HDS HiCommand Device Managers über den GetStorageArray XML API-Aufruf
* Modell - kommt direkt aus dem „arrayType“-Attribut des HDS HiCommand Device Managers über den GetStorageArray XML API-Aufruf
* Anbieter – HDS
* Family - kommt direkt aus dem Attribut „arrayFamily“ des HDS HiCommand Device Managers über den GetStorageArray XML API-Aufruf
* IP – hierbei handelt es sich um die Management-IP-Adresse des Arrays, keine vollständige Liste aller IP-Adressen im Array
* Rohkapazität: Ein base2-Wert, der die Summe der Gesamtkapazität aller Festplatten in diesem System darstellt, unabhängig von der Festplattenrolle.




=== Storage-Pool

Die folgenden Begriffe beziehen sich auf Objekte oder Referenzen, die auf HDS Storage Pool Asset Landing Pages zu finden sind. Viele dieser Bedingungen gelten auch für andere Datensammler.

* Typ: Der Wert hier ist einer von:
+
** RESERVIERT – Wenn dieser Pool für andere Zwecke als Datenvolumes, i.e, Journaling, Snapshots bestimmt ist
** Thin Provisioning – wenn es sich um einen HDP-Pool handelt
** RAID-Gruppe – aus ein paar Gründen werden Sie diese wahrscheinlich nicht sehen:
+
Data Infrastructure Insights ist ein starker Standpunkt, um zu vermeiden, dass bei allen Kosten eine doppelte Kapazität gezählt wird. Auf HDS muss man normalerweise RAID-Gruppen von Festplatten erstellen, Pool-Volumes auf diesen RAID-Gruppen erstellen und Pools (oft HDP, könnte aber besonderer Zweck sein) aus diesen Pool Volumes erstellen. Wenn Data Infrastructure Insights sowohl die zugrunde liegenden RAID-Gruppen wie auch die Pools meldet, würde die Summe ihrer Rohkapazität die Summe der Festplatten erheblich übersteigen.

+
Stattdessen verkleinert der Datensammler HDS Command Suite von Data Infrastructure Insights die Größe von RAID-Gruppen willkürlich nach der Kapazität von Pool Volumes. Dies kann dazu führen, dass Data Infrastructure Insights die RAID-Gruppe überhaupt nicht meldet. Darüber hinaus werden alle resultierenden RAID-Gruppen so gekennzeichnet, dass sie in der Data Infrastructure Insights WebUI nicht sichtbar sind, aber sie fließen in das Data Warehouse (DWH) von Data Infrastructure Insights ein. Der Zweck dieser Entscheidungen ist es, UI-Gerinnung für Dinge zu vermeiden, die den meisten Benutzern egal sind – wenn Ihr HDS-Array RAID-Gruppen mit 50 MB frei hat, können Sie diesen freien Speicherplatz wahrscheinlich nicht für ein sinnvolles Ergebnis nutzen.



* Node – k. A., da HDS Pools nicht an einen bestimmten Node gebunden sind
* Redundanz: Der RAID-Level des Pools. Möglicherweise mehrere Werte für einen HDP-Pool, die aus mehreren RAID-Typen bestehen
* Kapazität % - der Prozentsatz, der für die Datenverwendung des Pools verwendet wird, wobei die verwendete GB und die gesamte logische GB-Größe des Pools verwendet werden
* Überzuviel Kapazität - ein abgeleiteter Wert, der angibt, „die logische Kapazität dieses Pools wird durch diesen Prozentsatz überzeichnet, aufgrund der Summe der logischen Volumes, die die logische Kapazität des Pools um diesen Prozentsatz überschreiten“
* Snapshot - zeigt die Kapazität an, die für die Snapshot-Nutzung in diesem Pool reserviert ist




=== Storage-Node

Die folgenden Begriffe beziehen sich auf Objekte oder Referenzen, die auf den HDS Storage Node Asset Landing Pages zu finden sind. Viele dieser Bedingungen gelten auch für andere Datensammler.

* Name: Der Name des Front-End-Director (FED) oder Channel-Adapters auf monolithischen Arrays oder der Name des Controllers auf einem modularen Array. Ein bestimmtes HDS-Array verfügt über zwei oder mehr Storage-Nodes
* Volumes – die Volume-Tabelle zeigt jedes Volume an, das einem beliebigen Port dieses Speicherknoten zugeordnet ist




== Inventaranforderungen

Zur Erfassung von Bestandsdaten müssen Sie Folgendes haben:

* IP-Adresse des HiCommand Device Manager-Servers
* Schreibgeschützter Benutzername und Kennwort für die HiCommand Device Manager-Software und Peer-Berechtigungen
* Port-Anforderungen: 2001 (http) oder 2443 (https)
* Melden Sie sich mit Benutzernamen und Kennwort bei der HiCommand Device Manager-Software an
* Überprüfen Sie den Zugriff auf HiCommand Device Manager \http://<HiCommand_Device_Manager_IP>:2001/Service/StorageManager




== Performance-Anforderungen erfüllt

Zur Erfassung von Leistungsdaten müssen die folgenden Anforderungen erfüllt sein:

* HDS USP, USP V und VSP Performance
+
** Performance Monitor muss lizenziert sein.
** Überwachungsschalter muss aktiviert sein.
** Das Export-Tool (Export.exe) muss in die Data Infrastructure Insights AU kopiert werden.
** Die Version des Exportwerkzeugs muss mit der Microcode-Version des Ziel-Arrays übereinstimmen.


* AMS-Leistung:
+
** NetApp empfiehlt dringend, ein dediziertes Dienstkonto auf AMS-Arrays zu erstellen, damit Dateninfrastrukturdaten zum Abrufen von Leistungsdaten verwendet werden können. Storage Navigator ermöglicht nur ein Benutzerkonto, das gleichzeitig mit dem Array angemeldet ist. Wenn Data Infrastructure Insights dasselbe Benutzerkonto wie Verwaltungsskripte oder HiCommand verwendet, kann es dazu kommen, dass Data Infrastructure Insights, Verwaltungsskripte oder HiCommand aufgrund der Beschränkung der gleichzeitigen Anmeldung eines Benutzerkontos nicht mit dem Array kommunizieren kann
** Performance Monitor muss lizenziert sein.
** Das CLI-Dienstprogramm Storage Navigator Modular 2 (SNM2) muss auf der Data Infrastructure Insights AU installiert werden.






== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| HiCommand Server | IP-Adresse oder vollqualifizierter Domänenname des HiCommand Device Manager-Servers 


| Benutzername | Benutzername für den HiCommand Device Manager-Server. 


| Passwort | Passwort, das für den HiCommand Device Manager-Server verwendet wird. 


| GERÄTE – VSP G1000 (R800), VSP (R700), HUS VM (HM700) UND USP-SPEICHER | Geräteliste für VSP G1000 (R800), VSP (R700), HUS VM (HM700) und USP-Speicher. Jeder Speicher benötigt: * Array IP: IP-Adresse des Speichers * Benutzername: Benutzername für den Speicher * Passwort: Passwort für den Speicher * Ordner mit Export Utility JAR-Dateien 


| SNM2Geräte - WMS/SMS/AMS-Speicher | Geräteliste für WMS/SMS/AMS-Speicher. Jeder Speicher benötigt: * Array's IP: IP address of the Storage * Storage Navigator CLI Pfad: SNM2 CLI Pfad * Konto Authentifizierung gültig: Wählen Sie gültige Konto Authentifizierung * Benutzername: Benutzername für den Speicher * Passwort: Passwort für den Speicher 


| Wählen Sie Tuning Manager für Leistung | Andere Leistungsoptionen überschreiben 


| Tuning Manager Host | IP-Adresse oder vollqualifizierter Domain-Name des Tuning Managers 


| Tuning Manager-Port Überschreiben | Wenn leer, verwenden Sie den Standardport im Feld Tuning Manager für Performance auswählen. Geben Sie andernfalls den zu verwendenden Port ein 


| Benutzername Für Tuning Manager | Benutzername für Tuning Manager 


| Kennwort Für Tuning-Manager | Passwort für Tuning Manager 
|===
Hinweis: Bei HDS USP, USP V und VSP kann jede Festplatte zu mehr als einer Array-Gruppe gehören.



== Erweiterte Konfiguration

|===


| Feld | Beschreibung 


| Verbindungstyp | HTTPS oder HTTP: Zeigt auch den Standardport an 


| HiCommand Server-Port | Port, der für den HiCommand Device Manager verwendet wird 


| Abfrageintervall für Bestand (min) | Intervall zwischen Bestandsabstimmungen Der Standardwert ist 40. 


| Wählen Sie „Ausschließen“ oder „Einschließen“, um eine Liste anzugeben | Geben Sie an, ob die unten aufgeführte Array-Liste beim Sammeln von Daten aufgenommen oder ausgeschlossen werden soll. 


| Geräteliste filtern | Kommagetrennte Liste der einzuschließenden oder auszuschließenden Geräteseriennummer 


| Leistungsintervall (Sek.) | Intervall zwischen Performance-Abstimmungen Der Standardwert ist 300. 


| Ausfuhrzeitlimit in Sekunden | Zeitüberschreitung beim Exportieren der Dienstprogrammfunktion. Der Standardwert ist 300. 
|===


== Fehlerbehebung

Einige Dinge zu versuchen, wenn Sie Probleme mit diesem Datensammler stoßen:



=== Inventar

[cols="2*"]
|===
| Problem: | Versuchen Sie dies: 


| Fehler: Benutzer hat nicht genügend Berechtigung | Verwenden Sie ein anderes Benutzerkonto, das über mehr Berechtigungen verfügt oder die Berechtigung des Benutzerkontos, das im Datensammler konfiguriert ist, erhöht 


| Fehler: Speicherliste ist leer. Entweder sind Geräte nicht konfiguriert oder der Benutzer verfügt nicht über ausreichende Berechtigungen | * Verwenden Sie DeviceManager, um zu überprüfen, ob die Geräte konfiguriert sind. * Verwenden Sie ein anderes Benutzerkonto, das mehr Berechtigungen hat, oder erhöhen Sie die Berechtigung des Benutzerkontos 


| Fehler: HDS Speicher-Array wurde einige Tage lang nicht aktualisiert | Untersuchen Sie, warum dieses Array nicht in HDS HiCommand aktualisiert wird. 
|===


=== Performance

[cols="2*"]
|===
| Problem: | Versuchen Sie dies: 


| Fehler: * Fehler beim Ausführen des Exportdienstprogramms * Fehler beim Ausführen des externen Befehls | * Bestätigen Sie, dass das Exportdienstprogramm auf der Data Infrastructure Insights Acquisition Unit installiert ist * Bestätigen Sie, dass der Speicherort des Exportdienstprogramms in der Data Collector-Konfiguration korrekt ist * Bestätigen Sie, dass die IP des USP/R600-Arrays in der Konfiguration des Data Collectors korrekt ist * Öffnen Sie einen CMD und das Kennwort in der Konfiguration des Data Collectors * Bestätigen Sie, dass die Export Utility-Version mit der Speicher-Microcode-Version kompatibel ist * aus der Data Infrastructure Insights Acquisition Unit, öffnen Sie eine CMD - Aufforderung zur Installation mit dem folgenden Ordner konfigurieren: runWin.bat 


| Fehler: Export Tool-Anmeldung für Ziel-IP fehlgeschlagen | * Bestätigen Sie, dass Benutzername/Passwort korrekt ist * Erstellen Sie eine Benutzer-ID hauptsächlich für diesen HDS-Datensammler * Bestätigen Sie, dass keine anderen Datensammler für die Erfassung dieses Arrays konfiguriert sind 


| Fehler: Exportwerkzeuge protokolliert "Zeitbereich für Überwachung nicht abrufen". | * Bestätigung der Leistungsüberwachung auf dem Array ist aktiviert. * Versuchen Sie, die Exportwerkzeuge außerhalb von Data Infrastructure Insights aufzurufen, um zu bestätigen, dass das Problem außerhalb von Data Infrastructure Insights liegt. 


| Fehler: * Konfigurationsfehler: Speicher-Array wird vom Exportdienstprogramm nicht unterstützt * Konfigurationsfehler: Speicher-Array wird nicht von Speicher-Navigator Modular CLI unterstützt | * Nur unterstützte Storage-Arrays konfigurieren. * Verwenden Sie „Filter Device List“, um nicht unterstützte Speicher-Arrays auszuschließen. 


| Fehler: * Fehler beim Ausführen des externen Befehls * Konfigurationsfehler: Speicher-Array nicht gemeldet von Inventory * Konfigurationsfehler:Exportordner enthält keine JAR-Dateien | * Überprüfen Sie den Speicherort des Exportdienstprogramms. * Prüfen Sie, ob Speicher-Array in Frage in HiCommand Server konfiguriert ist * Festlegen des Performance-Abfrageintervalls als mehrere 60 Sekunden. 


| Fehler: * Fehler Storage Navigator CLI * Fehler beim Ausführen von auPerform Befehl * Fehler beim Ausführen des externen Befehls | * Bestätigen Sie, dass Storage Navigator Modular CLI auf der Data Infrastructure Insights Acquisition Unit installiert ist * Bestätigen Sie, dass Storage Navigator Modular CLI-Speicherort in der Data Collector-Konfiguration korrekt ist * Bestätigen Sie, dass die IP des WMS/SMS/SMS-Arrays in der Konfiguration des Data Collectors korrekt ist * Bestätigen Sie, dass Storage Navigator Modular CLI-Version kompatibel ist mit Microcode-Version des Speicher-Arrays konfiguriert im Data Collector * von der Data Infrastructure Insights Acquisition Unit, öffnen Sie eine CMD-Eingabeaufforderung und führen Sie den folgenden Befehl aus: 


| Fehler: Konfigurationsfehler: Speicher-Array wird vom Inventory nicht gemeldet | Überprüfen Sie, ob Speicher-Array in Frage im HiCommand-Server konfiguriert ist 


| Fehler: * Kein Array ist beim Speicher Navigator Modular 2 CLI registriert * Array ist nicht bei der Speicher Navigator Modular 2 CLI registriert * Konfigurationsfehler: Speicher-Array nicht bei StorageNavigator Modular CLI registriert | * Öffnen Sie die Eingabeaufforderung und ändern Sie das Verzeichnis in den konfigurierten Pfad * führen Sie den Befehl „set=STONAVM_HOME=“ aus. * Führen Sie den Befehl „auunitref“ aus * Bestätigen Sie, dass die Befehlsausgabe Details des Arrays mit IP enthält * Wenn die Ausgabe keine Array-Details enthält, registrieren Sie das Array mit Storage Navigator CLI: - Öffnen Sie die Eingabeaufforderung und ändern Sie das Verzeichnis auf den konfigurierten Pfad - führen Sie den Befehl „set=STONAVM_HOME=“ aus. - Führen Sie den Befehl „auunitaddauto -ip <ip>“ aus. Ersetzen Sie <ip> durch die richtige IP. 
|===
Weitere Informationen finden Sie auf der link:concept_requesting_support.html["Support"] Seite oder im link:reference_data_collector_support_matrix.html["Data Collector Supportmatrix"].
