---
sidebar: sidebar 
permalink: task_dc_emc_scaleio.html 
keywords: data collector, scaleIO, PowerFlex EMC, DELL 
summary: Konfigurieren des DELL EMC ScaleIO/PowerFlex-Datenkollektors. 
---
= DELL EMC ScaleIO / PowerFlex-Datensammler
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Der ScaleIO/PowerFlex-Datensammler sammelt Bestandsinformationen vom ScaleIO- und PowerFlex-Speicher.  Zur Konfiguration benötigt dieser Datensammler die ScaleIO/PowerFlex-Gateway-Adresse sowie einen Administrator-Benutzernamen und ein Administrator-Passwort.



== Terminologie

Data Infrastructure Insights erhält die folgenden Bestandsinformationen vom ScaleIO/PowerFlex-Datensammler.  Für jeden von Data Infrastructure Insights erworbenen Asset-Typ wird die am häufigsten verwendete Terminologie für dieses Asset angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| MDM-Cluster (Metadaten-Manager) | Storage 


| SDS (ScaleIO/PowerFlex-Datenserver) | Speicherknoten 


| Speicherpool | Speicherpool 


| Volumen | Volumen 


| Gerät | Scheibe 
|===
Hinweis: Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diesen Datensammler darstellen.



== Anforderungen

* Nur-Lese-Zugriff auf das Admin-Benutzerkonto
* Portanforderung: HTTPS-Port 443




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| ScaleIO/PowerFlex-Gateway(s) | IP-Adressen oder FQDNs von ScaleIO/PowerFlex-Gateways, getrennt durch Komma (,) oder Semikolon (;) 


| Benutzername | Administrator-Benutzername für die Anmeldung beim ScaleIO/PowerFlex-Gerät 


| Passwort | Kennwort zur Anmeldung beim ScaleIO/PowerFlex-Gerät 
|===


== Erweiterte Konfiguration

Klicken Sie auf das Kontrollkästchen Inventar, um die Inventarerfassung zu aktivieren.

[cols="2*"]
|===
| Feld | Beschreibung 


| HTTPS-Port | 443 


| Inventarabfrageintervall (min) | Der Standardwert ist 60. 


| Verbindungs-Timeout (Sek.) | Der Standardwert ist 60. 
|===


== Fehlerbehebung

Weitere Informationen finden Sie in derlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
