---
sidebar: sidebar 
permalink: task_dc_ibm_cleversafe.html 
keywords: data collector, IBM Cleversafe 
summary: Konfigurieren des IBM Cleversafe-Datenkollektors. 
---
= IBM Cleversafe-Datenkollektor
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights verwendet diesen Datenkollektor, um Bestands- und Leistungsdaten für IBM Cleversafe-Speichersysteme zu ermitteln.


NOTE: Für IBM Cleversafe gilt ein anderer Tarif als für verwaltete Einheiten (Raw TB).  Für jeweils 40 TB unformatierte IBM Cleversafe-Kapazität wird 1link:concept_subscribing_to_cloud_insights.html#pricing["Verwaltete Einheit (MU)"] .



== Terminologie

Data Infrastructure Insights erhält die folgenden Bestandsinformationen vom IBM Cleversafe-Datenkollektor.  Für jeden von Data Infrastructure Insights erworbenen Asset-Typ wird die am häufigsten verwendete Terminologie für dieses Asset angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Speicherpool | Speicherpool 


| Container | Internes Volumen 


| Container | Dateifreigabe 


| NFS-Freigabe | Aktie 
|===
Hinweis: Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diesen Datensammler darstellen.



== Anforderungen

* Die IP-Adresse der externen Datendienste für den Cluster
* Administrator-Benutzername und -Passwort
* Port 9440




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Manager-IP oder Hostname | IP-Adresse oder Hostname des Verwaltungsknotens 


| Benutzername | Benutzername für das Benutzerkonto mit Superuser- oder Systemadministratorrolle 


| Passwort | Kennwort für das Benutzerkonto mit der Rolle „Superuser“ oder „Systemadministrator“ 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Inventarabfrageintervall (min) | Intervall zwischen den Bestandsabfragen. 


| HTTP-Verbindungs-Timeout (Sek.) | HTTP-Timeout in Sekunden. 
|===


== Fehlerbehebung

Weitere Informationen zu diesem Datensammler finden Sie imlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
