---
sidebar: sidebar 
permalink: task_cs_delete_agent.html 
keywords: agent, Workload Security, delete agent, Cloud Secure 
summary: Löschen von Workload Security-Agenten 
---
= Löschen eines Workload Security Agent
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Wenn Sie einen Workload Security Agent löschen, müssen zuerst alle mit dem Agent verknüpften Datensammler gelöscht werden.



== Löschen eines Agenten


IMPORTANT: Durch das Löschen eines Agenten werden alle mit dem Agenten verknüpften Datensammler gelöscht.  Wenn Sie die Datensammler mit einem anderen Agenten konfigurieren möchten, sollten Sie vor dem Löschen des Agenten eine Sicherungskopie der Datensammlerkonfigurationen erstellen.

.Bevor Sie beginnen
. Stellen Sie sicher, dass alle mit dem Agenten verknüpften Datensammler aus dem Workload Security-Portal gelöscht werden.
+
Hinweis: Ignorieren Sie diesen Schritt, wenn sich alle zugehörigen Collector im Status STOPPED befinden.



.Schritte zum Löschen eines Agenten:
. Melden Sie sich per SSH bei der Agent-VM an und führen Sie den folgenden Befehl aus.  Geben Sie bei der entsprechenden Aufforderung „y“ ein, um fortzufahren.
+
....
sudo /opt/netapp/cloudsecure/agent/install/cloudsecure-agent-uninstall.sh
Uninstall CloudSecure Agent? [y|N]:
....
. Klicken Sie auf *Workload-Sicherheit > Collectors > Agents*
+
Das System zeigt die Liste der konfigurierten Agenten an.

. Klicken Sie auf das Optionsmenü für den Agenten, den Sie löschen.
. Klicken Sie auf *Löschen*.
+
Das System zeigt die Seite *Agent löschen* an.

. Klicken Sie auf *Löschen*, um den Löschvorgang zu bestätigen.

