---
sidebar: sidebar 
permalink: task_research_failed_collector.html 
keywords: data collector, changes, failures 
summary: Datensammlerfehler 
---
= Untersuchung eines gescheiterten Datensammlers
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Wenn ein Datensammler eine Fehlermeldung und eine hohe oder mittlere Auswirkung aufweist, müssen Sie dieses Problem mithilfe der Übersichtsseite des Datensammlers und der darin verknüpften Informationen untersuchen.

Führen Sie die folgenden Schritte aus, um die Ursache für fehlgeschlagene Datensammler zu ermitteln.  Fehlermeldungen zum Datensammler werden im Menü *Admin* und auf der Seite *Installierte Datensammler* angezeigt.

.Schritte
. Klicken Sie auf *Admin* > *Datensammler* > *Installierte Datensammler*.
. Klicken Sie auf den verknüpften Namen des fehlerhaften Datensammlers, um die Seite „Zusammenfassung“ zu öffnen.
. Überprüfen Sie auf der Seite „Zusammenfassung“ den Bereich „Kommentare“, um alle Notizen zu lesen, die möglicherweise von einem anderen Techniker hinterlassen wurden, der diesen Fehler möglicherweise ebenfalls untersucht.
. Beachten Sie alle Leistungsmeldungen.
. Bewegen Sie den Mauszeiger über die Segmente des Ereigniszeitleistendiagramms, um zusätzliche Informationen anzuzeigen.
. Wählen Sie eine Fehlermeldung für ein Gerät aus, die unterhalb der Ereigniszeitleiste angezeigt wird, und klicken Sie auf das Symbol „Fehlerdetails“, das rechts neben der Meldung angezeigt wird.
+
Die Fehlerdetails umfassen den Text der Fehlermeldung, die wahrscheinlichsten Ursachen, verwendete Informationen und Vorschläge, was zur Behebung des Problems versucht werden kann.

. Im Bereich „Von diesem Datensammler gemeldete Geräte“ können Sie die Liste filtern, um nur die Geräte anzuzeigen, die Sie interessieren, und Sie können auf den verknüpften *Namen* eines Geräts klicken, um die Asset-Seite für dieses Gerät anzuzeigen.
. Wenn Sie zur Übersichtsseite des Datensammlers zurückkehren, überprüfen Sie den Bereich *Letzte Änderungen anzeigen* unten auf der Seite, um festzustellen, ob das Problem durch kürzliche Änderungen verursacht worden sein könnte.

