---
sidebar: sidebar 
permalink: task_dc_ms_hyperv.html 
keywords: data collector, Microsoft, Hyper-V 
summary: Konfigurieren des Microsoft Hyper-V-Datenkollektors. 
---
= Microsoft Hyper-V-Datensammler
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Der Microsoft Hyper-V-Datensammler erfasst Inventar- und Leistungsdaten aus der virtualisierten Server-Computerumgebung.  Dieser Datensammler kann einen eigenständigen Hyper-V-Host oder einen ganzen Cluster erkennen – erstellen Sie einen Sammler pro eigenständigem Host oder Cluster.



== Terminologie

Data Infrastructure Insights erhält die folgenden Bestandsinformationen von Microsoft Hyper-V (WMI).  Für jeden von Data Infrastructure Insights erworbenen Asset-Typ wird die am häufigsten verwendete Terminologie für dieses Asset angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Virtuelle Festplatte | Virtuelle Festplatte 


| Gastgeber | Gastgeber 


| Virtuelle Maschine | Virtuelle Maschine 


| Cluster Shared Volumes (CSV), Partitionsvolume | Datenspeicher 


| Internet-SCSI-Gerät, Multi-Path-SCSI-LUN | LUN 


| Fiber Channel-Anschluss | Hafen 
|===
Hinweis: Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diesen Datensammler darstellen.



== Anforderungen

Zur Konfiguration dieses Datensammlers sind folgende Voraussetzungen erforderlich:

* Für Hyper-V muss Port 5985 für die Datenerfassung und den Remotezugriff/die Remoteverwaltung geöffnet sein.
* IP-Adresse oder FQDN des Clusters oder eigenständigen Hypervisors.  Die Verwendung des Floating-Cluster-Hostnamens oder der IP ist wahrscheinlich der zuverlässigste Ansatz, anstatt den Collector auf nur einen bestimmten Knoten in einem Cluster zu richten.
* Benutzerkonto auf Administratorebene, das auf allen Hypervisoren im Cluster funktioniert.
* WinRM muss aktiviert sein und auf allen Hypervisoren lauschen
* Portanforderungen: Port 135 über WMI und dynamische TCP-Ports zugewiesen 1024-65535 für Windows 2003 und älter und 49152-65535 für Windows 2008.
* Die DNS-Auflösung muss erfolgreich sein, auch wenn der Datensammler nur auf eine IP-Adresse verweist.
* Bei jedem Hyper-V-Hypervisor muss die „Ressourcenmessung“ für jede VM auf jedem Host aktiviert sein.  Dadurch stehen jedem Hypervisor auf jedem Gast mehr Daten für Data Infrastructure Insights zur Verfügung.  Wenn dies nicht festgelegt ist, werden für jeden Gast weniger Leistungsmetriken erfasst.  Weitere Informationen zur Ressourcenmessung finden Sie in der Microsoft-Dokumentation:
+
link:https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/hh831661(v=ws.11)["Übersicht über die Hyper-V-Ressourcenmessung"]

+
link:https://docs.microsoft.com/en-us/powershell/module/hyper-v/enable-vmresourcemetering?view=win10-ps["Aktivieren Sie VMResourceMetering"]




NOTE: Der Hyper-V-Datensammler erfordert eine Windows-Erfassungseinheit.



== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Cluster-IP-Adresse oder Floating-Cluster-FQDN | Die IP-Adresse oder der vollqualifizierte Domänenname für den Cluster oder einen eigenständigen, nicht geclusterten Hypervisor 


| Benutzername | Administrator-Benutzername für den Hypervisor 


| Passwort | Passwort für den Hypervisor 


| DNS-Domänensuffix | Das Hostnamensuffix, das mit dem einfachen Hostnamen kombiniert wird, um den FQDN eines Hypervisors darzustellen 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Inventarabfrageintervall (min) | Der Standardwert beträgt 20 Minuten. 
|===


== Fehlerbehebung

Weitere Informationen zu diesem Datensammler finden Sie imlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
