---
sidebar: sidebar 
permalink: task_dc_nutanix.html 
keywords: data collector, Nutanix, NX Series 
summary: Konfiguration des Nutanix NX Datensammlers. 
---
= Nutanix NX-Datensammler
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Data Infrastructure Insights verwendet den Nutanix NX Datensammler, um Inventar- und Leistungsdaten für Nutanix NX Speichersysteme zu erfassen.



[[terminology]]
== Terminologie

Data Infrastructure Insights erhält die folgenden Bestandsinformationen vom Nutanix-Datensammler.  Für jeden von Data Infrastructure Insights erworbenen Asset-Typ wird die am häufigsten verwendete Terminologie für dieses Asset angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="50,50"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Speicherpool | Speicherpool 


| Nutanix-Container | Internes Volumen 


| Nutanix-Container | Dateifreigabe 


| NFS-Freigabe | Aktie 
|===
Hinweis: Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diesen Datensammler darstellen.



[[requirements]]
== Anforderungen

* Die IP-Adresse der externen Datendienste für den Cluster
* Nur-Lese-Benutzername und -Passwort, es sei denn, es werden Volume-Gruppen verwendet. In diesem Fall sind der Administrator-Benutzername und das Administrator-Passwort erforderlich.
* Portanforderung: HTTPS 443




[[configuration]]
== Konfiguration

[cols="50,50"]
|===
| Feld | Beschreibung 


| Externe Prism-IP-Adresse | Die IP-Adresse der externen Datendienste für den Cluster 


| Benutzername | Benutzername für das Admin-Konto 


| Passwort | Passwort für das Admin-Konto 
|===


[[advanced-configuration]]
== Erweiterte Konfiguration

[cols="50,50"]
|===
| Feld | Beschreibung 


| TCP-Port | TCP-Port, der für die Verbindung mit dem Nutanix-Array verwendet wird.  Der Standardwert ist 9440. 


| Inventarabfrageintervall (min) | Intervall zwischen den Bestandsabfragen. Der Standardwert beträgt 60 Minuten. 


| Leistungsabfrageintervall (Sek.) | Intervall zwischen Leistungsabfragen. Der Standardwert beträgt 300 Sekunden. 
|===


[[troubleshooting]]
== Fehlerbehebung

Weitere Informationen zu diesem Datensammler finden Sie imlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
