---
sidebar: sidebar 
permalink: task_dc_huawei_oceanstor.html 
keywords: data collector, Huawei, OceanStor, Dorado 
summary: 'Konfigurieren des Huawei OceanStor (REST/HTTPS)-Datensammlers.' 
---
= Huawei OceanStor Datensammler
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights verwendet den Huawei OceanStor (REST/HTTPS)-Datensammler, um Inventar und Leistung für Huawei OceanStor- und OceanStor Dorado-Speicher zu ermitteln.



== Terminologie

Data Infrastructure Insights erhält die folgenden Bestands- und Leistungsinformationen vom Huawei OceanStor.  Für jeden von Data Infrastructure Insights erworbenen Asset-Typ wird die am häufigsten verwendete Terminologie für dieses Asset angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Speicherpool | Speicherpool 


| Dateisystem | Internes Volumen 


| Regler | Speicherknoten 


| FC-Port (zugeordnet) | Volumenkarte 


| Host-FC-Initiator (zugeordnet) | Volumenmaske 


| NFS/CIFS-Freigabe | Aktie 


| iSCSI-Link-Ziel | iSCSI-Zielknoten 


| iSCSI-Link-Initiator | iSCSI-Initiatorknoten 


| Scheibe | Scheibe 


| LUN | Volumen 
|===


== Anforderungen

Zum Konfigurieren dieses Datensammlers sind die folgenden Voraussetzungen erforderlich:

* IP-Adresse des Geräts
* Anmeldeinformationen für den Zugriff auf den OceanStor-Gerätemanager
* Port 8088 muss verfügbar sein




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| OceanStor-Host-IP-Adresse | IP-Adresse oder vollqualifizierter Domänenname des OceanStor Device Managers 


| Benutzername | Name, der für die Anmeldung beim OceanStor Device Manager verwendet wird 


| Passwort | Passwort zur Anmeldung beim OceanStor Device Manager 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| TCP-Port | TCP-Port, der für die Verbindung mit dem OceanStor Device Manager verwendet wird.  Der Standardwert ist 8088. 


| Inventarabfrageintervall (min) | Intervall zwischen den Bestandsabfragen. Der Standardwert beträgt 60 Minuten. 


| Leistungsabfrageintervall (Sek.). | Der Standardwert beträgt 300 Sekunden. 
|===


== Fehlerbehebung

Weitere Informationen zu diesem Datensammler finden Sie imlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
