---
sidebar: sidebar 
permalink: task_dc_emc_recoverpoint.html 
keywords: data collector, RecoverPoint, EMC, DELL 
summary: Konfigurieren des DELL EMC RecoverPoint-Datenkollektors. 
---
= Dell EMC RecoverPoint-Datensammler
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Der Hauptanwendungsfall des EMC RecoverPoint-Datensammlers besteht darin, Volume-zu-Volume-Replikationsbeziehungen zu ermitteln, die das RecoverPoint-Speichergerät ermöglicht.  Dieser Collector erkennt auch das Recoverpoint-Gerät selbst.  Bitte beachten Sie, dass Dell/EMC eine VMware-Backup-Lösung für VMs verkauft – „RecoverPoint für VMs“ – die von diesem Collector nicht unterstützt wird.

Zur Konfiguration benötigt der Datensammler die IP-Adresse der Speicherprozessoren sowie einen schreibgeschützten Benutzernamen und ein Passwort.

Der EMC RecoverPoint-Datenkollektor erfasst die Volume-zu-Volume-Replikationsbeziehungen, die RecoverPoint über andere Speicher-Arrays hinweg koordiniert.  Data Infrastructure Insights zeigt ein Speicherarray für jeden RecoverPoint-Cluster und sammelt Inventardaten für Knoten und Speicherports auf diesem Cluster.  Es werden keine Speicherpool- oder Volumedaten erfasst.



== Anforderungen

Zur Konfiguration dieses Datensammlers sind folgende Angaben erforderlich:

* IP-Adresse oder vollqualifizierter Domänenname des Speicherprozessors
* Benutzername und Kennwort nur zum Lesen
* REST-API-Zugriff über Port 443




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Adresse von RecoverPoint | IP-Adresse oder vollqualifizierter Domänenname des RecoverPoint-Clusters 


| Benutzername | Benutzername für den RecoverPoint-Cluster 


| Passwort | Für den RecoverPoint-Cluster verwendetes Kennwort 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| TCP-Port | Für die Verbindung mit dem Recoverpoint-Cluster verwendeter TCP-Port 


| Inventarabfrageintervall (Minuten) | Intervall zwischen den Bestandsabfragen. Der Standardwert beträgt 20 Minuten. 


| Ausgeschlossene Cluster | Durch Kommas getrennte Liste von Cluster-IDs oder -Namen, die beim Polling ausgeschlossen werden sollen. 
|===


== Fehlerbehebung

Weitere Informationen zu diesem Datensammler finden Sie imlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
