---
sidebar: sidebar 
permalink: task_dc_ibm_svc.html 
keywords: IBM, SVC,SAN 
summary: Konfigurieren des IBM SAN Volume Controller-Datenkollektors. 
---
= Konfigurieren des IBM SAN Volume Controller-Datenkollektors
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Der IBM SAN Volume Controller (SVC)-Datenkollektor sammelt Inventar- und Leistungsdaten mithilfe von SSH und unterstützt eine Vielzahl von Geräten, auf denen das SVC-Betriebssystem ausgeführt wird.

Die Liste der unterstützten Geräte umfasst Modelle wie SVC, v7000, v5000 und v3700.  Informationen zu unterstützten Modellen und Firmware-Versionen finden Sie in der Data Infrastructure Insights Supportmatrix.



== Terminologie

Data Infrastructure Insights erhält die folgenden Bestandsinformationen vom IBM SVC-Datenkollektor.  Für jeden von Data Infrastructure Insights erworbenen Asset-Typ wird die am häufigsten verwendete Terminologie für dieses Asset angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Fahren | Scheibe 


| Cluster | Storage 


| Node | Speicherknoten 


| Mdisk-Gruppe | Speicherpool 


| Vdisk | Volumen 


| MDisk | Backend-LUNs und -Pfade 
|===
Hinweis: Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diesen Datensammler darstellen.



=== Inventaranforderungen

* IP-Adresse jedes SVC-Clusters
* Port 22 verfügbar
* Benutzername und Kennwort nur zum Lesen




=== Leistungsanforderungen

* SVC-Konsole, die für jeden SVC-Cluster obligatorisch und für das SVC Discovery Foundation-Paket erforderlich ist.
* Für die Anmeldeinformationen ist nur zum Kopieren von Leistungsdateien von Clusterknoten auf den Konfigurationsknoten eine Administratorzugriffsebene erforderlich.
* Aktivieren Sie die Datenerfassung, indem Sie per SSH eine Verbindung zum SVC-Cluster herstellen und Folgendes ausführen: _svctask startstats -interval 1_
+
Hinweis: Alternativ können Sie die Datenerfassung über die SVC-Verwaltungsbenutzeroberfläche aktivieren.





== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Cluster-IP-Adressen | IP-Adressen oder vollqualifizierte Domänennamen des SVC-Speichers 


| Inventar-Benutzername | Benutzername für die SVC-CLI 


| Inventarkennwort | Passwort für die SVC-CLI 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Inventarabfrageintervall (min) | Intervall zwischen den Bestandsabfragen. Der Standardwert beträgt 40 Minuten. 


| Leistungsabfrageintervall (Sek.) | Intervall zwischen Leistungsabfragen. Der Standardwert beträgt 300 Sekunden. 


| So bereinigen Sie gedumpte Statistikdateien | Aktivieren Sie dieses Kontrollkästchen, um die gespeicherten Statistikdateien zu bereinigen. 
|===


== Fehlerbehebung

Wenn bei diesem Datensammler Probleme auftreten, können Sie Folgendes versuchen:

[cols="2*"]
|===
| Problem: | Versuchen Sie Folgendes: 


| Fehler: „Der Befehl kann nicht initiiert werden, da er nicht auf dem Konfigurationsknoten ausgeführt wurde.“ | Der Befehl muss auf dem Konfigurationsknoten ausgeführt werden. 
|===
Wenn bei diesem Datensammler Probleme auftreten, können Sie Folgendes versuchen:

[cols="2*"]
|===
| Problem: | Versuchen Sie Folgendes: 


| Fehler: „Der Befehl kann nicht initiiert werden, da er nicht auf dem Konfigurationsknoten ausgeführt wurde.“ | Der Befehl muss auf dem Konfigurationsknoten ausgeführt werden. 
|===
Weitere Informationen zu diesem Datensammler finden Sie imlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
