---
sidebar: sidebar 
permalink: task_dc_brocade_bna.html 
keywords: data collector, Brocade, BNA 
summary: Konfigurieren des Brocade BNA-Collectors. 
---
= Brocade Network Advisor-Datensammler
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights verwendet den Brocade Network Advisor-Datensammler, um Bestands- und Leistungsdaten von Brocade -Switches zu erfassen.



== Terminologie

Data Infrastructure Insights erhält die folgenden Bestandsinformationen vom Brocade Network Advisor-Datensammler.  Für jeden von Data Infrastructure Insights erworbenen Asset-Typ wird die am häufigsten verwendete Terminologie für dieses Asset angezeigt.  Beachten Sie beim Anzeigen oder bei der Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter/Modellbegriff | Begriff „Data Infrastructure Insights“ 


| Schalten | Schalten 


| Hafen | Hafen 


| Virtuelles Gewebe, physisches Gewebe | Stoff 


| Logischer Switch | Logischer Switch 
|===
Hinweis: Hierbei handelt es sich lediglich um allgemeine Terminologiezuordnungen, die möglicherweise nicht jeden Fall für diesen Datensammler darstellen.



== Anforderungen

Zur Konfiguration dieses Datensammlers sind folgende Voraussetzungen erforderlich:

* Die Data Infrastructure Insights Acquisition Unit initiiert Verbindungen zum TCP-Port 443 auf dem BNA-Server.  Auf dem BNA-Server muss Version 14.2.1 oder höher ausgeführt werden.
* IP-Adresse des Brocade Network Advisor-Servers
* Benutzername und Kennwort für ein Administratorkonto
* Portanforderung: HTTP/HTTPS 443




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Brocade Network Advisor-Server-IP | IP-Adresse des Network Advisor-Servers 


| Benutzername | Benutzername für den Switch 


| Benutzername | Administrator-Benutzername 


| Passwort | Administratorkennwort 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Verbindungstyp | HTTPS (Standardport 443) oder HTTP (Standardport 80) 


| Verbindungsport überschreiben | Wenn das Feld „Verbindungstyp“ leer ist, verwenden Sie den Standardport. Andernfalls geben Sie den zu verwendenden Verbindungsport ein. 


| Passwort | Passwort für den Switch 


| Inventarabfrageintervall (min) | Der Standardwert ist 40 


| Bericht Access Gateway | Aktivieren Sie dieses Kontrollkästchen, um Geräte in den Access Gateway-Modus einzuschließen 


| Leistungsabfrageintervall (Sek.) | Der Standardwert ist 1800 
|===


== Fehlerbehebung

Wenn bei diesem Datensammler Probleme auftreten, können Sie Folgendes versuchen:



=== Inventar

[cols="2*"]
|===
| Problem: | Versuchen Sie Folgendes: 


| Sie erhalten eine Meldung, dass mehr als ein Knoten am Access Gateway-Port angemeldet ist oder dass der Datensammler das Access Gateway-Gerät nicht erkennen kann. | Überprüfen Sie, ob das NPV-Gerät ordnungsgemäß funktioniert und ob alle angeschlossenen WWNs den Erwartungen entsprechen.  Erwerben Sie das NPV-Gerät nicht direkt.  Stattdessen werden die NPV-Gerätedaten durch die Erfassung des Core Fabric Switch erfasst. 
|===
Weitere Informationen finden Sie in derlink:concept_requesting_support.html["Support"] Seite oder in derlink:reference_data_collector_support_matrix.html["Datensammler-Supportmatrix"] .
